### ISSUE TITLE
Charged porter in minecart

### ISSUE THREAD

**Issue by DeForce** [McJtyMods/RFTools#100]
Good Day,

Version 2.55
When I sit in minecart and use teleporter it uses energy but doesn't teleport.
Maybe say that you are sitting, or force port?

Best Regards,
DeForce

**Comment by McJty** [comment]
Hmm, interesting. It is also interesting to note that enderman also cannot teleport while in a minecart. I will check out if I can do anything about this.

**Comment by MichaelHillcox** [comment]
Unfortunately we're no longer supporting versions older than `1.12` and I don't have enough time to check this suggestion against all of the features of the mod but if this feature still hasn’t been implemented and you’d like to see it added to a newer version of the mod then please do create a new issue so we can review your suggestions again :+1:
