### ISSUE TITLE
Energy card not working with Draconic evolution energy core

### ISSUE THREAD

**Issue by mrgreaper** [McJtyMods/RFTools#1002]
Though given the capacity capable i would not be surprised if that was intentional rather then a bug...its ....a big number

**Comment by georgo** [comment]
I guess this is duplicating #973

**Comment by McJty** [comment]
Can you test out if it works if you use the latest McJtyLib from here:

http://jenkins.k-4u.nl/job/McJtyLib%201.11/lastSuccessfulBuild/artifact/build/libs/mcjtylib-1.1x-2.3.6-SNAPSHOT.jar

I implemented support but was not able to test it. Thanks

**Comment by georgo** [comment]
Can confirm it is working on Pylon (not the core - but honestly, I expected Pylon). Now it's not reporting internal buffer (like One Probe did), but real core energy. Kudos!
![2017-02-03_19 55 06](https://cloud.githubusercontent.com/assets/80399/22604225/d23fe716-ea4a-11e6-96f7-563ced3a9fee.png)

**Comment by georgo** [comment]
I can also confirm, RF Monitor is working and detecting correct buffer from Pylon.
