### ISSUE TITLE
Builder Block Preview invisible

### ISSUE THREAD

**Issue by aquilon74** [McJtyMods/RFTools#1005]
Hello, I noticed on Sky factory 3,  with the clearing quarry shape card, block preview option display blocks but they are invisible (but i suffocate if they appears on me).

**Comment by Stewker** [comment]
I seem to have this same issue. The builder will place preview blocks, you can run into them and etc, but they're just not visible basically negating their purpose. Another quirk is that it seems on singleplayer creative it appears to work fine as in you can actually see them, but on my multiplayer server (Infinity Lite 1.10 v1.6.0) the blocks are invisible. Finally this seemed to not be an issue before the modpack update which updated RFTools from 5.75-5.82.

**Comment by MichaelHillcox** [comment]
Thank you for taking the time to create this issue, as we're no longer supporting versions below `1.12`, I'm going to go ahead and close it but if this bug seems to continue over to newer versions, please do report it again so we can investigate the issue further.
