### ISSUE TITLE
Builder Quarry 'returned a null item'

### ISSUE THREAD

**Issue by Biochao** [McJtyMods/RFTools#1011]
Log: [fml-client-latest.txt](https://github.com/McJty/RFTools/files/733542/fml-client-latest.txt)

This is while using a clearing quarry.

Some info about my pack: 
Stone when broken with a pick is replaced with a cobblestone block then when that cobblestone is mined it drops rock items, not a cobblestone block. Cobblestone, dirt, and other 'soft' blocks are affected by gravity. Ores are dense, which means they can be mined 3 times on the same block.

All these tweaks come from [WTFs Expedition](https://minecraft.curseforge.com/projects/wtfs-expedition-cavebiomes-ores-trees-and-tweaks).

**Comment by MichaelHillcox** [comment]
1.14 has this commented so fixed? It's up for review in the code comment so I'll close this for now
