### ISSUE TITLE
Feature: configurable duration or toggle for 'matching inventory highlight' of storage scanner

### ISSUE THREAD

**Issue by shabble** [McJtyMods/RFTools#1015]
I'm using a storage scanner block for managing my refined storage crafter patterns, and when I want to find the crafter a particular pattern is in, the scanner's 'double-click inventory to highlight in-world' is invaluable.

Unfortunately, sometimes It's not long enough for me to get from the scanner and determine which of a large number of identical blocks it was indicating.  It would be nice if there was a way to control the duration from in-game somehow (triple-click, shift-double-click?), or some alternative such as making the highlighting a toggled action that needs explicitly turned off. Toggle would be my preferred option, but risks confusing people if they do it by mistake and can't figure out why a random block is highlighted. Maybe a sanity timeout (couple of mins?) in that case?

MC Version: 1.10.2
RFTools: rftools-1.1x-5.81.jar

**Comment by MichaelHillcox** [comment]
Unfortunately we're no longer supporting versions older than `1.12` and I don't have enough time to check this suggestion against all of the features of the mod but if this feature still hasn’t been implemented and you’d like to see it added to a newer version of the mod then please do create a new issue so we can review your suggestions again :+1:
