### ISSUE TITLE
mob spawns without weapons 1.11.2

### ISSUE THREAD

**Issue by ThisIsTheGitHubAccount4MUHAKL** [McJtyMods/RFTools#1029]
mcjtylib-1.1x-2.3.7.jar,rftools-1.1x-5.83.jar,1.11.2-forge1.11.2-13.20.0.2226

using RFTOOLS Spawner the mobs spawn WITHOUT WEAPONS
tested with skeleton, w.skeletons ans zombie.pigman

we need the enchanted weapons so much 

best regards

**Comment by MichaelHillcox** [comment]
Thank you for taking the time to create this issue, as we're no longer supporting versions below `1.12`, I'm going to go ahead and close it but if this bug seems to continue over to newer versions, please do report it again so we can investigate the issue further.
