### ISSUE TITLE
Linking power cells doesn't work anymore.

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [McJtyMods/RFTools#1031]
I'm using the 1.10.2 version, and linking powercells doesn't work anymore. Maybe I'm doing something wrong, but I used the same stuff as I always did. It always worked, suddenly it doesn't.

**Comment by McJty** [comment]
What are you doing exactly? For me everything is still working so just curious. Also what version of RFTools?

**Comment by Optimoos** [comment]
I'll just update this with my experience as I'm seeing a similar problem. Basically, in the All The Mods modpack v2.51b with RFTools 1.1x-5.87 (appears to be the latest release), the cards do not behave in a logical fashion. Placing them in slots and pulling them out does nothing, I have to shift click a stack of cards which will place them in the middle "Link" position at the same time, then shift click them again which somehow relocates them to the top left box. At this point I can pull out all but one and then manually place cards in the top left slot of other powercells.

Once a card is linked and in a cell, placing an unlinked card anywhere in the cell will not allow it to inherit the linking number, so you have to do it all at once.

I do not remember it being this finicky in other packs I've played, I seem to recall the cards just going where they need and moving from the top left slot to the top right slot on their own.

**Comment by Optimoos** [comment]
Having worked on this for a little longer, I need to amend my comment. I think the primary issue here is not functionality, it is merely that the description of the link card doesn't appear to get updated when it is inserted in the powercell when you are initially creating a link. After getting that figured out and having a "master" powercell functioning properly, I've been able to link additional cells without issue.

I would like to comment that the UI is not ultra clear on what is meant to be happening. Having the "master" slot with an arrow pointing toward the charging slot is confusing, to me it indicates that the link card should move to that slot when linked, and this confusion was compounded by the issue with the link card description not updating with its link id until removed from the master slot.

Anyway, the point is that I'm not actually experiencing an outright functionality problem, just some display issues and confusion around the UI.

Thanks for all your great work McJty.

**Comment by McJty** [comment]
That GUI desync problem is a weird one. Haven't been able to figure out why that is yet

I agree that it is a bit confusing but I'm not sure exactly how to make it clearer to be honest

**Comment by josephcsible** [comment]
https://github.com/McJty/RFTools/blob/19f938d39f9b1e5abf3200f47e7961f63d112092/src/main/java/mcjty/rftools/blocks/powercell/PowerCellTileEntity.java#L363-L367

This is why the desync exists. You're only setting the ID on the cards if you're on the server side.

**Comment by MichaelHillcox** [comment]
1.14 has changed this class pretty heavily. Let me know if it's still an issue.
