### ISSUE TITLE
No time dimlets except (Normal)?

### ISSUE THREAD

**Issue by Apocryphai** [McJtyMods/RFTools#1038]
I'm trying to craft a Time: Noon dimlet and after much trial and error have finally managed to get a Time Absorber to work. Now I find that I cannot craft any time dimlets except the Normal one. I've followed the guide [here](https://github.com/McJty/RFTools/wiki/RFTools-Dimlet-Construction-Examples) using the Dimlet Workbench and I've also tried all different tiers of Rarity, Energy and Memory modules but nothing seems to work.

In addition I can't even cheat one in since the only time dimlet that even shows up in JEI is Time(Normal).

Versions are:
RFTools 5.83
RFTools Dimensions 4.54
McJtyLib 2.3.7
CompatLayer 1.10-0.2.2

**Comment by McJty** [comment]
Is the time absorber at 100%? How are you trying to craft in?

Note that you can cheat in dimlets with the dimlet workbench if you are in creative

**Comment by Apocryphai** [comment]
Time Absorber is most definitely at 100%. Pics are probably quicker & easier than writing :) Here's the Time Absorber showing 100%: http://i.imgur.com/j37yFfa.png and here's me trying to craft it in the workbench, also showing that no time dimlets show up with a filter in the bench, nor in JEI except for the normal one: http://i.imgur.com/M9gFKet.png

I've tried deleting the RFTools config folders from both the server & client so that fresh, default ones are generated, same problem.

**Comment by McJty** [comment]
Can you search for 'noon' in the dimlet filter and double click the dimlet to see what parts it will move?

**Comment by Apocryphai** [comment]
Searching for noon turns up nothing, empty list.

**Comment by McJty** [comment]
Um that's strange... Can you find any time dimlet in that list?

**Comment by McJty** [comment]
BTW, it is normal that they don't appear in JEI. But it should show in the workbench

**Comment by Apocryphai** [comment]
Nope, no time dimlets show up in the workbench at all, whatever I search for - I've tried 'morning' 'noon' 'normal' 'default' and 'time' and nothing shows.

I'm starting to think my modpack has got corrupted somehow or that there's some conflict with other mods. 

I've got to go out now, back in a few hours. Really appreciate you taking the time to respond to issues like this :)

**Comment by MichaelHillcox** [comment]
Thank you for taking the time to create this issue, as we're no longer supporting versions below `1.12`, I'm going to go ahead and close it but if this bug seems to continue over to newer versions, please do report it again so we can investigate the issue further.
