### ISSUE TITLE
1.11.2( rftools builder cant mine exu2 moonstone) rftools-1.1x-5.84

### ISSUE THREAD

**Issue by SDUBZ** [McJtyMods/RFTools#1042]
client latest
[fml-client-latest.txt](https://github.com/McJty/RFTools/files/785689/fml-client-latest.txt)

**Comment by McJty** [comment]
This seems like a bug in Extra Utilities. Moonstone is returning itemstacks with null items from block.getDrops() and that's invalid.

@rwtema, any input on this?
