### ISSUE TITLE
builder using clearing quarry (silk or fortune) is mining/destroying a large set of blocks

### ISSUE THREAD

**Issue by DoomSquirter** [McJtyMods/RFTools#1048]
pack: https://mods.curse.com/modpacks/minecraft/257523-all-the-mods-presents-illumination
includes the mods that has poor ores, etc, so it definately changes a bunch of stuff in worldgen.

rftools-1.1x-5.84

Setup builder using pretty much all rftools stf (modular storage, energy cube).  setup a small square that includes roughly 8-10 stone, some tech reborn aluminum and some other mod's (project xy?) ore, and astral sorcery marble, some rustic mod's slate, and some clay.  

silk touch quarry picks up some slate and clay blocks but misses all the rest.  

Fortune does same but when you go back to area, there are xp orbs where the ores were, but again, nothing in the output modular storage.  

There are alot of mods here I've never used before, but this is the first time I've used the builder and seen this happen.  Note: am a huge fan of mod and huger fan of the builder as a quarry and have used it many times.  

No quarry cards are set to void anything, pretty stumped.

**Comment by McJty** [comment]
How is the quarry card setup? Can you show some screenshots?

**Comment by DoomSquirter** [comment]
very sorry for not replying earlier.  don't have the pack loaded atm but basic setup.  solid box, it's definately quarrying between point A and B and I have not checked any of the voids.

**Comment by McJty** [comment]
What are you using to collect the items from the builder? Can I see a screenshot?
