### ISSUE TITLE
Unable to get villager in 1.10.2

### ISSUE THREAD

**Issue by usafphoenix** [McJtyMods/RFTools#1053]
does current 1.10.2 release of RFtools have the villager, or no? i've tried everything i can think of after reading through configs and some of the code here, but can't seem to get a RFtools villager to spawn in void world (skyfactory3 version  3.0.7)
rftools-1.1x-5.84
rftoolsdim-1.1x-4.54

a thousand villager eggs in creative and many tests with 
/summon command with profession:10 fail to spawn the friendly neighborhood dimlet merchant.

**Comment by usafphoenix** [comment]
(rf tools config has his ID set to 10, but console output reports a runtimeException when 'attempting to set vilalger profession to unregistered profession: 10 null), which seems to mean that somehow, RFtools either has it's villager disabled for the time being, for the modpack as a whole, or there is some other quirky interaction preventing the original villager from being able to spawn.

**Comment by McJty** [comment]
The villager hasn't been implemented in 1.10 (yet)

**Comment by Pumpuli** [comment]
Haha, I just spent a long time trying to figure out why they weren't spawning. :D

I don't know anything about modding, but it seems to me that villagerId and profession are two different numbers? Also I saw that there's a method in Forge for registering a profession. I assume that's new in 1.10. Maybe you don't need the villagerId config anymore, but do you now need a profession id? :)

**Comment by ktole1999** [comment]
wait. is this the so called id profession crash that some have posted about. unable to register.

**Comment by usafphoenix** [comment]
@ktole1999, i imagine the id profession crash, is, indeed the result of the villager code being changed in 1.10.2 and needing the mod author to change function-calls/method names in their code. :-1: 
oh well.

**Comment by MichaelHillcox** [comment]
Thank you for taking the time to create this issue, as we're no longer supporting versions below `1.12`, I'm going to go ahead and close it but if this bug seems to continue over to newer versions, please do report it again so we can investigate the issue further.
