### ISSUE TITLE
Shape Card Client Crash

### ISSUE THREAD

**Issue by RehabOholic** [McJtyMods/RFTools#1078]
My client crashes when I try to cycle through the different shapes in the Shape card. I get 3 or so either direction and it just shuts down Minecraft.﻿

Playing on SkyFactory 3, latest build. 

No crash log is generated when crash happens.

**Comment by McJty** [comment]
There is always a crash log somewhere. Did you check all files in the logs folder? Also crash reports folder? Without a crash log I cannot do anything really

**Comment by RehabOholic** [comment]
I'm sorry, I loaded up the game so when I replicated the crash I could at least get the MultiMC Log, but when I stated I trashed the Shape Card First then tried it with a new crafted one. It didn't crash. I did update from an older version.

**Comment by megalous** [comment]
I have had the same crash. On a sponge-powered FTBBeyond1.5.3-Server in Aroma1997's Miningworld.
The builder never worked in the mining dimension haven't tried it in the overworld. The builder has been set with preview mode on, loop operation and maybe with move entities.

[Logfile created and uploaded by MultiMC](https://paste.ee/p/Hl3O4)

[Screenshots of the F3-Debugscreen and the quarry-shapecard settings](http://imgur.com/a/sCbGu)
