### ISSUE TITLE
[1.11.2] RFtools can't seem to push to Fluxed wires. Will still output to RFtools

### ISSUE THREAD

**Issue by Rosethorns** [McJtyMods/RFTools#1081]
Description:
It appears from some playing around that nothing in RFTools that outputs FU/RF will push to Fluxed wires.
Its too hard to tell whos side this is on so I'm posting it to both.

Recreate:

1.setup RFtools power provider
2.connect to provider using fluxed wire of any kind.
3.connect a power reciever.
4.no power will even enter the wire network
http://i.imgur.com/XIxfNHU.png

Versions:
Minecraft: 1.11.2
Forge: 13.20.0.2252
Fluxed Redstone: 2.6.0.54
RFTools: 2-0.011

Edit: It occurs to me I didn't clarify "Will still output to RFTools" Using a forestry engine as a power provider successfully pushed energy to the crafter in the linked picture.

**Comment by McJty** [comment]
As rftools can successfully push to other RF/FE/FU consumers I would think this is more like a bug in Fluxed Redstone but I like to hear what they say about it

**Comment by Rosethorns** [comment]
As I thought. I'll keep you posted.

**Comment by MichaelHillcox** [comment]
Thank you for taking the time to create this issue, as we're no longer supporting versions below `1.12`, I'm going to go ahead and close it but if this bug seems to continue over to newer versions, please do report it again so we can investigate the issue further.
