### ISSUE TITLE
1.10.2 - A couple of small "bugs"

### ISSUE THREAD

**Issue by tjsd** [McJtyMods/RFTools#1082]
Whenver you first search with the rftools scanner search bar and click in the JEI search bar the focus doesnt move away from the searchbar inside the storage scanner. You have to click once somewhere else first.

The matter beamers have a very limited acceptance of living matter. Newer stuff like raw mutton from sheep and rabbit does not get accepted.

Love your mods :) keep up the good work!

**Comment by McJty** [comment]
I'll added raw mutton and rabbit stuff. I know about the JEI problem. Not sure how to fix that yet though

**Comment by McJty** [comment]
@mezz, any advice on how I can detect that the user clicked on the JEI search bar and in that case stop eating keypresses (i.e. deactivate the focus on my own local search bar)?

**Comment by mezz** [comment]
I use `GuiScreenEvent.KeyboardInputEvent.Pre` to detect key presses, and I cancel it if I use the key.
Canceling that event also skips `GuiScreen#handleKeyboardInput` so your text box shouldn't get key inputs if it uses the event or that method.

**Comment by McJty** [comment]
Ok @mezz still confused about this. I can detect key events. That's no problem. But how do I know that your search bar is activated so that I need to clear the focus on my widget?

**Comment by mezz** [comment]
Ok, I thought the problem was about receiving key presses, not the focus indicator.
This may be easier to fix on JEI's side. I already detect any active `GuiTextField` for certain cases, so I can just call `setFocused(false)` on it when I get focus.

**Comment by McJty** [comment]
I'm afraid my gui library doesn't use GuiTextField. It is 100% custom so that will probably not work

**Comment by mezz** [comment]
I added a method to check if JEI has keyboard focus. 
It will require a check to see that JEI is loaded, unlike other JEI integration.
https://github.com/mezz/JustEnoughItems/commit/4eac89c784502eaa54c5b14c07e81f3660b5cc60

**Comment by McJty** [comment]
Thanks a lot! This will likely only work for 1.11 though so on 1.10 this will remain an issue forever. That's ok

**Comment by MichaelHillcox** [comment]
Thank you for taking the time to create this issue, as we're no longer supporting versions below `1.12`, I'm going to go ahead and close it but if this bug seems to continue over to newer versions, please do report it again so we can investigate the issue further.
