### ISSUE TITLE
[Feature Request] Let Powercells be able to give power to AE2 Energy Acceptor without wires

### ISSUE THREAD

**Issue by LewisLarsen** [McJtyMods/RFTools#1087]
Most blocks these days will happily give out energy to a block that is right next to it without the need for wires, I've discovered while setting up my AE system that the powercell doesn't give any energy to the acceptor without having wires connected to it. This might affect the ME Controller also  but I'm not sure.

**Comment by McJty** [comment]
The RFTools powercell uses standard RF and Forge Energy. If this is not working then that's most likely a bug in AE
