### ISSUE TITLE
Elevator moves players in spectator mode.

### ISSUE THREAD

**Issue by lurr** [McJtyMods/RFTools#1089]
As title says.

Minecraft 1.10.2
RFTools 1.1x-5.87
Forge 12.18.3.2254

**Comment by McJty** [comment]
What exactly is happening? Can you describe more precisely?

**Comment by lurquhar1221** [comment]
When an elevator is moving, it will move players up/down in all gamemodes (this means Spectator).
e.g. if a player is in spectator in the way of an elevator, the elevator will pick them up, even though they're in Spectator mode.

**Comment by McJty** [comment]
And why exactly is that a problem?

**Comment by legodude17** [comment]
I think they mean that because the player is in Spectator mode they should go through the blocks instead of being moved with the elevator.

**Comment by MichaelHillcox** [comment]
Thank you for taking the time to create this issue, as we're no longer supporting versions below `1.12`, I'm going to go ahead and close it but if this bug seems to continue over to newer versions, please do report it again so we can investigate the issue further.
