### ISSUE TITLE
Crafter not working with OpenComputers Recipes  

### ISSUE THREAD

**Issue by shiprek** [McJtyMods/RFTools#1099]
Playing on: Futures Edge V 0.4.1
Minecraft: 1.10.2
forge-12.18.3.229
Item: Tier 3 Crafter
http://imgur.com/a/tEunG

Setup nugget recipes and they work perfect. I am using a lever to power the crafter. Transistor and microchip recipes will not craft to either internal or external storage. I also have a tier 2 crafter setup to turn wood into blocks/sticks/wood tools and that works perfectly.

**Comment by MichaelHillcox** [comment]
Thank you for taking the time to create this issue, as we're no longer supporting versions below `1.12`, I'm going to go ahead and close it but if this bug seems to continue over to newer versions, please do report it again so we can investigate the issue further.
