### ISSUE TITLE
Builder Quarry turns nether portal into death trap [FTB Beyond 1.10.2 pack version 1.2.1]

### ISSUE THREAD

**Issue by mpijoan** [McJtyMods/RFTools#1105]
I made a mistake and let the builder run over my nether portal with a fortune quarry card, which turned all the blocks that formed the gate into dirt. Portal however still worked. (Purple portal blocks, dirt frame)

However when I /used/ said portal more out of a sense of morbid curiosity than anything, I spawned somewhere below the nether portal on the overworld and suffocated inside of a wall.

**Comment by MichaelHillcox** [comment]
Very funny but likely not a simple fix nor really an issue, it's kind of intented :P
