### ISSUE TITLE
[Feature Request] Screen Module button "switch' Option

### ISSUE THREAD

**Issue by mrdeadlocked** [McJtyMods/RFTools#1111]
It would be great to have an option on the screen button module to make its appearance more like a 'switch'. With simple 'on/off' item the button is hard to read. It would also be nice to allow 'inverting' the on/off on the display for a system that will be turned on with no redstone signal vs a system that can be turned on with redstone signal.

Here's a bad mockup left being current and the right being requested feature.

![image](https://cloud.githubusercontent.com/assets/461352/24358463/2dd22646-12cf-11e7-839f-8026b89de407.png)

**Comment by Lukas45** [comment]
A Redstone Lever module would be very nice indeed

**Comment by Viper007Bond** [comment]
A workaround meanwhile is to use a Redstone Module that displays the current status (on vs off).

**Comment by McJty** [comment]
You are all aware that screen buttons can already be in 'toggle' mode right?

**Comment by Viper007Bond** [comment]
Yep, but I believe OP's opinion is that it can be hard to tell which state it's in at a glance.

I don't really have an opinion on the matter myself, although I might find being able to change the button's text based on the on/off status.

**Comment by mrdeadlocked** [comment]
With the above pictures, it is hard to tell which state something is in. Especially when things can differ and be on or off with or without a Redstone signal. It would just be nice to have some more functionality if possible.

**Comment by BattleNachos** [comment]
Currently it's hard to tell at a glance if a button is toggled.  I love OPs suggestion, or even just an extra text field for a button module's toggled state.  e.g. Off when not pressed, On when pressed etc..

Also an invert signal option would be really handy when controlling machines that are on by default.
