### ISSUE TITLE
[Feature Request] Liquid Monitor Improvement FFS SUpport

### ISSUE THREAD

**Issue by mrdeadlocked** [McJtyMods/RFTools#1112]
Liquid Monitor does not see a fancy fluid storage tank liquid levels. is this something you can fix or FFS side of things?

https://github.com/Lordmau5/FFS

**Comment by McJty** [comment]
Most likely FFS because I'm using standard forge fluid system

**Comment by Zekralyx** [comment]
What do you mean with "does not see"? I made a test in my test world and got this:

![2017-04-11_13 35 18](https://cloud.githubusercontent.com/assets/2272746/24920015/0104477c-1ebc-11e7-9a0a-b555dcd3669b.png)
![2017-04-11_13 35 23](https://cloud.githubusercontent.com/assets/2272746/24920016/010a8d30-1ebc-11e7-80b4-0dd1a409afed.png)

That seems to be pretty much what you want. Or is it something else?

**Comment by mrdeadlocked** [comment]
I'll have to check again. I had an FFS Tank of syngas and it wasn't able to find the value of the full tank.

**Comment by MichaelHillcox** [comment]
Thank you for taking the time to create this issue, as we're no longer supporting versions below `1.12`, I'm going to go ahead and close it but if this bug seems to continue over to newer versions, please do report it again so we can investigate the issue further.
