### ISSUE TITLE
Material Absorber won't pickup soul sand

### ISSUE THREAD

**Issue by viveleroi** [McJtyMods/RFTools#1114]
Using RFTools (rftools-1.1x-5.87, rftoolsdim-1.1x-4.54)  in SkyFactory 3.0.8, I can't get a material absorber to work with soul sand. It works fine with end stone and quartz blocks which are the other two I tried.

When I place soul sand, and the absorber above it, nothing happens. I've asked in IRC (both `#ftb` and `#rftools` if this is intended (though I can't fathom why) but haven't gotten a reply.

**Comment by McJty** [comment]
The reason is that soulsand has no dimlet. I forgot to add that to the dimlet json. You can add it manually but I will fix this next release. Also please use the github for rftools dimensions in the future

**Comment by viveleroi** [comment]
Thanks. I didn't realize there was a separate repo, I will remember that for any future issues. I'll look around for the JSON and see if I can add it manually.

**Comment by MichaelHillcox** [comment]
Thank you for taking the time to create this issue, as we're no longer supporting versions below `1.12`, I'm going to go ahead and close it but if this bug seems to continue over to newer versions, please do report it again so we can investigate the issue further.
