### ISSUE TITLE
Flight Module issue

### ISSUE THREAD

**Issue by Tuffnoodle** [McJtyMods/RFTools#1117]
On our 1.10.2 FTB Beyond server
rftools- 1.1x-1.6.6

The flight that the flight module gives persists despite being far outside range of Environmental Controller; it also stays and allows players to keep flight after relogging onto the server, and after planned/forced server restarts.

**Comment by McJty** [comment]
Does it persist forever? How long did you wait for it to timeout?

**Comment by Tuffnoodle** [comment]
While testing, about 30 minutes. Players on our server were able to fly for quite a while, the only way they lost flight was dying.

**Comment by MichaelHillcox** [comment]
Thank you for taking the time to create this issue, as we're no longer supporting versions below `1.12`, I'm going to go ahead and close it but if this bug seems to continue over to newer versions, please do report it again so we can investigate the issue further.
