### ISSUE TITLE
Crashed while charging storage scanner

### ISSUE THREAD

**Issue by Sectmoon0000** [McJtyMods/RFTools#1123]
Version: forge 1.10.2-12.18.3.2185

I tried several times, the game will crashed when I opened the storage scanner if it's charging.

Crash report:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  SPFMLLoadingPlugin (soundphysics-mc1.10.2-v1.0.0.jar)
  FMLPlugin (InventoryTweaks-1.62-dev-66.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.60-beta.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.4.3.124-universal.jar)
  DepLoader (CodeChickenCore-1.10.2-2.3.5.91-universal.jar)
  LoadingHook (Mekanism-1.10.2-9.2.1.295.jar)
Contact their authors BEFORE contacting forge

// Don't do that.

Time: 4/3/17 7:43 PM
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at mcjty.rftools.blocks.storagemonitor.GuiStorageScanner.customRenderToolTip(GuiStorageScanner.java:587)
	at mcjty.rftools.blocks.storagemonitor.GuiStorageScanner.func_73863_a(GuiStorageScanner.java:556)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)
	at sun.reflect.GeneratedMethodAccessor21.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at Reflector.callVoid(Reflector.java:512)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1398)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at mcjty.rftools.blocks.storagemonitor.GuiStorageScanner.customRenderToolTip(GuiStorageScanner.java:587)
	at mcjty.rftools.blocks.storagemonitor.GuiStorageScanner.func_73863_a(GuiStorageScanner.java:556)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)
	at sun.reflect.GeneratedMethodAccessor21.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at Reflector.callVoid(Reflector.java:512)

-- Screen render details --
Details:
	Screen name: mcjty.rftools.blocks.storagemonitor.GuiStorageScanner
	Mouse location: Scaled: (222, 115). Absolute: (444, 477)
	Screen size: Scaled: (642, 354). Absolute: (1283, 708). Scale factor of 2

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Sect_moon'/424, l='MpServer', x=1205.80, y=74.00, z=-724.24]]
	Chunk stats: MultiplayerChunkCache: 361, 361
	Level seed: 0
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-192,64,219), Chunk: (at 0,4,11 in -12,13; contains blocks -192,0,208 to -177,255,223), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 5106493 game time, 7596925 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 91 total; [EntitySpider['Spider'/33793, l='MpServer', x=1154.50, y=98.00, z=-755.50], EntityItem['item.item.tconstruct.edible.slimeball_blue'/20483, l='MpServer', x=1190.13, y=79.00, z=-764.85], EntityBlueSlime['Blue Slime'/518, l='MpServer', x=1168.12, y=62.47, z=-722.65], EntityItem['item.item.tconstruct.edible.slimeball_blue'/30471, l='MpServer', x=1167.66, y=83.00, z=-751.68], EntityWorm['entity.actuallyadditions.actuallyadditions.worm.name'/520, l='MpServer', x=1235.50, y=66.50, z=-708.50], EntityWorm['entity.actuallyadditions.actuallyadditions.worm.name'/521, l='MpServer', x=1236.50, y=66.50, z=-706.50], EntityWorm['entity.actuallyadditions.actuallyadditions.worm.name'/522, l='MpServer', x=1234.50, y=66.50, z=-706.50], EntitySpark['Spark'/527, l='MpServer', x=1233.50, y=68.50, z=-733.50], EntityZombie['Zombie'/33042, l='MpServer', x=1152.26, y=40.00, z=-680.51], EntityCreeper['Creeper'/33043, l='MpServer', x=1161.50, y=40.00, z=-672.50], EntityCreeper['Creeper'/34068, l='MpServer', x=1262.50, y=28.00, z=-798.50], EntityCreeper['Creeper'/34069, l='MpServer', x=1262.50, y=28.00, z=-800.50], EntitySheep['Sheep'/534, l='MpServer', x=1270.80, y=69.00, z=-766.64], EntitySpider['Spider'/31254, l='MpServer', x=1211.50, y=23.00, z=-796.50], EntityPig['Pig'/535, l='MpServer', x=1267.20, y=67.00, z=-704.26], EntitySkeleton['Skeleton'/34072, l='MpServer', x=1260.50, y=28.00, z=-798.50], EntitySpark['Spark'/537, l='MpServer', x=1262.50, y=68.50, z=-713.50], EntityBabySkeleton['Baby Skeleton'/34073, l='MpServer', x=1160.34, y=30.00, z=-706.48], EntityBabySkeleton['Baby Skeleton'/34074, l='MpServer', x=1162.17, y=30.00, z=-706.15], EntityBabySkeleton['Baby Skeleton'/34075, l='MpServer', x=1160.50, y=30.00, z=-708.50], EntityItem['item.item.tconstruct.edible.slimeball_blue'/32059, l='MpServer', x=1161.13, y=107.00, z=-749.35], EntityBat['Bat'/34129, l='MpServer', x=1221.85, y=30.70, z=-795.04], EntitySkeleton['Skeleton'/33106, l='MpServer', x=1210.50, y=28.00, z=-794.50], EntitySkeleton['Skeleton'/33874, l='MpServer', x=1168.49, y=29.00, z=-701.71], EntitySkeleton['Skeleton'/33107, l='MpServer', x=1209.50, y=28.00, z=-793.50], EntitySkeleton['Skeleton'/33875, l='MpServer', x=1162.50, y=30.00, z=-704.50], EntitySkeleton['Skeleton'/33108, l='MpServer', x=1210.50, y=28.00, z=-793.50], EntitySkeleton['Skeleton'/31317, l='MpServer', x=1194.50, y=25.00, z=-802.50], EntitySkeleton['Skeleton'/31318, l='MpServer', x=1196.50, y=25.00, z=-802.50], EntityBlueSlime['Blue Slime'/32089, l='MpServer', x=1146.69, y=96.75, z=-740.62], EntityBlueSlime['Blue Slime'/32090, l='MpServer', x=1146.85, y=95.00, z=-739.26], EntityItem['item.tile.gravel'/18269, l='MpServer', x=1215.19, y=32.00, z=-786.60], EntityLatchedRenderer['unknown'/5216, l='MpServer', x=1205.80, y=74.00, z=-724.24], EntityItem['item.item.tconstruct.edible.slimeball_blue'/34400, l='MpServer', x=1173.84, y=79.00, z=-752.45], EntityZombie['entity.Zombie.name'/31843, l='MpServer', x=1161.85, y=30.00, z=-707.86], EntityBat['Bat'/28004, l='MpServer', x=1230.02, y=40.08, z=-777.25], EntitySpider['Spider'/31844, l='MpServer', x=1163.12, y=30.00, z=-706.57], EntityBat['Bat'/28005, l='MpServer', x=1245.84, y=31.84, z=-772.57], EntityCreeper['Creeper'/31845, l='MpServer', x=1165.50, y=30.00, z=-704.50], EntityCreeper['Creeper'/31846, l='MpServer', x=1162.50, y=30.00, z=-707.60], EntitySpider['Spider'/9833, l='MpServer', x=1196.50, y=47.00, z=-789.50], EntityItem['item.item.tconstruct.edible.slimeball_blue'/31849, l='MpServer', x=1173.09, y=79.00, z=-755.60], EntitySheep['Sheep'/627, l='MpServer', x=1257.54, y=65.00, z=-779.19], EntityBlueSlime['Blue Slime'/30581, l='MpServer', x=1167.25, y=82.14, z=-749.11], EntitySkeleton['Skeleton'/35193, l='MpServer', x=1254.50, y=17.00, z=-690.50], EntityItem['item.item.tconstruct.edible.slimeball_blue'/31104, l='MpServer', x=1167.54, y=94.00, z=-758.44], EntityCreeper['Creeper'/22410, l='MpServer', x=1142.50, y=40.00, z=-682.50], EntityLatchedRenderer['unknown'/655, l='MpServer', x=1203.89, y=74.00, z=-726.04], EntityCreeper['Creeper'/34960, l='MpServer', x=1154.50, y=40.00, z=-677.50], EntityBat['Bat'/24732, l='MpServer', x=1171.47, y=28.10, z=-798.74], EntitySkeleton['Skeleton'/32926, l='MpServer', x=1246.50, y=35.00, z=-783.50], EntityVillager['Villager'/423, l='MpServer', x=1279.30, y=78.00, z=-695.50], EntityPlayerSP['Sect_moon'/424, l='MpServer', x=1205.80, y=74.00, z=-724.24], EntitySquid['Squid'/32425, l='MpServer', x=1207.24, y=54.41, z=-686.20], EntityLatchedRenderer['unknown'/426, l='MpServer', x=8.50, y=65.00, z=8.50], EntitySkeleton['Skeleton'/28842, l='MpServer', x=1267.50, y=31.00, z=-750.50], EntitySquid['Squid'/32426, l='MpServer', x=1203.76, y=53.37, z=-679.21], EntitySquid['Squid'/32427, l='MpServer', x=1205.90, y=53.62, z=-678.47], EntitySquid['Squid'/32428, l='MpServer', x=1207.00, y=51.13, z=-681.51], EntitySquid['Squid'/32429, l='MpServer', x=1158.71, y=56.42, z=-666.68], EntitySquid['Squid'/32430, l='MpServer', x=1167.41, y=56.05, z=-666.24], EntitySquid['Squid'/32431, l='MpServer', x=1163.50, y=56.48, z=-668.55], EntitySquid['Squid'/32432, l='MpServer', x=1156.73, y=56.37, z=-675.44], EntitySheep['Sheep'/435, l='MpServer', x=1165.33, y=99.00, z=-768.99], EntityZombie['Zombie'/27582, l='MpServer', x=1170.50, y=33.00, z=-695.50], EntitySheep['Sheep'/448, l='MpServer', x=1149.49, y=82.00, z=-775.73], EntitySheep['Sheep'/458, l='MpServer', x=1193.73, y=86.00, z=-773.50], EntityCreeper['Creeper'/32715, l='MpServer', x=1165.50, y=20.00, z=-696.50], EntityZombie['Zombie'/28619, l='MpServer', x=1280.50, y=23.00, z=-654.50], EntityCreeper['Creeper'/32716, l='MpServer', x=1163.50, y=20.00, z=-699.50], EntityCreeper['Creeper'/32717, l='MpServer', x=1165.50, y=20.00, z=-696.50], EntityBat['Bat'/31694, l='MpServer', x=1206.70, y=15.79, z=-803.27], EntitySheep['Sheep'/467, l='MpServer', x=1164.58, y=82.00, z=-745.62], EntityBlueSlime['Blue Slime'/31962, l='MpServer', x=1158.41, y=105.00, z=-746.28], EntitySheep['Sheep'/478, l='MpServer', x=1159.28, y=92.00, z=-771.54], EntitySheep['Sheep'/479, l='MpServer', x=1155.54, y=98.00, z=-752.73], EntityZombie['Zombie'/30943, l='MpServer', x=1217.50, y=30.00, z=-674.50], EntitySkeleton['Skeleton'/34783, l='MpServer', x=1246.50, y=16.00, z=-712.50], EntitySheep['Sheep'/480, l='MpServer', x=1153.52, y=98.00, z=-753.72], EntityZombie['Zombie'/30944, l='MpServer', x=1217.50, y=30.00, z=-672.50], EntitySkeleton['Skeleton'/34784, l='MpServer', x=1246.50, y=16.00, z=-713.50], EntitySheep['Sheep'/481, l='MpServer', x=1152.54, y=100.00, z=-763.25], EntityCreeper['Creeper'/30945, l='MpServer', x=1218.50, y=30.00, z=-672.50], EntityCreeper['Creeper'/35041, l='MpServer', x=1269.50, y=41.00, z=-800.50], EntitySheep['Sheep'/482, l='MpServer', x=1134.54, y=64.00, z=-727.32], EntityItem['item.item.egg'/13794, l='MpServer', x=1153.34, y=63.00, z=-689.88], EntityItem['item.item.egg'/14306, l='MpServer', x=1166.49, y=72.00, z=-707.44], EntityChicken['Chicken'/492, l='MpServer', x=1152.80, y=63.00, z=-689.33], EntityBlueSlime['Blue Slime'/496, l='MpServer', x=1200.26, y=69.68, z=-744.07], EntityChicken['Chicken'/499, l='MpServer', x=1167.11, y=72.00, z=-707.33], EntityPig['Pig'/503, l='MpServer', x=1169.77, y=79.00, z=-747.46]]
	Retry entities: 2 total; [EntityLatchedRenderer['unknown'/426, l='MpServer', x=8.50, y=65.00, z=8.50], EntityLatchedRenderer['unknown'/655, l='MpServer', x=1203.89, y=74.00, z=-726.04]]
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:524)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:392)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 561962976 bytes (535 MB) / 4556783616 bytes (4345 MB) up to 21461467136 bytes (20467 MB)
	JVM Flags: 22 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx20G -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+UseNUMA -XX:+CMSParallelRemarkEnabled -XX:MaxGCPauseMillis=50 -XX:+UseAdaptiveGCBoundary -XX:-UseGCOverheadLimit -XX:+UseBiasedLocking -XX:SurvivorRatio=8 -XX:TargetSurvivorRatio=90 -XX:MaxTenuringThreshold=15 -XX:UseSSE=3 -XX:+UseFastAccessorMethods -XX:+UseStringCache -XX:+UseCompressedOops -XX:+OptimizeStringConcat -XX:+UseFastAccessorMethods -XX:+AggressiveOpts -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 3, tallocated: 104
	FML: MCP 9.32 Powered by Forge 12.18.3.2185 Optifine OptiFine_1.10.2_HD_U_D6 60 mods loaded, 60 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2185.jar) 
	UCHIJAAAA	Forge{12.18.3.2185} [Minecraft Forge] (forge-1.10.2-12.18.3.2185.jar) 
	UCHIJAAAA	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.10.2.jar) 
	UCHIJAAAA	actuallyadditions{1.10.2-r90} [Actually Additions] (ActuallyAdditions-1.10.2-r90.jar) 
	UCHIJAAAA	JEI{3.13.6.389} [Just Enough Items] (jei_1.10.2-3.13.6.389.jar) 
	UCHIJAAAA	appleskin{1.0.4} [AppleSkin] (AppleSkin-mc1.10.2-1.0.4.jar) 
	UCHIJAAAA	Psi{r1.0-42} [Psi] (Psi-r1.0-42.jar) 
	UCHIJAAAA	AutoRegLib{1.0-2} [AutoRegLib] (AutoRegLib-1.0-2.jar) 
	UCHIJAAAA	Baubles{1.3.8} [Baubles] (Baubles-1.10.2-1.3.8.jar) 
	UCHIJAAAA	bedbugs{@VERSION@} [Bed Bugs] (BedBugs-1.10.2-1.1.4.jar) 
	UCHIJAAAA	BiomesOPlenty{5.0.0.2109} [Biomes O' Plenty] (BiomesOPlenty-1.10.2-5.0.0.2109-universal.jar) 
	UCHIJAAAA	guideapi{@VERSION@} [Guide-API] (Guide-API-1.10.2-2.0.2-45.jar) 
	UCHIJAAAA	BloodMagic{1.9.4-2.1.0-69} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.9.4-2.1.0-69.jar) 
	UCHIJAAAA	Botania{r1.9-339} [Botania] (Botania r1.9-339.jar) 
	UCHIJAAAA	CodeChickenLib{2.4.3.124} [CodeChicken Lib] (CodeChickenLib-1.10.2-2.4.3.124-universal.jar) 
	UCHIJAAAA	CodeChickenCore{2.3.5.91} [CodeChicken Core] (CodeChickenCore-1.10.2-2.3.5.91-universal.jar) 
	UCHIJAAAA	endercore{1.10.2-0.4.1.60-beta} [EnderCore] (EnderCore-1.10.2-0.4.1.60-beta.jar) 
	UCHIJAAAA	Waila{1.7.0} [Waila] (Waila-1.7.0-B3_1.9.4.jar) 
	UCHIJAAAA	EnderIO{1.10.2-3.0.1.126_beta} [Ender IO] (EnderIO-1.10.2-3.0.1.126_beta.jar) 
	UCHIJAAAA	EnderStorage{2.1.5.84} [EnderStorage] (EnderStorage-1.10.2-2.1.5.84-universal.jar) 
	UCHIJAAAA	valkyrielib{1.10.2-0.10.5f} [Valkyrie Lib] (valkyrielib-1.10.2-0.10.5f.jar) 
	UCHIJAAAA	environmentaltech{1.10.2-0.10.5h} [Environmental Tech] (environmentaltech-1.10.2-0.10.5h.jar) 
	UCHIJAAAA	ExtraUtils2{1.0} [ExtraUtils2] (extrautils2-1.10.2-1.1.2.jar) 
	UCHIJAAAA	fastleafdecay{v11} [Fast Leaf Decay] (FastLeafDecay-v11.jar) 
	UCHIJAAAA	forestry{5.2.16.331} [Forestry] (forestry_1.10.2-5.2.16.331.jar) 
	UCHIJAAAA	fw{1.5.0} [Fullscreen Windowed] (FullscreenWindowed-1.10.2-1.5.0.jar) 
	UCHIJAAAA	gravestone{1.5.9} [Gravestone] (GraveStone Mod 1.5.9.jar) 
	UCHIJAAAA	ichunutil{6.1.0} [iChunUtil] (iChunUtil-1.10.2-6.1.0.jar) 
	UCHIJAAAA	inventorytweaks{1.62-dev-66-c082db3} [Inventory Tweaks] (InventoryTweaks-1.62-dev-66.jar) 
	UCHIJAAAA	ironchest{1.10.2-7.0.11.797} [Iron Chest] (ironchest-1.10.2-7.0.11.797.jar) 
	UCHIJAAAA	jeibees{0.9.0.4} [JEI Bees] (jeibees-0.9.0.4-mc1.10.2.jar) 
	UCHIJAAAA	journeymap{1.10.2-5.4.2} [JourneyMap] (journeymap-1.10.2-5.4.2.jar) 
	UCHIJAAAA	jeresources{0.5.8.98} [Just Enough Resources] (JustEnoughResources-1.10.2-0.5.8.98.jar) 
	UCHIJAAAA	login_shield{1.10.2-19-gd16e7e0} [Login Shield] (Login_Shield-1.10.2-19-gd16e7e0.jar) 
	UCHIJAAAA	mantle{1.10.2-1.1.3.199} [Mantle] (Mantle-1.10.2-1.1.3.jar) 
	UCHIJAAAA	mcmultipart{1.3.0_87} [MCMultiPart] (MCMultiPart-experimental-2.0.0_88-universal.jar) 
	UCHIJAAAA	Mekanism{9.2.1} [Mekanism] (Mekanism-1.10.2-9.2.1.295.jar) 
	UCHIJAAAA	MekanismGenerators{9.2.1} [MekanismGenerators] (MekanismGenerators-1.10.2-9.2.1.295.jar) 
	UCHIJAAAA	MekanismTools{9.2.1} [MekanismTools] (MekanismTools-1.10.2-9.2.1.295.jar) 
	UCHIJAAAA	Neat{1.3-12} [Neat] (Neat 1.3-12.jar) 
	UCHIJAAAA	netherportalfix{1.0} [Nether Portal Fix] (netherportalfix-mc1.9.4-4.0.1.jar) 
	UCHIJAAAA	notenoughwands{1.5.1} [Not Enough Wands] (notenoughwands-1.1x-1.5.1.jar) 
	UCHIJAAAA	clayspawn{1.9.4-1.10.2a} [Pam's Clay Spawn] (Pam's Clay Spawn 1.9.4-1.10.2a.jar) 
	UCHIJAAAA	harvestcraft{1.9.4-1.10.2g} [Pam's HarvestCraft] (Pam's HarvestCraft 1.9.4-1.10.2h.jar) 
	UCHIJAAAA	refinedstorage{1.2.18} [Refined Storage] (refinedstorage-1.2.18.jar) 
	UCHIJAAAA	rftools{5.70} [RFTools] (rftools-1.1x-5.70.jar) 
	UCHIJAAAA	rftoolscontrol{1.6.2} [RFTools Control] (rftoolsctrl-1.1x-1.6.2.jar) 
	UCHIJAAAA	rftoolsdim{4.50} [RFTools Dimensions] (rftoolsdim-1.1x-4.50.jar) 
	UCHIJAAAA	Roguelike{1.5.4} [Roguelike Dungeons] (RoguelikeDungeons-1.10.2-1.5.4.jar) 
	UCHIJAAAA	shadowmc{3.5.0} [ShadowMC] (ShadowMC-1.10.2-3.6.0.jar) 
	UCHIJAAAA	flammpfeil.slashblade{mc1.10.2-r33} [SlashBlade] (SlashBlade-mc1.10.2-r33.jar) 
	UCHIJAAAA	SleepingBag{1.4.0} [Sleeping Bag] (SleepingBag-1.10.2-1.4.0.jar) 
	UCHIJAAAA	soundphysics{1.0.0} [Sound Physics] (soundphysics-mc1.10.2-v1.0.0.jar) 
	UCHIJAAAA	substratum{1.8.2.1} [Substratum] (Substratum-1.10.2-1.8.2.1.jar) 
	UCHIJAAAA	tconstruct{1.10.2-2.6.1.464} [Tinkers' Construct] (TConstruct-1.10.2-2.6.1.jar) 
	UCHIJAAAA	tinker_io{alpha 2.4.0a} [Tinker I/O] (tinker_io-1.10.2-alpha 2.4.0a.jar) 
	UCHIJAAAA	WailaHarvestability{1.1.9} [Waila Harvestability] (WailaHarvestability-mc1.10.2-1.1.9.jar) 
	UCHIJAAAA	icse{1.1.0.0} [I Can See Everything] (Wawla-1.10.2-2.3.1.214.jar) 
	UCHIJAAAA	wawla{2.3.1.214} [What Are We Looking At] (Wawla-1.10.2-2.3.1.214.jar) 
	Loaded coremods (and transformers): 
SPFMLLoadingPlugin (soundphysics-mc1.10.2-v1.0.0.jar)
  com.sonicether.soundphysics.SoundPhysicsCore
FMLPlugin (InventoryTweaks-1.62-dev-66.jar)
  invtweaks.forge.asm.ContainerTransformer
EnderCorePlugin (EnderCore-1.10.2-0.4.1.60-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
CCLCorePlugin (CodeChickenLib-1.10.2-2.4.3.124-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.RenderHookTransformer
DepLoader (CodeChickenCore-1.10.2-2.3.5.91-universal.jar)
  
LoadingHook (Mekanism-1.10.2-9.2.1.295.jar)
  
	GL info: ' Vendor: 'Intel' Version: '4.4.0 - Build 21.20.16.4550' Renderer: 'Intel(R) HD Graphics 530'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- WailaIntegration (Enabled/Not Forced)

	EnderIO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker. Always check the stack trace above to see which mod is most likely failing.):
                  * Optifine is installed. This is NOT supported.
                 This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
	Detailed RF API diagnostics:
                  * RF API class 'EnergyStorage' is loaded from: jar:file:/D:/C/Minecarft%20Saves+maps/forge1.10.2/mods/Mekanism-1.10.2-9.2.1.295.jar!/cofh/api/energy/EnergyStorage.class
                  * RF API class 'IEnergyConnection' is loaded from: jar:file:/D:/C/Minecarft%20Saves+maps/forge1.10.2/mods/Mekanism-1.10.2-9.2.1.295.jar!/cofh/api/energy/IEnergyConnection.class
                  * RF API class 'IEnergyContainerItem' is loaded from: jar:file:/D:/C/Minecarft%20Saves+maps/forge1.10.2/mods/Mekanism-1.10.2-9.2.1.295.jar!/cofh/api/energy/IEnergyContainerItem.class
                  * RF API class 'IEnergyHandler' is loaded from: jar:file:/D:/C/Minecarft%20Saves+maps/forge1.10.2/mods/Mekanism-1.10.2-9.2.1.295.jar!/cofh/api/energy/IEnergyHandler.class
                  * RF API class 'IEnergyProvider' is loaded from: jar:file:/D:/C/Minecarft%20Saves+maps/forge1.10.2/mods/Mekanism-1.10.2-9.2.1.295.jar!/cofh/api/energy/IEnergyProvider.class
                  * RF API class 'IEnergyReceiver' is loaded from: jar:file:/D:/C/Minecarft%20Saves+maps/forge1.10.2/mods/Mekanism-1.10.2-9.2.1.295.jar!/cofh/api/energy/IEnergyReceiver.class
                  * RF API class 'IEnergyStorage' is loaded from: jar:file:/D:/C/Minecarft%20Saves+maps/forge1.10.2/mods/Mekanism-1.10.2-9.2.1.295.jar!/cofh/api/energy/IEnergyStorage.class
                  * RF API class 'ItemEnergyContainer' is loaded from: jar:file:/D:/C/Minecarft%20Saves+maps/forge1.10.2/mods/Mekanism-1.10.2-9.2.1.295.jar!/cofh/api/energy/ItemEnergyContainer.class
                  * RF API class 'TileEnergyHandler' is loaded from: jar:file:/D:/C/Minecarft%20Saves+maps/forge1.10.2/mods/Mekanism-1.10.2-9.2.1.295.jar!/cofh/api/energy/TileEnergyHandler.class
	Detailed Tesla API diagnostics:
                  * Tesla API class 'Tesla' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.Tesla)
                  * Tesla API class 'TeslaCapabilities' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.capability.TeslaCapabilities)
                  * Tesla API class 'ITeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaConsumer)
                  * Tesla API class 'ITeslaHolder' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaHolder)
                  * Tesla API class 'ITeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaProducer)
                  * Tesla API class 'BaseTeslaContainer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainer)
                  * Tesla API class 'BaseTeslaContainerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainerProvider)
                  * Tesla API class 'InfiniteTeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumer)
                  * Tesla API class 'InfiniteTeslaConsumerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumerProvider)
                  * Tesla API class 'InfiniteTeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducer)
                  * Tesla API class 'InfiniteTeslaProducerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducerProvider)

	Launched Version: 1.10.2-forge1.10.2-12.18.3.2185
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 530 GL version 4.4.0 - Build 21.20.16.4550, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz

**Comment by McJty** [comment]
It looks as if some item (outside of RFTools) is crashing because rftools is just trying to render a tooltip of one of those items. If you can find out what the item would be it might help to report to that mod author

**Comment by MichaelHillcox** [comment]
Thank you for taking the time to create this issue, as we're no longer supporting versions below `1.12`, I'm going to go ahead and close it but if this bug seems to continue over to newer versions, please do report it again so we can investigate the issue further.
