### ISSUE TITLE
Rftools Worldgen crash and how to disable it 

### ISSUE THREAD

**Issue by LukaPix** [McJtyMods/RFTools#1126]
Is there a Option to disable the generation of the Rftools village parts and / or anything else from rftools that could generate in the Overworld and if not could you please implement it ?

i want this because im crashing on village generation.
crash: [https://hastebin.com/ofozimetog.rb](https://hastebin.com/ofozimetog.rb)

**Comment by McJty** [comment]
I no longer work on the 1.7.10 version of rftools but the more important question is why this is crashing? Village generation with rftools has never been a problem before and RFTools is heavily used in 1.7.10. Is there perhaps another mod that causes conflicts?

**Comment by LukaPix** [comment]
the last mods i added before it crashed ware gregs SG craft, Minetweaker and ContentTweaker but the crash dosent give me anything else than rftools. Also besides the crash i am getting KnowDimletConfiguration errors but im pretty sure they are coming from Minetweaker.

**Comment by MichaelHillcox** [comment]
Close as 1.7.10 is no longer supported. If this continues to be a bug on 1.12 or newer, please open a new issue.
