### ISSUE TITLE
Crash on placing Powercell from Moving Wand with Mechanical User

### ISSUE THREAD

**Issue by Alex-hawks** [McJtyMods/RFTools#1128]
#### Versions:
MC: 1.10.2
Forge: 12.18.3.2254
CompatLayer: 1.10-0.2.5
Not Enough Wands: 1.5.4
Extra Utils 2: 1.10.2-1.3.3

#### Reproduction:
https://puu.sh/vbqgw/894a702f59.jpg
That was on a server I play on. I did reproduce it in a "Single Player" world to get the crash below. The only 2 important blocks are the Mechanical User and the Powercell. Moving wand works fine in a player's hand on a Powercell. Mechanical User has no problem placing Powercells

#### Crash Report:
https://gist.github.com/Alex-hawks/1138a8a6e1c0cda991109c1cac460a36

**Comment by MichaelHillcox** [comment]
Thank you for taking the time to create this issue, as we're no longer supporting versions below `1.12`, I'm going to go ahead and close it but if this bug seems to continue over to newer versions, please do report it again so we can investigate the issue further.
