### ISSUE TITLE
Creative Powercell can't be infused

### ISSUE THREAD

**Issue by aiun** [McJtyMods/RFTools#1129]
It will not be usable if injected into Creative Powercell

**Comment by aiun** [comment]
4000000/4000000rf 20000rf/t ⇒infused 100%⇒0/0rf 30000rf/t
I hope
4000000/4000000rf 20000rf/t ⇒infused 100%⇒4000000/4000000rf 30000rf/t

**Comment by McJty** [comment]
The creative powercell is not really meant be infusable really. It is creative. People can't craft it
