### ISSUE TITLE
Laggy dimensions

### ISSUE THREAD

**Issue by ghost** [McJtyMods/RFTools#1132]
I created my first dimension in my single-player playthrough.

The dimension is lagging uncontrollably: Mobs lag, blocks lag, and I can’t even eat food.

**Comment by McJty** [comment]
More info please. Sneak right click with dimension tab in hand and show me that info

**Comment by PapiDimmi** [comment]
I just created a random dimension.

![rftools dimensions papidim info](https://cloud.githubusercontent.com/assets/25916106/24827568/a006ac1a-1c4c-11e7-8413-bad6d1e66620.png)

**Comment by McJty** [comment]
What computer specs? Does it stay laggy if you wait? Did you try other dimensions?

**Comment by PapiDimmi** [comment]
I have a high-end computer. My FPS is high—this is lag, not frame rate issues. It stays laggy as long as I’m in the dimension. I haven’t tried other dimensions, but I’ll try it.

**Comment by MichaelHillcox** [comment]
Thank you for taking the time to create this issue, as we're no longer supporting versions below `1.12`, I'm going to go ahead and close it but if this bug seems to continue over to newer versions, please do report it again so we can investigate the issue further.
