### ISSUE TITLE
Optimize Shield Projectors in general

### ISSUE THREAD

**Issue by Brend-Smits** [McJtyMods/RFTools#1133]
Hello, 
On servers, whenever a player decides to change a setting on a large shield projector, it will lag the entire server. Dragging the TPS down from 20 to 5~ for about 5 seconds.
I think this is because it has to replace a large amount of block in a short period of time. 
Would it be possible to add a config option for server owners to decide the speed of which the shield projector replaces block? This way the lag will probably be lowered.
In the link included, you will see what is causing the lag whenever this happens: 
https://toastynetworks.net/rsampler.php?id=7703e98895964952bc77401786bb5858

Sponge:    Minecraft: 1.10.2
    SpongeAPI: 5.2.0-SNAPSHOT-a3257a0
    SpongeForge: 1.10.2-2254-5.2.0-BETA-2272
    Minecraft Forge: 12.18.3.2254
RFtools: rftools-1.1x-5.91
rftoolsctrl-1.1x-1.6.6
Modpack: FTB Beyond

**Comment by McJty** [comment]
This is unfortunatelly not very easy to implement. I'll think about it

**Comment by lAimBotl** [comment]
this will also look cooler :)

**Comment by MichaelHillcox** [comment]
Thank you for taking the time to create this issue, as we're no longer supporting versions below `1.12`, I'm going to go ahead and close it but if this bug seems to continue over to newer versions, please do report it again so we can investigate the issue further.
