### ISSUE TITLE
Blocks cant be quarried inside of Minecolonies boarders

### ISSUE THREAD

**Issue by djpanda** [McJtyMods/RFTools#1135]
RFTools Builderblock with Quarry Card can be placed but not able to remove any Block inside the colonyboarders

https://github.com/Minecolonies/minecolonies/issues/753#issuecomment-292717309

**Comment by McJty** [comment]
That's not something I can do much about I think

**Comment by djpanda** [comment]
The Builder are working the blocks up and lyer by leyer in his chunks but they didnt get removed in the world

**Comment by McJty** [comment]
The builder uses standard block breaking mechanics so if those are failing then something in minecolonies is most likely broken. Make sure you're using the latest version of RFTools because I *did* so some fixes related to that

**Comment by djpanda** [comment]
We are using rftools-1.1x-5.91.jar

**Comment by Terpo** [comment]
Just an update here: problem still exists. The builder can build stuff but can't break anything. 
compatlayer-1.11.2-0.2.9.jar
minecolonies-universal-1.11.2-0.8.3293.jar
rftools-1.1x-6.12.jar

**Comment by McJty** [comment]
This must be something on their side as the builder just use normal breaking mechanics

**Comment by MichaelHillcox** [comment]
Thank you for taking the time to create this issue, as we're no longer supporting versions below `1.12`, I'm going to go ahead and close it but if this bug seems to continue over to newer versions, please do report it again so we can investigate the issue further.

**Comment by djpanda** [comment]
Didnt tested it with the Quarry Card on newer versions but tried to place Blocks with the RF Builder and ShapeCard on minecolonies-0.11.776-ALPHA-universal.jar. Didnt worked as well on version. tried to add RFBuilder as Officer and it didnt change anything

**Comment by MichaelHillcox** [comment]
If you can test and it's still an issue then let us know in a new issue, I'm currently attempting to reduce the amount of old or stale issues so I'm closing anything that is "likely" to no longer be an issue with newer versions

**Comment by TheKrowi** [comment]
I was looking for the same problem when I stumbled upon this issue. It still exists and is reproducible by setting `B:enableColonyProtection=true` in minecolonies.cfg (or ingame through the mod options menu). I had this set to true by default. When putting it to false and trying to run the builder with the clearing shape card again actually removed the blocks.
