### ISSUE TITLE
Wireless storage loses power intermittently in low TPS situations

### ISSUE THREAD

**Issue by asteranx** [McJtyMods/RFTools#1150]
I've noticed this on several servers and in local games as well. In low TPS situations (anything less than 10-ish) the modular storage tablet with a wireless card linked to a wireless modular storage device will blink on and off while you have the tablet interface open, and print an error message to chat saying that the storage is out of range and/or out of power when you try interacting with it.

I've ensured that both the tablet and storage block have ample power, and verified the issue in both cross dimensional and standard access modes on the block.

I've seen this in prior versions of the mod as well (going back to infinity evolved when I really started (ab)using the tablet), but the version I'm currently experiencing it in is whatever version is part of skyfactory 3.0.8.

**Comment by electroCutie** [comment]
I am also having this issue

**Comment by Sakata-MC** [comment]
I'm getting this issue with 20TPS.  It also destroyed a few items when i was shift-clicking items into tablet.

**Comment by MichaelHillcox** [comment]
Thank you for taking the time to create this issue, as we're no longer supporting versions below `1.12`, I'm going to go ahead and close it but if this bug seems to continue over to newer versions, please do report it again so we can investigate the issue further.
