### ISSUE TITLE
Crafting recipe Ore Dictionary for environmental controller modules

### ISSUE THREAD

**Issue by Hazmatik** [McJtyMods/RFTools#1166]
In the changelog it for version rftools-1.1x-5.91 its says "In all crafting recipes (storage system, logic blocks, base blocks, screen modules, ...) ore dictionary crafting is now used for lapis lazuli, inksacs and chests" playing on the latest version of FTB Beyond using rftools-1.1x-5.92 the recipes for the environmental controller modules still require ink sacs and no other ore dictionary black dye will work.

**Comment by MichaelHillcox** [comment]
Thank you for taking the time to create this issue, as we're no longer supporting versions below `1.12`, I'm going to go ahead and close it but if this bug seems to continue over to newer versions, please do report it again so we can investigate the issue further.
