### ISSUE TITLE
[RFT Dimensions] Exception generating new chunk crash

### ISSUE THREAD

**Issue by KappaKiddie** [McJtyMods/RFTools#1170]
https://pastebin.com/u9sgjmLp

Every time someone logs in and tries to generate the world, the server crashes
Dimension type: Glowstone world
RFTools version: rftools-1.1x-6.00
RFToolsDim Version: rftoolsdim-1.1x-4.55
Forge Version: 12.18.3.2254

**Comment by McJty** [comment]
Can you *please* add more information. Just a crash log is not sufficient. I need versions, I need information on what you're doing. What kind of dimension. And so on.

**Comment by KappaKiddie** [comment]
Done :p

**Comment by McJty** [comment]
Also I notice you have sponge. Do you have a recent version? Because this could be a bug in sponge

**Comment by KappaKiddie** [comment]
I'm using the latest version for forge 2554

**Comment by MichaelHillcox** [comment]
Thank you for taking the time to create this issue, as we're no longer supporting versions below `1.12`, I'm going to go ahead and close it but if this bug seems to continue over to newer versions, please do report it again so we can investigate the issue further.
