### ISSUE TITLE
Manual crafting in modular storage GUI?

### ISSUE THREAD

**Issue by memotype** [McJtyMods/RFTools#1172]
I assume I'm doing something wrong, but for some reason, if I manually enter a crafting recipe in the crafting grid of a modular storage GUI, it won't let me craft that item unless I store it in one of the stored recipes. Seems like something so obvious, and yet I don't see any existing issue for it, so I have to assume I'm missing something obvious. And yet, it seems like it should just work.

For example. I grab a stack of wood planks with my mouse, and right-click-drag a chest recipe in the crafting grid. Then I click "1" to craft 1 chest and nothing happens. If I then click on an empty "'< Recipe >" slot, click "store" and then click "1" it works. Also, if I click the "+" from JEI, I can craft without having to store the recipe. Seems like I should be able to manually enter a recipe without having to store it or look it up in JEI...?

Edit: oh yeah, I also updated RFTools to 1.3.1 from the curseforge page. I added it to FTB Beyond and disabled the old version of RFTools. Minecraft version 1.10.2.

Edit 2: I have the same issue with the storage tablet.

**Comment by NillerMedDild** [comment]
I can confirm this is still happening.

**Comment by MichaelHillcox** [comment]
Thank you for taking the time to create this issue, as we're no longer supporting versions below `1.12`, I'm going to go ahead and close it but if this bug seems to continue over to newer versions, please do report it again so we can investigate the issue further.
