### ISSUE TITLE
Powercells: Stats numbers can overflow

### ISSUE THREAD

**Issue by Viper007Bond** [McJtyMods/RFTools#1174]
I'm using Powercells to transmit large amounts of RF. When the numbers get very large, they overflow to negative.

![2017-04-27_20 20 45](https://cloud.githubusercontent.com/assets/406254/25775575/1a324528-325d-11e7-84c2-227c717600bd.png)

v1.1x-5.88

**Comment by MichaelHillcox** [comment]
Thank you for taking the time to create this issue, as we're no longer supporting versions below `1.12`, I'm going to go ahead and close it but if this bug seems to continue over to newer versions, please do report it again so we can investigate the issue further.
