### ISSUE TITLE
All linked powercells lose link 1.11.2  1.1x-6.00

### ISSUE THREAD

**Issue by jjjworley** [McJtyMods/RFTools#1184]
Second time this has happened. I have two power sources powering two input powercells in a network of about fifteen powercells. Suddenly they become unlinked and lose all stored power. To restore the connections I have to open each powercell and reseat the linking card. When I reseat the first card and hover over the power meter, it reads 4 million rf. Reseating each successive card will add that powercell's rf amount to the total.

Also note that the powercells just stop working, and won't take power until the card is taken out and put back in (reseating).

Not sure if this crash report is related, but the report happened about the time that I lost all power.
https://1drv.ms/t/s!AiLDi1O4i24zhQu2mfKJXkWZZLdV

**Comment by McJty** [comment]
That crash seems unrelated. Very weird report though. Never seen that before. For now I have no idea what could have caused it

**Comment by McJty** [comment]
Note that powercell information is stored in a separate file (not in the world itself) (data/RFToolsPowerCellNetwork.dat). I hope you don't have anything external to MC that removes/changes/destroys that file?

**Comment by jjjworley** [comment]
If it happens again I will look at this file and see if it has changed. I am glad to know about this file, sometimes I lose one of my powercells and this file lists all the coordinates. Thank you for the best mods, I couldn't play 1.11.2 without them.

**Comment by MichaelHillcox** [comment]
Thank you for taking the time to create this issue, as we're no longer supporting versions below `1.12`, I'm going to go ahead and close it but if this bug seems to continue over to newer versions, please do report it again so we can investigate the issue further.
