### ISSUE TITLE
[1.10.2] Crash on load 

### ISSUE THREAD

**Issue by ErnestoPeroPezzi** [McJtyMods/RFTools#1190]
Hello, I am experiencing a crash on load after attaching a Weak Powercube to a Fancy Fluid Storage Metaphaser. 

https://pastebin.com/fqU4EBT6

I have also put the issue on that mods page, but the dev does not seem that active so I am taking my chances here as well. Note that it occured after I tried linking an empty cell with it

**Comment by McJty** [comment]
A bug in that mod. It is doing RF output client side and that's not legal. So yes, should be fixed at their side. Can you put the link to their ticket here?

**Comment by ErnestoPeroPezzi** [comment]
I apologize as I do not know what you mean by "ticket", but here is a link to their Github if anything:

https://github.com/Lordmau5/FFS/issues

**Comment by legodude17** [comment]
I believe they meant something like this:
Lordmau5/FFS#10

**Comment by McJty** [comment]
A ticket is a bug report. Like this one

**Comment by MichaelHillcox** [comment]
Thank you for taking the time to create this issue, as we're no longer supporting versions below `1.12`, I'm going to go ahead and close it but if this bug seems to continue over to newer versions, please do report it again so we can investigate the issue further.
