### ISSUE TITLE
Dimensional shard ore seems to be missing

### ISSUE THREAD

**Issue by ShadwDrgn** [McJtyMods/RFTools#1194]
In a dimension that seems to have normal worldgen, but no dimensional shards. I've quarried 245 chunks so far and gotten tons of diamonds, redstone, gold, lapis, and various other stuff. Even got a bunch of draconium. still no dimensional shards.

**Comment by Space-Fodder** [comment]
I have the same problem
Clean install
MC      1.12.2
Forge   14.23.4.2705
McjtLib 1.12-3.0.0
RFTools 1.12-7.50
RFTools Control 1.12-1.9.0
No other mods
Default configs , Builder with clearing silk touch card and no filters.
I just can't find any Dimensional shard ore

**Comment by josephcsible** [comment]
What seed?

**Comment by Space-Fodder** [comment]
I have tried multiple worlds, again with all defaults.
the latest seed is 5801756004949907066.

**Comment by McJty** [comment]
Where are you looking? Dimension Shard Ore does not spawn in the overworld. Only in the nether, the end and in RFTools Dimensions

**Comment by Space-Fodder** [comment]
Yes I am an idiot. ( Putting on Dunce hat and standing in the corner)
 The nether has Dimentional Shard Ore.

This mod is awesome.
Thank you
