### ISSUE TITLE
I.E. Concrete Slabs Not Picked Up By Builder

### ISSUE THREAD

**Issue by Darkosto** [McJtyMods/RFTools#1197]
Hello sir,

During some testing yesterday, I discovered the Concrete slabs from Immersive Engineering are deleted when using a Builder with a Quarry card installed. It will, however, pick up full Concrete Blocks (So, I don't believe I was voiding them). I tried 2 different cards and yielded the same result.

Is it possible this block could be allowed to be mined?

MC: 1.11.2
Forge: 2299
I.E.: 0.11-59-103
RFTools: 6.01

Thank you for your time!
Darkosto

**Comment by McJty** [comment]
Did you report it at IE as well as that sounds like a bug there. I use the normal break block methodology which should work for all blocks

**Comment by Darkosto** [comment]
Yep, I already spoke to Blu and he suspects it's not on his end.

**Comment by MichaelHillcox** [comment]
Thank you for taking the time to create this issue, as we're no longer supporting versions below `1.12`, I'm going to go ahead and close it but if this bug seems to continue over to newer versions, please do report it again so we can investigate the issue further.
