### ISSUE TITLE
crafter wont work as expected (lootbags crafting)

### ISSUE THREAD

**Issue by macqo004** [McJtyMods/RFTools#1202]
![2017-05-25 13_44_25-minecraft 1 7 10](https://cloud.githubusercontent.com/assets/4783435/26449122/c39a5c34-4150-11e7-885e-407774d389a7.jpg)
As you can see crafter wont put result in designed slot

**Comment by McJty** [comment]
Versions please!

Also can you explain the expected result a bit better?

**Comment by macqo004** [comment]
rftools-4.23
mc 1.7.10

**Comment by McJty** [comment]
Can you toggle between ext/int and see if that helps. Don't forget to press apply

**Comment by macqo004** [comment]
tried it already. nothing changes
rarely (like 1 in a 100 or so) i see bag landing in the correct slot (or it looks like it lands)

**Comment by McJty** [comment]
Is there something extracting from the crafter?

**Comment by macqo004** [comment]
when I do the next tier (legendary lootbag) it works fine (extracts)

**Comment by macqo004** [comment]
when I do the next tier (legendary lootbag) it works fine (extracts)
then i "forget" legendary recipe
then it for about 10 seconds extract epic lootbags (till my chest is full) and stops even if the chest is empty
