### ISSUE TITLE
space chamber crash when moving a sequencer

### ISSUE THREAD

**Issue by meson11** [McJtyMods/RFTools#1203]
rftools 6.0.1, ftb beyond 1.8.0

moving a sequencer causing a game crash. after starting the game again, the sequencer is moved correctly.
(I want to use this for an multiple endergenic generator, i figured out, at game start some generator setups don't work until the one of the sequencers are replaced. at the moment i realise this with block breaker and placer from actually additions and a xnet setting, but with the builder i could to it for all 25 stacked endergenerators i have at once)
[crash-2017-05-26_10.25.16-server.txt](https://github.com/McJty/RFTools/files/1031261/crash-2017-05-26_10.25.16-server.txt)

**Comment by meson11** [comment]
seems to be fixed in version 1.12 - 7.23

**Comment by McJty** [comment]
Why did you reopen this?

**Comment by meson11** [comment]
in verstion 1.12 - 7.32 in ftb revelation the issiue is there again
[crash-2018-04-19_12.49.21-server.txt](https://github.com/McJty/RFTools/files/1927798/crash-2018-04-19_12.49.21-server.txt)

**Comment by McJty** [comment]
I need more info. What are you doing exactly?

**Comment by meson11** [comment]
i made a space chamber around a line of 5 sequencers. so that 5 blocks are within the spacechamber. then move it with a builder. moving stone or stairs is working as it should. but triing it with sequencers the game is crashing
