### ISSUE TITLE
Question only - no issue

### ISSUE THREAD

**Issue by ktole1999** [McJtyMods/RFTools#1207]
I have a player that no longer plays on server but has left a world loaded. I have looked and cant seem to find the machinery. i tried to take ownership but failed. Is there a way to locate the source? This is 1.10.2

**Comment by McJty** [comment]
What do you want to do with the dimension? An admin can take ownership

**Comment by ktole1999** [comment]
i try to take ownership /rftfim setowner 2 bebobobo and it says player and dimension are incorrect. i also tried id:2 as well as dimension name and same error. i guess i am doing something wrong.

**Comment by MichaelHillcox** [comment]
Thank you for taking the time to create this issue, as we're no longer supporting versions below `1.12`, I'm going to go ahead and close it but if this bug seems to continue over to newer versions, please do report it again so we can investigate the issue further.
