### ISSUE TITLE
Shape card/builder crash when switching to hollow shapes

### ISSUE THREAD

**Issue by lAimBotl** [McJtyMods/RFTools#1210]
I shift r-clicked the builder clicked 2 points around 100 blocks from each other,
 and tried to swap to the sphere shape, but crashed.

 Confirmed in latest release

 Weird it did not give me a crash report,
 but it gave me a log thing in the main folder.
[Crash log thing.txt](https://github.com/McJty/RFTools/files/1036649/Crash.log.thing.txt)

**Comment by lAimBotl** [comment]
seems to have fixed itself.

**Comment by MichaelHillcox** [comment]
Thats a seg fault... thats bad but nothing useful found sorry. let us know if this happens again
