### ISSUE TITLE
[Request] "IntC" Output method for crafters

### ISSUE THREAD

**Issue by InjuredWolf** [McJtyMods/RFTools#1215]
Pam's HarvestCraft adds a recipe to turn water buckets into Fresh Water. I want to use the Fresh Water again for something internal, but need to have the bucket go in the output to be refilled. Is that a feature that can become a reality? Would basically work like ExtC, but with the locations swapped.
This is in 1.10.2.

**Comment by MichaelHillcox** [comment]
Thank you for taking the time to create this issue, as we're no longer supporting versions below `1.12`, I'm going to go ahead and close it but if this bug seems to continue over to newer versions, please do report it again so we can investigate the issue further.
