### ISSUE TITLE
[SpongeForge]Developers' Delight UI won't stay open on shift click

### ISSUE THREAD

**Issue by macks2008** [McJtyMods/RFTools#1218]
I can't seem to use the DD on interactive blocks (or at least not ones like Skyblock chests and Crafting Stations as I was hoping. Haven't tried on internal blocks, i.e. blocks from any of your mods). If I right-click the block's normal interface opens, and if I shift right-click, while the debugger interface opens, it instantaneously closes before I can actually use it or even read it. Am I doing something wrong here or something? I could've sworn it worked on a SkyChest from Applied Energistics 2 a while back
I am running this with spongeforge btw, so it might be that.

**Comment by macks2008** [comment]
anyone home?

**Comment by MichaelHillcox** [comment]
Unfortunately we're no longer supporting versions older than `1.12` and I don't have enough time to check this suggestion against all of the features of the mod but if this feature still hasn’t been implemented and you’d like to see it added to a newer version of the mod then please do create a new issue so we can review your suggestions again :+1:
