### ISSUE TITLE
1.10.2 Liquid Monitor not reading EnderIO Tanks

### ISSUE THREAD

**Issue by AnthonyKane5528X** [McJtyMods/RFTools#1219]
Hello McJty, 

Sorry to bother you with this, but apparently its still not fixed.  I tried reading an EnderIO Fluid Tank with an RFTools Liquid Monitor.   The liquid monitor cannot/will not see the Fluid Tank.  I tested it further by seeing if it would measure fluids in other "tanks", like a drum from Extra Utilities and it works just fine.

Here are the mod versions:
EnderCore 1.10.2-0.4.1.66
EnderIO 1.10.2-3.1.1.83
RFTools 1.1x-6.01

I know that there is ticket for a similar issue, and you said it had something to do with Null Stacks.  Also in that same ticket you said you had spoken with the EnderIO devs and that it would be fixed with their next release.  

Well I'm using a version of EnderIO that was released after that ticket.  So it should have been fixed.  But still the Liquid Monitor cannot see their fluid tank.

Let me know if you need me to report this to them.

Thanks, Anthony.

**Comment by MichaelHillcox** [comment]
Thank you for taking the time to create this issue, as we're no longer supporting versions below `1.12`, I'm going to go ahead and close it but if this bug seems to continue over to newer versions, please do report it again so we can investigate the issue further.
