### ISSUE TITLE
Issues while trying to lunch modded minecraft

### ISSUE THREAD

**Issue by Ventrylock** [McJtyMods/RFTools#1221]
Hi,
I'm having crash when i try to lunch minecraft with some mods. And it's apears that RFtools is the problem.
Here you can see the crash log.

[crash-2017-06-05_13.53.55-client.txt](https://github.com/McJty/RFTools/files/1052116/crash-2017-06-05_13.53.55-client.txt)

Thx for replying.
Ventrylock

**Comment by McJty** [comment]
Can you give me the versions of CompatLayer and McJtyLib?

**Comment by Ventrylock** [comment]
McJtyLib : 2.3.11
and i don't have CompatLayer. Is it wrong ?

**Comment by Ventrylock** [comment]
mcjtylib-1.1x-2.3.11
compatlayer-1.11.2-0.2.9

**Comment by McJty** [comment]
Actually closer inspection shows that the problem seems to be in IC2 as well. Seems like an incompatibility between RFTools and IC2. I'll see if I can solve this

**Comment by Ventrylock** [comment]
Ok thx you for replying so fast. I'm waiting for your answer :) !

**Comment by MagicBOTAlex** [comment]
i guess he gave up.
