### ISSUE TITLE
Crash when loading into any world

### ISSUE THREAD

**Issue by Breadabix** [McJtyMods/RFTools#1222]
When I try to add custom dimlets using https://github.com/McJty/RFTools/wiki/Adding-a-Dimlet , but when I try and load into a world I get 'A fatal error has occured, the connection has been terminated'. I am in minecraft 1.7.10 using version rftools-4.23.

**Comment by McJty** [comment]
I need to see a crashlog. Also show me exactly how you added the dimlet

**Comment by Breadabix** [comment]
I dont crash, just disconnected from the world. Also I didnt even add a dimlet, just the userdimlets.json.
I have tried changing it to CFG and I can join a world with no custom dimlets, just tried adding a dimlet to see if it works

**Comment by McJty** [comment]
Well show me what you added then. I cannot diagnose what I cannot see

**Comment by ktole1999** [comment]
so you are creating custom dimlets and sounds like the world is timing out while loading.

**Comment by Breadabix** [comment]
I was being a complete idiot, sorry guys. I Havnt done this before and have managed to make it work. This can be closed. Thanks

**Comment by ktole1999** [comment]
what was the resolution. could be useful to others that might come across this

**Comment by Breadabix** [comment]
I just didnt put the first and last square brackets into the file, 
![image](https://cloud.githubusercontent.com/assets/19786108/26807056/e7086fae-4a4b-11e7-8868-230692499da0.png)
Anyone who comes across this, make sure you dont miss anything like I did, it causes so much annoyance.

**Comment by ktole1999** [comment]
You should use notepad++ for code checking




Sent via the Samsung Galaxy S® 6, an AT&T 4G LTE smartphone


-------- Original message --------

**Comment by Breadabix** [comment]
I am using notepad++, but I just missed the first and last square brackets in the image to begin with.

**Comment by ktole1999** [comment]
Ahhh. Easy mistake



Sent via the Samsung Galaxy S® 6, an AT&T 4G LTE smartphone


-------- Original message --------
