### ISSUE TITLE
Redstone Module Disconnecting

### ISSUE THREAD

**Issue by ProxyPlayerHD** [McJtyMods/RFTools#1230]
I set a Redstone Modules to a Transmitter across my base to Display the status of my BR.
It worked very good until i disconnected and reconnected to the Server next day.
The Screen just read <invalid> and reconnecting the module to the Transmitter did nothing.
I had to relocate the transmitetr and then reconnect the Module for it to work Properly again, but i cannot do this everytime i come back on the server.

**Comment by McJty** [comment]
Versions?

**Comment by ProxyPlayerHD** [comment]
1.7.10-9.1.0.281

**Comment by MichaelHillcox** [comment]
Close as 1.7.10 is no longer supported. If this continues to be a bug on 1.12 or newer, please open a new issue.
