### ISSUE TITLE
Storage Scanner or Modular Storage crafting deletes items that are defined to give back on craft

### ISSUE THREAD

**Issue by davqvist** [McJtyMods/RFTools#1231]
MC 1.10.2
Forge 2316
RFTools 6.01

If you craft something that you are supposed to get back on craft (when using reuse() for example in CraftTweaker) then you don't get the item back.

Steps to reproduce:
1.) Add RFTools, IC2, JEI and CraftTweaker to instance
2.) Add following script to scripts folder: 
`recipes.addShaped(<ic2:jetpack:27>, [[<ic2:casing:3>, <ore:circuitBasic>, <ic2:casing:3>], [<ic2:casing:3>, <ic2:fluid_cell>, <ic2:casing:3>], [<minecraft:redstone>, <minecraft:elytra>.reuse(), <minecraft:redstone>]]);`
3.) Start Minecraft and world and place Modular Storage down with Redstone, Iron Item Casings, Universal Fluid Cells, Basic Circuits and one Elytra in it
4.) Use the Elytra recipe to craft the Jetpack
5.) Elytra is gone even though you are supposed to get it back.

**Comment by MichaelHillcox** [comment]
Thank you for taking the time to create this issue, as we're no longer supporting versions below `1.12`, I'm going to go ahead and close it but if this bug seems to continue over to newer versions, please do report it again so we can investigate the issue further.
