### ISSUE TITLE
Suggestion: Plane (not plain) Terrain type

### ISSUE THREAD

**Issue by therodet** [McJtyMods/RFTools#1237]
Terrain type similar to a super-flat world, but generating around Y=60, with a few even layers of the world material, and either no bedrock, or bedrock with random holes sandwiched between layers of said material.

**Comment by McJty** [comment]
But the flat terrain is already like that isn't it? I mean in rftools dimensions (you reported to the wrong mod btw)

**Comment by therodet** [comment]
Oops on the wrong mod bit...
And no, not like 'Flat' terrain. This would literally be only a few layers thick, and then void beneath so you could build above and below. This thought was inspired by some comments I came across regarding the Invertigo terrain.
