### ISSUE TITLE
[1.10.2][RFTools 6.01] Storage Scanner causing massive lag even while not scanning

### ISSUE THREAD

**Issue by wingertge** [McJtyMods/RFTools#1244]
I'm not sure what caused it to start after being fine for a long time, but since today the storage scanner causes a massive amount of tick lag even though it's not scanning for inventories or anything. See:

> [12:22:04] [EntityProfiler/INFO] [TickProfiler]:
> TPS: 1.6333333
>                           Single Entity | Time/Tick |      %
> StorageScannerTileEntity {-54,52,251}:0 |   603.067 | 98.369
>      TileExternalStorage {-64,57,247}:0 |     0.914 |  0.149
>      tile.TileController {-54,52,249}:0 |     0.732 |  0.119
>      TileExternalStorage {-71,52,247}:0 |     0.480 |  0.078
>        tile.TileExporter {-45,52,242}:0 |     0.402 |  0.066
>     Chunk | Time/Tick |      %
> 0: -4, 15 |   605.881 | 98.828
> 0: -5, 15 |     1.166 |  0.190
> 0: -2, 14 |     0.932 |  0.152
> 0: -4, 14 |     0.818 |  0.133
> 0: -3, 15 |     0.688 |  0.112
>     All Entities of Type | Time/Tick |      %
> StorageScannerTileEntity |   603.067 | 98.369
>      TileExternalStorage |     1.706 |  0.278
>      tile.TileController |     0.756 |  0.123
>        tile.TileExporter |     0.711 |  0.116
>   monster.EntitySkeleton |     0.429 |  0.070
>   Average Entity of Type | Time/tick | Calls
> StorageScannerTileEntity |   603.067 |    49
>      tile.TileController |     0.252 |   147
>      TileExternalStorage |     0.213 |   392
>   tileentity.TileGrinder |     0.112 |    49
>   monster.EntityEnderman |     0.104 |   192

There is no log output while running. I'm happy to do more debugging for any info you need.

**Comment by McJty** [comment]
Was there an update of any kind? Is there an item in the storage scanner input slot that it is trying to insert somewhere? Is the storage full? Is there automation inserting/extracting out of this?

I need more info

**Comment by wingertge** [comment]
Right, sorry. I always forget what kind of info you'd need to reproduce an issue. There was no update, but it was trying to insert an item into storage which was full. This shouldn't cause such an extreme amount of lag so I didn't think it was relevant. No automation was connected to it apart from a quick dump screen linked to the scanner. To be more specific about my setup, the range on the scanner was maxed out (20) and I used it to insert patterns into my Refined Storage autocrafting setup. The only inventories that were marked as routable were all those crafters (40-ish), with a ton of unrouted drawers and the likes.

**Comment by McJty** [comment]
It was probably relevant. If you have a really big storage system then this can be very slow as it will try to find room for that item constantly.

**Comment by McJty** [comment]
I may be able to solve this by putting a delay on this after it failed a few times

**Comment by wingertge** [comment]
I was going to suggest that too. I like to put at least a second delay in between expensive checks like that. Anyways glad I could help with my report :)

**Comment by MichaelHillcox** [comment]
Thank you for taking the time to create this issue, as we're no longer supporting versions below `1.12`, I'm going to go ahead and close it but if this bug seems to continue over to newer versions, please do report it again so we can investigate the issue further.
