### ISSUE TITLE
Redstone receiver stuck on channel -1

### ISSUE THREAD

**Issue by ToxicHutchyy** [McJtyMods/RFTools#1245]
Hi,

I'm trying to use the redstone transmitter and receiver but the receiver is stuck on channel -1, and wont link to the transmitter.

I have right clicked the receiver to the transmitter and still nothing.

**Comment by MichaelHillcox** [comment]
Thank you for taking the time to create this issue, as we're no longer supporting versions below `1.12`, I'm going to go ahead and close it but if this bug seems to continue over to newer versions, please do report it again so we can investigate the issue further.
