### ISSUE TITLE
[1.11.2] moving chests with builder

### ISSUE THREAD

**Issue by Terpo** [McJtyMods/RFTools#1246]
forge 2315
rftools 1.1x 6.01 (yeah, I'm not 100% up to date on the server ^^)
full modlist: http://blog.terpo.org/upload/mc/modlist.txt

What I did:
Set up a space chamber to move my whole house to a new place (~ 12 chunks away).
House did contain everything, including TEs and so on. 
The new area was completly cleaned by hand.
The house was not turned during the process.

When moving the house all normal block worked fine and it also moved vanilla chests. Well, the old vanilla chests are gone and the moved ones are empty. So the builder seems to eat chest content. All other TEs, including non vanilla chests did stay at the old place (was expecting that).

This happened in a server <-> client environment. Did not have the time to test it in SP again.

**Comment by MichaelHillcox** [comment]
Thank you for taking the time to create this issue, as we're no longer supporting versions below `1.12`, I'm going to go ahead and close it but if this bug seems to continue over to newer versions, please do report it again so we can investigate the issue further.
