### ISSUE TITLE
RFTools -> JEI Issues

### ISSUE THREAD

**Issue by Morbidcactus** [McJtyMods/RFTools#1248]
I posted [https://github.com/mezz/JustEnoughItems/issues/918](https://github.com/mezz/JustEnoughItems/issues/918) to the JEI github, having an odd issue with some recipes I autofill in a crafting card or a storage scanner using too many resources. The recipes themselves also display as using some items as stacks rather than single items.

I've noticed the recipe issue with several mods, not just ones from RFTools, just thought it may be worth posting this issue here as well.

![2017-06-29_14 20 07](https://user-images.githubusercontent.com/29522189/27703972-04eba1e2-5cd7-11e7-8ccc-5aecd003839a.png)
![2017-06-29_14 20 20](https://user-images.githubusercontent.com/29522189/27703973-04f58cca-5cd7-11e7-92e5-55b48b10bcbc.png)
![2017-06-29_14 20 31](https://user-images.githubusercontent.com/29522189/27703974-04f849d8-5cd7-11e7-8e1a-71e28258517c.png)
![2017-06-29_14 20 52](https://user-images.githubusercontent.com/29522189/27703975-04f815a8-5cd7-11e7-8b97-f28ac1f3f886.png)

**Comment by Famous5000** [comment]
Can you fix the URL to point to the correct link? It just points to url/ when clicked on via e-mail, but on Git returns a 404 error. There's a handy "Hyperlink" button <ctrl + K> that lets you insert the links without problem. [Like this.](https://github.com/mezz/JustEnoughItems/issues/918) [The text to replace is in brackets] (while the URL is inserted in the parentheses.)
