### ISSUE TITLE
how to manually unloade loaded dimensions

### ISSUE THREAD

**Issue by ktole1999** [McJtyMods/RFTools#1249]
I cant seem to find any command to unload a loaded dimension so i can sadedel. I am not using the very latest. using 5.92 for 1.10.2

21:35:33  [Info] Loaded: id:3, rftools_dimension
21:35:33  [Info] Loaded: id:2, rftools_dimension
21:35:33  [Info] Loaded: id:4, rftools_dimension
21:35:33  [Info] Loaded: id:5, rftools_dimension
21:35:33  [Info] Loaded: id:8, rftools_dimension
21:35:33  [Info] Loaded: id:11, rftools_dimension

**Comment by McJty** [comment]
Does safedel not work? It should unload them automatically

**Comment by ktole1999** [comment]
It says it can't delete while still in use. I have tried this on a fresh server restart and still can't.



Sent via the Samsung Galaxy S® 6, an AT&T 4G LTE smartphone


-------- Original message --------

**Comment by McJty** [comment]
I will have to look into this but later
