### ISSUE TITLE
right click powercell crash (1.11.2)

### ISSUE THREAD

**Issue by ilvinc3nt** [McJtyMods/RFTools#1251]
when i right click a powercell it crashes.

i think it depends on new thermal expansion (coFH Core that it requires forge 13.20.1.2388) or codeChiken (i updated it too).
So, i should remove that modes and try, but i'm sure it's gonna work good

this is the entire log:

https://pastebin.com/Bx3dU7wM

**Comment by McJty** [comment]
I will check this out. @mezz, this looks similar. What is going on?

**Comment by ilvinc3nt** [comment]
i have downgraded thermal (v. 5.2.4.8), forge (v. 13.20.0.2345) and CodeChikenLib (v. 2.7.0.268)  and i removed draconic and now everything works again.

i think the problem is releated to CodeChikenLib 3.0.0.274. it's required by draconic and thermal.

**Comment by mezz** [comment]
Nothing has changed in JEI related to this. 
The NPE is from here but I'm not sure which part of the chain is causing it:
https://github.com/McJty/McJtyLib/blob/1.11/src/main/java/mcjty/lib/container/GenericGuiContainer.java#L54

**Comment by McJty** [comment]
@ilvinc3nt What pack are you using btw?

**Comment by ilvinc3nt** [comment]
@McJty no pack here. they are my favorite mods all together (about 100 mods)

**Comment by KingLemming** [comment]
There is literally nothing in that log that points to CCL or CoFH anything in any way. Just putting that out there.

**Comment by McJty** [comment]
Yes, not putting the blame and I wasn't able to reproduce it with all of those mods anyway. The weird thing is that something is having access to one of my gui's but initGui() hasn't been called on it so it is not properly initialized. At this moment no idea what could cause that

**Comment by McJty** [comment]
I'm releasing a version of McJtyLib that protects against this and will log the error so that we can still try to track down the real problem. Probably a mod that does something wrong in a gui event or something

**Comment by tommyTT** [comment]
Hey there, I just saw this issue after I encountered it yesterday for myself. The problem seems to be with NEI. In the log below you can see the minimum amount of mods I have to install to reproduce this. It doesn't happen with your latest fix to McJtyLib. Hope this helps!

[Crash Log](https://gist.github.com/tommyTT/16d96ac0182bc1bd7d0f0f6c404c5cfe)

**Comment by covers1624** [comment]
Not sure how NEI could be at fault here, NEI doesn't hack up GuiContainer in 1.11 anymore, Its almost entirely event based..

**Comment by ilvinc3nt** [comment]
i've updated these mods (minecraft 1.11.2):
forge 13.20.1.2388
CodeChickenLib 3.0.0.274
CoFHCore 4.2.5.11
ThermalExpantion 5.2.5.11
ThermalDynamics 2.2.5.8
ThermalFoundation 2.2.4.8
RedstoneArsenal 2.2.4.6
mcjtylib 2.4.3

removed:
EnderStorage
NotEnoughItems

not tested
Draconic-Evolution (with BrandonsCore)

Now everything works again!!!
