### ISSUE TITLE
Question on powering dimensions

### ISSUE THREAD

**Issue by ConnorPr** [McJtyMods/RFTools#1256]
I have a quick question, can I power my dimension (named Main Base) from inside itself? Like if i was to put a Dimension Builder in it with its dimension tab while powering it, would it continue to charge and maintain itself? I'm only asking because I'm using Solar Panels in this dimension where it is always Noon, so I basically have limitless energy, I just need to know if I can harness that energy to make the dimension self-sustaining

**Comment by McJty** [comment]
Yes that should work
