### ISSUE TITLE
Porter does not properly carry data when upgrading.

### ISSUE THREAD

**Issue by Darkere** [McJtyMods/RFTools#1259]
Upgrading the Charged porter to advanced charged porter the destination is carried over. However, while right clicking with it still teleports you, the UI of the advanced porter shows no destinations.

Version 1.12 6.10 beta1

**Comment by MichaelHillcox** [comment]
Please re-open if this is still an issue for you as I don't have the time to test it myself and 1.12 is only getting bug fixes now
