### ISSUE TITLE
Game Crash on GUI open

### ISSUE THREAD

**Issue by Smtgr14** [McJtyMods/RFTools#1263]
**Issue:**
The game crashed whilst rendering screen
Error: java.lang.NullPointerException: Rendering screen

**Steps to Reproduce**
1) Load game
2) Load a New or Existing World
3) Place any RF Tools block w/ a GUI
4) Right click the block
5) Game will crash, server remains unaffected.

**Error Reported & Crash Report**
```
The game crashed whilst rendering screen
Error: java.lang.NullPointerException: Rendering screen
```
[crash-2017-07-03_09.25.15-client.txt](https://github.com/McJty/RFTools/files/1119872/crash-2017-07-03_09.25.15-client.txt)

**Comment by McJty** [comment]
@mezz Another one...

We're aware of this problem but atm it is eluding us

**Comment by McJty** [comment]
@Smtgr14 what modpack is this?

**Comment by McJty** [comment]
I'm releasing a version of McJtyLib that protects against this and will log the error so that we can still try to track down the real problem. Probably a mod that does something wrong in a gui event or something

**Comment by thiakil** [comment]
> Probably a mod that does something wrong in a gui event or something

Technically I wouldn't say it's "wrong", as the `InitGuiEvent.Pre` event is designed to be cancelled. Perhaps we need some clarification as to what Forge expects to happen after that event is cancelled? Essentially functions shouldn't be blindly expecting something set in initGui to be non-null I guess?

For reference:

	/**
	 * This event fires just after initializing {@link GuiScreen#mc}, {@link GuiScreen#fontRendererObj},
	 * {@link GuiScreen#width}, and {@link GuiScreen#height}.<br/><br/>
	 * 
	 * If canceled the following lines are skipped in {@link GuiScreen#setWorldAndResolution(Minecraft, int, int)}:<br/>
	 * {@code this.buttonList.clear();}<br/>
	 * {@code this.initGui();}<br/>
	 */

**Comment by ilvinc3nt** [comment]
i've updated these mods (minecraft 1.11.2):
forge 13.20.1.2388
CodeChickenLib 3.0.0.274
CoFHCore 4.2.5.11
ThermalExpantion 5.2.5.11
ThermalDynamics 2.2.5.8
ThermalFoundation 2.2.4.8
RedstoneArsenal 2.2.4.6
mcjtylib 2.4.3

removed:
EnderStorage 
NotEnoughItems

not tested
Draconic-Evolution (with BrandonsCore)

Now everything works again!!!

**Comment by Smtgr14** [comment]
I've started removing mods and found it's forestry's beta I left installed by mistake.
The updated McJtyLib does fix the issue.

**Comment by raoulvdberge** [comment]
Heh, I was also getting some NPEs in RS for fields that are initialized in `initGui`. Why in the world would that event be cancel-able?! `initGui` is the place where you initialize things...

**Comment by McJty** [comment]
Have you found out what mod is doing the canceling?

**Comment by raoulvdberge** [comment]
Nope.. I just added null guards.
