### ISSUE TITLE
Crash with RFTools 6.01 and RFTools 6.1 on MC 1.11.2

### ISSUE THREAD

**Issue by ghetta82** [McJtyMods/RFTools#1265]
I have a problem with minecraft 1.11.2 

LOG.TXT. it's my log that minecraft crash while loading.

LOG2.TXT it's my friend log that load minecraft without problem.

i tried to remove your lib, rftools and xnet and minecraft start without problem. Do u have any idea?

this is my spec:
1700 ryzen
32gb ram gskill
asrock K4 motherboard

[latest2.txt](https://github.com/McJty/RFTools/files/1123162/latest2.txt)

[latest.txt](https://github.com/McJty/RFTools/files/1123160/latest.txt)

**Comment by ghetta82** [comment]
Solved, was Afterbunner but i don't know why MC crash only with RFTools and afterbunner activated

**Comment by Kazzamkablam** [comment]
Weird issue, happens on 1.10.2 too but only with RFTools, no idea what's with that.

**Comment by MichaelHillcox** [comment]
Thank you for taking the time to create this issue, as we're no longer supporting versions below `1.12`, I'm going to go ahead and close it but if this bug seems to continue over to newer versions, please do report it again so we can investigate the issue further.
