### ISSUE TITLE
About Block Protector

### ISSUE THREAD

**Issue by Aknightofvoid** [McJtyMods/RFTools#1266]
the Block Protector can protect block by ender dragon 's hit?

**Comment by Aknightofvoid** [comment]
please help me！！！

**Comment by McJty** [comment]
Depends on the version of rftools and MC

**Comment by Aknightofvoid** [comment]
@McJty which version？

**Comment by McJty** [comment]
That is a question I should ask you. What version are you using?

**Comment by Aknightofvoid** [comment]
rftoolsdim-1.1x-5.02

**Comment by McJty** [comment]
it is the version of rftools that I need

**Comment by Aknightofvoid** [comment]
so，this version is ok？

**Comment by McJty** [comment]
I repeat my question:


it is the version of rftools that I need
--

**Comment by Aknightofvoid** [comment]
rftools-1.1x-6.01

**Comment by McJty** [comment]
yes, that version should be able to do it. Note that it cannot prevent the dragon from flying through them though

**Comment by Aknightofvoid** [comment]
sorry，i thought the Block Protector belong Rftoolsdim

**Comment by Aknightofvoid** [comment]
what meaning？

**Comment by Aknightofvoid** [comment]
the dragon flying the block is hit block，isn‘t it？

**Comment by McJty** [comment]
yes? I don't understand your question?

**Comment by Aknightofvoid** [comment]
Dragon fly through the block is not hit the  block?

**Comment by Aknightofvoid** [comment]
im chinese，so I'm a little bad English

**Comment by McJty** [comment]
The block protector will protect the blocks from being destroyed.
But it will not prevent the dragon flying through them

**Comment by Aknightofvoid** [comment]
oh，that is a bad information for me .
now minecraft version1.10.2 ,how to prevent the dragon flying through the block?

**Comment by McJty** [comment]
You can't. At least I don't know of any way to do that

**Comment by Aknightofvoid** [comment]
all right , thank you for answer my questions

**Comment by Aknightofvoid** [comment]
i also hava last question,the dying dragon ,fly to death in the middle，In this process，why the dragon can break the protected block ? but sometime cant？

**Comment by McJty** [comment]
hmm. Make sure it has enough power and don't protect too many blocks. The amount of power usage depends on the number of power and how much 'stress' the blocks get

**Comment by Aknightofvoid** [comment]
what is  'stress' the blocks ？

**Comment by McJty** [comment]
Put a lot of damage/destruction on them

**Comment by Aknightofvoid** [comment]
ok,i think you can add a function to the Block Protector，can protect the dragon flying through block

**Comment by McJty** [comment]
No I can't. I don't have any clue on how to do that

**Comment by Aknightofvoid** [comment]
hmm，that is too bad

**Comment by Aknightofvoid** [comment]
thank you for answer my questions

**Comment by Aknightofvoid** [comment]
you are friendly

**Comment by Aknightofvoid** [comment]
oh，maybe I understand the wrong your mean，your mean is the Block Protector can protect the block from the dragon fly to it and cant break the block，but the dragon can fly though block？

**Comment by Aknightofvoid** [comment]
if i have enough power

**Comment by McJty** [comment]
yes, the blocks should not get destroyed. But the dragon can still fly through them

**Comment by Aknightofvoid** [comment]
How much power

**Comment by Aknightofvoid** [comment]
Did you calculate it?

**Comment by McJty** [comment]
No I didn't really

**Comment by Aknightofvoid** [comment]
can you test it ？

**Comment by McJty** [comment]
I don't have the time. Why don't you test it?

**Comment by Aknightofvoid** [comment]
the Block Protector each size ，how much the most power input？

**Comment by Aknightofvoid** [comment]
Because I can't get the accurate numerical test, but you can

**Comment by McJty** [comment]
Check the rftools config file. There are several values there which explain how it works

**Comment by Aknightofvoid** [comment]
I'm afraid I can't，i am just a noob
