### ISSUE TITLE
[1.10.2] Block protector is not working with wither

### ISSUE THREAD

**Issue by GabrielR52** [McJtyMods/RFTools#1272]
The same block protector with all the selected blocks is not working with wither

**Comment by McJty** [comment]
How many blocks did you protect with it? Keep in mind that power usage is proportional to the number of blocks and the number of blocks getting damaged by the wither. Perhaps you are running out of power.

**Comment by GabrielR52** [comment]
There are 65 blocks selected, and even with a lot of energy the wither managed to break
http://imgur.com/lH847q3

And I can not break
http://imgur.com/n4lmFB5

**Comment by McJty** [comment]
65 blocks is too much. The problem is the energy spike that occurs when the wither is doing its projectiles. Two possible solutions: infuse the block protector so it is more efficient. Use two block protectors each protecting half of the blocks

**Comment by GabrielR52** [comment]
http://imgur.com/83m3SuZ
Now it has 64 blocks, I put 3 block protector with 20 blocks each, and 1 with the last 4 blocks, and it still did not work
http://imgur.com/eOv3TvN

**Comment by McJty** [comment]
How much RF/t is each protector getting?

**Comment by GabrielR52** [comment]
100 RF/t

**Comment by McJty** [comment]
That's not much

**Comment by GabrielR52** [comment]
The block protector is using 100 RF/t, but the output that the capacitor sends 150,000/t if the block needs

**Comment by McJty** [comment]
Um, well then I don't know. I use a single block protector for 20 or so blocks in my world for the wither and it works fine

**Comment by GabrielR52** [comment]
I'm using the 
compatlayer version: 1.10-0.2.9 
mcjtylib: 1.1x-2.4.3
Rftools: 1.1x-6.10 and the 
forge: 12.18.3.2185 is anything related to any of these mods?

Or did I do it wrong?
http://imgur.com/Gufw1fW

**Comment by GabrielR52** [comment]
If you can pass the version you are using for me to test

**Comment by GabrielR52** [comment]
Well I've got it, the only way is to spawn the wither in a 3x3 location or if not, it'll be able to break

**Comment by Eufranio** [comment]
Is your setup on a 3x3 or 3x1 area, @McJty?
