### ISSUE TITLE
Suggestion More uses to the book! in 1.12

### ISSUE THREAD

**Issue by winsrp** [McJtyMods/RFTools#1282]
Could it be that you can make the RFtools manual recipe show in the new minecraft 1.12 recipe book when you acquire redstone, or a book, and when you craft this book all the recipes to rftools get added? I read something about a custom knowledge book but not sure if that is something craftable? trying to not use JEI for recipes. tx

**Comment by Protheus** [comment]
I would love to see the RFTools Book in a Botania  way... All the items in the mod are AWESOME.. except teh book.. it is .. simple ;-)

**Comment by MichaelHillcox** [comment]
Simple but works! haha. There are a few suggestions for the book which I'll defer to. The in-game guide is normally up to date...
