### ISSUE TITLE
modular storage does not recognize dimlets

### ISSUE THREAD

**Issue by Turmfalke2** [McJtyMods/RFTools#1284]
hi,
So I am not exactly sure how it is supposed to work, given that all documentation available (like the wiki here) is completly outdated and the in game manual crashes me the moment I try to open it ( https://pastebin.com/qgefsUFx ). I found that the modular storage was made with the intention of providing a better way of storing dimlets and that it is supposed to have a module for grouping them ( https://github.com/McJty/RFTools/wiki/RFTools-Modular-Storage ). I can't find that module in JEI. However I found a generic item search module, but that completely fails to recognize the dimlets and just puts them all below the "unknown" headline.

It seems odd that you wouldn't even recognize your own items?

E: rftools-1.1x-5.92
    rftoolsdim-1.1x-5.02

**Comment by McJty** [comment]
Dimlets have changed a lot in 1.10 and later and some things haven't been reimplemented yet. Still on my todo

**Comment by MichaelHillcox** [comment]
Thank you for taking the time to create this issue, as we're no longer supporting versions below `1.12`, I'm going to go ahead and close it but if this bug seems to continue over to newer versions, please do report it again so we can investigate the issue further.
