### ISSUE TITLE
[Bug]Display text problems

### ISSUE THREAD

**Issue by along00852** [McJtyMods/RFTools#1313]
Can not display Chinese language [zh_tw.lang]

1.11.2-forge1.11.2-13.20.1.2421
compatlayer-1.11.2-0.2.9.jar
mcjtylib-1.1x-2.4.3.jar
rftools-1.1x-6.12.jar

**Comment by MichaelHillcox** [comment]
Thank you for taking the time to create this issue, as we're no longer supporting versions below `1.12`, I'm going to go ahead and close it but if this bug seems to continue over to newer versions, please do report it again so we can investigate the issue further.
