### ISSUE TITLE
Blacklisted dimlets

### ISSUE THREAD

**Issue by MelanX** [McJtyMods/RFTools#1320]
Hi, I'm playing RFTools 1.1x-6.12 on Minecraft 1.10.2 with Forge version 12.18.3.2422 and have blacklisted dimlets. I don't know where I can whitelist these dimlets. I just need the 'Normal Day' dimlet but cannot use it. Am I doing something wrong? I didn't edit anything in the configs. Maybe because it's my own modpack and other mods blacklisted this (and other) dimlets? I would be very happy if you can help me. 

If you need an image: 
![2017-08-03_19 59 20](https://user-images.githubusercontent.com/26039509/28935903-45ad2596-7886-11e7-9d47-62d9b082d5fa.png)

**Comment by MichaelHillcox** [comment]
Thank you for taking the time to create this issue, as we're no longer supporting versions below `1.12`, I'm going to go ahead and close it but if this bug seems to continue over to newer versions, please do report it again so we can investigate the issue further.
