### ISSUE TITLE
[RFTools-1.1x-6.12.jar] [1.11.2] RFTools Advanced Porter - When you teleport people cannot see you.

### ISSUE THREAD

**Issue by Sammu2188** [McJtyMods/RFTools#1340]
I'm not sure if somebody has submitted this already, but the situation is that when I teleport using the Advanced Charged Porter, they cannot see me. I've had this situation multiple times and it's getting tiring to relog every time someone says "I cannot see you".
- Why do I think it's the charged porter? I'm the only one using the porter in the server and in the past, I have given everyone a Charged Porter themselves but after that, it has become more of a problem. From my experience, the Matter Transmitter works perfectly fine and does not turn the player invisible.
- Could it be server lag? Possibly, but not likely as my server has been perfectly fine and no errors have occurred like,

> Can't keep up! - skipping 50 ticks

 Or something like that whenever teleporting.
- I can show you server mods and the 'bat' startup. Maybe that will help.
![modslist1](https://user-images.githubusercontent.com/8924258/29544389-a2a0f420-869c-11e7-93a5-e4130a543d31.PNG)
![modslist2](https://user-images.githubusercontent.com/8924258/29544391-a2a85724-869c-11e7-94a3-18450f008dcc.PNG)
![serverbat](https://user-images.githubusercontent.com/8924258/29544390-a2a302ce-869c-11e7-96c5-09ac876784cc.PNG)

I could be wrong so correct me if you can.

Edit: I almost forgot about the effects this has - https://youtu.be/3YtN-QIzElg

**Comment by McJty** [comment]
Very strange though as the matter transmitter and charged porter use exactly the same teleportation code

**Comment by Milletus** [comment]
I experienced the same issue. We were playing on lan and the same thing happened. Was only resolved by logging out and restarting the host world

**Comment by MichaelHillcox** [comment]
Thank you for taking the time to create this issue, as we're no longer supporting versions below `1.12`, I'm going to go ahead and close it but if this bug seems to continue over to newer versions, please do report it again so we can investigate the issue further.
