### ISSUE TITLE
[suggestion] Saving structure to shape card for builder

### ISSUE THREAD

**Issue by winsrp** [McJtyMods/RFTools#1341]
Well, long story short, it would be great to save schematics for the builder on the shape cards, so I can copy building I see on the map (with so many mods generating stuff, this is a nice feature to have), and it would give a better use to shape cards, you only need like 1 or 2 at most over the curse of the game.

**Comment by Darkere** [comment]
You can already do this. It's just not quite as cheap as a shape card as you need make the 8 space chamber blocks and the space chamber card(and a wrench...).

**Comment by winsrp** [comment]
not really since if you take the space chambers blocks out then the structure will no longer copy. The idea is to have the shape cards contain the copied layout so you can move the space chambers somewhere else and copy another structure and so on. and when you want to paste a structure, then you just take out the corresponding shape card put it in a builder and you can have your structure where you want it.

**Comment by UncleOwen** [comment]
I would also like this feature.

My use case: I'd like to automate [creating compact](https://github.com/thraaawn/CompactMachines) machines inside a compact machine. For this I don't have space to build the structure twice.

**Comment by UncleOwen** [comment]
I just found the scanner which is pretty much exactly what I need. So ignore my previous comment. Great mod and sorry for the noise!
