### ISSUE TITLE
[1.10.2] Elevator cannot use painted blocks from Ender IO

### ISSUE THREAD

**Issue by moosedrop907** [McJtyMods/RFTools#1343]
Not sure if this is fixed in later versions, or even if you care much about mod compatibility, but I am unable to make my elevator platform out of painted blocks from Ender IO. I've tested it with multiple kinds of blocks from vanilla, RF tools, and Ender IO, and they work just fine so long as they are not painted. 

Thanks!

**Comment by McJty** [comment]
Well getting compatibility for painted blocks from EnderIO is probably going to be rather hard

**Comment by MichaelHillcox** [comment]
Unfortunately we're no longer supporting versions older than `1.12` and I don't have enough time to check this suggestion against all of the features of the mod but if this feature still hasn’t been implemented and you’d like to see it added to a newer version of the mod then please do create a new issue so we can review your suggestions again :+1:
