### ISSUE TITLE
[1.10.2] Builder block crashes server/minecraft client while moving Item conduit

### ISSUE THREAD

**Issue by zylkowski** [McJtyMods/RFTools#1344]
Builder block crashes server/minecraft client while moving Item conduit(Ender IO) with filter in it.

**Comment by McJty** [comment]
Logs please

**Comment by MachoPikacho** [comment]
Wow that was fast here you go: https://pastebin.com/H5P4AxGa

**Comment by DJ411** [comment]
I'm using the Builder Block and its doing this to my energy conduits. [https://gyazo.com/af1f84fd1438dc585117b8f99109e51c](url) I'm on a server and its not crashing. They look like this while coping or moving back.

**Comment by MichaelHillcox** [comment]
Thank you for taking the time to create this issue, as we're no longer supporting versions below `1.12`, I'm going to go ahead and close it but if this bug seems to continue over to newer versions, please do report it again so we can investigate the issue further.
