### ISSUE TITLE
Client crash when clicking `?` (guide) icon in dialing device

### ISSUE THREAD

**Issue by JaSpr** [McJtyMods/RFTools#1346]
#Versions: 
Age of Engineering 1.0.5
Minecraft 1.10.2
FML 12.18.3.2422

RFTools 1.1x-5.9.2
RFTools Controls 1.1x-1.6.8
RFTools Dimensions 1.1x-5.04
McJtyLib 1.1x-2.4.3
MCP 9.32

Clicked the `?` icon to read the guide and the client immediately crashed...

[Crash Log](https://gist.github.com/JaSpr/e7cec9b94a3fcc20059af00da59d60cd)

**Comment by JaSpr** [comment]
Just duplicated.

**Comment by McJty** [comment]
The manual in AoE is broken and that's known. If only I knew why...

**Comment by MichaelHillcox** [comment]
Thank you for taking the time to create this issue, as we're no longer supporting versions below `1.12`, I'm going to go ahead and close it but if this bug seems to continue over to newer versions, please do report it again so we can investigate the issue further.
