### ISSUE TITLE
Problem whith ID (1.7.10)

### ISSUE THREAD

**Issue by dalexBob** [McJtyMods/RFTools#1347]
Hello, I have a problem:
I have delet a lot of dimension whith /safedel and when I want to create a new dimension, I have a ID from a hold dimension and in the dialing device I don't see the new dimension. Have you got an idea?
(sorry for the mistakes of hortograph, I'm not english)

**Comment by McJty** [comment]
Are you using different dimlets?

**Comment by dalexBob** [comment]
Hello,Yes I use different dimlets.


Envoyé depuis mon appareil mobile Samsung.

-------- Message d'origine --------
De : McJty <notifications@github.com> 
Date : 29/08/2017  12:07  (GMT+01:00) 
À : McJty/RFTools <RFTools@noreply.github.com> 
Cc : dalexBob <alexandre.delaurie@free.fr>, Author <author@noreply.github.com> 
Objet : Re: [McJty/RFTools] Problem whith ID (1.7.10) (#1347) 

Are you using different dimlets?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/McJty/RFTools","title":"McJty/RFTools","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/McJty/RFTools"}},"updates":{"snippets":[{"icon":"PERSON","message":"@McJty in #1347: Are you using different dimlets?"}],"action":{"name":"View Issue","url":"https://github.com/McJty/RFTools/issues/1347#issuecomment-325618198"}}}

**Comment by McJty** [comment]
Can you describe exactly what you're doing and what is happening? I'm not fully understanding the problem

**Comment by dalexBob** [comment]
I have a minecraft's savegame and I had 56 rftools dimensions, I used /safedel and /deldim to reduce the number of  dimensions. After, I made a new rftools dimension, she has an ID and this ID was an old dimension and in the dialing device she not appear and now when I use /help I have an error.

-------- Message d'origine --------
De : McJty <notifications@github.com> 
Date : 29/08/2017  13:32  (GMT+01:00) 
À : McJty/RFTools <RFTools@noreply.github.com> 
Cc : dalexBob <alexandre.delaurie@free.fr>, Author <author@noreply.github.com> 
Objet : Re: [McJty/RFTools] Problem whith ID (1.7.10) (#1347) 

Can you describe exactly what you're doing and what is happening? I'm not fully understanding the problem

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/McJty/RFTools","title":"McJty/RFTools","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/McJty/RFTools"}},"updates":{"snippets":[{"icon":"PERSON","message":"@McJty in #1347: Can you describe exactly what you're doing and what is happening? I'm not fully understanding the problem"}],"action":{"name":"View Issue","url":"https://github.com/McJty/RFTools/issues/1347#issuecomment-325636093"}}}

**Comment by McJty** [comment]
Well it is normal that you get the old ID's as they are reused.  Can you give me some logs and the exact error you get?

**Comment by dalexBob** [comment]
I'm sorry but I just watch and there is more error but I do not understand how do we get back the visible dimension in the dialing device.


Envoyé depuis mon appareil mobile Samsung.

-------- Message d'origine --------
De : McJty <notifications@github.com> 
Date : 29/08/2017  14:57  (GMT+01:00) 
À : McJty/RFTools <RFTools@noreply.github.com> 
Cc : dalexBob <alexandre.delaurie@free.fr>, Author <author@noreply.github.com> 
Objet : Re: [McJty/RFTools] Problem whith ID (1.7.10) (#1347) 

Well it is normal that you get the old ID's as they are reused.  Can you give me some logs and the exact error you get?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/McJty/RFTools","title":"McJty/RFTools","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/McJty/RFTools"}},"updates":{"snippets":[{"icon":"PERSON","message":"@McJty in #1347: Well it is normal that you get the old ID's as they are reused.  Can you give me some logs and the exact error you get?"}],"action":{"name":"View Issue","url":"https://github.com/McJty/RFTools/issues/1347#issuecomment-325655138"}}}

**Comment by McJty** [comment]
I need logs

**Comment by dalexBob** [comment]
I'm sorry but what is the log?It's the save?


Envoyé depuis mon appareil mobile Samsung.

-------- Message d'origine --------
De : McJty <notifications@github.com> 
Date : 29/08/2017  15:23  (GMT+01:00) 
À : McJty/RFTools <RFTools@noreply.github.com> 
Cc : dalexBob <alexandre.delaurie@free.fr>, Author <author@noreply.github.com> 
Objet : Re: [McJty/RFTools] Problem whith ID (1.7.10) (#1347) 

I need logs

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/McJty/RFTools","title":"McJty/RFTools","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/McJty/RFTools"}},"updates":{"snippets":[{"icon":"PERSON","message":"@McJty in #1347: I need logs"}],"action":{"name":"View Issue","url":"https://github.com/McJty/RFTools/issues/1347#issuecomment-325662191"}}}

**Comment by McJty** [comment]
You can find logs in the minecraft logs folder. That's where all crashes and problems are logged

**Comment by dalexBob** [comment]
This day, I have 4 logs 

 

De : McJty [mailto:notifications@github.com] 
Envoyé : mardi 29 août 2017 15:38
À : McJty/RFTools
Cc : dalexBob; Author
Objet : Re: [McJty/RFTools] Problem whith ID (1.7.10) (#1347)

 

You can find logs in the minecraft logs folder. That's where all crashes and problems are logged

**Comment by McJty** [comment]
Yes I need the last one where you tried to create a dimension

**Comment by dalexBob** [comment]
As I did not know when I created a new one.

 

De : McJty [mailto:notifications@github.com] 
Envoyé : mardi 29 août 2017 15:50
À : McJty/RFTools
Cc : dalexBob; Author
Objet : Re: [McJty/RFTools] Problem whith ID (1.7.10) (#1347)

 

Yes I need the last one where you tried to create a dimension

**Comment by dalexBob** [comment]
Have you found something interesting?

**Comment by DeFazer** [comment]
I think that without a log there isn't much interesting to find - the problem is quite obscure and hard to replicate without additional information. Maybe you could just attach all the logs there are?
(I'm not a developer of RFTools or affiliated with them in any way, just trying to help.)

**Comment by dalexBob** [comment]
You want all logs since when I started the save?


Envoyé depuis mon appareil mobile Samsung.

-------- Message d'origine --------
De : DeFazer <notifications@github.com> 
Date : 12/09/2017  03:02  (GMT+01:00) 
À : McJty/RFTools <RFTools@noreply.github.com> 
Cc : dalexBob <alexandre.delaurie@free.fr>, Author <author@noreply.github.com> 
Objet : Re: [McJty/RFTools] Problem whith ID (1.7.10) (#1347) 

I think that without a log there isn't much interesting to find - the problem is quite obscure and hard to replicate without additional information. Maybe you could just attach all the logs there are?

(I'm not a developer of RFTools or affiliated with them in any way, just trying to help.)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/McJty/RFTools","title":"McJty/RFTools","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/McJty/RFTools"}},"updates":{"snippets":[{"icon":"PERSON","message":"@DeFazer in #1347: I think that without a log there isn't much interesting to find - the problem is quite obscure and hard to replicate without additional information. Maybe you could just attach all the logs there are?\r\n(I'm not a developer of RFTools or affiliated with them in any way, just trying to help.)"}],"action":{"name":"View Issue","url":"https://github.com/McJty/RFTools/issues/1347#issuecomment-328700605"}}}

**Comment by dalexBob** [comment]
you want the logs since I started my game?

 

De : DeFazer [mailto:notifications@github.com] 
Envoyé : mardi 12 septembre 2017 03:02
À : McJty/RFTools
Cc : dalexBob; Author
Objet : Re: [McJty/RFTools] Problem whith ID (1.7.10) (#1347)

 

I think that without a log there isn't much interesting to find - the problem is quite obscure and hard to replicate without additional information. Maybe you could just attach all the logs there are?
(I'm not a developer of RFTools or affiliated with them in any way, just trying to help.)

**Comment by McJty** [comment]
Not sure if logs will help here. In fact not sure what I can do about this at this stage. The 1.7.10 version of the mod is no longer in development. What about new dimensions? Do these work? Or does every dimension simply fail? If every dimension fails then a log when you are attempting to create a dimension would help

**Comment by dalexBob** [comment]
Hello,

I sent you a mail with a log and a document, do you have receive this one?

If you received the mail, did you find something?

 

De : McJty [mailto:notifications@github.com] 
Envoyé : mercredi 13 septembre 2017 19:05
À : McJty/RFTools
Cc : dalexBob; Author
Objet : Re: [McJty/RFTools] Problem whith ID (1.7.10) (#1347)

 

Not sure if logs will help here. In fact not sure what I can do about this at this stage. The 1.7.10 version of the mod is no longer in development. What about new dimensions? Do these work? Or does every dimension simply fail? If every dimension fails then a log when you are attempting to create a dimension would help

**Comment by McJty** [comment]
Hmm. No I did not get that. You can mail me directly at mcjty1@gmail.com
Note however that I'm not sure I will be able to do much about this and I also no longer work on the 1.7.10 version of rftools

**Comment by MichaelHillcox** [comment]
Close as 1.7.10 is no longer supported. If this continues to be a bug on 1.12 or newer, please open a new issue.
