### ISSUE TITLE
Text missplacing [Low priority]

### ISSUE THREAD

**Issue by TheSnowyChickens** [McJtyMods/RFTools#1348]
I use the newest version from Forge / RFTools / RFTools Dim (30.08.2017)

![grafik](https://user-images.githubusercontent.com/29357962/29892606-796db270-8dcf-11e7-985f-4f1690dbdeeb.png)
 
I think you see the problem (the text over my inventory :) ) . I have the GUI on "Large" in the options , the picture is in "normal" ,because the resolution.
I have a Elevator button installed.

**Comment by DeFazer** [comment]
Having the same issue, and it persists at all GUI scale levels from "Small" to "Auto". I have Optifine installed, though; maybe it's somehow related, although I'm pretty sure it doesn't change anything in GUI rendering.

**Comment by MichaelHillcox** [comment]
Thank you for taking the time to create this issue, as we're no longer supporting versions below `1.12`, I'm going to go ahead and close it but if this bug seems to continue over to newer versions, please do report it again so we can investigate the issue further.
