### ISSUE TITLE
No dragons spawning in dragon dimension

### ISSUE THREAD

**Issue by cps9716** [McJtyMods/RFTools#1349]
I created a dimension with a ender dragon dimlet, and it spawned 1 ender dragon.  No more dragons spawned after that, and no ender dragons will spawn no matter how many dimensions I create and no matter what dimlet combination I use.  I'm at a loss, and would really appreciate some advice.  Thank you!

**Comment by McJty** [comment]
Versions please

**Comment by cps9716** [comment]
I'm playing Sky Factory 3 ver. 3.013 (Minecraft ver. 1.10.2 (modded) forge-12.18.3.2316,  RFTools Dimensions ver. 1.12)

**Comment by cps9716** [comment]
The specific .jar file is 1.1x-5.02.jar

**Comment by McJty** [comment]
Very strange. I've seen others do this with succes (like DireWolf20) so no idea what could be wrong...

**Comment by cps9716** [comment]
I also tried breaking the Dialer Device, Matter Transmitters/Recievers, etc. to try and fix the issue, to no avail.  Is it possible that making a new ender dragon dimlet could solve the issue?  Also, could having Optifine installed be a potential issue?

**Comment by McJty** [comment]
I have no clue.

BTW. Next time please report to the correct mod. Dimensions are in the RFTools Dimensions mod

**Comment by MichaelHillcox** [comment]
Thank you for taking the time to create this issue, as we're no longer supporting versions below `1.12`, I'm going to go ahead and close it but if this bug seems to continue over to newer versions, please do report it again so we can investigate the issue further.
