### ISSUE TITLE
[1.12.1] Dimension suddenly goes missing

### ISSUE THREAD

**Issue by llloyd4** [McJtyMods/RFTools#1353]
So, I created a dragon dimension. Was working just fine but today I accidentally stepped on the teleporter and it said "Something wrong with the destination!" and I am like "O.o", so I peek at the dialer and it's not listed. I peek at the Dimension Builder, it shows the tab is still there, mousing over the tab it says "Dimension Ready to Use" , shows 40,000,000 RF and holding pretty steady there. So with a fully charged phase field generator on the hot bar, my DE Advanced Dislocator set to Home by default, I use it to teleport to the dimension. All I see is a large purple and black checker in front of me and the  Journymap mini map goes from showing what I remember of the dimension to a large black splot that covers most of it. I dug up some /rftdim commands, but /rftdim recover 2  , the id of the world is 2, returns 'Unknown RfTools command: recover" . So I decide to rebuild it, it's only 40 MRf, so I deconstruct the dimlet in the Dimensional Inscriber to recover the ultra valuable mob dimlet ender_dragon and type /rftdim safedel 2 , returns the error that the dimension is still in use. O.o As this is a single player world and I am in the overworld, eh? O.o So I am stuck at this point, do I need to delete the dim2 folder out of the save folder and restart?

**Comment by McJty** [comment]
Well dragons destroy everything in their path so it is likely the matter receiver was removed by a dragon.

Otherwise no idea what went wrong there. Very strange. I recommend restoring from a backup

**Comment by llloyd4** [comment]
Yeah that's why I make a teleport destination with the Advanced Dislocator.
That lets me pop in even with the matter transmitter gone. Restore? Ok. As
I deleted the DIM2 folder and remade it and no go.

**Comment by McJty** [comment]
BTW. Please report dimension problems to the right mod (RFTools Dimensions is a separate mod)

**Comment by llloyd4** [comment]
Oh! Apologies. >.<
