### ISSUE TITLE
request shield generator 

### ISSUE THREAD

**Issue by Varg95** [McJtyMods/RFTools#1364]
i would like to ask to make the shield projector Opaque so that it renders the blocks next too it. I ask cuz i made custom model for it and now it looks a bit weird. furthermore its not really a building block so it shouldn't  make difference in performance. it could be a config option too. 

Anyway thanks for your time.  
a friendly supporter

**Comment by McJty** [comment]
Can you explain what you mean? I don't understand

**Comment by Varg95** [comment]
![2017-09-12_16 56 40](https://user-images.githubusercontent.com/23167416/30332792-88dfa536-97db-11e7-925d-aaadb4d866c0.png)
Okay yours is the one on the left is the shield projector of your mod as you can see it doesn't show the block behind it. the one on the right is the same model but does show the block behind it. I understand you cant make all blocks like that but cuz this isn't a building block it shouldn't be a big problem.

**Comment by McJty** [comment]
That doesn't look like a screen projector from my mod. In fact I have never seen that block before.  Wrong mod?

**Comment by McJty** [comment]
Ah sorry you made a custom model . I missed that

**Comment by Varg95** [comment]
sorry i should have stated it more clearly

**Comment by josephcsible** [comment]
I don't think this is supported even by vanilla blocks. I think that if you were to, for example, replace vanilla cobblestone with this model, the same thing would happen. Performance would tank if what was behind every block had to be rendered, just in case one of them was customized to not be solid anymore.
