### ISSUE TITLE
Something seriously wrong here; multiple issues

### ISSUE THREAD

**Issue by thelapisfox** [McJtyMods/RFTools#1366]
MC Version: 1.10.2
Modpack: DW20 v.1.12.1
RFTools Version: 6.01 & 6.13

At first I thought this was a Refined Storage issue but since I am not experiencing issues with multiple mods, my only conclusion is that this is being caused by RFTools. Here are my issues;

I had no problems at all until I moved to an RFTools void dim. From the very moment I moved my refined storage and opencomputers systems into the new dim, issues began;

1) Refined Storage: Controller breaks constantly; So does all Importers. I have to break and replace them constantly;
2) OpenComputers: I have an OpenComputer set up to control my reactors and turbines and every time I teleport into the dim, the computer breaks. It doesn't matter if it is running or not, but the hard drives within the computer get reset to a new id. This breaks the filesystem as it is no longer looking in the right place (i.e. before leaving the dim, the id/folder is listed as 37d642f7-8e32-4182-86dc-3062e4115e1f. When I return to the dim, the id/folder is now listed as 0619f96d-ecf0-41cf-93a1-668d7b039b85).

This has made my save completely unplayable and I have spent months getting to where I am. As I said, I am pretty sure this is a problem with RFTools as the problems did not start until I moved into the dim and multiple mods are being affected. Also, keep in mind these are just the ones I have noticed. There might be other issues that I have not seen.

EDIT: I decided to look at the forge log before submitting this (I checked before and found nothing), I am now noticing some errors cropping up.

`[11:50:47] [ic2-poolthread-8/WARN]: Tile com.raoulvdberge.refinedstorage.integration.ic2.ControllerEnergyIC2$1@578f0571 (dim 6: 11/65/-16) removal without registration
[11:50:47] [Server thread/WARN]: Tile com.raoulvdberge.refinedstorage.integration.ic2.ControllerEnergyIC2$1@5fa4dfae (dim 6: 11/65/-16) was invalidated in grid update (ADDITION)
[11:50:47] [ic2-poolthread-10/WARN]: Tile com.raoulvdberge.refinedstorage.integration.ic2.ControllerEnergyIC2$1@5fa4dfae (dim 6: 11/65/-16) removal without registration
[11:50:48] [Server thread/WARN]: Tile com.raoulvdberge.refinedstorage.integration.ic2.ControllerEnergyIC2$1@16e98d9b (dim 6: 11/65/-16) was invalidated in grid update (ADDITION)
[11:50:48] [ic2-poolthread-12/WARN]: Tile com.raoulvdberge.refinedstorage.integration.ic2.ControllerEnergyIC2$1@16e98d9b (dim 6: 11/65/-16) removal without registration
[11:50:48] [Server thread/WARN]: Tile com.raoulvdberge.refinedstorage.integration.ic2.ControllerEnergyIC2$1@5f254eb8 (dim 6: 11/65/-16) was invalidated in grid update (ADDITION)`

**Comment by McJty** [comment]
Is the dimension powered? Chunkloaded? Many people are living without problems in my dimensions so something special must be going on

**Comment by thelapisfox** [comment]
I have my reactor and turbines in the same dimension flowing into a level 5 Draconic energy core. From there, I use the Draconic gems to transfer energy around. This includes to both the refined storage and dimension charger (which is in the same dimension). I also have the entire area chunkloaded via the FTB Utilities.

**Comment by MichaelHillcox** [comment]
Thank you for taking the time to create this issue, as we're no longer supporting versions below `1.12`, I'm going to go ahead and close it but if this bug seems to continue over to newer versions, please do report it again so we can investigate the issue further.
