### ISSUE TITLE
[1.12.1] - Living matter not being accepted

### ISSUE THREAD

**Issue by Protheus** [McJtyMods/RFTools#1367]
I'm using;
- rftools-1.12-6.13
- mcjtylib-1.12-2.4.4

and the following living matter are not accepted (added to the matter beam in stacks (64):
![image](https://user-images.githubusercontent.com/1455178/30477192-980dc618-9a0c-11e7-9ee9-a67ca836dc7c.png)

In the screenshot the **BLUE** section of items are living matter **not accepted**.
The **RED** section of items are the ones that **are accepted**.

Issue #1358 had the same issue but he/she updated to X and worked.. Im using the latest (curse site)

**Comment by McJty** [comment]
Fully depends on configs and what other mods do to those foods. Can you check the configs?

**Comment by Protheus** [comment]
aahh.. maybe it is Harvestcraft... as that did something to the default food. thank you

**Comment by trittimo** [comment]
Just in case anybody else runs into this issue, I was able to resolve this problem by changing the "B:enablevanillafoodBalance=true" option to "B:enablevanillafoodBalance=false" option in harvestcraft.cfg.
