### ISSUE TITLE
Screen server handling.

### ISSUE THREAD

**Issue by Magi1053** [McJtyMods/RFTools#1369]
The Screen tile entity from RF Tools doesn't respect claims. When I right click on any button on the screen, I get the message in chat `You don't have permission to interact with the block rftools:screen.`but it didn't prevent the interaction, the button still got pressed.
https://github.com/MinecraftPortCentral/GriefPrevention/issues/472#event-1252627198

**Comment by MichaelHillcox** [comment]
This is likely not our issue
