### ISSUE TITLE
Crash when clicking on shape card which has been used before

### ISSUE THREAD

**Issue by twoworlds** [McJtyMods/RFTools#1373]
MC 1.12.1 server and client
Forge 14.22.1.2485 on client and server
rftools 1.12-6.13

Here is what I did: 

Placed the builder, used a void shape card and set the desired dimensions. Inserted the shape card and hit the preview button. I saw, that the dimensions are not correct, so i take out the shape card to correct the dimensions. On right clicking the shape card, my client crashes. 
I can log onto my server again after restarting the client but the problem persists. I right click the shape card and it crashes again.

Here ist the crashlog : https://pastebin.com/xVUHbYXS

**Comment by McJty** [comment]
I don't know why it is crashing with a shapecard but the crash occurs in chickenlib and so doesn't seem related to rftools.  I would report to them. It may be that some item displayed in JEI is causing the crash

**Comment by twoworlds** [comment]
Thanks for your reply, I will report it to them !

**Comment by covers1624** [comment]
This is not me, It is bibliocraft.

**Comment by twoworlds** [comment]
Ok, I will take it to bibliocraft ;)
