### ISSUE TITLE
RFTools Builder Quarry - Ignores GriefPrevention Claims

### ISSUE THREAD

**Issue by Keanu73** [McJtyMods/RFTools#1375]
Hi, so I've been playing on this server, which has the plugin called GriefPrevention. You can find the plugins and mods list on their website, for reference: https://kaos-network.com/servers/sonarx

So just today, the RFTools Builder Quarry had managed to quarry someone's house, making half of it dirt. It was fully claimed with GriefPrevention, and your mod had bypassed it and managed to grief someone's house. The server owner isn't happy about this, and he wants you to look into this as much as possible.

![quarriedhouse](https://cdn.discordapp.com/attachments/333884695617994752/361540168173355008/2017-09-24_16.48.53.png)

**Comment by osmarks** [comment]
Weirdly, the shield generator seems to NOT have this problem, displaying a red message in chat if it's going to place in a claim.

**Comment by McJty** [comment]
This is not something that can/should be fixed on my side. The Builder is already properly using the right methods to break and place blocks as far as I know.

**Comment by Keanu73** [comment]
I'm sure there's a way to write something to add compatibility with GriefPrevention.

**Comment by McJty** [comment]
Still not for me to do. That's for GriefPrevention to add support for mods properly

**Comment by osmarks** [comment]
Why is it that the shield generator is fine but the builder is not though?

**Comment by McJty** [comment]
I have no clue. Not sure how GriefPrevention works

**Comment by keanucz** [comment]
How time passes by....
