### ISSUE TITLE
[1.7.10] Dragon dimlet not spawning dragons

### ISSUE THREAD

**Issue by ic3cr34m** [McJtyMods/RFTools#1378]
I'm using FTB Infinity Evolved but for some reason when I created the dragon dimlet, no dragons are spawning. I've tried everything which included restarting the server, changing the spots of the dimlet and adding terrain/biome dimlets. None are working.
The dragons simply aren't there.

**Comment by McJty** [comment]
Can you give more information? Logs? What kind of other dimlets you were using?

**Comment by ic3cr34m** [comment]
Hey, thanks for the reply. And sorry for getting back late.
We were just using the dimlet for the dragon, and it still wasn't working. Then we tried adding a biome and terrain dimlet but still nothing.

I'm just going to do this again and show you the logs, so give me like 5-10 minutes.

**Comment by ic3cr34m** [comment]
`6.09 10:39:20 [Server] INFO ... 2 more
26.09 10:39:45 [Server] INFO CONSOLE issued server command: /list 
26.09 10:39:45 [Server] INFO default: Owner | Ic3Cr34m
26.09 10:40:17 [Server] INFO CONSOLE issued server command: /list 
26.09 10:40:17 [Server] INFO default: Owner | Ic3Cr34m
26.09 10:40:43 [Server] INFO id = 19 for , descriptor = @MDragon,sDark Cyan Color
26.09 10:40:43 [Server] INFO Base seed: 4967746611176416699
26.09 10:40:43 [Server] INFO World version: 1
26.09 10:40:43 [Server] INFO Terrain: TERRAIN_PLATEAUS
26.09 10:40:43 [Server] INFO Base block: Stone
26.09 10:40:43 [Server] INFO Base fluid: Water
26.09 10:40:43 [Server] INFO Biome controller: CONTROLLER_DEFAULT
26.09 10:40:43 [Server] INFO Sun brightness: 1.0
26.09 10:40:43 [Server] INFO Star brightness: 1.0
26.09 10:40:43 [Server] INFO Sky color: 0.0, 0.6, 0.6
26.09 10:40:43 [Server] INFO Fog color: 1.0, 1.0, 1.0
26.09 10:40:43 [Server] INFO Mob: net.minecraft.entity.boss.EntityDragon
26.09 10:40:43 [Server] INFO Sync dimension info to clients!
26.09 10:40:43 [Server] INFO Loading dimension 19 (DIM19) (net.minecraft.server.dedicated.DedicatedServer@50613ba5)
26.09 10:40:43 [Server] INFO Loaded a world with the tfEnforcedProgression game rule not defined.  Defining it.
26.09 10:40:43 [Server] INFO Default configuration file written: /plugins/WorldGuard/worlds/DIM19/config.yml
26.09 10:40:43 [Server] INFO Default configuration file written: /plugins/WorldGuard/worlds/DIM19/blacklist.txt
26.09 10:40:43 [Server] INFO (DIM19) TNT ignition is PERMITTED.
26.09 10:40:43 [Server] INFO (DIM19) Lighters are PERMITTED.
26.09 10:40:43 [Server] INFO (DIM19) Lava fire is blocked.
26.09 10:40:43 [Server] INFO (DIM19) Fire spread is UNRESTRICTED.
26.09 10:40:43 [Server] INFO Loaded configuration for world 'DIM19'
26.09 10:40:43 [Server] INFO Sync dimension info to clients!
26.09 10:40:45 [Server] INFO Unloading dimension 19
26.09 10:40:48 [Server] INFO CONSOLE issued server command: /list 
26.09 10:40:48 [Server] INFO default: Owner | Ic3Cr34m
26.09 10:41:02 [Server] INFO Loading dimension 19 (DIM19) (net.minecraft.server.dedicated.DedicatedServer@50613ba5)
26.09 10:41:11 [Server] INFO /config/JourneyMapServer/DIM19.cfg not found!
26.09 10:41:11 [Server] INFO Attempting to create new config file for: DIM19
26.09 10:41:20 [Server] INFO CONSOLE issued server command: /list 
26.09 10:41:20 [Server] INFO default: Owner | Ic3Cr34m
26.09 10:41:51 [Server] INFO CONSOLE issued server command: /list 
26.09 10:41:51 [Server] INFO default: Owner | Ic3Cr34m`

**Comment by MichaelHillcox** [comment]
Close as 1.7.10 is no longer supported. If this continues to be a bug on 1.12 or newer, please open a new issue.
