### ISSUE TITLE
[1.7.10] Question regarding dimlets

### ISSUE THREAD

**Issue by ic3cr34m** [McJtyMods/RFTools#1382]
I'm using FTB Infinity Evolved, lately I've been receiving a lot of issues. my main issue is trying to make it so I always get the dimension I put in. For example, I tried to make a mob Ocelot dimension and I never found ocelots. What am I missing that I have to do? Does there have to be other dimlets for other things?

**Comment by McJty** [comment]
Can you be more specific? What dimlets did that ocelot dimension contain?

**Comment by ic3cr34m** [comment]
Sorry, I meant to be more specific just couldn't figure out what else to say haha.
These are the dimlets in order that it contained:

1. Terrain Amplified
2. Biome Jungle
3. Sky Normal
4. Time Normal
5. Mob Ocelot

**Comment by McJty** [comment]
Hmm that should work... No idea at the moment. Try to check if they really don't spawn

**Comment by ic3cr34m** [comment]
Yeah I flew around the map for 5 minutes and none spawned, haha.
I'll give it 10 minutes though and go further just to double check and then I'll get back to you.

**Comment by ic3cr34m** [comment]
So after searching for a while, I finally found ONE.
But with the mob dimlets isn't it supposed to add tons of mobs?

**Comment by MichaelHillcox** [comment]
Close as 1.7.10 is no longer supported. If this continues to be a bug on 1.12 or newer, please open a new issue.
