### ISSUE TITLE
Crafter don't respect CraftTweaker

### ISSUE THREAD

**Issue by forestbat** [McJtyMods/RFTools#1383]
@McJty 
I use CT to add a recipe which use shear of winter in reliquary to make IE's copper wire。
recipes.addShapeless(<immersiveengineering:material:20>,[<ore:plateCopper>,<xreliquary:shears_of_winter>.reuse()]);
And it's normal in vanilla crafting table。
But when I put the recipe in rftools' crafter，the shear is still consumed——I lost my shear。
![2017-09-29_12 10 44](https://user-images.githubusercontent.com/23413915/31000662-ffa5b8cc-a50f-11e7-9d68-2264d5063b86.png)

**Comment by McJty** [comment]
Version?

**Comment by forestbat** [comment]
7.00 alpha。

**Comment by McJty** [comment]
And Minecraft version?

**Comment by forestbat** [comment]
1.11.

**Comment by forestbat** [comment]
@McJty  A month has passed，do you solved the problem？

**Comment by McJty** [comment]
I honestly have no clue and I'm even not sure the bug isn't in crafttweaker. The RFTools Crafter just uses the regular minecraft crafting system and other non-consumable recipes work fine
