### ISSUE TITLE
Builder Quarries don't respect block protection.

### ISSUE THREAD

**Issue by tgarr0** [McJtyMods/RFTools#1384]
I first found out about this problem when someone's Builder Quarry dirtified blocks within FTBUtilities claims on a FTB Unstable server. In order to make sure that FTBUtilities wasn't to blame, and that this problem hadn't already been fixed, I set up a Forge (1.12.2-14.23.0.2493) server with just RFTools (1.12-7.00alpha1) and a vanilla spawn-protection radius. I made sure that I wasn't opped, and that there was another existing op on the server (now that Minecraft drops spawn protection when there aren't ops). The Builder proceeded to dirtify everything in its card's radius, including the protected area.
![quarry overreach](https://user-images.githubusercontent.com/4881555/31042123-d06c9242-a56e-11e7-8fa9-bd9a41f227c5.png)

**Comment by McJty** [comment]
This has come up before but as far as I know I'm using the right methods to harvest blocks and so I think the bug is not my side. I have no clue how else I should do this

**Comment by tgarr0** [comment]
I was previously under the assumption that things were handled via checking whether the player that placed the block could break any given block, rather than through the use of a FakePlayer. It would definitely seem to be on Forge itself that FakePlayers can manipulate blocks within spawn-protection.
I guess that reduces this issue to a feature request for checking whether the Builder's owner can manipulate blocks before doing anything (assuming that this is possible, wouldn't kill performance, and wouldn't completely defeat the purpose of using a FakePlayer).

**Comment by McJty** [comment]
This is not possible because the player that placed the Builder is not always online while the Builder works. So I can't be sure I have access to the original owner
