### ISSUE TITLE
RFTools Mekanism Conversion

### ISSUE THREAD

**Issue by Fently** [McJtyMods/RFTools#1389]
I noticed that the conversions in RFTools is pretty wacked. I calculated a Mekanism Wind Generator to be able to produce 25J/Tick, which is 10RF/T. However, after using an rf network, I noticed it said 102RF/Tick. Wait, what?

So I decided to get more thorough to make sure. I connected a wind turbine to a powercell, and counted how many ticks it would take to reach 800'000RF by having the two right next to each other. After it was done, I found it could reach 800'000RF in 7880Ticks (101.5RF/Tick)

Why exactly is this, when the Joules to RF ratio is supposed to be 1J : 0.4RF ? It's been messing me up all day

**Comment by McJty** [comment]
Report this to Mekanism. I just show whatever RF values I get using the RF API. I don't do any conversion

**Comment by ouroborus** [comment]
@Xopharios According to the [Wind Generator](http://wiki.aidancbrady.com/wiki/Wind_Generator) entry on the Mekanism wiki, the output varies by elevation. Additionally, the page states that the minimum J/t is 60 (at the minimum elevation of 25). Inverting the formula relating elevation to J/t shows that an output of 101.5RF/t (253.75J/t) would be achieved near elevation 130.
