### ISSUE TITLE
[suggestion] include schematics!

### ISSUE THREAD

**Issue by winsrp** [McJtyMods/RFTools#1408]
so as you know there is this minecraft community standard for schematics, and now that you have your preview machines + builder, i was thinking that you could change a little bit all that code and make something that loads a schematic into a card and then print it with the builder, that would be super cool!

I would love to make an item with a house schematic in it on my server and just give it to another player, schematics could be saved on the server, even custom ones, the same way dimensions are saved.

I have tried other mods, like schematica, they have a nice way to preview the schematic but for big things, it is a pain in the ass to build, since their printer function is like 4 blocks range around you, I tried "printing" a castle yesterday in creative, and it took me 4 hours!!... there is another one which is more friendly on that , which is called architect, but it currently doesn't support schematics, only their custom format, but it does have a way to attach some storage to the building process and all items are taken from the storage, so that looked more like something I can implement on my server, and there is where it hit me... if only I could load schematics with RfTools, since it has all the items to build, get items, make designs and now with the scanner and projector I could envision like a 3d progress bar of the project being build with the projector 3d image filling up as the project is being built.. that would be AWESOME!!!

Just laying it out in the wild.... I know it might be a pain in the ass to make, but you are the greatest modder out there!!! if someone could do it, it is you! =D

**Comment by McJty** [comment]
Note that the new shapecard system allows you to save/load the scans to a file and you can give those to other players.

**Comment by winsrp** [comment]
uhh... that sounds cool, but i would need to know the other players or put up some sort of shared open online storage, could they be saved on the server, and just give the shapecard to another placer, which links to the information on the server, or by giving them the shapecard, the server sends the shapecard information to their local computer, how does that works?

**Comment by McJty** [comment]
You can freely give around shapecards on the same server. That's no problem. They will work. Sending to local computer is not yet possible though. The files are currently stored in the server itself

**Comment by winsrp** [comment]
so let's see if I'm correct here, I make a house, I put it in a shapecard by scanning it, and then I can give that shapecard to another player... and if they put it in a scanner they will project correctly right?... now can he put it on a builder for it to be built? with a chest on top, like with space chambers?

**Comment by McJty** [comment]
yep

**Comment by winsrp** [comment]
I need to go try that right about now!!!.... jajaja... still waiting for that video, seems like there is more to this last change than meets the eye, !!! and that sounds like 90% of my request already done, lol... I just need to be able to upload schematics to the server and put them on a shapecard, those that are found online. =D

**Comment by winsrp** [comment]
so I had a "medium scan" (200,90,125) on the projector and picked a second card, to make a new scan (to scan a single house)(14,10,16), which is an area included in the bigger scan (not sure if that is an important detail or not), once I put that new card on the scanner and hit scan the preview is black, and the previous medium scan running on the projector became .. weird, might be a bug

**Comment by winsrp** [comment]
and if I take the medium scan out of the project now the small scan shows up on the scanner

**Comment by winsrp** [comment]
also it seems like the scanner is not taking into account the Y offset of the shapecard, it start always at 0 even if the shapecard has some other number.

**Comment by winsrp** [comment]
I might be doing something wrong

[https://imgur.com/a/oorY0](url)

I made a shape card, selected a little house I want, scanned it, put it on the builder, set a container with all the items it will need and more, and hit the lever... nothing happens, the preview looks to be ok, but nothing happens.
