### ISSUE TITLE
[issue] rftools-1.12-7.12.jar building from scan seems to have issues with doors

### ISSUE THREAD

**Issue by winsrp** [McJtyMods/RFTools#1417]
So finally manage to build something with the scan of a house and the builder, but... when it has to put a door, it just dies, and since it is building from top to bottom as well, I'm guessing it will also die when trying to put the actual door if the top part of the door block is ignored., 

Suggesting, build from bottom to up... this should fix all issues with thing that might get not placed correctly, and first build all blocks and then all other stuff, like doors, torches, redstone, etc. so it should be like a 2 pass over the scan, one for blocks and another for placement items, not sure if minecraft has any distinction on those.

**Comment by winsrp** [comment]
btw the new builder interface and the error messages, ... great work.

**Comment by winsrp** [comment]
it would be even greater if on the builder gui there would be like a little screen with the actual detail of the error like the name of the block itself that is missing.

**Comment by McJty** [comment]
What do you mean by 'dies'? It crashes?

**Comment by winsrp** [comment]
it just stops at the top "door tile" saying it is missing a block... I can tell now with the new block indicator of where it is at.

**Comment by McJty** [comment]
Doors are problematic like that. I have no good way to solve that really

**Comment by winsrp** [comment]
build from the bottom up?
