### ISSUE TITLE
[1.12.2]Logic block have a strange delay

### ISSUE THREAD

**Issue by Flithor** [McJtyMods/RFTools#1425]
![logic delay bug](https://user-images.githubusercontent.com/23412916/32130983-cd75be6a-bbd5-11e7-8c1c-1d972d2f2f44.gif)
If the logic block output face to north or south will have 1 tick delay, but face to west or east will not have delay.

**Comment by McJty** [comment]
That's because tile entities have a 'semi-random' ticking order in a chunk. Nothing I can do about

**Comment by Flithor** [comment]
So, that say this is the games block refresh order caused this bug, so you can't solve it?

**Comment by McJty** [comment]
Indeed. If you're working on such per-tick precision then you cannot depend on ticking order.

**Comment by Flithor** [comment]
But I think you need to remind the player this problem...
Since it can''t resolved, then it will be available as a "feature" to inform the player.
"Face to North or South will delay 1 tick, Face to West or East will not delay."

**Comment by McJty** [comment]
It is not that strict. It happens to be that way for you but that may change depending on other tile entities (that are not even connected) in the same chunk or other criteria. It is defined so I can't tell the user what it will be

**Comment by MichaelHillcox** [comment]
Closed in preference for #854
