### ISSUE TITLE
[Issue]Storage/1.11.2/items not being displayed and cannot craft

### ISSUE THREAD

**Issue by jmc529** [McJtyMods/RFTools#1441]
I can't seem to craft within modular storage tile entities and in one of my storage modules I only see 17 items, but it has ~190. I can access those items within the scanner.

**Comment by McJty** [comment]
You may have typed something in the search box?

**Comment by jmc529** [comment]
Ah yes that was dumb, sorry!

**Comment by jmc529** [comment]
Oh but, My storage modules still won't craft. Only my scanner. Do you have any idea what could cause this?

**Comment by McJty** [comment]
Show a screenshot?

**Comment by jmc529** [comment]
I made a small video demonstrating it.
https://youtu.be/xMV-4Y67klw

**Comment by MichaelHillcox** [comment]
Thank you for taking the time to create this issue, as we're no longer supporting versions below `1.12`, I'm going to go ahead and close it but if this bug seems to continue over to newer versions, please do report it again so we can investigate the issue further.
