### ISSUE TITLE
[1.12.2] Network Tool GUI does not work

### ISSUE THREAD

**Issue by Fatmice** [McJtyMods/RFTools#1446]
RFTools 7.12
Network tools GUI flashes briefly then disappears when wacked on some energy conduits carrying RF.  If wacked on to the ground or some block, the GUI will appear but no useful information can be seen of course.  Holding the item will show energy network, which I guess is part of the new behavior.

**Comment by McJty** [comment]
I cannot reproduce this. Are you using sneak-right click to open the GUI?

**Comment by Fatmice** [comment]
No, I just hold the tool in my hand then wack the cable.  If the tool is held in the hand, I see an outline of all RF consumers.  Whacking a cable will make the GUI briefly appears then disappears.

**Comment by McJty** [comment]
What if you use sneak-right click?
That's how you're supposed to open the gui for it

**Comment by Fatmice** [comment]
Hm I just did that, sneak-right click.  GUI flashes then disappears.

**Comment by Fatmice** [comment]
Same as the block protector issue.  Single player works fine, only happens in multiplayer.

**Comment by josephcsible** [comment]
Why did you close this? Is it fixed for you now?

**Comment by Fatmice** [comment]
Same comment as #1448

**Comment by Fatmice** [comment]
This fixed the problem
https://github.com/SpongePowered/SpongeForge/commit/a684cccd0355d1387a30a7fee08d23fa308273c9
