### ISSUE TITLE
[1.10.2] Builder (show area) block stay in world

### ISSUE THREAD

**Issue by chezpaul** [McJtyMods/RFTools#1480]
When I use the builder and click the icon that let's you see the area that will be worked on in blue. When I deactivate the button, the area is still showing and is also "live" blue blocks that I can break.
In order to make the area disappear, I need to break them all.

I am running Forge 2511 and latest RFTools 7.14, this happens on the Mercury planet that comes from Extra Planets mod.
Maybe it's related.
I never tried this on the overworld.

**Comment by McJty** [comment]
This has been reported before but I have no clue why it is happening. In any case, right clicking such a block will make them disappear in bigger numbers

**Comment by McJty** [comment]
BTW, 7.14 is not latest. 7.15 is latest but it makes no difference in this case

**Comment by chezpaul** [comment]
Well two days ago, that was the latest.  ;-)

**Comment by MichaelHillcox** [comment]
Unfortunately we're no longer supporting versions older than `1.12` and I don't have enough time to check this suggestion against all of the features of the mod but if this feature still hasn’t been implemented and you’d like to see it added to a newer version of the mod then please do create a new issue so we can review your suggestions again :+1:
