### ISSUE TITLE
The Storage Scanner counts the contents of double chests twice

### ISSUE THREAD

**Issue by Undeadbanana** [McJtyMods/RFTools#1583]
Unsure why this is happening but the quantity of items in the scanner is displaying twice as high as it should be. e.g; Shows 4 ender pearls when there's actually only 2. Using newest versions of your mods as of January 25th

**Comment by josephcsible** [comment]
Screenshot of the inventory in question in the world, and one of the scanner GUI?

**Comment by Undeadbanana** [comment]
Actually, just figured it out. It's scanning some double chests twice. Scans them as single inventories.

https://imgur.com/a/umS9W

I just did a scan because I thought maybe upgrading some Iron Chests messed with something. The scan did get rid of some extra chests, started with 16 in Scanner GUI and new scan only showed 14. Gonna rescan again.

**Comment by Undeadbanana** [comment]
![2018-01-25_17 09 52](https://user-images.githubusercontent.com/4379427/35420559-0b925c9a-01f3-11e8-87a1-3039b8c0f690.png)
![2018-01-25_17 09 59](https://user-images.githubusercontent.com/4379427/35420560-0ba840b4-01f3-11e8-868a-ffdd20bbc642.png)

I'll put the images here so you don't have to go to an external site

**Comment by Undeadbanana** [comment]
It's only doing this double-chest-as-single-chest scan to two of my chests.

**Comment by josephcsible** [comment]
Can you find any kind of pattern in which double chests it happens with and which ones it doesn't?

**Comment by Undeadbanana** [comment]
Actually, I can. Just noticed it's happening to a third chest; All 3 chests despite being Spruce/Oak say they're from the mod Quark. The only Spruce chests that it's not happening to are Minecraft vanilla chests.

**Comment by Undeadbanana** [comment]
I wouldn't say it applies to all modded chests, I'm using some chests from Iron Chests and those are free of this bug. As of right now, it's only affecting the Quark chests. Scanning double chests as single chests but reading the entirety of the double chests contents for each scan.

**Comment by Undeadbanana** [comment]
Not sure if this is needed but I'm using Quark-r1.4-122.jar, updated yesterday January 24th.

**Comment by josephcsible** [comment]
Is it accurate that it applies to all modded chests that occupy multiple blocks?

**Comment by Undeadbanana** [comment]
Yes, that's accurate; I can't find any other double chests at the moment.

**Comment by josephcsible** [comment]
Hmm, in my testing, this happens to vanilla double chests too. Can you confirm whether this is the case on your end?

**Comment by Undeadbanana** [comment]
You're right, it's all double chests

**Comment by Undeadbanana** [comment]
This might also be the same problem; I've got two powercells linked, when one is placed I have about 150k RF, when I place the other in the world it says I now have 310k RF in the linked powercells.

*Ignore first screenshot*

https://imgur.com/a/ed6vn

**Comment by Undeadbanana** [comment]
![2018-01-26_16 55 48](https://user-images.githubusercontent.com/4379427/35466845-9e034c5a-02bc-11e8-820c-377dd999fcbc.png)
![2018-01-26_17 12 43](https://user-images.githubusercontent.com/4379427/35466846-9e1a0f76-02bc-11e8-81bc-a367c748ad7e.png)
![2018-01-26_17 12 50](https://user-images.githubusercontent.com/4379427/35466847-9e30dc42-02bc-11e8-877a-ba14936aff08.png)
![2018-01-26_17 12 54](https://user-images.githubusercontent.com/4379427/35466848-9e466df0-02bc-11e8-99ab-d70300436474.png)

**Comment by josephcsible** [comment]
That looks unrelated; can you open a new issue for it?

**Comment by Enverex** [comment]
This seems to affect the "Racks" in MineColonies too. It counts each block a rack occupies as a separate inventory, thus duplicating everything inside in 2-block wide racks (racks can be 1 or 2 wide, like a normal chest).

**Comment by winsrp** [comment]
I have verified that this is affecting minecolonies racks as well, when reading contents from the warehouse, everything is doubled.

**Comment by josephcsible** [comment]
Will be fixed in the next release. I tested this for vanilla double chests, Quark double chests, and MineColonies racks. It's possible that other mods' blocks may still have this problem. If so, there's nothing more we can do about it on our end. They'll need to do two things on their end: use IItemHandler instead of IInventory, and make sure that their IItemHandlers returned by different blocks are equal according to the equals and hashCode methods.
