### ISSUE TITLE
[Feature] Pump using filter

### ISSUE THREAD

**Issue by donqixot** [McJtyMods/RFTools#1606]
Can we have filter on fluids using Pump (Builder). I noticed this issue was brought up already few times #1101 and #1465. I wonder if there is a plan to complete this? Builder is tremendously helpful with various functions, but when pumping fluids near the ocean, it is such a pain!

**Comment by SmartGuy202** [comment]
I have confirmed that buckets of the fluid you would like to exclude/include will count as the blocks themselves. Just make sure the black/whitelist setting is set properly. I'm using RFTools 1.12-7.55 as part of the Direwolf20 1.12 FTB Pack.

**Comment by donqixot** [comment]
Great, thank you! I will test this in the next few days and close this thread.

**Comment by Paxination** [comment]
I've tried this, to pump just lava from the nether.  I keep getting energized glowstone in my lava system which is annoying to fix as i have to break all pipes and tanks and remove it before i can get lava going again.

Its set on whitelist, i dont know if changing the other settings fixes it or not.  Not sure how they would affect it.

**Comment by Paxination** [comment]
i've had blood get in now too, i have it set on whitelist as well

**Comment by MichaelHillcox** [comment]
Closed in preference of  #1101
