### ISSUE TITLE
Suggestion For Dimension Freezing

### ISSUE THREAD

**Issue by natedogith1** [McJtyMods/RFTools#162]
I hope suggesting this isn't stepping out of line. But I was thinking, would it be easier to freeze a dimension by providing your own world class that overrides the update methods so that they don't run (or run limitedly) when the world doesn't have power?

**Comment by McJty** [comment]
Yes, but how can one provide their own World class without ASM?

**Comment by natedogith1** [comment]
Forge's DimensonManager class seems to have a setWorld method. And this method is called in the WorldServer constructor, so I think you should just be able to extend the WorldServer class and provide a world that way.

**Comment by MichaelHillcox** [comment]
As the implementation would appear to be not supported that well with the new Dimension system in forge / mc as of 1.14 (partially in 1.12) this would have to be brought up again referring to a newer version of the game.
