### ISSUE TITLE
[issue] storage tablet crafting not working unless craft recipe is saved

### ISSUE THREAD

**Issue by winsrp** [McJtyMods/RFTools#1721]
Issue description: 

You have an storage table with tier 3 card in it, you try to use the crafting grid on the side but it does not work unless you save the recipe to the side list. (hitting the 1,4,8,* buttons don't do anything unless recipe is saved.)

Steps to reproduce: 

Versions:
* Minecraft: 1.12.2
* Forge: 14.23.3.2655
* McJtyLib: 2.6.7-snapshot
* RFTools:7.33

**Comment by McJty** [comment]
I have noticed this myself. I'll see if I can do anything about it

**Comment by winsrp** [comment]
thanks!

**Comment by McJty** [comment]
Fixed next release
