### ISSUE TITLE
Matter Beamer not accepting EIO item conduits

### ISSUE THREAD

**Issue by SplitInfinitive** [McJtyMods/RFTools#1741]
Issue description: 
item conduits do not connect to matter beamers.  They work fine in all other blocks that accept items in this mod.  The beamers also connect correctly energy and redstone conduits appropriately.  Beamers respond normally to other item pipes/ducts/transporters/etc.

Steps to reproduce: 
1) Place Matter Beamer
2) place item conduit

Versions:
* Minecraft: 1.12
* Forge: 2655
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: 2.6.7
* RFTools: 7.33

Possibly incompatible mods and versions: 

Relevant logs, if any: 

![2018-05-14_01 33 48](https://user-images.githubusercontent.com/24683195/39984003-eb7222c8-5716-11e8-9a28-c545cc1375d8.png)

**Comment by McJty** [comment]
Seems EnderIO only supports capabilities and this is one of the few blocks in rftools that doesn't have this. I'll fix this next update

**Comment by McJty** [comment]
Fixed next release
