### ISSUE TITLE
Not showing percentage?

### ISSUE THREAD

**Issue by acoolghuy** [McJtyMods/RFTools#1742]
Issue description:  Not showing percentage on screen.

Minecraft version: 1.12.2
Mod version: Draconic-Evolution-1.12-2.3.10.284-universal
Minecraft Forge version: 14.23.3.2688
CompatLayer (only if on Minecraft 1.10 or 1.11):
McJtyLib: mcjtylib-1.12-2.6.7
RFTools: rftools-1.12-7.33

![2018-05-15_17 58 53](https://user-images.githubusercontent.com/5675422/40072307-432563d6-586b-11e8-9c71-831fef2706ae.png)
![2018-05-15_17 59 17](https://user-images.githubusercontent.com/5675422/40072308-433c9db2-586b-11e8-95a2-4f22c95f5c91.png)

**Comment by acoolghuy** [comment]
The core is showing 1% why is the screen showing 0% im confused sorry.
The rf total is showing ok .

**Comment by McJty** [comment]
Probably different ways to round

**Comment by acoolghuy** [comment]
Ok thanks :)
