### ISSUE TITLE
[1.12.2] Trying to add Yellorite Ore to the Material Absorber config

### ISSUE THREAD

**Issue by chezpaul** [McJtyMods/RFTools#1745]
I want to add Yellorite Ore from Extreme Reactors into the Material Absorber config.
I try to edit the config/dimlet.json file by adding this:

{
    "filter": {
      "mod": “bigreactors”,
      "name": “brore”,
      "type": "material"
    },
    "settings": {
      "rarity": 5,
      "create": 10000,
      "maintain": 10000,
      "ticks": 1000,
      "worldgen": true,
      "dimlet": true
    }
  },

When I launch the server, it gets erased and of course, nothing happens.

Steps to reproduce: 
Happens every time

Versions:
* Minecraft: 1.12.2
* Forge: 14.23.3.2676
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: 1.12.2.6.7
* RFTools: 1.12 7.33

No Optifine or Sponge.
No server crashes.

**Comment by josephcsible** [comment]
`"Everything below this line will be regenerated from defaults every time. Remove this line if you do not want that",`
Add your entry above that line instead of below it.

**Comment by chezpaul** [comment]
I knew it had something to do with that line but just couldn't pinpoint it.  ;-)
Thanks man.
Great mods... thanks for still working on them.
