### ISSUE TITLE
Possible dead state with matter transmitters

### ISSUE THREAD

**Issue by Dekutanoth** [McJtyMods/RFTools#1747]
Issue description: 
Teleporting to and from the End with the matter transmitter/receiver causes the player to go into a "dead" state while actually alive and moving. Can't sleep on a bed, can't use the matter transmitters, AE/Refined Storage acts weird and won't update for you, trying to teleport with journeymap/console results in "cannot teleport while dead." It doesn't happen for the Nether or RFTools dimensions, only the End, oddly enough. I saw an interesting item in the server log: "Force-added player with duplicate UUID [my UUID]" while I was transmitting from the End. It was after that that I started to have the dead state problems. When I researched the log entry for answers, I found another github with this log entry, and a dev reply: 
"This is an issue with the mod

https://github.com/Bartz24/SkyResources/blob/1.10/src/main/java/com/bartz24/skyresources/events/EventHandler.java#L516

The dev's method can return null yet he never checks for it."

Maybe it's something, maybe not. I can't really give a crash report since there's no crash, but I'll check back here periodically in case you need more information. 

If you kill yourself or disconnect/reconnect, the issue goes away, since it clears your "dead" state.

Steps to reproduce: Teleport to the End and back using a matter transmitter and receiver. I believe it is the transmitter/receiver due to the fact that if you admin teleport/journeymap teleport/End portal, it works as intended and doesn't give you the error.

Versions:
* Minecraft: 1.12.2
* Forge: 14.23.3.2691
* McJtyLib: 1.12-2.6.7
* RFTools: 1.12-7.33

**Comment by McJty** [comment]
This is most likely not a bug in the matter transmitter but in some other mod that causes some kind of problem as teleporting from the end with Ender Utitiles or Astral Sorcery in some modpacks (like SevTech) causes the same issue

**Comment by josephcsible** [comment]
Can you reproduce this with only RFTools and its dependencies installed?

**Comment by douglasg14b** [comment]
This problem is happening to me in ATM3
