### ISSUE TITLE
Storage Scanner Rendering Issues. 

### ISSUE THREAD

**Issue by nocensangelus** [McJtyMods/RFTools#1749]
Issue description: java.lang.NullPointerException: Rendering screen 

Steps to reproduce: I have the storage Scanner Tablet with Salis Mundus in the crafting section when I try to open the tablet it crashes the game

Versions:
* Minecraft: 1.12.
* Forge: 14.23.3.26689
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: 1.12-2.6.7
* RFTools: 1.12-7.33

Possibly incompatible mods and versions: thaumcraft.common.lib.crafting.RecipeMagicDust.func_77569

Relevant logs, if any: 
https://paste.ee/p/HCry1

**Comment by McJty** [comment]
That's a bug in Thaumcraft as far as I can see. It is trying to render something in the 'Recipe.matches' function. That's extremely weird and wrong:

	at thaumcraft.common.lib.crafting.RecipeMagicDust.func_77569_a(RecipeMagicDust.java:43)
	at mcjty.rftools.craftinggrid.CraftingRecipe.findRecipe(CraftingRecipe.java:48)
