### ISSUE TITLE
RFTools Screen Crash

### ISSUE THREAD

**Issue by jusitnboggs** [McJtyMods/RFTools#1758]
Issue description: 
I updated/ installed some new mods on my server (none were McJtyMods)
then logged in to the server and I keep crashing I have only one RFTools screen in the basement I am on a different floor from it 
Steps to reproduce: 
![updated today](https://user-images.githubusercontent.com/2986451/40637333-12cfe730-62b9-11e8-8dd5-5511f220e37e.PNG)

Versions:
* Minecraft: 1.12.2
* Forge: 14.23.4.2703
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: mcjtylib-1.12-2.6.7
* RFTools: rftools-1.12-7.33

Possibly incompatible mods and versions: OptiFine 1.12.2 HD U D1

Relevant logs, if any: https://pastebin.com/YSqVfQL9

The mods listed in the photo were updated or installed today.

**Comment by McJty** [comment]
Can you tell me what is in the screen (which modules)?

**Comment by McJty** [comment]
Oh, do you have something that has a really HUGE amount of power in it perhaps?

**Comment by jusitnboggs** [comment]
I have using 1 text and 2 RF+ and it is hooked up to a tier 8 DE energy core

**Comment by jusitnboggs** [comment]
while we talking about this your RF+ won't show the % of energy in the core idk if that is a bug or if its just not supposed

**Comment by McJty** [comment]
How much energy is in it?

**Comment by jusitnboggs** [comment]
well over 40,000,000,000,000,000 that was about 14 hrs ago and it is gaining about 1T/T

**Comment by McJty** [comment]
Will be fixed next release
