### ISSUE TITLE
Crash when launching world

### ISSUE THREAD

**Issue by Bneboy** [McJtyMods/RFTools#1759]
Hey, I get a weird crash that seems to have to do something with the spawner. I don't have any idea if I am correct, though. Using the latest versions, just released earlier.

https://pastebin.com/FavTiLRR

**Comment by josephcsible** [comment]
See if deleting your rftools.cfg and letting it regenerate fixes it.

**Comment by Bneboy** [comment]
Nope. I get a similar/same crash.
https://pastebin.com/KUTiRGKK

**Comment by josephcsible** [comment]
This looks the same as #1769. Can you try following the same troubleshooting instructions I put there?
