### ISSUE TITLE
[RFTools - 1.12-7.50-alpha] Block protection crash

### ISSUE THREAD

**Issue by Sinxar** [McJtyMods/RFTools#1760]
Issue description: Crash when using Crescent Hammer on an Itemduct

Steps to reproduce: Use Crescent Hammer on Itemduct.

Versions:
* Minecraft: 1.12.2
* Forge: 2705
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: 3.0.0-alpha
* RFTools: 7.50-alpha

Possibly incompatible mods and versions: Thermal Dynamics 2.5.0.12-universal Optifine

Relevant logs, if any: https://hastebin.com/zoxivurafa.sql

**Comment by Aakryd** [comment]
Also occurs on all other Thermal Dynamics ducts

**Comment by MasterEnderman** [comment]
Have another one.
Crash Report: https://paste.dimdev.org/qolejafase.txt

**Comment by McJty** [comment]
Will be fixed next release
