### ISSUE TITLE
[Issue] client crash when opening GUI for "elevator button screen module" on screen

### ISSUE THREAD

**Issue by winsrp** [McJtyMods/RFTools#1763]
Issue description: 

Clicking the "elevator button screen module" crashes the client opening it

Steps to reproduce: 

Make elevator (3 stops in this case), 
put screens inside and outside the elevator
put "the elevator button screen module" in the screens
Try to open one of the GUIs, by clicking on the button as show below

![image](https://user-images.githubusercontent.com/13665046/40751848-3b691870-642a-11e8-8b57-6a03e3a2dad0.png)

Versions:
* Minecraft: 1.12.2
* Forge: 2655
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: 3.0.0 alpha
* RFTools: 7.50-alpha

Relevant logs, if any: 

https://pastebin.com/3CNXxiL7

**Comment by McJty** [comment]
I will check this out

**Comment by McJty** [comment]
Fixed next release

**Comment by winsrp** [comment]
thanks!
