### ISSUE TITLE
Block protector crash

### ISSUE THREAD

**Issue by kave777** [McJtyMods/RFTools#1765]
Issue description: Block protector crash

Steps to reproduce: 

Versions:
* Minecraft: 1.12.2
* Forge: 14.23.4.2703
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: 3.0.0-alpha  
* RFTools :7.50-alpha 

Possibly incompatible mods and versions: 
probably not

Relevant logs, if any: 
here is the crash : https://paste.ee/p/R2U75
here is the logs : https://paste.ee/p/gR6eX

**Comment by McJty** [comment]
Already fixed and ready for next release
