### ISSUE TITLE
Powercell Client Crash

### ISSUE THREAD

**Issue by Discomanco** [McJtyMods/RFTools#1766]
**Issue description:** 
When interacting with a Powercell that is not yours, it crashes everyone near it. It's only a client crash, as the server is just fine with it. He (my base partner) was the owner of a Powercell, and I had to move it, so I picked it up (without problems), and when I placed it back down, it had its first crashing issue.
I MCEdited (MCEdit 1.0) it out (which also deleted our Modular Storage a few chunks away). I placed it down, setting me as Owner. He then tried to make some Powercell Link Cards, which caused it to go into crashing mode again. I MCEdit it out again (The Modular Storage which I had cheated back in, got deleted again), and we haven't really touched it since.
**The conditions are as follows:** 
Me (Server OP) and another are teaming up.
We're together in a claimed area by FTBUtilities - he has Moderator rank, so he can interact with anything freely.
He was the Owner of the first Powercell, I (server OP) placed it down, sending it into Crash Mode.
I was the Owner of the 2nd Powercell, he tried to link cards to it, sending it into Crash Mode.

**Steps to reproduce:** 
Be 2 people in Multiplayer, may need claimed area by FTBU?
One places a Powercell down, setting Owner.
The other picks it up (may need OP), and places it back down
???
Profit?

Don't have time to test it further at this point

**Versions:**
* Minecraft: 1.12.2
* Forge: .2689
* McJtyLib:  2.6.7
* RFTools: 7.33

Relevant logs, if any: 
https://paste.dimdev.org/fujipaziqu.txt

**Comment by josephcsible** [comment]
Can you reproduce this without NuclearCraft?

**Comment by Lukas45** [comment]
Managed to reproduce it in SP
Happens when a Powercell is connected directly a NuclearCraft battery (the connected side set to Output), and the Powercell just errors out. If I put a wire between the 2, it works just fine (which is a fine workaround). Same modpack ofc.
