### ISSUE TITLE
Builder / Quarry filter doesn't discern between Thermal Foundation Ores

### ISSUE THREAD

**Issue by melbellrocks** [McJtyMods/RFTools#1767]
Issue description: I have a builder setup with a silk touch quarry card, with a filter in it to only get a few things I needed:  three vanilla MC ores and the certus and charged certus ores from AE2.  I found I was running low on nickel, so I add Thermal Foundation Nickel Ore to my filter, and now the builder gets the original stuff, plus ALL Thermal Foundation ores, not just nickel.

Steps to reproduce: I am currently playing on a FoolCraft 3 server, but I also created a single player world with only rftools, thermal foundation, jei, and all of their dependancies - and it happened in that world as well.  Same behavior, adding a thermal foundation ore to the builder filter allows all thermal foundation ores.

Screenshots for reference:
Builder GUI: https://imgur.com/EZ2SUsY
Shape Card GUI: https://imgur.com/hsGVKR7
Filter GUI: https://imgur.com/s8sLc9n

Versions:
* Minecraft: 1.12.2
* Forge: 14.23.3.2673
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: 1.12-2.6.7
* RFTools: 1.12-7.33

Possibly incompatible mods and versions: 

Relevant logs, if any:

**Comment by josephcsible** [comment]
Thermal Foundation's ores aren't different items. They're all the same item, just with different damage/metadata. To make the filter match on damage/metadata, click the "D" button in the filter GUI.

**Comment by melbellrocks** [comment]
Heh, well that explains it!  Thank you!
