### ISSUE TITLE
Crash when using tools to shift+rightclick on blocks/tileentities/etc (block protector?)

### ISSUE THREAD

**Issue by Matakor** [McJtyMods/RFTools#1768]
Issue description: title

Steps to reproduce: 

1. tool (yeta wrench in this example)
2. shift right click on anything to do something (e.g, break/pickup a conduit)
3. crash to desktop

Versions:
* Minecraft: 1.12.2
* Forge: 14.23.4.2705
* McJtyLib: 3.0.0-alpha
* RFTools: 7.50-alpha

Possibly incompatible mods and versions: Optifine, latest. shouldn't be relevant

Relevant logs, if any: https://pastebin.com/WNwY0vbj

**Comment by Matakor** [comment]
This error text from the minecraft log may be relevant as well: https://pastebin.com/raw/6GsEQwip

**Comment by Matakor** [comment]
Disabling the block protector in the cfgs does not bypass this.

**Comment by falkreon** [comment]
Experienced this while shift+rightclicking a Thermal Expansion portable fluid tank with a crescent hammer to collect it. Adding my crashlog to the pile. Hope it helps.

https://gist.github.com/falkreon/3aa277594893e681e0735e4d4ced0c04

**Comment by McJty** [comment]
Already fixed and ready for next release
