### ISSUE TITLE
Support copy/paste text in machines

### ISSUE THREAD

**Issue by skydark** [McJtyMods/RFTools#177]
As a Chinese linux minecrafter, I always use copy/paste to input Chinese in minecraft, like on vanilla signs, NEI search bar and AE terminal. However, if I paste text (no matter Chinese or English) in rftools machines such as storage scanner and text module of screen, they only show an unrecognizable character instead. Could you please add support to copy/paste in rftools machines?
And thanks for your awesome mod!

**Comment by NoX-programer** [comment]
Cyrillic symbols are affected too. Just try to name Matter Transmitter (Receiver) with some non-english word. Looks like the mod is totally unable to work with national letters.

**Comment by MichaelHillcox** [comment]
Unfortunately we're no longer supporting versions older than `1.12` and I don't have enough time to check this suggestion against all of the features of the mod but if this feature still hasn’t been implemented and you’d like to see it added to a newer version of the mod then please do create a new issue so we can review your suggestions again :+1:

**Comment by MichaelHillcox** [comment]
This being said, I'll also note that the translations in MC are much better and hopefully this has been resolved somewhere down the line :D
