### ISSUE TITLE
Clientside Crash (not sure if MouseTweaks or RFTools)

### ISSUE THREAD

**Issue by Vyraal1** [McJtyMods/RFTools#1770]
Issue description: 
Clientside crash when I tried to open the GUI of a powercell

Steps to reproduce: 

I tried to open a powercell GUI - https://hastebin.com/axohiqunuy.sql

Versions:
* Minecraft: 1.12.2
* Forge: 2705
* McJtyLib: 3.0.0-alpha
* RFTools: 7.50-alpha

Possibly incompatible mods and versions: 

None of any that I'm aware, this is on the Enigmatica 2 Expert modpack.

Relevant logs, if any: 

Crash report again - https://hastebin.com/axohiqunuy.sql

**Comment by IChris2698I** [comment]
I ran into this crash as well; same exception, same stack trace. I was successfully opening Powercells in a previous version of Enigmatica 2 Expert, which used rftools-1.12-7.33.jar

**Comment by josephcsible** [comment]
Should be fixed as of the final release of 7.50. Please confirm.
