### ISSUE TITLE
Mousetweaks interaction crash

### ISSUE THREAD

**Issue by Lukas45** [McJtyMods/RFTools#1771]
Issue description: 
When opening certain machines, it causes a client crash.
Which machine is affecting seems to be inconsistent. For my partner, it's moving items into the Modular Storage crafting with the JEI '+', but even that it's inconsistent
For me, it's opening the Crafter Tier 3's, which seems to be super consistent

Steps to reproduce: 
Open the GUI of a Crafter
???
Profit!

Versions:
* Minecraft: 1.12.2
* Forge: .2705
* McJtyLib: 3.0.0
* RFTools: 7.5.0

Possibly incompatible mods and versions: 
MouseTweaks 2.8

Relevant logs, if any: 
https://paste.dimdev.org/ejukipikiy.txt
Also reproduced in a test-client with only WAILA, JEI, RFT and MouseTweaks.

**Comment by CharCharthemonkey** [comment]
i can confirm as well happens to me too with rftools but on the cells
[crash-2018-06-04_15.55.48-client.txt](https://github.com/McJtyMods/RFTools/files/2069965/crash-2018-06-04_15.55.48-client.txt)
[crash-2018-06-04_16.01.45-client.txt](https://github.com/McJtyMods/RFTools/files/2069966/crash-2018-06-04_16.01.45-client.txt)

**Comment by McJty** [comment]
Please update McJtyLib
