### ISSUE TITLE
Client crash at logging in after teleport crash

### ISSUE THREAD

**Issue by fr4gus** [McJtyMods/RFTools#1772]
Issue description: Client keeps crashing when trying to log in after teleport crashed the client.v

Steps to reproduce: 
 Teleported using a Matter Trasmitter. I created a Destination Analyzer to check teleport was ok, and it was. During teleport, the client crashed, and now, I can't log into the server.

Versions:
* Minecraft: 1.12.2
* Forge: 14.23.3.2655
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib:
* RFTools: 1.12-7.50

Possibly incompatible mods and versions: 

Relevant logs, if any: 
This is the link for the crash report: https://gist.github.com/fr4gus/7046d9eeca7d2127cd79948415867c39

**Comment by McJty** [comment]
Already fixed and ready for next release

**Comment by winsrp** [comment]
same thing here, do you know when the next release might be up @McJty ?
