### ISSUE TITLE
Crash with FTBUtilities & Rftools Builder

### ISSUE THREAD

**Issue by raphydaphy** [McJtyMods/RFTools#1775]
Issue description: When logging in to a world which has an RFTools Builder running in  a chunk loaded by FTBUtilities, there is a chance it will crash the game with this report: https://pastebin.com/zKDBRddF

Steps to reproduce: Place an rftools builder (in a different dimension to the one you are in?), load the chunk with FTBUtilities, turn the builder on with a quarry shape card then leave the area and log out. When you log in there is a chance it will crash on loading.

Versions:
* Minecraft: 1.12.2
* Forge: 14.23.4.2705
* McJtyLib: 1.12-2.6.7
* RFTools: 1.12-7.33
* FTBUtilities: 5.0.2.14
* FTBLib: 5.0.2.14

Possibly incompatible mods and versions: Not using sponge or optifine. 

I also submitted this to the FTBUtilities issue tracker because I don't know which mod is at fault here.

**Comment by McJty** [comment]
Update RFTools and/or FTBUtilities will probably fix it

**Comment by raphydaphy** [comment]
yea it seems fine after updating both mods - sorry
