### ISSUE TITLE
Blocks Disappear when Wrenched

### ISSUE THREAD

**Issue by NillerMedDild** [McJtyMods/RFTools#1776]
Issue description: 
Shift-right clicking with any Wrench on a RFTools Tile Entity destroys it. This only happens when Tool Progression is present. I have tested in an instance with only Tool Progression, JEI, McJtyLib and RFTools. This did not happen in RFTools versions prior to the recent alpha/beta. I have also reported this to Tool Progression.

Steps to reproduce: 
Place Modular Storage
Shift-right Click with a SmartWrench

Versions:
* Minecraft: 1.12.2
* Forge: 1.12.2-14.23.4.2705
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: 1.12-3.0.0
* RFTools: 1.12-7.51
* ToolProgression-1.12.2-1.5.1

Possibly incompatible mods and versions: 

Relevant logs, if any:

**Comment by NillerMedDild** [comment]
https://github.com/tyra314/ToolProgression/issues/33

**Comment by tyra314** [comment]
Should be fine in the upcoming version [1.5.2](https://minecraft.curseforge.com/projects/tool-progression/files/2570720)

**Comment by LumberWizard** [comment]
@tyra314 it is in fact not fine, at least not in 1.5.4.

**Comment by tyra314** [comment]
@LumberWizard I just tested it in my dev env, it does indeed work for me. Please open an issue at [my mod's issue tracker](https://github.com/tyra314/ToolProgression/issues) detailing all versions used and if there are overrides done with ToolProgression.

**Comment by LumberWizard** [comment]
@NillerMedDild perhaps it's a config issue?

**Comment by NillerMedDild** [comment]
It's not a config issue, I just tested in an instance with only RFTools, JEI and Tool Progression, and the configs from E2E, and it worked just fine. So it's some other mod causing it.

**Comment by medtryx** [comment]
I just had this happen to me: A modular storage block disappear when when wrenched with a Flux-Infused Battle wrench in Enigmatica 2 Expert Version 1.41.

**Comment by NillerMedDild** [comment]
I don't think RFTools holds the blame for that :)

**Comment by tyra314** [comment]
Gosh. I guess it‘s tool progression...

A certain quartz infused axe is a wrench 🤔 that’s a new rabbit hole.
