### ISSUE TITLE
Power Relay i section does not stay visually enabled (goes back to red when closing the block)

### ISSUE THREAD

**Issue by krakaen** [McJtyMods/RFTools#1777]
Issue description: power relay I section does not keep the color blue when it is activated. Once you leave the block and come back, it shows as disabled, but it is still enabled

Steps to reproduce: 
use a power relay and click the i section to enable it, leave the block and reopen it. Tested on server.

Versions:
* Minecraft: 1.12.2
* Forge: 14.23.4.2705
* McJtyLib: 3.0.0
* RFTools: 7.51

**Comment by josephcsible** [comment]
The relay doesn't have any toggles for enabled/disabled, so I assume you mean the orange/blue toggles for input/output.

**Comment by josephcsible** [comment]
Will be fixed in the next release.
