### ISSUE TITLE
Builder Not Placing Items In Inventories / Dropping Them in World

### ISSUE THREAD

**Issue by Vyraal1** [McJtyMods/RFTools#1778]
Issue description: 

This is not the first time this has happened, I've quarried in the overworld successfully before without problems, but about 1/3rd of the time the blocks just get dropped in world, but I didn't manage to get it on video. 

This has happened with an RFTools Powercell powering it, or a Mekanism Quantum Entangloporter, and whenever it decides to  ignore inventories, it'll even refuse to insert into a vanilla chest. The end result is what when I go back to check on my quarry or take apart my builder, my framerate gets absolutely crushed by all of the item entities on the ground, requiring an command to delete all item entities, not to mention the lost output of the quarry itself.

Steps to reproduce: 

1) Place builder block, put quarry card in
2) Turn it on, watch fps drop.

https://www.youtube.com/watch?v=sMYORMVNVf0&feature=youtu.be

Made a video demonstrating the problem, I can't reproduce it 100% of the time, but it seems to drop coal blocks, and chisel blocks as mentioned earlier.

Versions:
* Minecraft: 1.12.2
* Forge: 2705
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: 1.12-2.6.7-SNAPSHOT
* RFTools: 7.33

Possibly incompatible mods and versions: 
Modpack is Enigmatica 2 Expert

**Comment by NillerMedDild** [comment]
I believe this is caused by Tool Progression, because the quarried blocks aren't part of the `blocks_overwrites` 
I'll report it there now.

**Comment by tyra314** [comment]
I'm trying to reproduce this issue, but I hadn't much luck. I tried it in my dev environment, a plain RFTools and TPr instance and in the Enigmatica 2expert pack, but I haven't seen this behavior once. @Vyraal1 could you walk me through the steps to reproduce the issue? Have you made any changes to the settings in the Builder GUI? Also, you mention the filter card, how did you set up the card? And what exactly was the outcome? Was the outcome any different from not using a filter card?

**Comment by NillerMedDild** [comment]
I was able to reproduce both with and without the filter.

**Comment by tyra314** [comment]
Okay, I found it and fixed it on my end in ToolProgression v1.5.3
