### ISSUE TITLE
Infuser not working

### ISSUE THREAD

**Issue by Keridos** [McJtyMods/RFTools#1779]
Issue description: 
Machine Infuser not working on builder

Steps to reproduce: 
Fill Machine Infuser with builder and dimensional shards.

Versions:
* Minecraft: 1.12.2
* Forge: 1.12.2-14.23.4.2703
* McJtyLib: mcjtylib-1.12-3.0.0
* RFTools: rftools-1.12-7.50

**Comment by josephcsible** [comment]
You'll need to be more specific than "not working". Can you upload a video of exactly what you're trying to do? Also, what other mods do you have installed? Does it work with only RFTools and its dependencies?

**Comment by McJty** [comment]
Fixed next release (will require an update of both McJtyLib and RFTools)
