### ISSUE TITLE
Crash with RFTools 7.52 and Botania

### ISSUE THREAD

**Issue by unikmhz** [McJtyMods/RFTools#1785]
Issue description: 
Weird interaction between RFTools (possibly McJtyLib), Botania and Baubles leading to a crash.

Steps to reproduce: 
1. Equip "The Spectator" bauble from Botania.
2. Go near an RFTools matter transmitter.
3. Press sneak key (shift).
4. Observe the crash.

Versions:
* Minecraft: 1.12.2
* Platform: Linux x86_64, MultiMC, Oracle JDK 1.8.0_172
* Forge: 2707
* McJtyLib: 3.0.1 (mcjtylib_ng)
* RFTools: 7.52

Possibly incompatible mods and versions: FoamFix (tried with both anarchy and lawful), VanillaFix (which actually caught this crash and identified 3 mods involved).

Crash report and detailed modlist: 
[crash-2018-06-12_21.56.14-server.txt](https://github.com/McJtyMods/RFTools/files/2095461/crash-2018-06-12_21.56.14-server.txt)

**Comment by unikmhz** [comment]
Additional info: when MMcJtyLib and all dependent mods are downgraded to pre-3.0.0 version (2.6.7 in my case), without touching any other mods, the crash disappears and everything works as intended.

**Comment by josephcsible** [comment]
Probably caused by 9cecac8

**Comment by McJty** [comment]
Fixed next release
