### ISSUE TITLE
[issue] Going to the end and back with the charged porter breaks GUIs

### ISSUE THREAD

**Issue by winsrp** [McJtyMods/RFTools#1786]
Issue description: 

Going to the end and back with the charged porter wont allow me to open the modular storage screens, gonig on an elevator, doesn't picks the middle floors correctly leaving me on the base floor, powercell gui doesn't work either etc..

In order to fix it, I need to log out of the server and log back in. 

Dying in the end which takes me back to the overworld seems to avoid this issue, as everything works fine.

* RFTools: 7.51

**Comment by Zarkov2** [comment]
I am seeing the same problem using RFTools 7.51 (ATM3 5.9.5 and 5.9.7b) and Matter Transmitter / Receiver.

The following message appears in the log when going back from The End:
`[20:49:25] [Server thread/WARN] [net.minecraft.world.WorldServer]: Force-added player with duplicate UUID < uuid value >`

The message does not appear when going to The End using matter transmitter / receiver, and it doesn't appear if I return from The End using another method (e.g. DE Advanced Dislocator).

Once the problem happens, RFTools crafter GUI cannot be opened. It will flash briefly for a frame or so, then vanish. Also, Thermal Expansion machines will no longer get GUI updates. The GUIs on TE machines needs to be closed and reopened to see progress.

**Comment by xxMattewxx** [comment]
May be related to this issue, posted recently here: https://github.com/McJtyMods/RFTools/issues/1747

**Comment by josephcsible** [comment]
Will be fixed in the next release of McJtyLib.
