### ISSUE TITLE
Colour choosing in a screen module crashes client

### ISSUE THREAD

**Issue by 016Nojr** [McJtyMods/RFTools#1787]
When choosing colour for text on a screen, holding down the left mouse button and "drag" the cursor outside the colour window crashes the game

Versions:
* Minecraft: 1.12.2
* Forge: 14.23.4.2705
* McJtyLib: 3.0.0
* RFTools: 7.50

[Crash log](https://gist.github.com/016Nojr/42b5525474ee60a64b958b7f4913a0ac)

**Comment by nataliejean2412** [comment]
I just got a nearly identical crash trying to click the RGB values in a module.

[Crash Log](https://paste.ee/p/Bn2aP)

**Comment by Jizanthapus** [comment]
Me too 
[Crash Report](https://paste.ee/p/KGU40)

**Comment by josephcsible** [comment]
Will be fixed in the next release of McJtyLib. In the meantime, you can avoid the crash by making sure you release the mouse button before moving the mouse outside of the color picker area.
