### ISSUE TITLE
Machine infuser will not infuse Builder

### ISSUE THREAD

**Issue by Taconite12** [McJtyMods/RFTools#1788]
Issue description: 

When trying to infuse the builder, it will not infuse.
Power, dimensional shards, and the builder are all provided to the infuser but nothing happens

Steps to reproduce: 

1. place machine infuser in the world
2. fill with power
3. place dimensional shards in machine infuser
4. place builder in machine infuser
5. nothing happens

Versions:
* Minecraft: 1.12.2
* Forge: 14.23.4.2705
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: 1.12-3.0.0
* RFTools: 1.12-7.50

Possibly incompatible mods and versions: 

Relevant logs, if any:

**Comment by josephcsible** [comment]
This has been fixed since 2 releases ago. You're 3 releases behind.

**Comment by Taconite12** [comment]
Dang sorry about that, I thought FTB would have put the most up to date
version in the pack
