### ISSUE TITLE
crash when putting items into a remote storage from a tablet

### ISSUE THREAD

**Issue by Delerium** [McJtyMods/RFTools#1789]
Issue description: 
When putting an item into my tablet that is linked to a remote storage, I crash to desktop.  Remote storage itself works fine in a modular storage block, just not the tablet.

Steps to reproduce: 
open tablet linked to remote storage and try and put an item into it.

Versions:
* Minecraft: 1.12.2
* Forge: 2705
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: 3.0.1
* RFTools: 7.53

Possibly incompatible mods and versions: 
Optifine

Relevant logs, if any: 
[crash-2018-06-15_15.22.12-client.txt](https://github.com/McJtyMods/RFTools/files/2107409/crash-2018-06-15_15.22.12-client.txt)

**Comment by ShadwDrgn** [comment]
This also bugs when taking an item out. RFTools and mcjtylib are my only mods. Though i'm on 7.50. Any interaction at all with a tablet using remote storage seems to crash the client. forge 2705
Here's my crash report.
[crash-2018-06-17_12.42.04-client.txt](https://github.com/McJtyMods/RFTools/files/2109192/crash-2018-06-17_12.42.04-client.txt)

**Comment by McJty** [comment]
Fixed next version
