### ISSUE TITLE
Crash when opening environmental controller

### ISSUE THREAD

**Issue by Habeeb-M** [McJtyMods/RFTools#1795]
Issue description: Crash when opening environmental controller

Steps to reproduce: Not sure, I opened my environmental controller and it crashed. I am on a server.

Versions:
* Minecraft: 1.12.2
* Forge: 8.0.99.99
* McJtyLib: 1.12.2-3.0.0
* RFTools: 1.12.2-7.50

Possibly incompatible mods and versions: Using SpongeForge

Relevant logs, if any: https://gist.github.com/Habeeb-M/5e51ba643b3e7b1a74ffc9069b78d225

**Comment by josephcsible** [comment]
Your McJtyLib and RFTools versions are both outdated. See if it still happens when you update.

**Comment by Habeeb-M** [comment]
I'll have to ask the server owner to update.

**Comment by josephcsible** [comment]
Any update on this? Also, assuming it still crashes for you, can you try this build and post the crash log it gives? [mcjtylib-1.12-3.0.2+f2de7c9.zip](https://github.com/McJtyMods/RFTools/files/2174000/mcjtylib-1.12-3.0.2.f2de7c9.zip)

**Comment by Habeeb-M** [comment]
The server had a recent , so I can't test right now. If the issue pops up again, I'll reopen this.
