### ISSUE TITLE
Shield Generators do not retain infused % when boundaries are set (wrench use) (1.12.2)

### ISSUE THREAD

**Issue by KiraMaelstrom** [McJtyMods/RFTools#1797]
Issue description: Shield Generators do not retain infusion charge on second state

![2018-06-24_21 50 38](https://user-images.githubusercontent.com/40530714/41830914-ae547bb8-77f8-11e8-9cc0-6a126e3129bf.png)
![2018-06-24_21 50 30](https://user-images.githubusercontent.com/40530714/41830915-ae6b050e-77f8-11e8-8cd3-eb7d3ca9ed21.png)

Steps to reproduce: Broke shield gen/replaced. Tried new shield gen. Went to SP world

* Minecraft: 1.12.2
* Forge: recommended
* CompatLayer (only if on Minecraft 1.10 or 1.11): latest
* McJtyLib: latest
* RFTools: lastest
* OptiFine IS in use

**Comment by josephcsible** [comment]
The issue template specifically says to say actual version numbers, not just ”latest”.

**Comment by KiraMaelstrom** [comment]
* Minecraft: 1.12.2
* Forge: 14.23.3.2655 (1.12.2)
* McJtyLib: 1.12-2.6.7-SNAPSHOT
* RFTools: 1.12-7.33
* OptiFine In Use - OptiFine_1.12.2_HD_U_D2

**Comment by McJty** [comment]
Well that's definitely not latest. Can you upgrade to latest and try again?

**Comment by KiraMaelstrom** [comment]
Give me a few to update and test. If it is the issue, I'll be talking with server host to update.

**Comment by KiraMaelstrom** [comment]
Cool. Client crashes entirely. I'll have to test further tomorrow when I have more time.
[crash-2018-06-24_23.31.48-client.txt](https://github.com/McJtyMods/RFTools/files/2131967/crash-2018-06-24_23.31.48-client.txt)

**Comment by McJty** [comment]
You'll have to update all mods using mcjtylib
