### ISSUE TITLE
redstone transmitter and receiver blocks do not show up in vanilla creative menu

### ISSUE THREAD

**Issue by AtomicBlom** [McJtyMods/RFTools#1798]
Issue description: 
Attempting to load a clean instance of Forge with only McJtyLib and RFTools does not make transmitter or receiver available to creative menu.

Steps to reproduce: 
1. Create a blank instance of Minecraft, install Forge
2. Add McJty Lib and RFTools
3. Search for "Redstone" in the creative menu (or peruse the RFTools tab)
4. Observe that Redstone Receiver and Redstone Transmitter are missing.

Versions:
* Minecraft: 1.12.2
* Forge: 14.23.3.2702
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: 1.12-3.0.2
* RFTools: 1.12-7.54

Possibly incompatible mods and versions: 

Relevant logs, if any:

**Comment by McJty** [comment]
Fixed next release (even before you submitted thick ticket! I can predict the future :-) )

**Comment by AtomicBlom** [comment]
Cheers mate ;)

I was just typing up a big long investigation into the issue :P
