### ISSUE TITLE
Multiple crashes in Coop Life 2

### ISSUE THREAD

**Issue by TheDarkPreacher** [McJtyMods/RFTools#1801]
Issue description: Had a client crash when scrolling in the storage scanner that was reading off a Refined Storage Interface. SOTMead had a different crash involving the Remote Storage Tablet.

Steps to reproduce: Crash 1: Scroll through the storage scanner with many items rendered. Crash 2: Attempt to pull items out of the remote storage tablet.

Versions:
* Minecraft: 1.12.2
* Forge: 14.23.4.2705
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: 1.12-3.0.1
* RFTools: 1.12-7.53

Possibly incompatible mods and versions: 

Relevant logs, if any: 
Crash 1:
https://pastebin.com/7Z3Wet3u
Crash 2:
https://pastebin.com/76zrJUWx

Additional note: This issue will be cc'd to Vaygrim as well, so the GrimCo team can have a look.

**Comment by josephcsible** [comment]
Please report Crash 1 to Tech Reborn's issue tracker.

**Comment by TheDarkPreacher** [comment]
If I may, why? Tech Reborn isn't referenced in the crash report, and it wasn't a Tech Reborn item that caused the crash.

**Comment by josephcsible** [comment]
Lines 18 through 20 indicate that it was involved.

**Comment by josephcsible** [comment]
Can you verify if the latest builds of Reborn Core and Tech Reborn fix this?
