### ISSUE TITLE
PacketGetMonitorLog.java:40 is loading chunks outside main thread

### ISSUE THREAD

**Issue by LemADEC** [McJtyMods/RFTools#1802]
Issue description: 
PacketGetMonitorLog.java:40 is loading chunks outside main thread

Steps to reproduce: 
Investigating lag on FTB Continuum

Versions:
* Minecraft: 1.12.2
* Forge: 14.23.4.2707
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: 1.12-3.0.1
* RFTools: 1.12-7.53

**Comment by McJty** [comment]
Oh that's indeed wrong. But is this the cause for log? I will fix it anyway

**Comment by LemADEC** [comment]
I've a crap log of lag issues with RFTools right now, trying to sort it out.
I suspect some X and Z coordinates are inverted in the power cell network too.

**Comment by McJty** [comment]
Well this one is fixed next release (soon). Make other tickets if you find other issues. Thanks for reporting
