### ISSUE TITLE
Console spam with PowerCellTileEntity:buildNetwork:384

### ISSUE THREAD

**Issue by LemADEC** [McJtyMods/RFTools#1803]
Issue description: 
Console spamming 40x per second with
```
[04:16:55] [Server thread/INFO] [STDOUT]: [mcjty.rftoolspower.blocks.PowerCellTileEntity:buildNetwork:384]: Bad network at pos = BlockPos{x=-1536, y=129, z=-1547}
[04:16:55] [Server thread/INFO] [STDOUT]: [mcjty.rftoolspower.blocks.PowerCellTileEntity:buildNetwork:384]: Bad network at pos = BlockPos{x=-1536, y=129, z=-1547}
```
Steps to reproduce: 
Investigating lag on FTB Continuum when a player join his Advanced Rocketry base in space around DIM2 (2559 128 -1534).
There's no blocks in any dimension at those coordinates (except for AE2 storage space being filled with its filler block).

Versions:
Minecraft: 1.12.2
Forge: 14.23.4.2707
CompatLayer (only if on Minecraft 1.10 or 1.11):
McJtyLib: 1.12-3.0.1
RFTools: 1.12-7.53

Suggestion:
Specify the dimension in such logs, and clear the data since it's invalid?

**Comment by McJty** [comment]
Hmm, the fact that this error occurs is a bad sign. The only way I can see this happening if there were powercells at some spot and the dimension that contained those cells was regenerated for example. In any case. I'll add more diagnostics info to be able to figure out where it is going wrong and try to avoid repeating the message (only report it once)

**Comment by LemADEC** [comment]
is there any easy way to clear the data source in the mean time?

**Comment by LemADEC** [comment]
We had to reset all AdvancedRocketry dimensions due to serious issue in that mod (i.e. deleting the dimension folder). If RFTools store information for those dimension outside the DIMx folder, it's possible it created that issue.

**Comment by McJty** [comment]
Hmm. I'm going to provide you with a version of RFTools Power that fixes this already (but only server side so clients will not have to update) as I don't know how this can actually occur

**Comment by McJty** [comment]
See discord

**Comment by LemADEC** [comment]
Thanks!
Patch has been deployed on both Continuum and Revelation, we'll see how it goes.

**Comment by ThorVonAwesome** [comment]
Any chance this patch can be made public? I have the same issue on my server as well.

**Comment by McJty** [comment]
It has been released yesterday
