### ISSUE TITLE
High CPU usage with Tier3 Crafter

### ISSUE THREAD

**Issue by LemADEC** [McJtyMods/RFTools#1804]
Issue description: 
As observed with LagGoogles, a Tier3 crafter is using ~6ms per tick while crafting octuple compressed cobblestone:
![image](https://user-images.githubusercontent.com/4776032/42056982-30d0abfe-7b1c-11e8-87c0-415157f3e773.png)
![image](https://user-images.githubusercontent.com/4776032/42057000-3c8cbe92-7b1c-11e8-9458-5a8dcc014772.png)

Versions:
* Minecraft: 1.12.2
* Forge: 14.23.4.2707
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: mcjtylib-1.12-3.0.1
* RFTools: rftools-1.12-7.53

Possibly incompatible mods and versions: 
LagGoggles-SPONGEFORGE-1.12.2-4.1
spongeforge-1.12.2-2705-7.1.0-BETA-3217

Reducing crafter speedOperation from 5 to 1 helped a bit, but it's still too high:
![image](https://user-images.githubusercontent.com/4776032/42058646-58beba48-7b21-11e8-8f72-635512420526.png)

**Comment by McJty** [comment]
This is normal. The crafter is doing a lot of things which would normally require a more complicated setup and several blocks. Not sure this can be optimized a lot further

**Comment by LemADEC** [comment]
Even in slow mode and reduced operation is up to 2.4 ms/t now.

**Comment by LemADEC** [comment]
Why closing a live issue?

**Comment by MichaelHillcox** [comment]
McJty stated that there isn't much more he can do to resolve the issue and by the looks of it slow mode partially resolve the issue? Also, a note to this issue, the operations you are doing lag on most mods I've seen that support compressing items. StorageDraws particually die when you do this operation for compressed cobble. (Not sure if they've fixed that yet)
