### ISSUE TITLE
Storage Scanner/Storage Tablet 

### ISSUE THREAD

**Issue by icedwarr** [McJtyMods/RFTools#1805]
Issue description: I am running RFTools from the "FTB Revelation 2.1.0 modpack".
I have been using a remote storage system using the storage scanner, storage tablet and a couple modular storage with Yabba barrels for dirt/cobblestone.
The problem is that when taking stacked items such as dirt or cobblestone (even if they are inside a modular storage block) it simply doesn't allow me to take them, or if it does its at most one stack.

Steps to reproduce: 
1. Setup a normal storage system using the storage scanner, tablet and modular storage blocks.
2. Add a few stackable items (10 stacks of dirt) and nonstackable items (potions, armor, weapons)
3. Try taking out the items, when clicking the stackable items you will notice that they cannot be pulled out unlike the nonstackable items which work.
4. To try and help I've made and uploaded a video showing the problem. https://youtu.be/LHlNscvAyg4

Versions:
* Minecraft: 1.12.2
* Forge: 14.23.4.2705
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: 1.12-3.0.1.jar
* RFTools: 1.12-7.53.jar

I am using optifine, 1.12.2_HD_U_D2

**Comment by jinks** [comment]
The same issue exists with v7.54 in the DW20 pack.

I can't take any item out of the scanner that has more than one stack (usually count > 64).

**Comment by icedwarr** [comment]
The problems are similar yes, but I didn't intend to copy a issue.

This is also done using only RFTools, you could easily exclude the Yabba barrels and the problem would still exist.

I apologize if this is considered a ripoff of issue #1793, I will remove it if anyone else considers so..

**Comment by McJty** [comment]
This has me totally baffled... I cannot reproduce this no matter what I do. Is this single player or server btw? Also from what version on did this start fo fail?

**Comment by McJty** [comment]
Ok. a few questions and an experiment.

a) does it fail from the storage tablet and from the scanner directly or only from the tablet?
b) does requesting a single item work in all cases (i.e. shift click)

Also I made a debug version to help diagnose this problem which is available here:

http://jenkins.k-4u.nl/job/RFTools%201.12/lastSuccessfulBuild/artifact/build/libs/rftools-1.12-7.54.jar

It would help a lot if you could try to reproduce this issue with this version. In the log it should show 'REQUEST ATTEMPT' blocks. I'm interested in those. Thanks!

**Comment by McJty** [comment]
So any news? Is this bug still there? Anyone has been able to test this with my debug version?

**Comment by icedwarr** [comment]
Sorry I haven't been playing for a while, I'll test it out now.

**Comment by icedwarr** [comment]
Update: After playing with the new version for a bit the bug does still exist, McJty if you don't mind show me how you are trying to replicate the bug. Perhaps I can see what you might be doing different.

Also I do believe AstralSorcery is causing this bug. Try testing the bug with a modpack (In revelations2 the bug is 100% present)

**Comment by McJty** [comment]
But can you try to reproduce the bug with the debug version I pasted above? And then show me the log
