### ISSUE TITLE
Version 7.54 - All Powercells have the same icon

### ISSUE THREAD

**Issue by BillboardEric** [McJtyMods/RFTools#1808]
![image](https://user-images.githubusercontent.com/8685981/42398203-ee663da8-8136-11e8-8729-a4be6233d646.png)
![image](https://user-images.githubusercontent.com/8685981/42398218-fa3ffd94-8136-11e8-9546-d3867bd3b52e.png)
![image](https://user-images.githubusercontent.com/8685981/42398228-04e700bc-8137-11e8-8d67-d27bc0409765.png)

This may be intended but not sure.

I even tested on an instance with just RFTools w/ their libraries and JEI

Forge 2729
Latest McJtyLib

**Comment by josephcsible** [comment]
Same underlying problem as McJtyMods/XNet#288. Just as per that one, downgrading to Forge 2715 will work around this until it's properly fixed.

**Comment by josephcsible** [comment]
Will be fixed in the next release.
