### ISSUE TITLE
[Feature] Limit number of items a crafter will keep in stock.

### ISSUE THREAD

**Issue by Lodran** [McJtyMods/RFTools#181]
I've been setting up crafters to produce Solar Expansion solar panels, and I'm finding that the crafters waste a lot of materials by building entire stacks of items when only a small number are needed.

It would be nice to be able to configure the stack size of a crafter's inventory on a per-slot basis.

**Comment by McJty** [comment]
While that could be useful I'm not sure how to actually do this in a way that the user can understand. How would you actually configure this in the GUI?

**Comment by Lodran** [comment]
The simple approach would be something similar to the Ender IO crafter, which has a single toggle button which switches between "Buffering Single Items" and "Buffering Item Stacks".

The Ender IO crafter applies the buffer limit to it's input side.  A better approach would be to apply the limit to both sides.

In your case, the button would control buffering on a per-recipe basis, would buffer the number of items needed to fulfill the recipe, and also limit the crafter's output inventory to one item (or two, if the "keep" option has been selected).

A more complex approach (for those wanting to tweak performance) would be to use up/down buttons to adjust the number between single items and full stacks.

**Comment by NoX-programer** [comment]
IMHO, the best way it was done by Logistic pipes mod - take a look of Logistics Crafting Table. However, we can try to do the clever with RFTools crafter by supporting exact quantity of items with Translocators (Translocator mod). And sorry for advertising other mods.

**Comment by MichaelHillcox** [comment]
As this would seem to add a large amount of complexity to the visual configuration of the block. I'd suggest using another mod for achieving the desired effect.
