### ISSUE TITLE
Crash while trying to open coal generator GUI

### ISSUE THREAD

**Issue by mcdodge34** [McJtyMods/RFTools#1810]
I'm using the foolcraft 3 pack with some mods added (advanced rocketry, mystical agriculture, ender utilities, random things, cloche call, mystical agraditions), I just created my first coal generator for this game, then I get this crash related to rendering screen https://pastebin.com/Za1ThY0p

Forge version : forge-14.23.4.2705
Mcjtylib version : 1.12-3.0.2
Rftools version : 1.12-7.54

**Comment by josephcsible** [comment]
Can you try this build of McJtyLib and post the crash log it gives? [mcjtylib-1.12-3.0.2+f2de7c9.zip](https://github.com/McJtyMods/RFTools/files/2174000/mcjtylib-1.12-3.0.2.f2de7c9.zip)

**Comment by mcdodge34** [comment]
Launching the game at this moment, be patient, you'll have your answers, should I test it on server or local singleplayer would work, I can create a test server if needed.

**Comment by josephcsible** [comment]
Doesn't matter. Anywhere that you can reproduce the crash is fine.

**Comment by mcdodge34** [comment]
Hum, no crash when I try to open the coal generator with this version, will fireup a test server real quick to make sure its not a server related issue.

**Comment by josephcsible** [comment]
Odd. This build definitely doesn't fix the crash; it just makes the output more useful.

**Comment by mcdodge34** [comment]
Very strange, no problem with this build, should I try other blocks perhaps

**Comment by josephcsible** [comment]
Perhaps the crash is intermittent. Just keep running that build until it happens again, I guess.

**Comment by mcdodge34** [comment]
I'm firing up the old version to confirm if it happens again on my server, will keep watching this topic if it happens again once I'm using more rftools stuff

**Comment by mcdodge34** [comment]
Must be a random crash, can I suspect foamfix here, I know this mod does things differently, and more than once I remove it and find out the crashes don't happen anymore. Anyways, I'll drop the new version in my server this afternoon once I have time to restart it, for now, I need to go to work, I just got a call

**Comment by josephcsible** [comment]
Not FoamFix. A lot of people have been having this exact crash, and not all of them have FoamFix.

**Comment by mcdodge34** [comment]
Strange thing is I tried to google it first, usually when I copy a part of the crashlog I get to a github issue, but not this time, taxi just came to pick me up, will be back later (GMT-4 here)

**Comment by TherminatorX** [comment]
Getting the same crash here, was trying to open a T3 crafter.
Crashed twice to make sure, took all me gear off to see if that was it and crashed again, used the posted build and didn't crash, switched back to regular lib 3.0.2 and crashed once more.
https://pastebin.com/UmGQdgT1

Will use the posted build for a while with regular play and post again if a crash happens.

**Comment by josephcsible** [comment]
If the trend of only the normal build making it crash continues, let me know and I'll make a new custom build that might trigger it. Also, can you check the regular logs generated from the debug build to see if they have any errors that didn't cause a crash?

**Comment by TherminatorX** [comment]
Well I keep my Game Output tab loaded while playing, and this happens whenever I open the window:

> [main/ERROR] [mcjty.lib.varia.Logging]: java.lang.RuntimeException: Internal error! getSideWindowBounds() called before initGui!

Also sometimes this will get puked up shortly after (noticed it happen during the other build's non-crashes too):
https://pastebin.com/fHNxJqgu

**Comment by josephcsible** [comment]
Can you try this build? It should definitely give you a useful crash report. https://github.com/josephcsible/McJtyLib/releases/download/1.12-3.0.2%2Bblamingnonnulllist/mcjtylib-1.12-3.0.2+blamingnonnulllist.jar

**Comment by josephcsible** [comment]
Hmm, this gets weirder and weirder. How about this one: https://github.com/josephcsible/McJtyLib/releases/download/1.12-3.0.2%2Bblame2/mcjtylib-1.12-3.0.2+blame2.jar

**Comment by mcdodge34** [comment]
Will try tomorrow, very strange behavior, its really random.

**Comment by TherminatorX** [comment]
Alright, that version does crash me when opening up my crafter, but it's got new lines of code it's pointing to as the reason, guessing that's your work.
https://pastebin.com/WPywMf2p

**Comment by TherminatorX** [comment]
Any update on this @josephcsible?

**Comment by josephcsible** [comment]
We discovered it's caused by NEI. Uninstall that and it will stop crashing. The next release of McJtyLib will have a change that works around the crash, but it doesn't actually fix the bug (only NEI can do that), so it might cause it to behave weirdly.

**Comment by mcdodge34** [comment]
Sad trombone playing here... RIP NEI, very useful till Minecraft 1.10 was released and we saw JEI taking its place, aside from the F7 + F9 options that were awesome and perhaps their cheaty magnet mode and trash can, I won't miss it that much, we got replacements to cover theses, I can't figure out what else could NEI do that JEI doesn't.

**Comment by josephcsible** [comment]
Looks like literally everything NEI does can also be done by at least one other mod now:

https://docs.google.com/spreadsheets/d/1NEWZjKvWB-SibY1BXc1zoYkK7AhjMMBZess9wMy--6w/htmlview#gid=0

**Comment by josephcsible** [comment]
Per #1815, this should have been fixed for over a year now.
