### ISSUE TITLE
Right clicking auto crafter t3 crash

### ISSUE THREAD

**Issue by Pythonic-Rainbow** [McJtyMods/RFTools#1815]
Versions:
* Forge: 2732
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: 3.0.2
* RFTools: 7.55

https://pastebin.com/neqjKcWL

**Comment by McJty** [comment]
We are aware of this and currently our theory is that this is a bug in NEI which has a thread that causes the gui to be used wrong.

**Comment by Pythonic-Rainbow** [comment]
@McJty thanks for the quick reply. So.. what shall I do? Downgrade the mod to 7.54?
I remember I submitted a similr issue back in 7.20

**Comment by Pythonic-Rainbow** [comment]
Hey btw, it was working before until I updated
Chisel & Bits
CrayFish Furniture
Waystones

**Comment by McJty** [comment]
Downgrading will not fix it. The bug is in NEI. Not in our mods

**Comment by Pythonic-Rainbow** [comment]
But I didn't update NEI. It used to work until I updated the above mods

**Comment by josephcsible** [comment]
Can you try temporarily removing NEI to confirm that it works right without it?

**Comment by Pythonic-Rainbow** [comment]
The problem is it works again now.... It sometimes don't work and sometimes work
Without changing anything :(

**Comment by McJty** [comment]
yes, that's the symptom which we also experienced. Without NEI it should work all the time. With NEI it works sometimes

**Comment by McJty** [comment]
Yes but nothing we can do from our side. Perhaps report to NEI while referring to this ticket

**Comment by covers1624** [comment]
Don't exactly understand why and how this could be NEI.. It's completely ASM free and works purely on events now, and only item panel refreshes are done on a separate thread and that is completely separate from what ever gui you have open.

**Comment by covers1624** [comment]
I have a fix for this, Feel free to close this.

**Comment by McJty** [comment]
Thanks @covers1624 !
