### ISSUE TITLE
 Builder does not count EnderIO Dimensional Tranceiver as valid liquid tank

### ISSUE THREAD

**Issue by LuciusV** [McJtyMods/RFTools#1817]
Issue description: Builder does not count EnderIO Dimensional Tranceiver as valid liquid tank

Steps to reproduce: 

Put down RF Tools Builder and EnderIO Dimensional Tranceiver on top of it. Builder will be able to collect blocks and put it into Tranceiver or place blocks taking them from Tranceiver. Builder will not be able to push/push liquids (capability which Tranceiver definitely has).

Versions:
* Minecraft: 1.12.2
* Forge: 1.12.2-14.23.4.2705
* McJtyLib: 1.12-3.03
* RFTools: 1.12-7.55

**Comment by McJty** [comment]
Not an issue on our side. Rftools follows the standard fluid capability system and works fine with other modded tanks

**Comment by HenryLoenwind** [comment]
cc'ed: The Dimensional Transceiver is not a tank, it it a fluid transport system. It tries to input fluids into the builder, but as the builder also is no tank, that fails.

**Comment by LuciusV** [comment]
So, it is impossible to use one builder for both liquids and items, hence it only can work with block above it which can either be liquid tank or item container?
