### ISSUE TITLE
[1.12.2] Client crash when changing color of elevator buttons.

### ISSUE THREAD

**Issue by Hazmatik** [McJtyMods/RFTools#1818]
Issue description: Client crashes when changing the color of the elevator buttons in the elevator button module in the screen GUI using the color picker.

Steps to reproduce: 
Install elevator button module
Try to change the color

Versions:
* Minecraft: 1.12.2
* Forge: forge-14.23.4.2705
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: 1.12-3.0.1
* RFTools: 1.12-7.53

Possibly incompatible mods and versions: 
Modpack is FTB Continuum version 1.3.1

Relevant logs, if any: 
https://pastebin.com/NuUWhiNG

**Comment by McJty** [comment]
Can you update to more recent versions of mcjtylib and rftools and see if the bug still occurs. I'm on vacation right now so can't do much more

**Comment by ParadoxBomb** [comment]
Issue description: 
Client crash when clicking on the numbers of the color picker in the Screen button module

Steps to reproduce:
1) Place Screen
2) Place Button Module in Screen
3) Sneak-click to open GUI
4) Select the color picker for the button label
5) Click on one of the color values
6) CTD

Versions:

    Minecraft: 1.12.2
    Forge: 14.23.4.2739
    CompatLayer (only if on Minecraft 1.10 or 1.11):
    McJtyLib: 1.12-3.0.3
    RFTools: 1.12-7.55

Possibly incompatible mods and versions:

Relevant logs, if any:
https://pastebin.com/LVR7mdp7

**Comment by Hazmatik** [comment]
Looking more at it, it seemed to do fine when picking a solid color from the color picker but if I try to pick one below the line where the colors start to have "transparency" to them is when the crash occurs.

**Comment by josephcsible** [comment]
Will be fixed in the next release of McJtyLib. In the meantime, you can avoid the crash by making sure you release the mouse button before moving the mouse outside of the color picker area.
