### ISSUE TITLE
[1.12] Matter Beamers waste all resources

### ISSUE THREAD

**Issue by BonaireDreams** [McJtyMods/RFTools#1819]
Issue description: Not sure if working as intended or bug. Matter beamers wasted 25k seeds, 29k wheat and 19k carrots overnight with spawner "turned off". Turned off meaning no nether star material to actually spawn withers.

Steps to reproduce: 

I created a wither farm using 1 RFtools spawner and 4 matter beamers. I manually added 3 nether stars to one beamer and 512 soul sand to another. Then, because the beamers take so long adding the material (even enfused) I had Xnet pipes adding wheat, seeds and potatoes to all 4 beamers. I carried on working around my base then turned on the spawner as I don't trust wither's when I'm not around. After spawning and killing all the withers I had Nether Star material for I left the beamers on to stock up the wheat/seed/potatoe material for the next run. Unfortunately I forgot to turn it back off. When I checked back the next morning the spawner was full with 6400 material, but all seeds, potatoes & wheat in my storage was gone.

Should the beamers not stop when the spawner is full?

Versions:
* Minecraft: 1.12.2
* Forge: 14.23.4.2732
* McJtyLib: 3.03
* RFTools: 7.55

Relevant logs, if any:

**Comment by McJty** [comment]
This is actually as intended. The spawners actually don't have the concept of being full. It is perfectly legal to overload a certain value with something. For example, you can put a ton of living material in a spawner and only when you actually want to spawn a few withers you insert the nether star

**Comment by BonaireDreams** [comment]
Your comment seems to contradict itself or maybe I'm not reading it right. In my example the spawner did have a concept of being "full" as it stopped accepting living material after it was at 6400. All the other (several hundred thousand) living material was just destroyed as the beamers kept feeding the spawner all night but it never accepted any after it reached 6400. My intention was to preload it with living material and do just as you suggest, throw in a few nether stars when needing to spawn withers. But if the Beamers continue to push material into the spawner, it should continue to accept it and not stop at 6400 allowing the remaining material to be destroyed.

**Comment by McJty** [comment]
Hmm weird that it stopped accepting living material. That shouldn't have happened

**Comment by BonaireDreams** [comment]
I havent run it in a bit and there's been some updates. I'll test it in the next day or 2 and open a new case with details if it still does it.
