### ISSUE TITLE
[1.7.10] Twilight forest crash

### ISSUE THREAD

**Issue by TomTheHero** [McJtyMods/RFTools#1824]
Steps to reproduce: Unknown

Versions:
* Minecraft: 1.7.10
* Forge: 10.13.4.1614
* McJtyLib: Unknown
* RFTools: rftools-4.23

Possibly incompatible mods and versions: 
Thermos Version: ca.tcpr:Thermos:1.7.10-1614.56
fastcraft-1.23

Crash report: https://pastebin.com/aVVAvKFC

**Comment by josephcsible** [comment]
1.7.10 isn't really supported anymore.

**Comment by TomTheHero** [comment]
And yet it remains the most commonly used version and by far the most efficient one aswell

**Comment by McJty** [comment]
1.7.10 had stopped being the most popular version some time ago. These days FTB forums and Reddit are all about 1.12. besides it really is too much work to support multiple versions of Minecraft. I have about 26 mods
