### ISSUE TITLE
Crashing when trying to open crafter

### ISSUE THREAD

**Issue by KSIxxr3b3l** [McJtyMods/RFTools#1825]
Issue description: world crash when trying to open crafter tier 3

Steps to reproduce: i've got a yabba barrel connected to a garden cloche that is pumping mystical ag inferium into the crafter using itemduct and servo.

Versions: 
* Minecraft: 1.12.2
* Forge: latest
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: 3.0.3
* RFTools: 7.55

Possibly incompatible mods and versions: fastcraft

Relevant logs, if any: https://paste.dimdev.org/volabeyoga.mccrash

**Comment by McJty** [comment]
Known and it's a bug in NEI. Until fixed remove that mod to avoid this

**Comment by MauveCloud** [comment]
> Minecraft: 1.12.2

> Possibly incompatible mods and versions: fastcraft

Wait, what?  The original Fastcraft is for MC 1.7.10.  I found a reddit post from earlier this month where the author of Fastcraft posted a preview of Fastcraft 2, but it's for MC 1.10.2.  I also searched the log you linked, and there's no mention of Fastcraft.

**Comment by KSIxxr3b3l** [comment]
mistake on my end as I was doing multiple things when I made this report. I knew I had a fps mod in the pack but couldn't remember which one and was thinking fastcraft.
