### ISSUE TITLE
[1.7.10] Block protection and inventory items

### ISSUE THREAD

**Issue by spitefulcoder** [McJtyMods/RFTools#1828]
Issue description: 

You cannot block protect inventory items such as chests, crates etc. I have the wrench in orange mode, and no combination of sneaking, left/right clicking and so-on allows me to block protect these items.

Versions:
* Minecraft: 1 7 10 (ftb infinity evolved)
* Forge: forge-10.13.4.1614
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: mcjtylib-1.8.1
* RFTools: rftools-4.23

**Comment by josephcsible** [comment]
1.7.10 is no longer supported.
