### ISSUE TITLE
Environmental controller feather falling not working

### ISSUE THREAD

**Issue by Sulexa** [McJtyMods/RFTools#1831]
Issue description: 
Environmental controller doesn't apply feather falling with module feather falling or feather falling plus installed. (But work for other module like saturation)
Steps to reproduce: 
Set up a fall (13 block in my test)
Jump without armor : You should loose some heart (3 heart in my test)
Place a Environmental controller with either feather falling or father falling plus installed, you still loose the same amount of heart (still 3 heart in my test) 

Versions:
* Minecraft: 1.12.2
* Forge: 14.23.4.2726
* CompatLayer (only if on Minecraft 1.10 or 1.11): Not installed (1.12)
* McJtyLib: 1.12-3.0.2
* RFTools: 1.12-7.54

Possibly incompatible mods and versions: 

Relevant logs, if any:

**Comment by McJty** [comment]
Show me the gui of your environmental controller. Also does it have enough power? Check the tooltip or try to reduce the area. Power consumption can be pretty heavy for big range

**Comment by Sulexa** [comment]
This is my environmental controller gui
![2018-08-19_11 35 25](https://user-images.githubusercontent.com/13980552/44307541-5a50aa00-a3a4-11e8-8683-620fadcc8d44.png)
I have a feather falling plus module
![2018-08-19_11 35 31](https://user-images.githubusercontent.com/13980552/44307542-5a50aa00-a3a4-11e8-97f9-e59a6b7eb76d.png)
It say it's active and use 1672rf/tick
![2018-08-19_11 35 36](https://user-images.githubusercontent.com/13980552/44307543-5a50aa00-a3a4-11e8-840b-e7b2cc9a5b25.png)
And if i check my energy i really use 1672rf/tick
![2018-08-19_11 35 40](https://user-images.githubusercontent.com/13980552/44307544-5a50aa00-a3a4-11e8-80ce-f3c8a30ed740.png)
I jump from some height in vanilla
![2018-08-19_11 35 56](https://user-images.githubusercontent.com/13980552/44307545-5ae94080-a3a4-11e8-8be3-9cd862815eee.png)
And i get the exact same damage as jumping without the environmental controller
![2018-08-19_11 36 02](https://user-images.githubusercontent.com/13980552/44307539-59b81380-a3a4-11e8-9261-7e1b52cd8802.png)
![2018-08-19_11 44 54](https://user-images.githubusercontent.com/13980552/44307604-55402a80-a3a5-11e8-820d-a4cebdf6c025.png)

You can also see in every screenshot except last one i have the feather falling module displayed in the top left of my screen.
Also my original testing were on a multiplayer server and i have saturation plus activated which was working proprerly

Thx for your help :)

**Comment by McJty** [comment]
um, turns out this module was simply not implemented. Weird that this was overlooked for so long. In any case, will be implemented next release :-)
