### ISSUE TITLE
Item Filter not functioning (properly) in FTB Revelation 2.3.0

### ISSUE THREAD

**Issue by PotatoFlavour** [McJtyMods/RFTools#1832]
**Issue description:** 
I've tried sorting my items in a small auto smelter setup with a vertical digger (quarry) hooked up. The idea was to pull items from the quarry and split items I want to smelt (iron ore etc.) and items I don't want to smelt (diamonds etc.). The Item Filter seemed perfect for this. Trying to use the filter I noticed it wouldn't allow any kind of item flow regardless of the configuration. And when setting a configuration, leaving the UI and opening it back up, the configuration changed itself. I've tried hooking the filter up with containers, (EnderIO) Item Conduits, transfer pipes and hoppers.

**Steps to reproduce:** 
1. Place top to bottom: Hopper (A), Item Filter, Hopper (B)
2. Fill Hopper A with item X
3. Open Item Filter UI
4. Create ghost item of item X in slot 1 (bottom row)
5. In row U (Up), column 1, set to "Input"
6. In row D (Down), column 1, set to "Output"
The Item Filter is now configured to pull item X from the top and push item X to the bottom, yet no item flow is happening. Same happens with 2 ghost items, 1 for input, 1 for output. Same happens with the N, E, S, W sides (using EnderIO Item Conduits).

I configure my EnderIO Item Conduits with one side extracting, one side inserting, and setting it to always active (not needing a redstone signal to allow item flow).

1. Place Item Filter
2. Open Item Filter UI
3. Set all buttons in column 1 to "Input"
4. Leave Item Filter UI
5. Open Item Filter UI
Notice how the configuration has changed itself to a stairway pattern.

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.4.2726 (not sure)
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib:
* RFTools: 1.12-7.55
* Modpack: FTB Revelation 2.3.0

**Comment by josephcsible** [comment]
Can you reproduce this with just RFTools and its dependencies installed?

**Comment by PotatoFlavour** [comment]
No, sorry. I already needed help installing the modpack. I don't know how to enable/disable certain mods.

**Comment by Nick-77ab2** [comment]
^Yea, i've got the same exact thing happening with multiple other mods installed.

**Comment by McJty** [comment]
Fixed next release
