### ISSUE TITLE
Using control+A types a broken character instead of selecting all in the storage scanner

### ISSUE THREAD

**Issue by aaronhowser1** [McJtyMods/RFTools#1838]
Issue description: 
![image](https://user-images.githubusercontent.com/15698722/45092753-06500000-b0dc-11e8-8939-97f7ae9ebbd6.png)
I wanted to select what I'd typed and then replace it but instead it typed a weird broken character.

Steps to reproduce: 
Type anything into the Storage Scanner then hold control and tap A

Versions:
* Minecraft: 1.12.2
* Forge: forge-14.23.4.2759
* McJtyLib: mcjtylib-1.12-3.0.3
* RFTools: rftools-1.12-7.55

**Comment by McJty** [comment]
yes, that kind of functionality is currently not supported in those components

**Comment by McJty** [comment]
Also it is not likely to be implemented soon as the widget doesn't even support selection. So there is really no way for ctrl-A to work right now
