### ISSUE TITLE
Attempting to spawn Blizz with RFTools Spawner

### ISSUE THREAD

**Issue by matt9631** [McJtyMods/RFTools#1842]
Issue description: Attempting to add Blizz, Blitz, and Basalz to the RFTools spawner list. Still receiving NullRF for all 3.

Steps to reproduce: 
1. Change configs, add all three into the list.
2. Set up RFTools spawner with 3 matter beamers.
3. Attach power.
4. Insert syringes for each of the 3 mobs.
5. Receive NullRF in the spawner.

Versions:
* Minecraft: 1.12.2
* Forge: 14.23.4.2720
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: 1.12-3.0.2
* RFTools: 1.12-7.54

Possibly incompatible mods and versions: 

Relevant logs, if any:  https://pastebin.com/raw/t8bU0Mcc

**Comment by josephcsible** [comment]
Please post the config you tried.
