### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by thebigschnoz** [McJtyMods/RFTools#1844]
Issue description: NullPointerException - seems to be related to RFTools and EnderIO

Steps to reproduce: Starting a server

Versions:
* Minecraft: 1.12.2
* Forge: unknown
* McJtyLib: 1.12 - 3.0.5
* RFTools: 1.12 - 7.55
* Server 

Possibly incompatible mods and versions: 
* I'm thinking EnderIO?
* I have the modpack Lapito's Galacticraft 7.2 installed, and this issue only occurred after the update from 7.1.1

[crash-2018-09-13_04.51.50-server.txt](https://github.com/McJtyMods/RFTools/files/2377731/crash-2018-09-13_04.51.50-server.txt)

**Comment by josephcsible** [comment]
Will be fixed in the next release of McJtyLib: McJtyMods/McJtyLib@7a0f8b4
