### ISSUE TITLE
Dragon dimension tab issue

### ISSUE THREAD

**Issue by OculusRex** [McJtyMods/RFTools#1845]
Trying to set an issue with RFTools Dimensions brings me here so here goes.

When making a Dragon Dimension, the tab sets, I put it in the bulder and it builds and charges fine. The tab ID appears in the Dialling Device, dials and I can enter fine. The problem is, when I come out of it, say to recharge my weapons, it disappears from the Dialling Device and I have to make the tab again with a different material/terrain to get it to work again. Is this a known bug or just something unique to my server?

Dimensions ver. 1.12-5.60

Edit: This only happens when making a Dragon world.

**Comment by josephcsible** [comment]
Can you try to reproduce the issue with just RFTools Dimensions and its dependencies? By the way, 5.60 is now outdated. Please try with the latest versions.

Also, what's a "dragon dimension"? Just a dimension with an ender dragon dimlet, or something else?
