### ISSUE TITLE
Shield Projector blocks are off in a single chunk after a server restart 

### ISSUE THREAD

**Issue by Darkpye** [McJtyMods/RFTools#1850]
![the hole](https://user-images.githubusercontent.com/23051116/46087233-2ab66e00-c1aa-11e8-8fa2-0590c1b68481.jpg)

Issue description: After a server restart all shield blocks in a chunk are off while the rest of the shield is on.

The server we are playing on is fairly old, a resonant rise build from 1.7.10. I haven't seen this issue pop up on any of my searches so I just want to check whether or not this is something have seen before.

We are building a rather large shield dome, this dome is a combined structure of multiple shield projectors, whenever the server restart a single chunk of the shield is off while the rest of the shield is still on. This is interesting because the off section is comprised of at least 3 different shields that run in a band through the chunk.

Turning off the shield sections that are affected and then back on again fixes the issue until the next server restart.

See attached image of our dynmap, the affected region is the perfectly square hole in the dome structure.

Steps to reproduce: 

Issue reoccurs on server restart, would have no idea how to generally try to reproduce this it is part a shield that is currently in the region of around 75k template blocks. Our current version of RFtools only allows up to 1024 blocks per projector.

Versions:
* Minecraft: 1.7.10
* Forge: 10.13.4.1448
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib:
* RFTools: 3.11

**Comment by josephcsible** [comment]
Minecraft 1.7.10 is no longer supported.
