### ISSUE TITLE
Allow users to use CTRL+A/C/V in GUIs

### ISSUE THREAD

**Issue by vini2003** [McJtyMods/RFTools#1863]
Be it in the RFTools Storage Scanner, XNet Controller, or any other GUIs, pressing CTLR+A/C/V currently doesn't work. That would make dealing with names much easier and faster, making the GUIs more usable.

**Comment by hnOsmium0001** [comment]
This is implemented in https://github.com/McJtyMods/McJtyLib/pull/96
@McJty Can you please close this issue?
