### ISSUE TITLE
Dimension Information Missing & Dimension isn't always night

### ISSUE THREAD

**Issue by drunkripper** [McJtyMods/RFTools#1872]
Issue description: 

Steps to reproduce: 
- Go into dimension
- Wait
- Advanced Solar Panels from Mekanism no longer consider them selfs 

Versions:
* Minecraft: 1.12.2
* Forge: 14.23.5.2772
* McJtyLib: 1-12.3.0.7
* RFTools: 1.12-7.58
* RFTools: Dimensions 1.12-5.63

Possibly incompatible mods and versions: 
- SpongeForge
- FoamFix
- Optifine

rftdim info:
- ID: 72
Description string: @CSingle,BMinecraft:desert,tNoon,SNone,fNone,eNone,d0,d1,d0,d1,d3,d2
Owned by: TheFakeJaneDoe
 Digits: 010132
 Base seed: 2093000116178180542
 World Version: 2
 Terrain: TERRAIN_VOID
  Base Block: Stone
  Base fluid: Water
  Biome controller_ CONTROLLER_SINGLE
  Biome: Desert
  Feature: FEATURE_NONE
  Structure: STRUCTURE_NONE
  Sun brightness: 1.0
  Star brightness: 1.0
  Sky Color: 1.0, 1.0, 1.0
  Fog Color: 1.0, 1.0, 1.0
  Cloud Color: 1.0, 1.0, 1.0
  Celestial Angle: 0.0

**Comment by josephcsible** [comment]
I don't know what you're trying to say. Please describe the problem in more detail.
