### ISSUE TITLE
Sensor block and ender lillys

### ISSUE THREAD

**Issue by InThayne** [McJtyMods/RFTools#1875]
Sensors do not seem to detect ender lillys at any stage of growth aside from number=0, which is just perpetually on.  Looking to harvest at number=100.

**Comment by josephcsible** [comment]
The problem is that Extra Utilities chose to use the word "growth" for their block state instead of the word "age", which every vanilla crop and basically every other modded crop uses. Rather than asking us to special-case our sensor just for them, you should ask them to change "growth" to "age".

**Comment by InThayne** [comment]
Great, makes sense!  Was hoping for an 'oh do this' sort of answer rather than a change on your part.  Perhaps the lillys shouldn't be so easily harvested anyways for balance.

**Comment by josephcsible** [comment]
I'm actually working on a PR for them that will make that change, so stay tuned.

**Comment by josephcsible** [comment]
I just opened rwtema/Extra-Utilities-2-Source#234 for that.
