### ISSUE TITLE
Custom config not syncing with clients.

### ISSUE THREAD

**Issue by coryjreid** [McJtyMods/RFTools#1878]
Issue description: Adding custom mobspawner information to server config does not automatically synchronize to clients.

Steps to reproduce: 
1. Add spawn information as described in #1199 to server config
2. Restart server and client completely
3. Login to server
4. Insert Blitz syringe into mob spawner
5. Receive nullRF
6. Close Minecraft completely
7. Manually copy/replace rftools.cfg on the client with config file from server
8. Repeat steps 3-4
9. Spawner shows correct info
10. Insert items into beamers
11. Mobs can spawn now

Versions:
* Minecraft: 1.12.2
* Forge: 14.23.5.2768
* CompatLayer (only if on Minecraft 1.10 or 1.11): N/A
* McJtyLib: 3.0.7
* RFTools: 7.58

Possibly incompatible mods and versions: OptiFine 1.12.2 HD U E2

Relevant logs, if any: No logs, no crash

Other:
I tried customizing the server config and rebooting, removing the rftools.cfg from the client, launching the game and letting the default config regenerate, and logging into the server. My config never updates with the changes from the server.

**Comment by McJty** [comment]
This is normal. I just didn't implement config syncing for this as it is not that easy. Just make sure the client configs match the server configs

**Comment by coryjreid** [comment]
Oh, okay. Thank you for the info @mcjty. May I ask one more question that's a branch from this?

I want to use an item from ThermalFoundation (eg. a Blitz rod) with the spawner. However, the item requires a data value to be provided when given with the `/give` command. Is it possible to use this item? 

To give the item the give command would be as follows: `/give <player> thermalfoundation:material 1 2050`, with the 2050 being critical to getting the right item.

I tried using `thermalfoundation:material:2050` but that didn't work.
