### ISSUE TITLE
Can you use custom ThermalFoundation item as a requirement to spawn mobs with the mobspawner?

### ISSUE THREAD

**Issue by coryjreid** [McJtyMods/RFTools#1880]
Issue description: 
Using ThermalFoundation item that requires a `data` value as a mob spawning requirement with mobspawner doesn't work.

I want to use an item from ThermalFoundation (eg. a Blitz rod) with the spawner. However, the item requires a data value to be provided when given with the `/give` command. 

To give the item the give command would be as follows: `/give <player> thermalfoundation:material 1 2050`, with the 2050 being critical to getting the right item.

Is it possible to use this item?

Steps to reproduce: 
1. Edit config and add item `thermalfoundation:material:2050` as follows:

```
    S:"thermalfoundation:blitz.spawnamount.0" <
        I
        thermalfoundation:material:2050
        0
        0.1
     >
    S:"thermalfoundation:blitz.spawnamount.1" <
        B
        minecraft:sand
        0
        50.0
     >
    S:"thermalfoundation:blitz.spawnamount.2" <
        L
        
        0
        9.0
     >
```
2. Reboot clients/server and login to server
3. Insert syringe into mobspawner, see incorrect item

Versions:
* Minecraft: 1.12.2
* Forge: 14.23.5.2768
* CompatLayer (only if on Minecraft 1.10 or 1.11): N/A
* McJtyLib: 3.0.7
* RFTools: 7.58

Possibly incompatible mods and versions: OptiFine 1.12.2 HD U E2

Relevant logs, if any: No logs, no crash

**Comment by josephcsible** [comment]
Try like this instead:
```
    S:"thermalfoundation:blitz.spawnamount.0" <
        I
        thermalfoundation:material
        2050
        0.1
     >
    S:"thermalfoundation:blitz.spawnamount.1" <
        B
        minecraft:sand
        0
        50.0
     >
    S:"thermalfoundation:blitz.spawnamount.2" <
        L
        
        0
        9.0
     >
```

**Comment by coryjreid** [comment]
I am but a humble idiot. I had no clue that's what the following number was. Thank you so much - that worked!
