### ISSUE TITLE
Dimension Request

### ISSUE THREAD

**Issue by BlueNine9** [McJtyMods/RFTools#1884]
There's no world with platinum block or molten platinum.

I need a lot of platinum blocks, but I have no where to find them.

Please add a world with platinum/molten platinum.

Thanks ; )

**Comment by josephcsible** [comment]
What's the problem exactly? Do the dimlets not exist? Did you try adding them to the config?

**Comment by BlueNine9** [comment]
I solved it by adding them to the config.
