### ISSUE TITLE
Crash with Storage Scanner when trying to craft something

### ISSUE THREAD

**Issue by SanAndreasP** [McJtyMods/RFTools#1891]
**Issue description:**
I crashed after trying to craft Hardened Fluiducts from Thermal Dynamics and hovering over the "craft 1 item" button

**Steps to reproduce:**
1. Storage Scanner hooked up to an XNet network connected to an Actually Additions item interface, which connects AA storage crates via filtered item lasers
2. open up the Scanner GUI, grab the recipe for Fluiducts from JEI, with no hardened glass in the storage
3. hover over the "craft 1 item" button

PS: I had this crash with the exact same stack trace whilst trying to craft Cow Bait from Ex Compressum, with enough items to craft it in the storage.

**Versions:**
* Minecraft: 1.12.2
* Forge: 14.23.5.2796
* CompatLayer (only if on Minecraft 1.10 or 1.11): n/a
* McJtyLib: 1.12-3.0.7
* RFTools: 1.12-7.59

**Possibly incompatible mods and versions:**
* VanillaFix (1.0.10-SNAPSHOT)
* FoamFix (0.10.3-1.12.2)

Relevant logs, if any: 
https://paste.dimdev.org/xojufilupa.mccrash

**Comment by josephcsible** [comment]
There looks to be about 300 mods in your pack, which is way too many for us to reasonably troubleshoot/reproduce anything. Can you see if you can reproduce this issue with a minimal set of mods installed (RFTools, XNet, Thermal Dynamics, Actually Additions, Ex Compressum, and their dependencies)? If not, then one of your other mods is almost certainly at fault, and you should figure out which one and report it to their tracker.

**Comment by SanAndreasP** [comment]
mmh, I tested it extensively now with a minimal mod setup, I cannot reproduce it at all and this error only rarely occurs on my big modded instance. So I guess it's some other mod messing with something. I'll close this now as it's unlikely it is this mod's fault.
