### ISSUE TITLE
Spawner use mod items/blocks

### ISSUE THREAD

**Issue by Peppe-KSP** [McJtyMods/RFTools#1895]
Issue description: Trying to configure spawner syringe values for thermal foundation mobs blitz, blizz, basalz.  Referencing thermalfoundation:material 2048, 2050, 2052 for their respective bars, but in game it shows the living category items in that slot with the correct quantity. 

Can ore dictionary be used?  there is an ore dictionary entry called ore:rodBlizz,  ore:rodBlitz, and  ore:rodBasalz, but using those with 0 for the third line crashed.

Steps to reproduce: Add config to rftoolscfg -> mobspawnamounts:
```
S:"thermalfoundation:basalz.spawnamount.0" <
        I
        thermalfoundation:material
        2052
        0.1
     >
    S:"thermalfoundation:basalz.spawnamount.1" <
        B
        minecraft:obsidian
        0
        0.25
     >
    S:"thermalfoundation:basalz.spawnamount.2" <
        L
        
        0
        30.0
     >
    S:"thermalfoundation:blitz.spawnamount.0" <
        I
        thermalfoundation:material
        2050
        0.1
     >
    S:"thermalfoundation:blitz.spawnamount.1" <
        B
        minecraft:sandstone
        0
        0.5
     >
    S:"thermalfoundation:blitz.spawnamount.2" <
        L
        
        0
        30.0
     >
    S:"thermalfoundation:blizz.spawnamount.0" <
        I
        thermalfoundation:material
        2048
        0.1
     >
    S:"thermalfoundation:blizz.spawnamount.1" <
        B
        minecraft:packed_ice
        0
        0.5
     >
    S:"thermalfoundation:blizz.spawnamount.2" <
        L
        
        0
        30.0
     >
```
With thermal foundation mod installed.  Get a blizz syringe and place in spawner.  See .1 living items, .5 packed ice, and 30 living items required.  Expect .1 living item to be a blizz rod. 

Have mobspawnrf with additional items as well - rf value works no issues:
    I:"thermalfoundation:basalz"=2500
    I:"thermalfoundation:blitz"=2500
    I:"thermalfoundation:blizz"=2500

Versions:
* Minecraft: 1.12.2
* Forge: 14.23.5.2806
* CompatLayer (only if on Minecraft 1.10 or 1.11):
* McJtyLib: mcjtylib-1.12-3.0.7
* RFTools: rftools-1.12-7.59

Possibly incompatible mods and versions: 

Relevant logs, if any:

**Comment by josephcsible** [comment]
This is confirmed to work for other users, so something's wrong with your setup. Things to try to help debug:

1. Post a screenshot of exactly what you see that demonstrates the problem, as your description is a bit unclear
2. See if you can reproduce the problem with just Thermal Foundation, RFTools, and their dependencies installed
3. Upload your entire rftools.cfg file

**Comment by Peppe-KSP** [comment]
Problem persists after reducing mods to: COFH core, COFH world, mcjtylib, redstone flux, rftools, thermal foundation
what i see in game: https://imgur.com/a/2qDdffd
CFG file: https://pastebin.com/tbawsHjE

**Comment by josephcsible** [comment]
This was indeed a bug in RFTools. It will be fixed in the next release, so your config will work the way you want it to then. If you want to be able to spawn these in the meantime, you can work around the bug by using a vanilla item in place of thermalfoundation:material.
