### ISSUE TITLE
[Request/Wiki] Configuration file documentation

### ISSUE THREAD

**Issue by Timeslice42** [McJtyMods/RFTools#203]
A link to the configuration documentation page should be in the right sidebar under the "Overview" section.

The configuration documentation page needs to be updated to document the new format, especially including the "knowndimlets" and "recurrentcomplex" sections of "dimlets.cfg"

**Comment by Timeslice42** [comment]
Having it point to the /rftcfg command might be a good start.

**Comment by MichaelHillcox** [comment]
I'm not sure when this would have been implemented but at the very least, as of 1.12 each line in the config should have a pretty reasonable comment. If you feel more could be expended. Please reopen and explain which options are unclear. Thanks :D
