### ISSUE TITLE
Suggestion: New Explosives

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [McJtyMods/RFTools#205]
Almost every techmod, magicmod, whathaveyoumod add new items, blocks, tools, etc. but strangely almost none of them add any new explosives to the game.

I kinda want to have more choices besides TNT. Bigger, smaller, better, different, anything, really :).

New kaboom is gud!

**Comment by MichaelHillcox** [comment]
There are a few mods out there that add supper TNT and nukes and things (go override some IC2 Machines) I think it's likely out of scope for this mod as it's more of a tech tools mod and not a Kitchen sink tech mod. I'll close unless you want to bring it up again in a new issue.
