### ISSUE TITLE
[Request] Ability to use crafter to compress 2x2 or 3x3

### ISSUE THREAD

**Issue by permdaddy** [McJtyMods/RFTools#221]
It would be nice if a crafter could just take whatever is put in it and automatically craft it 2x2 or 3x3.

**Comment by McJty** [comment]
What exactly do you mean by this?

**Comment by permdaddy** [comment]
For example if a crafter is set to compress 2x2 then if you gave it wood
planks it would churn out crafting tables. If you set it to 3x3 it would
churn out metal blocks if you fed it ingots.

**Comment by McJty** [comment]
That sounds more like something for a different machine. In the GUI of the crafter it is not really easy to define this type of recipe atm.
