### ISSUE TITLE
[Request/Feature] Timer restricted value

### ISSUE THREAD

**Issue by ghost** [McJtyMods/RFTools#236]
Hey, i have a request for the Timer, can u add an config option to set an restricted value. So that User can´t add value under 5 secs.
Greetings Aik

**Comment by MichaelHillcox** [comment]
Unfortunately we're no longer supporting versions older than `1.12` and I don't have enough time to check this suggestion against all of the features of the mod but if this feature still hasn’t been implemented and you’d like to see it added to a newer version of the mod then please do create a new issue so we can review your suggestions again :+1:
