### ISSUE TITLE
Builder resets progress after server restart

### ISSUE THREAD

**Issue by brian91292** [McJtyMods/RFTools#237]
I'm playing on a public Infinity server (Infinity 1.7.0) and I've just recently started using the builder to steal some... massive structures from the twilight forest. Anyway, the server is set to auto-restart every 2 hours, and each time after the server restarts the builder seems to completely forget where it left off, and just start over from the beginning. This makes moving these large structures very difficult, as I have to continuously move the space chamber around so it doesnt rescan all the blocks it's already moved.

I've noticed this bug in both move mode and in swap mode, haven't tried any of the others yet.

**Comment by MichaelHillcox** [comment]
Close as 1.7.10 is no longer supported. If this continues to be a bug on 1.12 or newer, please open a new issue.
