### ISSUE TITLE
Suggestion: Handheld "Screen"

### ISSUE THREAD

**Issue by Crumbology** [McJtyMods/RFTools#240]
A handheld item that works like a screen but opens a screen like gui on right click, config like the screen on shift right click perhaps, allowing remote monitoring and interaction using existing screen modules.

**Comment by McJty** [comment]
The ability to combine a tablet with a screen is planned

**Comment by MichaelHillcox** [comment]
Unfortunately we're no longer supporting versions older than `1.12` and I don't have enough time to check this suggestion against all of the features of the mod but if this feature still hasn’t been implemented and you’d like to see it added to a newer version of the mod then please do create a new issue so we can review your suggestions again :+1:
