### ISSUE TITLE
Suggestion: Better button module documentation

### ISSUE THREAD

**Issue by joeltinez** [McJtyMods/RFTools#248]
I struggled quite a bit trying to figure out how to use the button module to dial a particular dimension (inspired by the [screenshot shown](https://github.com/McJty/RFTools/wiki/RFTools-Screen-Modules) in the screen module docs). The documentation on this is pretty scant on your wiki and from external sources.

For example, the [screen module page](https://github.com/McJty/RFTools/wiki/RFTools-Screen-Modules) says this about the button module: "It can be configured as a toggle or as a single signal button. It uses the wireless redstone system from RFTools.". Then, on looking up the wireless redstone system wiki, it says "Note that there is a screen 'button' module that also works with this wireless redstone system.", but it doesn't say exactly _how_ to use it. 

Eventually, I found you could shift + right click on the redstone receiver to bind the button, but it would've saved me some time if the docs just mentioned it explicitly. Maybe a screenshot of a working setup would be nice too.

**Comment by joeltinez** [comment]
BTW, I would've just created a PR for this myself, but I guess GitHub doesn't support PRs for the wiki out of the box. Have you considered putting your docs in your main repo, and using [GitHub pages](https://pages.github.com/)?

**Comment by McJty** [comment]
I'm afraid that the wiki is indeed a bit out of date. I try to focus on the in-game manual which always contains (or should contain) up-to-date information. But you are right about the wiki being outdated.

As to 'Github pages' I wasn't aware of that.

**Comment by joeltinez** [comment]
Thanks. The only problem with in-game documentation is you can't Google it :).

**Comment by MichaelHillcox** [comment]
Unfortunately we're no longer supporting versions older than `1.12` and I don't have enough time to check this suggestion against all of the features of the mod but if this feature still hasn’t been implemented and you’d like to see it added to a newer version of the mod then please do create a new issue so we can review your suggestions again :+1:
