### ISSUE TITLE
Biomes spawning without grass

### ISSUE THREAD

**Issue by s0uthw3st** [McJtyMods/RFTools#268]
Similar to closed issue #196 - biomes that would normally have grass spawn with plain dirt.
- Some blocks of grass do occasionally spawn (seen with Oasis and Extreme Hills biomes, near spawned lakes) as part of generated surface features
- Grass does not spread onto dirt spawned in these dimensions (tested by both waiting for natural spread and forcing spreading via Extra Utilities watering can) unless the dirt is broken and replaced
- Dirt in these dimensions is normal dirt (id 3) as confirmed by silk-touch
- Appears to affect 'surface' dirt only - dirt patches generated as part of the stone layers seem to be unaffected

Tested with Terrain Island dimlet with Single Biome (modded) Oasis, Shield, and (vanilla) Extreme Hills biomes.

Screenshot of unchanged dirt around a natural lake that spawned with grass blocks:
http://imgur.com/wJDCN0V

Dimension Tab info, for reference:

```
Base seed: -4498955698251640059
World version: 1
Terrain: TERRAIN_ISLAND
Base block: Stone
Base fluid: Water
Biome controller: CONTROLLER_SINGLE
Biome: Extreme Hills
Feature: FEATURE_NONE
Structure: STRUCTURE_NONE
Sun brightness: 1.0
Star brightness: 1.0
Sky color: 1.0, 1.0, 1.0
Fog color: 1.0, 1.0, 1.0
Sky body: BODY_LARGEPLANET
Weather rain: 0.0
Weather thunder 0.0
Celestial angle: 0.0
```

Version 3.11 of RFTools, as part of FTB Direwolf20 Pack 1.6.1

**Comment by flobernd** [comment]
I can confirm this for the Flower Forest biome. It seems like you got an "off by one" error in your island generation code (normal, amplified, etc works great). It's always the topmost layer of the biome missing.

**Comment by Sasstraliss** [comment]
Confirmed for version 3.2+

**Comment by meritasix** [comment]
Confirmed in 4.34, last version available for 1.7

**Comment by SnowMntGaming** [comment]
Was this just overlooked or ignored? Still happening and we're on 1.12.2.

**Comment by McJty** [comment]
I'm not sure this is actually a big. Just a way things work

**Comment by MichaelHillcox** [comment]
Thank you for taking the time to create this issue, as we're no longer supporting versions below `1.12`, I'm going to go ahead and close it but if this bug seems to continue over to newer versions, please do report it again so we can investigate the issue further.
