### ISSUE TITLE
Modular Storage deletes mfr plastic sheets.

### ISSUE THREAD

**Issue by technolem** [McJtyMods/RFTools#271]
MFR uses a custom stack size of 96 for its plastic sheets. When you have several stacks of plastic in a modular storage and select compact stacks, it combines them and deletes 32 each time. This will repeat each click until there is only 64 left.

RFtools 3.20
MFR   2.8.1B1-125

**Comment by McJty** [comment]
How the heck does MFR even make stacks of 96? Not sure if there is much that I can do about that... Weird.

**Comment by MichaelHillcox** [comment]
Close as 1.7.10 is no longer supported. If this continues to be a bug on 1.12 or newer, please open a new issue.
