### ISSUE TITLE
Balance bug with liquid Ludicrite dimlet

### ISSUE THREAD

**Issue by patw** [McJtyMods/RFTools#296]
As a R2, it's a bit too easy to get this one going. Considering how costly it is to make the material, does it make more sense for it to be a R4 or R5?

**Comment by McJty** [comment]
Can you hold the dimlets in your hand and type /rftcfg dimletcfg and then tell me what that says so that I can rebalance it? Thanks

**Comment by Riddler76** [comment]
Hi,

For liquid vibrant need a balance.
I put this in the cfg.

	I:"rarity.Liquid.phasedgold"=2
	I:"rfcreate.Liquid.phasedgold"=9000
	I:"rfmaintain.Liquid.phasedgold"=4000
	I:"ticks.Liquid.phasedgold"=500

But is not operationnal in game.

**Comment by McJty** [comment]
In what config did you add that?

**Comment by Riddler76** [comment]
Yes i add that in the cfg server side.
In nei its ok but when create a world with dimlet, the power consuption not change.

**Comment by McJty** [comment]
But in which config file? There is config/rftools/main.cfg and config/rftools/dimlet.cfg. This should go to dimlets.cfg

Note that power consumption of a dimension is not only for that single dimlet but also for all other dimlets.

Also note that dimensions that are already created are not changed when the config file changes. It will only work on new dimensions that are created with that dimlet.

**Comment by Riddler76** [comment]
Ok, i don't recreate my dimenssion, i test it ans say you if is ok ;-) thank you.
Sorry fort my poor english, i'm french ^^
