### ISSUE TITLE
Some? Railcraft dimlets show as <unknown dimlet>

### ISSUE THREAD

**Issue by VashaTS** [McJtyMods/RFTools#299]
Dimlet researcher is producing those dimlets.

Example screenshot: http://i.imgur.com/rIxfXsU.png

Affected dimlets: Ids from 127 to 134:

> milte.railcraft.brick.nether2
> milte.railcraft.brick.bloodstained2
> milte.railcraft.brick.infernal2
> milte.railcraft.brick.infernal5
> milte.railcraft.brick.abyssal2
> milte.railcraft.brick.sandy2
> milte.railcraft.brick.quarried2
> milte.railcraft.brick.frostbound2

Modpack: Direwolf20 v 1.7

**Comment by McJty** [comment]
Those are all from Railcraft. Is Railcraft included in the pack? Any special configs?

**Comment by VashaTS** [comment]
Yes, Railcraft is in the pack: `Railcraft_1.7.10-9.6.1.0` and `mcjtylib-1.2.0`
May this be config issue?
