### ISSUE TITLE
(Suggestion) Alternative Ways to power dimensions

### ISSUE THREAD

**Issue by GeneralAtrox** [McJtyMods/RFTools#302]
Hi there. 

Just a bit of a suggestion really that I've come across a bit of a problem where if you either lose the realized dimension or re-use it for something else you can no longer power the old dimension without the original dimlets. 

I personally can't remember each exact dimlet I had for this specific out-of-power dimension so it's making it a big mission to guess-craft it all back together. 

I was wondering if there could be a machine implemented to keep track of powering these dimensions in some way, perhaps the builder could be expanded so you could select the currently built dimensions and choose which and what to funnel power. 

Obviously it's my fault it's gotten a bit messy and I'm the one who repurposed the realized dimension but this was as I was learning the mod and playing around with certain things. I would prefer the ability to get both the transmitter + receiver when creating a dimension, that would save the hassle of having to create many more and losing out on them when you decide to abandon the dimension.

**Comment by expl0s1ve** [comment]
This would be OP, you would only need to get each dimlet once and reuse them over and over again.

**Comment by GeneralAtrox** [comment]
I don't see the problem in that since you wouldn't need a second world with the same dimlets except cosmetic ones.

As a new player to the mod I lost several worlds before I'd realised you had to rememver the dimlet combination thus meaning I had to swap to creative to get my things back

**Comment by GeneralAtrox** [comment]
Maybe rather than additonal

**Comment by GeneralAtrox** [comment]
Power methods.  You could have dimlet memory combinations.

**Comment by McJty** [comment]
The problem with this is dimlets like efficiency. Make one world with four efficiency dimlets, power them using the alternative method and then just extract the dimlets again and you have 4 efficiency dimlets you can use for another dimension.

**Comment by GeneralAtrox** [comment]
I think my only issue is that none of the worlds indicate what dimlets are being used so unless you write it down, at the time I didn't know you had to remember the combinations, you're not going to get far when you start re-purposing dimensions to add other bits in.

A small suggestion would be to add extra info onto the dialing device (that lets you setup your transmitters) to show what dimlets are used in that specific dimension holding Shift or Ctrl (like Tinkerers Construct uses). This would help new players remember what worlds do what if they've gone ahead and built a few.

**Comment by McJty** [comment]
Note that if you are in a dimension you can type /rftdim info to get the dimlets used (might need op permission though, don't remember).

**Comment by McJty** [comment]
Also in creative you can create a new dimension tab from a given dimension using the /rftdim createtab command. See https://github.com/McJty/RFTools/wiki/RFTools-Commands
for more info about that

**Comment by GeneralAtrox** [comment]
For the server I was on, you did need OP permissions to use any commands on RFTools. 

Oh that's a cool command. Although to prevent the need for it the suggestion above will solve that.

**Comment by McJty** [comment]
Your suggestion also has a problem. Sometimes people want to keep their dimension private and don't want others to know what dimlets were used (to prevent people from going to them). 

So that's the major issue. There are lots of ways to abuse this.

**Comment by GeneralAtrox** [comment]
I've not used it but the security manager should cover this kind of problem right? Also wouldn't setting transmitters/receivers to private prevent these problems?

**Comment by McJty** [comment]
The security manager only protects blocks. Not dimensions. Setting private access to the receiver would help but still it was merely to illustrate that this is not a trivial thing to do.

**Comment by GeneralAtrox** [comment]
Adding a security option to the dialing device is an easy work around. Similar to how tesseracts work where  they  don't let you access the block and give you a warning. This should be present on the important machines, especially the charging station, imagine a user stealing your world and then you die in it because it's too high demand for it to stay charged long enough.
