### ISSUE TITLE
Storage Module Tablet to automatically pick-up items

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [McJtyMods/RFTools#303]
I'd like to have a module inside the Storage Module Tablet, besides the 300 stack module, to automatically pick up items. Better yet, allow it also to filter what items it can or can't pick up. This would allow me to drop the backpack mod I have.

**Comment by MichaelHillcox** [comment]
But you have a mod providing the needed functionality? Plus: DevNulls in 1.12 :D I think this might be out of scope.
