### ISSUE TITLE
Security Terminal not saving Ownership upon unloading/reloading Dimension Chunks (Interaction with Applied Energistics 2)

### ISSUE THREAD

**Issue by MonkeyMechanic** [McJtyMods/RFTools#309]
This originally was posted in the Applied Energistics 2 Github here: https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/1841

> I have an issue where I cannot setup a Security Terminal within my Void Dimension using RF Tools as upon leaving the dimension enough for it to unload and then re-entering, complete access to the system is denied and I can only view the items using a terminal. Interfaces/Import Buses cannot also put items into the system as well as they too are locked out. I cannot also access the Security Terminal to change these permissions. The only way to regain access to my system and to restore Interface/Import Bus functionality, I have to remove the Security Terminal from the network entirely.
> 
> I believe the issue has to deal with ownership of the Security Terminal/Network being saved the server when the Dimension is unloaded as there are no chunk loaders keeping it loaded. I do not have access to the server logs at all as the server isn't mine so I cannot confirm by looking into these logs.

From some of the feedback I've received, It seems like this is an issue with RFTools and not Applied Energistics. The dimensions might be missing a call to notify Tile Entities about the unloading of chunks within the dimensions themselves. Personally I am not exactly sure which mod is causing the problem but I figure letting authors from both mods know about this issue might help resolve this faster. Hope this is enough information, and the ticket in the Applied Energistics GitHub is linked above.

**Comment by McJty** [comment]
It is not RFTools that is unloading chunks. That's something that Minecraft itself does. RFTools simply makes a dimension. I will go over the code related to this a bit but I have doubts that this is something that I can do a lot about. Also would be nice to test how this behaves in other dimensions like Mystcraft

**Comment by MonkeyMechanic** [comment]
I tested a small system in Extra Utilities' Last Millennium dimension and it seems to not have an issue. It looks to be completely isolated to RF Tools Dimensions. Unfortunately the modpack I am currently using no longer uses Mystcraft as it was causing problems with continuously creating dimensions when they weren't being requested, so I can't test it within dimensions created with that particular mod.
