### ISSUE TITLE
Suggestion - question

### ISSUE THREAD

**Issue by JustABunchOfPillows** [McJtyMods/RFTools#319]
Is there any possible way. to limit the amount of dimension per player, to 1 dimension for example.. then make it so they can only "remake" that dimension, with new items on it.. for example dim17 have redstone blocks, then change the dimension tab to have glowstone, then forcing the world to be deleted-remade with glowstone instead..

just something i've throught of. as it would limit the amount of worlds on a server then. Not sure if it's already a thing, so that's where the question goes. is this a thing already?.

**Comment by McJty** [comment]
The problem with this is that dimensions are not connected to a player. RFTools doesn't know which player made a dimension as the dimension is created in a machine even without the player being online at the time.

**Comment by JustABunchOfPillows** [comment]
well force it to private and the place where it was "made" or something along those lines. theres probably a way around it. but the issue is more creating worlds. who both collapses and/or wont work. it still takes up the dimension number of what i can see.. so would have been lovely with some kind of way to moderate it, whitout having to clean up every day.

**Comment by MichaelHillcox** [comment]
Unfortunately we're no longer supporting versions older than `1.12` and I don't have enough time to check this suggestion against all of the features of the mod but if this feature still hasn’t been implemented and you’d like to see it added to a newer version of the mod then please do create a new issue so we can review your suggestions again :+1:
