### ISSUE TITLE
[Request] Multiple modifier dimlets

### ISSUE THREAD

**Issue by expl0s1ve** [McJtyMods/RFTools#327]
For example, I want to create a flat world made of multiple materials. Maybe I can do this but I read the wiki and tried in game, couldn't get it to work. 
Something like:
[Material Block of Gold][Material Block of Diamond][Material Clay][Terrain Flat] and those blocks are randomly distributed in a flat world.

**Comment by McJty** [comment]
What you can do is to use the oregen dimlet. This is not exactly what you mean but it comes close:
[Material Default][Terrain Flat][Material X][Material Y][Material Z]...[Feature Oregen]
