### ISSUE TITLE
Crash Trying to add a name to a Matter Transporter

### ISSUE THREAD

**Issue by Reignofmagic** [McJtyMods/RFTools#343]
I have had 2 crashes (back to back) attempting to add a name to my Matter Transporter. 
I think it might be due to a cross mod interaction due to having over 220 mods installed. 

Here is the crash report: http://pastebin.com/r3JdbYW7

Let me know if you need anything else

**Comment by McJty** [comment]
I hate these kind of crash reports where nothing in the crash log indicates rftools. I've seen this before but I have absolutely no clue what could cause this. No code of rftools seems involved in this :-/

**Comment by Reignofmagic** [comment]
If it is any consolation, this type of crash has been popping up for both Reactorcraft and Rotarycraft machines today, which is odd since I have changed nothing in the configs or added any mods in the past week and it just started happening today.
