### ISSUE TITLE
[Enhancement] Allow Matter Reciever to Draw Power from Players Flux Capacitors 

### ISSUE THREAD

**Issue by mikeloeven** [McJtyMods/RFTools#353]
I play on a server that has strict restrictions on anything chunk loader and the main issue i run into is keeping the matter receivers charged some receivers are on other dimensions or places where there it is difficult to give them power. 

MY idea is to allow a matter receiver to search the players inventory for Flux Capacitors and drain the required power from them on arrival or barring that a craft able device that serves this purpose

**Comment by McJty** [comment]
Doesn't it work to simply place a tesseract near them that gets power from your base? When the receiver is not chunkloaded it will not get power but it will be quickly recharged as soon as you go to the receiver location.

**Comment by mikeloeven** [comment]
I posted this because i could not get power to flow through the tesseract only time it worked was when i had a friend stand in the base to load it

But just saying it would be nice to have a power supply you can take with you to protect you against unpowered receivers

**Comment by McJty** [comment]
Well there is already something that you can use and that is the Matter Booster. You can place this next to a matter transmitter and it will allow safe passage (at the cost of a bit more power to send you) to an unpowered matter receiver. You will still get some debufs but you will not die.

**Comment by mikeloeven** [comment]
Ill try using that
