### ISSUE TITLE
Override welcome area (Stained clay and matter receiver)

### ISSUE THREAD

**Issue by Dijkstra1** [McJtyMods/RFTools#365]
How easy would it be for me to make an adding mod that changes the welcome area completely, is there some method that I override or is just not possible

**Comment by McJty** [comment]
Currently there is no api for this but this is an interesting idea. The code for this can be found in GenericWorldGenerator. Perhaps you could make a patch to allow an api for this?

**Comment by Dijkstra1** [comment]
I have a better look at the code tonight and give it ago

**Comment by Dijkstra1** [comment]
I got a point where I can test what I have done, one little annoying thing though none of your assets are loading including the lang file

**Comment by MichaelHillcox** [comment]
@Dijkstra1 I know this is from around 3 years ago but did you ever make any progress on your mod :P
