### ISSUE TITLE
Game "freezes" upon entering unpowered dimension

### ISSUE THREAD

**Issue by teeg82** [McJtyMods/RFTools#377]
This is the first and only time encountering this issue, and at present I'm not entirely certain what's causing it. 

I accidentally teleported to an unpowered, already-deconstructed dimension, and within seconds the game appeared to freeze. The odd thing though is that it does not appear to be _actually_ frozen; the game behaves as though its stuck processing something heavy, and ticks every once in a while. My phase generator appears to drain at the expected rate, which I'm guessing is a result of the "time since last tick calculation", so I can tell it is at least occasionally updating, but inputs like mouse movement and keystrokes are often lost, especially if there's more than one.

I am using a modified FTB Infinity 1.12.1 with a few additional mods included (Galacticicraft, mekanism, meteorcraft).

The dimlets included, to the best of my recollection, were: liquid steam, biome deep ocean, terrain flat, time morning, sky bright day, and possibly the McJty dimlet. (I realize the flat terrain screws up the liquid; this was one of my many experiments as I've only recently started playing around with this mod.)

I can provide more information, or the world itself if needed, later this evening. Let me know if there's any additional information required (or whether I'm just doing something boneheaded).

**Comment by McJty** [comment]
This kind of report is nearly impossible for me to debug :-/
It certainly does not occur in all dimensions though

**Comment by teeg82** [comment]
Thats correct, it does not occur on all dimensions. This is the first time encountering this.

I am a developer too; I agree this is not a lot to go on. I will attempt to dig deeper and see if I can find some kind of more specific information.

**Comment by MichaelHillcox** [comment]
If you ever have an update, please do reopen 👍
