### ISSUE TITLE
New Environmental Controller particle effect

### ISSUE THREAD

**Issue by wlhlm** [McJtyMods/RFTools#389]
One thing in this otherwise excellent mod always struck me as odd, and that is the Environmental Controller active particle effect. I think it could be improved using vanilla particles, specifically `mobSpell`. The Controller even _has them printed on the front_ &mdash; what is the reasoning behind the current "floating spheres" effect? Maybe Performance?

Here's a quick hack of what I'm imagining it could look like:
![EnvironmentalControllerParticleComparison](https://cloud.githubusercontent.com/assets/1928113/11318959/53e356fc-9067-11e5-808a-a8f80566c614.gif)
left: old - right: new

What do you think?

**Comment by wlhlm** [comment]
In case someone is interested, here's what I did to change the particles:

https://gist.github.com/wlhlm/cacb2f8210775076cab3

I borrowed the particle spawning from `MaterialAbsorberTileEntity.java`. I don't know anything about Forge modding and my Java knowledge is also very limited, so this could totally be the wrong way to approach it (for example I've seen other mods use `randomDisplayTick()` for particle spawning), but maybe it helps as a starting point.

**Comment by McJty** [comment]
Well taste differs I suppose but I actually prefer the left option :-)
