### ISSUE TITLE
[Suggestion] Dimension with negative power cost?

### ISSUE THREAD

**Issue by skandver** [McJtyMods/RFTools#405]
So, that could be like dimension that never run out of power, but always have some kind of bad things inside - like, really fast spawned mobs regardless of blocks/light level, Hungry 5/Wither/Poison debuffs.

If you want get to that dimension, you need to maybe kill and Ender Dragon and use his Egg to create a special dimlet, that will create fully random dimension, with random negative power cost and effects.

Also, you cant just extract energy out of it - maybe some kind of setup, to "clean" energy?

Could be pretty interesting as end-game thing.

**Comment by McJty** [comment]
Yes indeed. But need a good mechanic to get to that to make sure it really is something people don't get too early in the game

**Comment by Zsashas** [comment]
The first thing I thought of when I saw "negative power cost" was something like you have to drain the power fast enough, or it builds up. Really fast. Random explosions/lightning/fires? Supercharged mobs?

**Comment by DoomRater** [comment]
"WE ARE ONLY TEMPORARILY DISABLING THE FILTERS.  CAREFULLY REMOVE THE HATCHES-"
(smash)
Could be that you need a filter and demonz invade if anything goes wrong and then you have to clean it all up Doom style.  Maybe a bit too much like being warped in Thaumcraft plus Invasion mod, but then again what mod actually manages to increase difficulty late game anyway?

**Comment by MichaelHillcox** [comment]
Unfortunately we're no longer supporting versions older than `1.12` and I don't have enough time to check this suggestion against all of the features of the mod but if this feature still hasn’t been implemented and you’d like to see it added to a newer version of the mod then please do create a new issue so we can review your suggestions again :+1:
