### ISSUE TITLE
Can provide more translated text？

### ISSUE THREAD

**Issue by XuyuEre** [McJtyMods/RFTools#411]
Can provide, for example, hold down shift display text and Waila text. Lang file is only the name of the block, and can not  hold the shift text translation. I saw the installation of Waila to provide Waila support, but did not find the Translation entries, hoping to add. In addition, I would also like to translate the manual, but this can not be，Because it will cover the English text,Hope to solve.thanks.:-D

**Comment by MichaelHillcox** [comment]
Unfortunately we're no longer supporting versions older than `1.12` and I don't have enough time to check this suggestion against all of the features of the mod but if this feature still hasn’t been implemented and you’d like to see it added to a newer version of the mod then please do create a new issue so we can review your suggestions again :+1:
