### ISSUE TITLE
Suggestion: Bright Dimlet

### ISSUE THREAD

**Issue by TechnicianLP** [McJtyMods/RFTools#414]
It would be nice to have a dimlet that makes every block in the dimension have a lightlevel of 15 (like the mystcraftpage) so clients don't have to update lighting
there could also be two variants:
 -visual brightness Dimlet (Dimension only Appears bright but isnt)(may also be inserted after
  creation as it is cosmetic)
 -perpetual brightness dimlet (Dimenion really bright so mobs can't spawn)

**Comment by MichaelHillcox** [comment]
As this issue is now 3 years old and hadn't yet been implemented. I'm gunna close and request that if you still want the feature that you add the recommendation to the correct repo for dimlet suggestions: https://github.com/McJtyMods/RFToolsDimensions/issues
