### ISSUE TITLE
Chunk loaders dont work in Dimensions

### ISSUE THREAD

**Issue by Mechrior** [McJtyMods/RFTools#416]
I am playing on the Vaygrims Chance: Season 3 modpack on the ATLauncher and have noticed that NONE of the chunk loaders that come with that pack (Railcraft, MFR, ComputerCraft) keep the realised dimensions loaded. I have even installed chicken chunks to rule out the other mods being the incompatible ones and its chunk loader does not work either no matter what settings I use.

I have a mobfarm (skyfactory style) and a cobble gen using item nodes from extra utilities feeding into an T3 Crafter from RFTools making octuple compressed cobble, neither of which work when i am not in the actual realised dimlet world with ANY of the chunk loaders.

Any help would be greatly appreciated.

**Comment by XFactHD** [comment]
I have a RFTools void world and I am using MFRs chunkloader and it works just fine.

**Comment by Mechrior** [comment]
XFactHD are you running the VC3 modpack if you dont mind me asking?
If not then you might not have the same conflict happenning that I do, I can easily record that it does not work for me, but it is only in the dimlet worlds

**Comment by XFactHD** [comment]
No, but I am using a modpack with over 200 mods. Could you put your mod list on pastebin.com and post the link here, please?

**Comment by Mechrior** [comment]
this is a direct copy of the .txt file i made containing the dir of the mods folder for VC3, minus the personal information

http://pastebin.com/hfLiYVBE

I will have an easier list by tomorrow as there is no .txt file with a list of mods for this mod pack, just the ATLauncher website https://www.atlauncher.com/pack/VaygrimsChance

**Comment by XFactHD** [comment]
No idea what is causing that. If you have time, could you take the mod pack apart and put one mod after the other back in, starting with RFTools and its prerequisites and tell me when it happens again.

**Comment by Mechrior** [comment]
Well im back after a few say, and have stripped the pack down and put it back together with minimal mods (RFtools, big reactors for power, tesseracts for transmission, ender storage for checking if it was still loaded, and chicken chunks to keep it loaded (had already tested the other loaders))

Dimensions still would not stay loaded, started adding mods back in  and nothing changed.

Decided to actually play the pack for a while and made another dimension to place the Blood Magic Convocationd Of The Damned in for the demons and dropped a chickne chunks chunk loader down. THAT LOADER WORKS!!!!!

So I went off and tested all my other dimensions I had made and stored away. EVERY one works unless it is a void dimension of some sort. The moment it has a void dimlet or generates a void on its own, ALL the chunk loaders I have access to stop working in those dimensions.

Dont know if this will help but thats what I have for the moment.

**Comment by McJty** [comment]
That is weird... What has being a void dimension to do with chunkloading???

**Comment by XFactHD** [comment]
This still seems weird to me. I also have a void dim and it stays loaded with a MFR chunk loader.

**Comment by Mechrior** [comment]
Later today I will retest the paack as a whole as my server host just updated it to the latest version (1.2) and see fi the problem still rears its head

**Comment by MichaelHillcox** [comment]
As this issue is super old now, could you confirm if this is still an issue, if it is then please reopen the issue and comment here 👍
