### ISSUE TITLE
Particle effect for transporter fields

### ISSUE THREAD

**Issue by Aedda** [McJtyMods/RFTools#42]
It might look nice to make a particle shower emanating from the transporter pads in lieu of the edge texture. Optional of course.

**Comment by MichaelHillcox** [comment]
Unfortunately we're no longer supporting versions older than `1.12` and I don't have enough time to check this suggestion against all of the features of the mod but if this feature still hasn’t been implemented and you’d like to see it added to a newer version of the mod then please do create a new issue so we can review your suggestions again :+1:
