### ISSUE TITLE
"Infinite" Unknown Dimlet

### ISSUE THREAD

**Issue by nrzimmer** [McJtyMods/RFTools#421]
I found an Unknow Dimlet inside a Runic Dungeons chest.

This specific item causes some issues.
- Logistics pipes can't extract it from any chest.
- When i put it inside a Dimlet Researcher it creates a new Dimlet but doesn't disapear, so i can have infinite dimlets.

I'm playing FTB Infinity Evolved (Expert Mode) Version 2.2.2
RFTools 4.13
Runicdungeons 1.1.6a
Logistics Pipes 0.9.3.70

**Comment by McJty** [comment]
You need to explain that a bit better as I don't know how logistics pipe works. Also if LP is duping dimlets then that sounds like a bug in that mod. But I need to understand what is going on

**Comment by nrzimmer** [comment]
I'll try to explain.

The issue with the pipes is that they can't transfer the item. I tested with other item transfer mods and the bug occurs with them too.

The first 3 images in this link show the problem with Itemducts:

http://imgur.com/a/p1rrI

First: Destination Chest
Second: Setup (One itemduct with a servo, redstone control disabled)
Third: Origin Chest

The other images show the duping.

I put the dimlet in the Dimlet Researcher and it doens't get consumed.

**Comment by nrzimmer** [comment]
There are a few of other things that happen:

* Can't Shift Click this Dimlet (Machines and inventories)
* Doesn't Stack

**Comment by McJty** [comment]
This has not been reported before and would be a serious bug so I'm really wondering what is going on here. I wonder if there is some kind of mod interaction going on. Is it only with that one dimlet that the problem occurs? Then it might be a bug in runic dungeons too

**Comment by nrzimmer** [comment]
Until now is only this single dimlet.

If there is anything you need, just tell me.

**Comment by McJty** [comment]
I think that this is most likely a bug in runic dungeons and how it generates loot. Perhaps it messes up the unknown dimlet itemstack somehow

**Comment by nrzimmer** [comment]
Is there a way to see the info inside the game? Or maybe export the data of my inventory into a json or something like this?

**Comment by Organics** [comment]
Just want to add that I have also encountered the same bug in FTB Infinity Evolved. Unsure if the bugged dimlet is from Runic Dungeons but we have found a large number of dimlets there so I suppose it's likely - that said, of all the dimlets we've found including at least 20 from runic dungeons, only one seems to have bugged like this.

**Comment by DaMachinator** [comment]
If you have minetweaker, enable cheats and type /mt hand with the bugged dimlet in hand. This should get you all the data on it.

**Comment by MichaelHillcox** [comment]
As this issue is super old now, could you confirm if this is still an issue, if it is then please reopen the issue and comment here 👍
