### ISSUE TITLE
Issue with generating chunks and creating a new world.

### ISSUE THREAD

**Issue by SethZurborg** [McJtyMods/RFTools#424]
From my observations, if you want a new world while another world is being generated, the world that is being generated will begin generating chunks belonging to the newly created world. 
Mod Pack being used FTB Infinity Evolved 2.2.2

Steps to Reproduce (Using RFTools as the dim creator)
1. Make a world, and allows a specific set of biomes.
2. Start filling the world using WorldBorder-Forge
3. Make new world that allow a single biome.
4. When the generation of the initial world is done, it will contain [misgenerated chunks](https://drive.google.com/file/d/0B0c5T4bkwhIiNjVhU1N5Mk9wd2M/view?usp=sharing)

Posted here and on the [WorldBorder-Forge](https://github.com/Gamealition/WorldBorder-Forge/issues/13) issue tracker.

**Comment by McJty** [comment]
What kind of dimensions were the two? I mean the type of terrain

**Comment by SethZurborg** [comment]
The first time this happened they were both normal terrain. The second time this happened one was normal, and the other was islands.

Both times it happened the world went from generating with a set of 7 biomes, to being exclusively one (Which was not part of the set of 7)

**Comment by McJty** [comment]
I don't really know what WorldBorder-Forge does so maybe it does something bad in this respect? Did you try with other dimension creators (mystcraft, deep dark, TF, ...)

**Comment by SethZurborg** [comment]
I will try the other dim providers when i can, so far i have only been able to reproduce using rftools dimensions.

**Comment by SethZurborg** [comment]
I have tried the other dim providers as have not been able to cause a replication of the issue, it is only reproducible when using 2 RFT created dims.

**Comment by MichaelHillcox** [comment]
As this issue is super old now, could you confirm if this is still an issue, if it is then please reopen the issue and comment here 👍
