### ISSUE TITLE
Block Protector, IC2 Nuke and SDX

### ISSUE THREAD

**Issue by lellasone** [McJtyMods/RFTools#426]
Hello, 

From what I can tell IC2 Nukes and SDX from TC seem to directly bypass Block Protectors without draining energy. I realize this is probobly not an issue on your side, but since those make up such an important part of the PVP balance in 1.7.10 I figured I would let you know. 

Thanks for everything you do. 
Your work is amazing, 
Jake

**Comment by MichaelHillcox** [comment]
Close as 1.7.10 is no longer supported. If this continues to be a bug on 1.12 or newer, please open a new issue.
