### ISSUE TITLE
[Feature Request] Storage Modules Sort for GenDustry 

### ISSUE THREAD

**Issue by duncanwebb** [McJtyMods/RFTools#431]
Hi

Would it be possible to have a sort module for the Genes samples and templates. I'm using storage modules to store the genes and am having to scan over each one to find a specific gene. The hardest one are the gene samples for species as there are a lot of species the other genes are less time consuming to find.

Templates could be sorted by species first and then other attributes like effect and flowers.

Thanks

**Comment by MichaelHillcox** [comment]
Personally I feel this would completely fall out of the scope of the mod. It would on the other hand be a great mod for someone to make that possibly uses RFTools as a base. I'll close this as it's super old but if you'd like it to be considered again for this mod either comment here and reopen or start up a new issue. Thanks 👍
