### ISSUE TITLE
DImension randomly loading and unloading

### ISSUE THREAD

**Issue by ghost** [McJtyMods/RFTools#435]
Having a bit of a strange issue with rftools. One of my dimensions is loading and unloading rapidly and for seemingly no reason.

In an attempt to fix this I purged the dimension folder. The server recreated it and the problem persists.

Example:
[16:27:47] [Server thread/INFO] [FML]: Unloading dimension 252
[16:28:01] [Server thread/INFO] [FML]: Loading dimension 252 (ArchonsNexusAlpha)

No players are entering or leaving the dimension. All testing was done on the latest version of rftools for 1.7.10 using the latest available version of Forge.

Edit: After using the dimdel command I'm now getting spammed with this:
Cannot Hotload Dim: Could not get provider type for dimension 252, does not exist

Any input you could provide would be wonderful.

Edit 2: Isolated the issue to DImDoors. DimDoors generating in rftools dimensions are causing the dimension to 'hotload'. For any stumbling across this, DImDoors allows you to whitelist the generating of dimdoors. I suggest setting it to Overworld only.

I'm going to keep this open until I am absolutely sure the problem lies with DimDoors. Sorry in advance if this ends up being a knee jerk post. (So tired I typed actually twice)

Edit 3: Removed DImDoors, dimension is still unloading and loading causing the entire server to stall out. This has to be an issue with RFTools. I've done all the testing I can. 

Edit 4: This is my fourth and final edit. Using /rftdim safedel to delete the dimension and promptly restarting the server has finally cleared this issue. Seven hours of head bashing coupled with fears of world corruption and I still have no clue as to what caused this.

**Comment by McJty** [comment]
Thanks for the detailed information but it is going to be hard to really find out what caused this. The dimension could have gotten corrupted by the presence of dimdoors before it.

**Comment by XFactHD** [comment]
I set up a server a few days ago to test something and I got a similar problem. Until I entered the RFTools dim, it kept loading and after that quickly unloading the dimension. The dimension contains a chunkloader at the spawnpoint.

**Comment by PsionicArchon** [comment]
Any clue as to what might have spawned in the dim?

Chunkloading the dimension does cause it to stop unloading however, what ever corruption was causing the initial issue would eventually stall out my server. 

Also, thanks for the reply McJty. It does appear to have been corrupted. I'm pretty exhausted, I'll spend some more time trying to reproduce the issue in a test world tomorrow. For the mean time, I suggest anyone making Overworld style dimensions with dimdoors installed either blacklist dimdoors from rftools dimensions or warn their servers.

**Comment by MichaelHillcox** [comment]
Close as 1.7.10 is no longer supported. If this continues to be a bug on 1.12 or newer, please open a new issue.
