### ISSUE TITLE
[1.7.10][RFTools 4.20][FTB infinity 2.3.5] inconsistent Endergenic Generator delay 

### ISSUE THREAD

**Issue by Vritra22189** [McJtyMods/RFTools#439]
in my creative testing world, 
i chained a few generator with 9 empty block separation (4 tick distance)
each hooked to a sequencer, which are hooked to the same 100ticks (5s) timer. 
(with the first sequencer pointing to a pearl injector)
and tuned the sequencer for max RF/t in each generator.
![2016-01-31_14 33 06](https://cloud.githubusercontent.com/assets/9210589/12700763/76101d50-c82a-11e5-982e-cf9cd4e60166.png)

but looking at the sequencer afterwards, the delay between each generator is inconsistent
varying from 3-5 ticks 
![2016-01-31_14 35 02](https://cloud.githubusercontent.com/assets/9210589/12700728/5d50d562-c829-11e5-98cd-ce322d18d820.png)
![2016-01-31_14 35 20](https://cloud.githubusercontent.com/assets/9210589/12700730/5d53a47c-c829-11e5-9239-87bb0f934b40.png)
![2016-01-31_14 35 31](https://cloud.githubusercontent.com/assets/9210589/12700731/5d542168-c829-11e5-89ea-83f102c2f355.png)
![2016-01-31_14 35 46](https://cloud.githubusercontent.com/assets/9210589/12700729/5d5299f6-c829-11e5-83c4-c925f8206792.png)
![2016-01-31_14 35 57](https://cloud.githubusercontent.com/assets/9210589/12700732/5d5478e8-c829-11e5-8fbe-d87547126ee8.png)
![2016-01-31_14 36 07](https://cloud.githubusercontent.com/assets/9210589/12700733/5d56f672-c829-11e5-9a98-af6787792ef2.png)

**Comment by Vritra22189** [comment]
the above trial have a delay of (4,3,5,4,4)
then upon reload the world, it failed outputting max RF/t, i have to re-tune the sequencer
this time it has a delay of (3,6,4,4,4)...

**Comment by McJty** [comment]
The problem is most likely that there is no guarantee in which order tile entities are ticked and since this is so timing sensitive the 'in-tick' order can matter a lot. Not sure exactly how I'm going to solve this though. I'm thinking I probably need to handle the entire 'multiblock' ticking at once

**Comment by Vritra22189** [comment]
what about having a block called Endergenic Stabilizer, which registers some generator and pearl injector, then tick them together?
then we can have the original generator as a not-so-stable generator, in which player have to sacrifice max efficiency to compensate stability.

p.s. ender monitor also fail to output any signal when generator is receiving&launching in the same tick.
