### ISSUE TITLE
Feature Request: Weather Absorber

### ISSUE THREAD

**Issue by Benie76** [McJtyMods/RFTools#442]
Ok. It seems the No Rain dimlet is extremely rare, to the point it's down-right ridiculous (and really annoying). It can't be crafted; only found. And I've been going through countless Unknown Dimlets and no luck.
Please... for the love of all that is not grindy and tedious to the point it's getting boring, give us a Weather Absorber. I think I rather wait 10 days having it in a Sandy biome to capture having no rain, than hunting forever for it.

At least, lower the rarity in finding the dang thing. It shouldn't be THIS rare...
Using the 1.10.0 version of the Direwolf20 pack.

**Comment by MichaelHillcox** [comment]
From what I can tell from the mod source,  you can modify the rarity of the dimlets in the config. Some dimlets are designs to be harder to find :P If you feel this should still be considered then please do reopen the issue.
