### ISSUE TITLE
CC Compatibility

### ISSUE THREAD

**Issue by AleTopp** [McJtyMods/RFTools#450]
Hi!
How do all the commands work with CC (dial, dialOnce, interrupt, etc.), or what i have to put in the brackets?
Sorry for my English, but I'm Italian.
Thanks
AleCraftNapoli

**Comment by MichaelHillcox** [comment]
Hmm, check the Wiki I guess? https://github.com/McJtyMods/RFTools/wiki/RFTools-Dialing-Device if this doesn't help then please do reopen the issue :D
