### ISSUE TITLE
Server crash Storage Module Tablet

### ISSUE THREAD

**Issue by OmegaCenti** [McJtyMods/RFTools#475]
https://gist.github.com/OmegaCenti/5b3c64e90082fb97f6aa

**Comment by McJty** [comment]
Can you tell me how you got this? When does this happen?

**Comment by OmegaCenti** [comment]
Unfortunately I cannot, I can tell you we have storage tablets in our inventories, they are upgraded, we randomly crash.

**Comment by OmegaCenti** [comment]
another one: https://gist.github.com/OmegaCenti/bd0a08904d72e817427b7345c256a89c

**Comment by OmegaCenti** [comment]
And another one, fresh server restart, member logs in, full server crash:

https://gist.github.com/OmegaCenti/8c4db17e38c0d0d34b505aa3f1fb6963

**Comment by MichaelHillcox** [comment]
Thank you for taking the time to create this issue, as we're no longer supporting versions below `1.12`, I'm going to go ahead and close it but if this bug seems to continue over to newer versions, please do report it again so we can investigate the issue further.
