### ISSUE TITLE
Matter receiver forgets its name when moved with frame mods or warp drive mod

### ISSUE THREAD

**Issue by zzzzzig** [McJtyMods/RFTools#507]
Hello!
I'm on Minecraft 1.7.10, and RFTools 4.23.
I've found a problem with the matter receiver and frame mods. If you move a matter receiver with a frame mod or WarpDrive mod, its name doesn't show up in dialing devices. There is still an entry in the 
dialing device list for the matter receiver, but the name is blank. The name is still in the matter receiver GUI.  If you change the name in the matter receiver GUI, the name then shows up in the dialing device. The Dialing device also seems to forget that the moved matter receiver was favorited.
Interestingly, this problem doesn't happen with the matter transmitter.

I have tested this with Funky Locomotion, Framez, Remain in Motion, and WarpDrive, and it happens on all four.

**Comment by Divineaspect** [comment]
Same thing is true with Archimedes Ships +

**Comment by MichaelHillcox** [comment]
Close as 1.7.10 is no longer supported. If this continues to be a bug on 1.12 or newer, please open a new issue.
