### ISSUE TITLE
Storage Module Tablet getting pulled out of inventory when open crashes game

### ISSUE THREAD

**Issue by LezChap** [McJtyMods/RFTools#537]
https://gist.github.com/LezChap/b5a44c818306715733e8429f12d78c7d

I was helping testing looking for dupe bugs similar to https://github.com/Nuchaz/BiblioCraft/issues/324

When I used the Storage Module Tablet using version 4.23 in 1.7.10 in FTB Infinity, using SFM Advanced Inventory Relay to pull the Tablet out of my inventory while open, it crashed my game to desktop.  Not sure how much up your updating to 1.9 might have fixed this, but figured I'd report it regardless in case it hadn't (it's an edge-case, and I didn't find anything in previous issues).

**Comment by BlueAgent** [comment]
I think I've encountered a similar issue, it might be the same thing.
This also occurs if you right click to open the storage, but then select a different slot on your hot bar before the GUI opens.

This leads me to believe, some code is expecting for item to be in hand once the server responds.

**Comment by McJty** [comment]
I'm not convinced that's a bug in RFTools. RFTools clearly marks the slot for the storage cell as one that you should not access from any side. Automation is not supposed to pull out of that slot. The issue from BlueAgent is weird though. I would like to see the log for that

**Comment by LezChap** [comment]
@McJty I'm talking about the storage tablet...the item you access in your inventory hotbar.  Automation that can pull items out of your inventory or hotbar can grab that as well...just like a golden bag of holding.  

Based on your response, it sounds like you're talking about the block, and not being able to access the storage item slot (forget what it's called) via Automation.  

I didn't think Forge had handlers for preventing other mods from accessing certain slots in your inventory and/or hotbar via Automation like they do for TileEntities/Blocks.

**Comment by MichaelHillcox** [comment]
Thank you for taking the time to create this issue, as we're no longer supporting versions below `1.12`, I'm going to go ahead and close it but if this bug seems to continue over to newer versions, please do report it again so we can investigate the issue further.
