### ISSUE TITLE
Storage Scanner highlighting causes arm to become transparent

### ISSUE THREAD

**Issue by ghost** [McJtyMods/RFTools#540]
![2016-05-20_16` 00 46](https://cloud.githubusercontent.com/assets/12205824/15440574/269e2a34-1ea4-11e6-9506-bc1e5b1e8021.png)
![2016-05-20_16 00 47](https://cloud.githubusercontent.com/assets/12205824/15440575/26aa38c4-1ea4-11e6-95fd-47d12aa9ff2e.png)

Settings:
![2016-05-20_16 03 36](https://cloud.githubusercontent.com/assets/12205824/15440618/6f8616ee-1ea4-11e6-9c46-fd398a7ec928.png)

I have an AMD graphics card.

**Comment by MichaelHillcox** [comment]
Thank you for taking the time to create this issue, as we're no longer supporting versions below `1.12`, I'm going to go ahead and close it but if this bug seems to continue over to newer versions, please do report it again so we can investigate the issue further.
