### ISSUE TITLE
[1.9.4] Builder improvement for clearing quarry and liquids

### ISSUE THREAD

**Issue by tommyTT** [McJtyMods/RFTools#558]
I'm using the builder and a clearing quarry card to clear out a huge amount of space in the nether but the many lava pockets are really causing an issue. Since the builder clears one chunk at a time, the lava pockets spill into the current chunk and because of the weird liquid physics in minecraft, the lava really spreads over a big area. Afterwards I have to manually plug those lava source blocks which causes the lava to slowly vanish but causing a lot of lag because of all the block updates. It is also very very slow. I could let the builder run again to clear it, but this isn't really ideal.
Somehow the builder should be able to prevent that from happening. I realize, that changing blocks outside the quarried area is a bad idea, but at least filling in those blocks that will be quarried later would be a start. For the outer borders of the quarried area I can only think of placing temporary blocks there to stop the liquid flowing into the quarried chunk. Maybe someone has a better idea?

Versions
Force 12.17.0.1952
RFTools 1.9.4-4.51
McJtyLib 1.9.4-1.8.7

**Comment by tyler489** [comment]
Would love to see a upgrade that makes the quarry function like a pump.

**Comment by Divineaspect** [comment]
Please. That would be so wonderful.

**Comment by McJty** [comment]
The builder voids liquid source blocks already so not sure what the issue is here?

**Comment by tommyTT** [comment]
It does void liquids but only inside the chunk it currently mines. My problem was the source blocks that are right at the edge in an adjacent chunk. Those blocks flow into the quarried chunk and depending on the speed of the builder, the fluid can flow a long way. Removing those source blocks afterwards then causes a lot of lag and is very slow. I could remove the source blocks outside the quarried chunks manually and let the builder run again, but it would be nice if the builder could handle all that directly.
In your recent youtube video you had the same thing happening with water, which isn't quite as bad and since you quarried out the source blocks later, it wasn't that big of a problem. I quarried in the nether (I had the nether metals mod in my pack) and the lava pockets where completely outside the quarried area. Since I quarried a very large area, that one source block afterwards flowed into about 7+ chunks which was a real pain to clean up by hand.

**Comment by tod** [comment]
It would be nice if there was a way to get it to ignore liquids, at least when not in "clearing" mode. The way it is now, when you use it near an ocean you have to be careful you don't create ugly large square sections.

**Comment by Optimoos** [comment]
Wanted to bump this issue. Expanding the radius of the quarry by 1 or somehow monitoring the neighboring chunks and replacing fluid blocks with dirt would prevent fluid from spilling into mined chunks. This means you'd have to have more than a single chunk loaded at a time but it's definitely preferable to using a clearing quarry in the nether.

Even using it in mining dimensions where any fluid exists means that fluids in adjacent chunks can flow, it's just particularly obnoxious in the nether.

**Comment by McJty** [comment]
Well why not use a quarry that replaces with dirt? For a clearing quarry I cannot really solve this in any nice and maintainable way. But the normal 'dirt' quarry is meant exactly for this kind of lag-free quarry solution. That's also how the ender quarry solves it btw

**Comment by Optimoos** [comment]
That was my initial solution as well. The only problem is in dimensions like Aroma's mining dimension (or hell, even just the overworld), the surface is dirt so it's very hard to determine where the quarry has done its work, so I switched to a clearing quarry. However, Aroma's also has natural water and lava generation which end up flowing if they're on the chunk boundary.

If it's not feasible, that's fine, just wanted to add my perspective.

**Comment by tod** [comment]
You could always build a cube 1 block bigger than your quarry to prevent flow. 

I really appreciate the pump upgrade that was added recently, but I do wish that there was a way to ignore liquids too so that you could quarry an ocean without turning it all to dirt.

**Comment by MichaelHillcox** [comment]
Unfortunately we're no longer supporting versions older than `1.12` and I don't have enough time to check this suggestion against all of the features of the mod but if this feature still hasn’t been implemented and you’d like to see it added to a newer version of the mod then please do create a new issue so we can review your suggestions again :+1:
