### ISSUE TITLE
[1.7.10] Crash when dimension generates chunks using Twilight Forest things

### ISSUE THREAD

**Issue by MapperTV** [McJtyMods/RFTools#560]
Using RFTools 4.23, McJtyLib 1.8.1 and Twilight Forest 2.3.7 (all are latest versions for 1.7.10), in a lightly modified Infinity Evolved modpack. Fastcraft is enabled.

Crashlog: http://pastebin.com/9UiQuXPK

This only happens on server side! (clients don't crash, but I guess single player mode will simply crash the client)

It happens when a player makes the server generating new chunks in a RFTools dimension using a Twilight Forest biome (which generate structures like trees, houses, ruins and spawn animals). Being in the dimension without creating chunks works fine.

Is there a way to prevent RFtools dimensions to use Twilight Forest biomes / blocks / whatever?

Note: The Twilight Forest dimension itself is fine, no problem. It only happens in RFTools dimensions.

**Comment by MichaelHillcox** [comment]
Close as 1.7.10 is no longer supported. If this continues to be a bug on 1.12 or newer, please open a new issue.
