### ISSUE TITLE
[1.9.4] Elevator platform split across chunk boundary loses part of platform

### ISSUE THREAD

**Issue by RealGrep** [McJtyMods/RFTools#562]
I've had two different but related glitches with my (truly awesomely cool) elevator. A few times, it has become disconnected from the rest of the platform which is across a chunk boundary from the first row of three glass blocks that form the part of the platform adjacent to the elevator block. Those three blocks will move and the other 6 blocks of the 3x3 platform get left behind.

Today, it completely lost those 6 blocks leaving only three blocks next to the elevator block. No idea where the other 6 blocks went, but it is no coincidence that they are directly across a chunk boundary.

Pretty sure that each time, I have flown off into the distance, then later come back. Perhaps when I come back to it, the way the chunks load with the platform split across chunk boundaries causes the issue.

Nothing seems to appear in the logs at those times, as far as I can see. I will keep an eye out for anything next time this happens and see if I can get more information that might help.

**Comment by McJty** [comment]
This will be a tough one to fix. I will try to look at it but in general I do recommend to avoid crossing chunk boundaries with the elevator platform. Or use a chunk loader to keep the elevator chunks loaded

**Comment by MichaelHillcox** [comment]
Thank you for taking the time to create this issue, as we're no longer supporting versions below `1.12`, I'm going to go ahead and close it but if this bug seems to continue over to newer versions, please do report it again so we can investigate the issue further.
