### ISSUE TITLE
[1.7.10] DraconiumOre cannot be quarried even changing the config

### ISSUE THREAD

**Issue by edusaraiva** [McJtyMods/RFTools#580]
I cant find a way to make the rftools quarry to mine Draconium Ores even changing the config.
Anyone can help me?

**Comment by McJty** [comment]
How did you change the config exactly? What version of RFTools?

**Comment by edusaraiva** [comment]
My version is:
FTB 2.5
Minecraft 1.7.10
rftools 4.23

And this is my config set both on my local host and my client

##########################################################################################################
# spaceprojector
#--------------------------------------------------------------------------------------------------------#
# Settings for the space projector system
##########################################################################################################

spaceprojector {
    # Maximum RF storage that the builder can hold
    I:builderMaxRF=10000000

    # RF per tick that the builder can receive
    I:builderRFPerTick=50000

    # RF per entity move operation for the builder
    I:builderRfPerEntity=5000

    # RF per block operation for the builder when used to build
    I:builderRfPerOperation=500

    # RF per player move operation for the builder
    I:builderRfPerPlayer=40000

    # Base RF per block operation for the builder when used as a quarry or voider (actual cost depends on hardness of block)
    I:builderRfPerQuarry=300

    # If true we allow the clearing quarry cards to be crafted (these can be heavier on the server)
    B:clearingQuarryAllowed=true

    # How much more expensive a move accross dimensions is
    D:dimensionCostFactor=5.0

    # The RF per operation of the builder is multiplied with this factor when using the fortune quarry shape card
    D:fortunequarryShapeCardFactor=2.0

    # Maximum dimension of the shape when a shape card is used in the builder
    I:maxBuilderDimension=512

    # Maximum offset of the shape when a shape card is used in the builder
    I:maxBuilderOffset=260

    # Maximum dimension for the space chamber
    I:maxSpaceChamberDimension=128

    # If true we go back to the old (wrong) sphere/cylinder calculation for the builder/shield
    B:oldSphereCylinderShape=false

    # If true we allow quarry cards to be crafted
    B:quarryAllowed=true

    # The base speed (number of blocks per tick) of the quarry
    I:quarryBaseSpeed=8

    # If true the quarry will chunkload a chunk at a time. If false the quarry will stop if a chunk is not loaded
    B:quarryChunkloads=true

    # Multiply the infusion factor with this value and add that to the quarry base speed
    I:quarryInfusionSpeedFactor=20

    # If true the quarry will skip all tile entities. Set this to false to allow harvesting ores that are tile entities. Be careful with this!
    B:quarrySkipTileEntities=false

    # If true we allow shape cards to be crafted. Note that in order to use the quarry system you must also enable this
    B:shapeCardAllowed=true

    # The RF per operation of the builder is multiplied with this factor when using the silk quarry shape card
    D:silkquarryShapeCardFactor=3.0

    # Maximum RF storage that the space projector can hold
    I:spaceProjectorMaxRF=100000

    # RF per tick that the space projector can receive
    I:spaceProjectorRFPerTick=1000

    # Can Tile Entities be moved? 'forbidden' means never, 'whitelist' means only whitelisted, 'blacklist' means all except blacklisted, 'allowed' means all
    S:tileEntityMode=allowed

    # The RF per operation of the builder is multiplied with this factor when using the void shape card
    D:voidShapeCardFactor=0.5
}

**Comment by Hirsu** [comment]
I'd like to confirm this issue.
Also using FTB Infinity 2.5.0 (so MC 1.7.10) and RFTools 4.23.

I'm running the modpack on a local server. I've changed both the server's and the client's configs so quarrySkipTileEntities is set to false. The builder still won't mine any draconium ore.

I'm just dropping by to let mcJty know about this issue, apparently I'm not the only one having it ;)

**Comment by FrostyGoblin** [comment]
I have exactly the same issue. Using a clearing quarry and the Draconium Blocks are all there, blinking away, laughing at me..

FTB Infinity Evolved 2.5.0
RFTools 4.23

I have changed the configs both locally and on the server, exactly like above. Also tried both settings in the actual builder, move tile entities and not. All the draconium is still there.

**Comment by MichaelHillcox** [comment]
Close as 1.7.10 is no longer supported. If this continues to be a bug on 1.12 or newer, please open a new issue.
