### ISSUE TITLE
Tesla Support

### ISSUE THREAD

**Issue by ProfessorProspector** [McJtyMods/RFTools#595]
I know you've talked about this, but it might be good to have an issue for dicussion.

**Comment by McJty** [comment]
I haven't had time to look into this yet. I would like (when I have time) to start with this by at least letting my RF monitor and RF screen module support tesla and then build up from there

**Comment by ProfessorProspector** [comment]
Alright, sounds good. If you want you could use this issue as a way to show progress updates

**Comment by EntityReborn** [comment]
Hello, re: https://github.com/aidancbrady/Mekanism/issues/4140 , I would like to bump this request.
