### ISSUE TITLE
[1.10] Liquid Absorber?

### ISSUE THREAD

**Issue by NanayaQ** [McJtyMods/RFTools#599]
So I started to look into Liquid Absorber I notice it only absorb lava and water atm I was trying to use it to absorb Fire Water (Enderio) and Syngas (Advance Generator), since I have enough materials to craft the dimlets for it. However I notice even though it absorb the fire water and syngas, but does not show it have absorb it nor can't be crafted in the rftool workbench (even though it said I can, but does not have the liquid absorber for it). I was wondering if its intended to use only water and lava, have to find then in other dimension, or is it a bug?

**Comment by McJty** [comment]
Is the dimlet listed in the dimlet workbench? I think most liquid dimlets are disabled by default right now. I'll check it out later in detail though

**Comment by NanayaQ** [comment]
Yes its listed in the [workbench](http://puu.sh/pNmCF/092c816fe8.jpg) both Syngas and Fire Water Dimlet. If its disable atm then I guess I'll just make another stack of coal generator automation for the time being then.

**Comment by McJty** [comment]
What version of rftools is this btw?

**Comment by MichaelHillcox** [comment]
Thank you for taking the time to create this issue, as we're no longer supporting versions below `1.12`, I'm going to go ahead and close it but if this bug seems to continue over to newer versions, please do report it again so we can investigate the issue further.
