### ISSUE TITLE
Matter Transmitter and Boats...

### ISSUE THREAD

**Issue by JorVaCoding** [McJtyMods/RFTools#624]
So when on a boat on top of a matter transmitter, it teleports you then it pulls you back to the spot of the boat, then teleports you back, in an endless cycle...

Version: rftools-1.10-5.04

**Comment by MichaelHillcox** [comment]
Thank you for taking the time to create this issue, as we're no longer supporting versions below `1.12`, I'm going to go ahead and close it but if this bug seems to continue over to newer versions, please do report it again so we can investigate the issue further.
