### ISSUE TITLE
Builder block (breaking texture on leaves with silk quarry)

### ISSUE THREAD

**Issue by DnTheMn** [McJtyMods/RFTools#627]
the silk clearing card mines leaves and it breaks the texture of them and it shows the leaves as the missing texture

**Comment by PresidentBizness** [comment]
Sideways may explain why my quarry picked up some good wood and more with bad textures.  It's not limited to spruce wood.  I've seen this on Acacia, Dark Oak, Oak as well.

**Comment by MichaelHillcox** [comment]
Thank you for taking the time to create this issue, as we're no longer supporting versions below `1.12`, I'm going to go ahead and close it but if this bug seems to continue over to newer versions, please do report it again so we can investigate the issue further.
