### ISSUE TITLE
Elevators give you permanent creative flight when disconnecting

### ISSUE THREAD

**Issue by Ellpeck** [McJtyMods/RFTools#632]
When you disconnect while riding an elevator and then connect again after the elevator has finished moving, you will be standing in the air and actually have creative flight and full control of it.
You can stop flying like normal, but it doesn't fix the issue as the creative flight ability still stays.

When riding an elevator again without disconnecting, the issue is fixed.

**Comment by Meli0** [comment]
I can confirm this on SF3 1.10, Direworl20 1.10 servers

**Comment by MichaelHillcox** [comment]
Thank you for taking the time to create this issue, as we're no longer supporting versions below `1.12`, I'm going to go ahead and close it but if this bug seems to continue over to newer versions, please do report it again so we can investigate the issue further.

**Comment by lukachukai1** [comment]
confirming this in 1.12.2 actually, it works (custom modpack)
