### ISSUE TITLE
Suggestion: Pump Card for Builder

### ISSUE THREAD

**Issue by DRTR0** [McJtyMods/RFTools#639]
Title explains it mostly. Not many pump options in 1.10. Please change that.

**Comment by MichaelHillcox** [comment]
Unfortunately we're no longer supporting versions older than `1.12` and I don't have enough time to check this suggestion against all of the features of the mod but if this feature still hasn’t been implemented and you’d like to see it added to a newer version of the mod then please do create a new issue so we can review your suggestions again :+1:
