### ISSUE TITLE
Dimlets not craftable

### ISSUE THREAD

**Issue by Tessellry** [McJtyMods/RFTools#646]
MC: 1.10.2
Forge: 12.18.1.2011
RFTools Version: 1.10-5.06
AT DonutCraft Version 1.10.2/0.0.6c

Been struggling for hours creating dimlets that require essence. For example Peaceful - I couldnt get it done with either the essence item taken from creative mode or manually; by doing it with 9 syringes of specific mobs blood. Zombie pigmen blood was registered as common zombie so it wasn't even possible to do the essence item in survival mode.

Not one of the creative structure essence items work either (Dungeon, Fortress ect)... I placed them in the last "drop-place" slot in the Dimlet Workbench... Maybe Im doing it wrong, but are they not supposed to be placed there? Every other part is correct but nothing happens no matter what essence is added.

Regarding structure, controller, effect, special and mob recipes in the Dimlet Workbench they only have 5 parts - the last (6th) is missing. Its especially confusing considering the essences do exist for the structures? As for the others - is it so that they are not supposed to be able to craft ?
I have tried it both in single- and multiplayer... to no avail. 

I have searched for information about this in different forums and wikis' but haven't found any information. Would be grateful for answers. Thank you.

**Comment by mkleiman312** [comment]
https://github.com/McJty/RFTools/issues/633

**Comment by Tessellry** [comment]
Yes I saw yours mkleiman. Did u have the same problem to about the blod - that the zombie pigmen registered as a common zombie ?

**Comment by mkleiman312** [comment]
No, I was simply cross-referencing because the issues are clearly related, at least in part.

**Comment by utoc** [comment]
Chiming in on this as well; Zombie Pigmen give "Zombie" blood with syringe with rfTools 5.21, mcjtylib 1.9.9 and FML 2076

**Comment by MichaelHillcox** [comment]
Closed in preference of #633
