### ISSUE TITLE
Ctrl keys put weird text in search bar

### ISSUE THREAD

**Issue by vdrake77** [McJtyMods/RFTools#652]
Ctrl+A should select all for quick highlighting, but does not.  Ctrl A S D F gives SOH, DC3, EOT, and ACK.

I keep doing this to myself and it keeps annoying me that it doesn't work.

**Comment by BrisingrAerowing** [comment]
As a note, those are [control characters](https://en.wikipedia.org/wiki/Control_character). On Windows, control + shift + a gives the SOH control character, so you likely have a stuck shift key. Try tapping each one to unstick it and try again.

**Comment by MichaelHillcox** [comment]
Thank you for taking the time to create this issue, as we're no longer supporting versions below `1.12`, I'm going to go ahead and close it but if this bug seems to continue over to newer versions, please do report it again so we can investigate the issue further.
