### ISSUE TITLE
Builder not copying some pretty basic vanilla blocks

### ISSUE THREAD

**Issue by steven6282** [McJtyMods/RFTools#663]
This might be me just not understanding how this build is supposed to work, but it seems to be unable to copy some pretty basic vanilla blocks.  I was setting up an enderman farm tonight, and built the first layer, cobblestone, redstone torches, pistons, and pressure plates.  The only part of it that the builder would copy is the cobblestone.  Everything else, even though it was in the chest on top of the builder did not get copied.

I can't imagine this is functioning as intended?  Otherwise it's usefulness seems extremely limited.  I had to resort to using Buildcrafts builder tonight and it handled everything except for the pressure plates.

**Comment by McJty** [comment]
I will check it out. What version of rftools btw?

**Comment by steven6282** [comment]
4.23, just playing with it some more, I set up a smaller test scenario to play with.  It moves a piston, but fails to move a redstone torch, instead just breaks it and drops it over where stuff is being moved from (guessing cause it moves the block it's attached to first.. and if there isn't a block at it's destination not sure what it will do).  Same thing for a pressure plate, so guessing that will happen on a move for anything that "attaches" to another block (redstone, torches, pressure plates, etc.).

Will not copy the blocks though.  I read something in the update notes about a tile entity thing, I think it only effects the quarry, but I tried setting it to false anyway to see if it would make a difference and did not appear to.

**Comment by DoomRater** [comment]
On the topic of failing to copy basic vanilla blocks, I can include upside down sandstone stair blocks.  I was going to copy a rather detailed wall with the builder repeatedly and since it failed to copy the stair blocks, I decided against it since that was the detail that took the longest in the first place.  However I have a feeling my version (the one included with Modsauce 2.2.4) is potentially older than the one reported here.  (indeed, 3.35)

**Comment by MichaelHillcox** [comment]
Close as 1.7.10 is no longer supported. If this continues to be a bug on 1.12 or newer, please open a new issue.
