### ISSUE TITLE
RF Module in Screen Flashing

### ISSUE THREAD

**Issue by Susjin** [McJtyMods/RFTools#669]
Depenting of the position that i'm looking in the screen, some parts of the numbers in the screen disappear, and i'm not using optfine, cause it is famous of doing that things.

Version:
RFTools: 5.11
Forge: 12.18.1.2024

Screenshots:
http://imgur.com/a/hqY1U

**Comment by McJty** [comment]
Do you have optifine or anything other client-side mod that affects rendering installed? Never seen that before

**Comment by Susjin** [comment]
Nop, i don't have any mods that changes rendering, but recently i disabled the bar and it stopped doing that

**Comment by McJty** [comment]
The bar? What bar?

**Comment by Susjin** [comment]
There is an red bar at the background of the numbers, and you can disable that bar in the screen
