### ISSUE TITLE
Endergenic Generators, sometimes cant work other times its over working.

### ISSUE THREAD

**Issue by sherkas** [McJtyMods/RFTools#679]
So this is my first experience with endergenics and using a pretty simple stable setup it works wonderfully.

Its incredibly bullet proof but I have seen a few oddities in the last couple days and wanted some help trying to see whats causing them. Its a simple 4x4 block gen setup (gen/seq/monitor facing the next). 

Anyways on lag or when placing pipes or extra blocks around the gens I notice timing goes off and they wont tick properly and I cant get a sustained flow. When they are clear around them, they work non stop and gen 10k rf/t reliably for quite a while.

Ive noticed on server up/downs that if I dont stop them prior that when the server comes up... they get into a ... near flawless loop. Typically my pearls do 7-10 launches each before a fail. (so a combined of 28-40 launches before a fail). When I get a flawless run, im getting 17-20 launches each ... but thats only what it displays, ive seen the pearl go for a few minutes non stop and generate some really high output when it should have failed already. So how would I go about testing this? Im pretty sure if you get pearls going and take down a server then bring it back up, it should give you a flawless run or two.

If I toss in more pearls into the injector, it uses them but the generators still say its on a 15+ pearl launch run. So is there anything I can test or help with for this issue? I know its kinda vague but just adding it to tracker for now.

**Comment by McJty** [comment]
I have noticed the same and I am planning a very thorough step-through in code of its operation to see how I can make it stable. I suspect the sub-tick redstone pulsing are messing it up

**Comment by sherkas** [comment]
I have a world with endergenics and plan to do a massive build with them so if you make any changes or have alpha/beta test I would gladly run and see how they respond if you need some testing help.

**Comment by tia79** [comment]
I cant even get them to work at all. I have watched tutorials but i always seem to destroy them since they dont work for me.

**Comment by MichaelHillcox** [comment]
Thank you for taking the time to create this issue, as we're no longer supporting versions below `1.12`, I'm going to go ahead and close it but if this bug seems to continue over to newer versions, please do report it again so we can investigate the issue further.
