### ISSUE TITLE
Energy Extractor not visible in 1.10-4.30beta47

### ISSUE THREAD

**Issue by xenoflot** [McJtyMods/RFTools#696]
Hi,

The Dimensions manual refers to an Energy Extractor however it does not present a recipe, nor is the item visible in JEI. Is this a something at my end or yours? :)

rftools-1.10-5.14
rftoolsdim-1.10-4.30beta47
forge 1.10.2-12.18.1.2064

**Comment by McJty** [comment]
It has not been ported yet to 1.10.2. It is on my todo
