### ISSUE TITLE
[Suggestion] Addition to the Powercells

### ISSUE THREAD

**Issue by Greg9711** [McJtyMods/RFTools#704]
My idea is that there could be a customizable multiblock that acts kinda like the Powercells that is just RF capacity for the Powercell RF storage, but you cant put in or pull out RF from the multiblock so that its just a RF storage for the Powercell (so you still have to get the Prismarine for Powercells to make use of the RF storage). I had this idea because i wanted a bigger RF storage within the Powercells RF storage without crafting a lot of them and just putting them on the ground doing nothing. For the recepie my suggestion is simular to the normal Powercell but without Prismarine because its kinda annoying to get :).

**Comment by MichaelHillcox** [comment]
See: EnderIo, Their multi-block is ideal for this use case. If you feel this is still a suggestion for us then please open the issue again :D
