### ISSUE TITLE
[1.10.2] [Bug?]  Is this a bug

### ISSUE THREAD

**Issue by Dijkstra1** [McJtyMods/RFTools#708]
Is this a bug or is intended, to me it seems like a bug, but do not fix just me I happy that it works.

[mcjty.zip](https://github.com/McJty/RFTools/files/438853/mcjty.zip)

**Comment by McJty** [comment]
I have noticed it too. Not decided if it is a bug or not :-)

**Comment by MichaelHillcox** [comment]
Feature? could you explain the bug a little bit more? I'll reopen the issue upon response.
