### ISSUE TITLE
Text editor with text wrapping for screens

### ISSUE THREAD

**Issue by Pandemoneus** [McJtyMods/RFTools#71]
I would like to suggest a text editor with text wrapping for screens. Right now we have text modules which only support one line and you have to try out how much letters fit in that one line. Instead I would like to recommend a text editor that automatically wraps lines and afterwards tells me how many text modules I will need to print said text on the screen.

**Comment by McJty** [comment]
I actually have plans to simply have multi-line support in a single text module.
Just didn't get around to working on this yet. Thanks for this ticket so that I do not forget :-)

**Comment by Pandemoneus** [comment]
No problem, I love your mod. :)

**Comment by mrdeadlocked** [comment]
On this same path would that include more scaling for the text? it would be nice to make it smaller.

**Comment by MichaelHillcox** [comment]
Unfortunately we're no longer supporting versions older than `1.12` and I don't have enough time to check this suggestion against all of the features of the mod but if this feature still hasn’t been implemented and you’d like to see it added to a newer version of the mod then please do create a new issue so we can review your suggestions again :+1:
