### ISSUE TITLE
[1.10.2] (5.21) Wire sometimes doesn't work when adjacent to redston on half slab

### ISSUE THREAD

**Issue by mgc11** [McJtyMods/RFTools#718]
It's unlikely to be noticed if you don't build redstone with slabs as I tend to do.  I'm not sure of exact circumstances but the image shows one pretty clear example.  

![rft-wire](https://cloud.githubusercontent.com/assets/21320948/18068845/6a1ce7f2-6e11-11e6-8735-b21514450223.png)

**Comment by MichaelHillcox** [comment]
Thank you for taking the time to create this issue, as we're no longer supporting versions below `1.12`, I'm going to go ahead and close it but if this bug seems to continue over to newer versions, please do report it again so we can investigate the issue further.
