### ISSUE TITLE
Powercell Suggestion 

### ISSUE THREAD

**Issue by koalalord9999** [McJtyMods/RFTools#719]
I understand the Powercell is supposed to be a multiblock, however, with that said... I would like it to also be like a Energy Cell, from Mekanism, Ender IO and Thermal Expansion. By that, I mean; It should act as a power source if placed in the 'power slot' of a machine that can be powered by a type of battery. 

Main example is the Mekanism Digital Miner. If I placed the Powercell into the energy slot, it would pull from the powercell network, with the card in it. Due to the nature of the multiblock, when placed in a battery slot, it would NOT add to the multiblock's power storage. If you have 14m RF in storage, and placed an Advanced Powercell into the battery slot, it would stay at 14m, not go up to 18m.

Just some quality of life update, if I would say so myself, so have a gander at it if you feel this would fit in with the flow of the mod :)
-Farewell

**Comment by MichaelHillcox** [comment]
Unfortunately we're no longer supporting versions older than `1.12` and I don't have enough time to check this suggestion against all of the features of the mod but if this feature still hasn’t been implemented and you’d like to see it added to a newer version of the mod then please do create a new issue so we can review your suggestions again :+1:
