### ISSUE TITLE
Bug in dialing device with opencomputers

### ISSUE THREAD

**Issue by dustpuppy** [McJtyMods/RFTools#724]
Sorry, pressed enter. Got empty comment :-)

**Comment by dustpuppy** [comment]
There is a bug in the dialing device regarding computer connection.
getTransmitterName and getReceiverName are not working.
Look at the picture.

Here's the code.
`local component = require("component")
local dialer = component.dialing_device
local ser = require("serialization")

for key,value in pairs(dialer) do
  if key == "getTransmitterName" then
    print (key,component.doc(dialer.address,key))
  end
end
print("----------------------------------------------------")
local transmitters = dialer.getTransmitters
local receivers = dialer.getReceivers

local tr = {}
for key,value in pairs(transmitters) do
  if key ~= "n" then
    print(ser.serialize(value))
    tr = value
  end
end
print("----------------------------------------------------")

print(dialer.getTransmitterName(tr))
`
![bildschirmfoto22](https://cloud.githubusercontent.com/assets/1313596/18230839/56b6d5e6-729f-11e6-8790-3cf12f0c82a6.png)

**Comment by MichaelHillcox** [comment]
As this is for 1.7.10, we won't be fixing it but if for any reason this is still a bug then please open a new issue with more up to date information 👍
