### ISSUE TITLE
[1.7.10] Owner dimlets can be found in huts

### ISSUE THREAD

**Issue by ohnx** [McJtyMods/RFTools#725]
On the wiki is mentions that owner dimlets (dimlets with id 638 and key `XOwner`) cannot be found in generated chests.

I've found multiple in the huts that generate in RFTools dimensions, I also think that my dimlet researcher managed to obtain one or two, as well.

The server that I'm playing on is running the FTB Infinity Evolved v2.6.0 modpack, which apparently has RFTools 4.23, and Thermos b57.

Has anyone else noticed this?

**Comment by MichaelHillcox** [comment]
Close as 1.7.10 is no longer supported. If this continues to be a bug on 1.12 or newer, please open a new issue.
