### ISSUE TITLE
cant protet certain blocks with the block protector.

### ISSUE THREAD

**Issue by leadheadfred** [McJtyMods/RFTools#726]
this could be a bug, this could be purposeful, or this could just be me being a moron. whatever the case, i cant protect my ender quarry,chunk loader or ender chest. is there a special way to protect things with inventorys?

**Comment by AxeFestis** [comment]
I am also facing this issue. I am unable to protect anything that opens when right clicked. For example a vanilla chest or an MineFactory Reloaded grinder. Shift-clicking does not help and just opens the inventory. I have read other tickets about this, maybe this is a conflict with another mod or configuration issue?

**Comment by InjuredWolf** [comment]
Hate to necro, but as far as I can tell, this is still a thing. Industrial Foregoing tileentities can't be protected (guessing due to right-click functionality) even when sneak-clicking it
