### ISSUE TITLE
[1.10.2] [Bug] Quarry is missing bits  

### ISSUE THREAD

**Issue by Dijkstra1** [McJtyMods/RFTools#728]
Was flying around my quarry noticed this, it has done few other times sine this picture was taken, this is a RFTools dim, and only the chunk with builder in is loader (by FTB Utilities), power and items out, and redstone single all in the same chunk as the quarry, and in the overworld item exaction and power gen in chunk loaded.  
![2016-09-07_16 14 53](https://cloud.githubusercontent.com/assets/11648771/18381836/b2f3df4e-766d-11e6-8fe2-23d9147f7da0.png)

**Comment by MichaelHillcox** [comment]
Could you confirm if this is still an issue in 1.12?
