### ISSUE TITLE
[Suggestion] Powercell charging via wireless charger from EnderIO

### ISSUE THREAD

**Issue by Morpheus1101** [McJtyMods/RFTools#734]
Would you consider adding support for the EnderIO Wireless charger to work in charging rftools powercells when in inventory?

**Comment by MichaelHillcox** [comment]
I'm pretty sure the wireless charger should just support the power cell but I can take a look.

**Comment by MichaelHillcox** [comment]
Unfortunately we're no longer supporting versions older than `1.12` and I don't have enough time to check this suggestion against all of the features of the mod but if this feature still hasn’t been implemented and you’d like to see it added to a newer version of the mod then please do create a new issue so we can review your suggestions again :+1:
