### ISSUE TITLE
[Feature] Read redstone signal strength instead of just on/off

### ISSUE THREAD

**Issue by DoomRater** [McJtyMods/RFTools#743]
I like running comparators out of chests to determine how full they are.  Only thing is, the redstone sensor only detects if there is a signal or not, not the actual signal strength as a number/bar.  This could be used to see how full a chest is, rather than just see what's in xth slot of a chest, or nearly anything else.  Could this be added?

**Comment by McJty** [comment]
What exactly do you mean by redstone sensor?

**Comment by DoomRater** [comment]
I really need to name the actual part I'm referring to exactly. I mean the Redstone Module currently only displays a message depending on whether it finds a signal or not, instead of having an option to show the redstone signal strength.

**Comment by MichaelHillcox** [comment]
Unfortunately we're no longer supporting versions older than `1.12` and I don't have enough time to check this suggestion against all of the features of the mod but if this feature still hasn’t been implemented and you’d like to see it added to a newer version of the mod then please do create a new issue so we can review your suggestions again :+1:
