### ISSUE TITLE
[Feature Request] More I18n Support

### ISSUE THREAD

**Issue by GWYOG** [McJtyMods/RFTools#744]
I know there has been some issues about this topic (like #89 and #411), but I think I should point it out  again since it's really important to let RFTools become more well-known. (Also because these text haven't been added I18n support in 1.10.2's RFTools)

Some days ago, there was a discussion about RFTools in a famous Chinese Minecraft forum (somewhere like reddit). Many Chinese players said that they really want to play with RFTools, however there are too much unlocalized text like the manual or many tooltips hardcoded like [this one](https://github.com/McJty/RFTools/blob/1.10/src/main/java/mcjty/rftools/blocks/teleporter/DialingDeviceBlock.java). 

If more I18n support are added, me and many other people would like to translate them. And then more players could play with RFTools and many other your mods. 

Though improving the tooltips may cost lots of time, the manual can be got localized a bit more easily. I18n support for the manual could be like [Tinker's Construct](https://github.com/SlimeKnights/TinkersConstruct/tree/master/resources/assets/tconstruct/book) or Reika's RotaryCraft, which provides a folder named like "en_US" or "zh_CN" for localized texts to place in. And this can be done through modifying the code about resource location [here](https://github.com/McJty/RFTools/blob/1.10/src/main/java/mcjty/rftools/items/manual/GuiRFToolsManual.java), I guess.

**Comment by MichaelHillcox** [comment]
From what I can tell this has been completed in #1083 if I'm wrong then please reopen the issue.
