### ISSUE TITLE
Matter Receiver does damage even when powered - v.1.10-5.22

### ISSUE THREAD

**Issue by Colonel-Rogue** [McJtyMods/RFTools#747]
Sometimes Instant Damage is still applied when transporting to any given Matter receiver whether powered/unpowered or chunk loaded/unloaded.

**Comment by McJty** [comment]
There is an enourmous lack of information here. Can you give me more details? Screenshots perhaps?

**Comment by Colonel-Rogue** [comment]
Wow, I just read my post again. Apologies. So over on the rr4 dev server we've been using rftools transporters. We recently updated to v.1.10-5.22. After we did, sometimes when transporting to a matter receiver it will apply the "Instant Damage" potion effect to whomever is transporting. Now, if memory serves, that's only supposed to happen when transporting to an unpowered or underpowered receiver. We tested with a matter booster (which had no effect), as well as a destination analyzer (which reported everything as ok), and while chunk loading the receiver. In these tests the receiver was always fully powered, as was the dialing device, and the matter transmitter. The matter transmitter was the only infused machine, infused at 100%. About 3/5 of the times I transported to the receiver in question I received the instant damage effect. If I did not have other items increasing my health and constantly healing me I would have died in almost every transport. There are no logged errors, no crashes, and except for the dying, no noticeable changes in immediate gameplay.  It is sometimes difficult to replicate because it does not happen on each and every transport, and at first glance does not appear to follow a pattern. Will try to capture event in screenshot or video later today when I have time. Is this information sufficient sans screenshots?

**Comment by McJty** [comment]
Where are these receivers located? In rftools dimensions? Overworld?

**Comment by Colonel-Rogue** [comment]
Both transmitter and receiver were in overworld.

**Comment by McJty** [comment]
Very weird. RFTools teleporters are widely used and I have never seen this reported before. If you have this again please check out the power in the receiver ASAP using WAILA or TOP

**Comment by Colonel-Rogue** [comment]
<iframe width="1280" height="720" src="https://www.youtube.com/embed/1Jrnn6fxwGg" frameborder="0" allowfullscreen></iframe>

**Comment by Colonel-Rogue** [comment]
This footage should suffice as proof
https://youtu.be/1Jrnn6fxwGg

**Comment by MichaelHillcox** [comment]
Thank you for taking the time to create this issue, as we're no longer supporting versions below `1.12`, I'm going to go ahead and close it but if this bug seems to continue over to newer versions, please do report it again so we can investigate the issue further.
