### ISSUE TITLE
Improvement to the Storage Scanner

### ISSUE THREAD

**Issue by TonRZN** [McJtyMods/RFTools#752]
I would love an search bar or/and a filter into the storage scanner, it get's difficulty if you have many inventories and bumping the range would also be nice

If you judge good/want to of course.

**Comment by TonRZN** [comment]
Also: Love your mods, keep the good work

**Comment by McJty** [comment]
A search bar filter is already there in the scanner. What do you mean exactly?

**Comment by TonRZN** [comment]
A search filter for the inventories, we have one for items right?

**Comment by McJty** [comment]
aha like that. Problem is that the gui is already so cluttered though. I have to think about it. Note that you can sort/change order of the inventories to make the grouping better

**Comment by TonRZN** [comment]
Cool, sorry for taking your time, and thanks for the patience

**Comment by Daenyth** [comment]
For me, #730 would be enough, instead of a search feature

**Comment by MichaelHillcox** [comment]
Unfortunately we're no longer supporting versions older than `1.12` and I don't have enough time to check this suggestion against all of the features of the mod but if this feature still hasn’t been implemented and you’d like to see it added to a newer version of the mod then please do create a new issue so we can review your suggestions again :+1:
