### ISSUE TITLE
[1.10.2] RFTools screen leave an unbreakable entity

### ISSUE THREAD

**Issue by phantomholo** [McJtyMods/RFTools#762]
I decided to play around with the screens in RFTools as they seemed cool, so I placed down one in my building and connected it to the screen controller. It was working fine until I exited my world and relaunched my game where it became an unbreakable entity. This could be a bug

**Comment by McJty** [comment]
How exactly did you reproduce this? What are the exact steps?

Also keep in mind that with a wrench you can make these screens invisible and indeed they are not breakable with tools. With sneak-wrench you can remove them. Did you try that?

**Comment by phantomholo** [comment]
First, I placed down the screen and inserted some rf modules in it. It was working fine until I relogged into my world where the screen appeared to be invisible with no text at all.

Yes, I have tried using the wrench by shift clicking but it doesn't seem to work

**Comment by McJty** [comment]
That's strange. I have never heard of this bug before and these screens are used a lot. What version of RFTools?

**Comment by phantomholo** [comment]
1.10-5.24

**Comment by McJty** [comment]
Weird. For now there is not much that I can do about this. I have never had a similar report of this. Perhaps some other mod you have is causing issues

**Comment by phantomholo** [comment]
How can I find out which mod is causing this?

**Comment by McJty** [comment]
Not easily I'm afraid. You could try by removing mods. But before you do that. Can you perhaps show some screenshots? Also was it a small or a big screen?

**Comment by phantomholo** [comment]
It was a small screen I believe, and the screenshot is here: http://imgur.com/a/YUPLG

**Comment by McJty** [comment]
With what wrench did you try to remove it? Did you try with the smart wrench from rftools?

**Comment by phantomholo** [comment]
I tried using the smart wrench and it didn't work

**Comment by McJty** [comment]
I give up... No clue how this can even happen

**Comment by phantomholo** [comment]
seems like that spot in the world will always be bugged then since I have no choice

**Comment by McJty** [comment]
Well you can get rid of it with McEdit I suppose

**Comment by phantomholo** [comment]
And how might I do that?

**Comment by McJty** [comment]
http://www.mcedit.net/

Haven't used it myself but this is how people get bad stuff out of worlds

**Comment by phantomholo** [comment]
Hmm I'm not that great at MCEdit either but I'll see what I can do, thanks for the help.

**Comment by levicc00123** [comment]
![2016-10-10_06 46 59](https://cloud.githubusercontent.com/assets/4361838/19236582/6368c538-8eb5-11e6-9361-ba126c34f246.png)


I'm having the same issue here. Using RFTools 1.10-5.51 and mcjtylib 1.10-2.1.4

**Comment by McJty** [comment]
Can you try to sneak-remove the screen (but make the wrench blue again, it is in the wrong mode)

**Comment by levicc00123** [comment]
I've tried removing the screens when the wrench was blue, no luck.

**Comment by McJty** [comment]
Can you describe exactly how the screen got there in the first place?

**Comment by MrNinja93** [comment]
Also had it happen just now, placed screen slightly wrong from where I wanted it (landed on an item conduit) had a lag spike mid place (Or connection lag as it was on a server) and it bugged out. Couldn't break it with pick or wrench or anything so I tried in creative, no luck there either, middle mouse clicked it to give myself that block and it gave me a block with unlocalized name rftools.screen_hitblock:0 

Is removable with /setblock x y z minecraft:air for anyone else with the issue wanting it gone and cheat access (In SSP you can open to LAN/enable cheats to do it) 

I'm on fairly ancient mod versions atm so:

Rftools-1.10-5.24
Mcjtylib-1.10-2.1.2

**Comment by McJty** [comment]
Ok that gives a bit more information. Still haven't been able to reproduce it though. I'll try a few more times with conduits and such

**Comment by MrNinja93** [comment]
Found a better non cheating removal method for people (provided you have ExUtils 2) mechanical miner mines and destroys it, so if you're on a server without admin access you can get rid of it. 

Haven't been able to trigger it since, I've left screens in a couple constant break/replace contraptions atm ones placing screens on conduit and one on a block to see if anything happens. Will leave it running and come back to it later today. 

Incase its relevant modlist of the private pack I'm running  (directory filename dump)
[Modlist.txt](https://github.com/McJty/RFTools/files/530786/Modlist.txt)

**Comment by Xiaminou** [comment]
This might be similar to a bug I have had a while ago which is that when you teleport a 2x2 or 3x3 screen with the builder it'll take the screen and leave behind the extended parts of it.

**Comment by AutismsDad** [comment]
I had the same issue in same version and only got rid of the buggy screen with the /setblock command from the server console.

**Comment by Desert229** [comment]
I have no clue how the /setcommand works and i cant find the ID of the bugged screen block. Would you be so kind and copy your command line so i can paste it? I have 4 bugged out screenblocks =/

**Comment by Desert229** [comment]
Same issue here /setblock works fine! For those who dont know how it works just type in "/setblock X Y Z air" where X Y and Z are the coordinates of the bugged out screen block

**Comment by AutismsDad** [comment]
So I can reproduce the issues by right clicking with the enderIO Yeta Wrench on the screen. Also Shift clicking with the Yeta sends it into its bug state.

**Comment by anguslmm** [comment]
Having this bug as well. It also happened for me when using the Yeta wrench, exactly as @Desert229 described. It isn't breakable by any of the in game means I've tried, including the smart wrench, but I haven't tried as @MrNinja93 suggested.

I also deleted the blocks in MCEdit, saved, reloaded in MCEdit to confirm the blocks were deleted, then when it loaded on the server, the blocks came back. I haven't done much minecraft modding, but I'd guess whatever entity is responsible for generating the screen hitblocks is probably getting bugged by the Yeta wrench to generate hitblocks where it isn't supposed to. Even if I take all screens in the area down, those hitblocks are there. I'll try removing the screen controller too.

Will use the setblock command if all else fails and report back.

**Comment by MichaelHillcox** [comment]
Thank you for taking the time to create this issue, as we're no longer supporting versions below `1.12`, I'm going to go ahead and close it but if this bug seems to continue over to newer versions, please do report it again so we can investigate the issue further.
