### ISSUE TITLE
Dragon Syringe Unknown?

### ISSUE THREAD

**Issue by RehabOholic** [McJtyMods/RFTools#766]
Playing "All The Mods Pack" the latest version and when you collect Dragons blood it show it as unknown. When making a Dimension with it it has Dragons in it, but they are 2 dragons stuck together and not doing anything. You can't hit them or anything. I new to RFtools Dimensions So I am sorry if I missed something in my search. Thanks for any help.

**Comment by McJty** [comment]
Yes, there is another report on this. I'll investigate later

**Comment by RehabOholic** [comment]
Ok, sorry. I will remove this one, Thanks again

**Comment by RehabOholic** [comment]
Thanks, I was trying to find a post on it to follow, but couldn't I was going to delete this one but also do not see away to remove it.

**Comment by Darkosto** [comment]
Ahhh, looks like the mod needs a rarity of 6 but the Workbench says it needs 5. It builds correctly when you use Rarity: 6

**Comment by RehabOholic** [comment]
Rarity 6 was used and it still has the same issue. I don't pretend to know why, only that the Dragon just says unknown, and doesn't seem to drop an egg after its been respawn, and when you take its blood it also says unknown mob. It spawns the Dragons in the world, but they are stuck in groups of 2-3 and can not be hit. Thanks thou for the advice.

**Comment by McJty** [comment]
I've had no time to look into this but I'll try to have a look later

**Comment by Darkosto** [comment]
@RehabOholic Works just fine for me with Rarity: 6  Control Circuit: https://sx.artdude.uk/hotlink-ok/darkosto/7y1b-684cc-1476726750.png

This is with default configs, minus only generating void dimensions.

**Comment by charlesimard** [comment]
I have the same issue playing on Direwolf's 20 1.10.2, dragons are unknown creatures...

**Comment by MichaelHillcox** [comment]
Thank you for taking the time to create this issue, as we're no longer supporting versions below `1.12`, I'm going to go ahead and close it but if this bug seems to continue over to newer versions, please do report it again so we can investigate the issue further.
