### ISSUE TITLE
Shift righclicking shields with shape cards

### ISSUE THREAD

**Issue by Darkere** [McJtyMods/RFTools#767]
You can use shape cards inside shield projectors and they work very well. However setting up the shape card is a pain as you can only either do it manually by typing the numbers in. 
Or like I do it by placing a builder, use that to setup the card, and then replace it with the shield.

Being able to right click the shield with a shape card would make this much easier.

**Comment by MichaelHillcox** [comment]
Unfortunately we're no longer supporting versions older than `1.12` and I don't have enough time to check this suggestion against all of the features of the mod but if this feature still hasn’t been implemented and you’d like to see it added to a newer version of the mod then please do create a new issue so we can review your suggestions again :+1:
