### ISSUE TITLE
[Suggestion] Sequencer needs a way to limit the number of slots that are read.

### ISSUE THREAD

**Issue by Kyrinon** [McJtyMods/RFTools#769]
I would suggest that shift clicking a slot would place an X in it or it and all the slots after it, then when the logic reaches it, it wold immediately return to the first slot. 

Ex: I was trying to use step mode for some in world crafting with a BUD. Place liquid, dispense item, pump up result. I could not just repeat the pattern because I only had three states and 64 is not divisible by three. Making it only read the first three would have been very useful.

**Comment by MichaelHillcox** [comment]
Unfortunately we're no longer supporting versions older than `1.12` and I don't have enough time to check this suggestion against all of the features of the mod but if this feature still hasn’t been implemented and you’d like to see it added to a newer version of the mod then please do create a new issue so we can review your suggestions again :+1:
