### ISSUE TITLE
[1.10.2][5.51] Fluid module is not detecting fluid inside extra utilities drums

### ISSUE THREAD

**Issue by Kazzamkablam** [McJtyMods/RFTools#773]
Fluid module is not detecting fluid inside extra utilities drums and gives 'invalid' instead.

Yeah that happens...

Versions:
rftools-1.10-5.51
mcjtylib-1.10-2.1.4
forge 2095
extrautils-1.10.2-alpha-1.1.0a

**Comment by MichaelHillcox** [comment]
Unfortunately we're no longer supporting versions older than `1.12` and I don't have enough time to check this suggestion against all of the features of the mod but if this feature still hasn’t been implemented and you’d like to see it added to a newer version of the mod then please do create a new issue so we can review your suggestions again :+1:
