### ISSUE TITLE
Crash after trying to use elevator

### ISSUE THREAD

**Issue by iluvdemomanandjunkrat** [McJtyMods/RFTools#775]
[crash-2016-10-10_11.32.13-client.txt](https://github.com/McJty/RFTools/files/518796/crash-2016-10-10_11.32.13-client.txt)

**Comment by McJty** [comment]
What kind of block are you trying to move with the elevator?

**Comment by McJty** [comment]
Hi? Can you please tell me what block the elevator was trying to move? i.e. what blocks were in the platform?

**Comment by iluvdemomanandjunkrat** [comment]
Sorry, It was blocks from chisel

**Comment by McJty** [comment]
In that case it might be a bug in Chisel. Can you report to them so they can look at this?

**Comment by MichaelHillcox** [comment]
Thank you for taking the time to create this issue, as we're no longer supporting versions below `1.12`, I'm going to go ahead and close it but if this bug seems to continue over to newer versions, please do report it again so we can investigate the issue further.
