### ISSUE TITLE
Suggestion: Prevent recievers from being stolen from dimensions.

### ISSUE THREAD

**Issue by sherkas** [McJtyMods/RFTools#778]
I feel cheaty about it, but if im rolling dimensions (say a void or something else) I know that I can go in, check it... take the receiver and leave. 

After sometime you never need to build another reciever and early game this is a huge boon. I would like to see the receivers tied to the world and either unbreakable, or when broken they delete.

Would even love a config setting to prevent this. CanStealRecievers=True  (by default would keep current way intact).

That way I could turn it off and play it probably how it was intended.

Also, I think rftools is sick. Im always finding more items in this mod and its definitely become a major part of my minecraft experience.

**Comment by McJty** [comment]
Not being able to remove receivers has some disadvantages. That way you cannot get rid of them in the dialer too and many people want to get rid of destinations that they are never going to use again

**Comment by sherkas** [comment]
If they never wish to visit that spot again, I would say then it should by default break the reciever with no item given back. That way in my situation, I dont get anything however in there situation that location can never be accessed again.

I know making your own receiver you wouldnt want this effect but I believe you add a owner tag and that should fix it. No owner breaking receivers = gone (new worlds and such) but if its owned then return it.

Would that be a solution?

**Comment by MichaelHillcox** [comment]
Unfortunately we're no longer supporting versions older than `1.12` and I don't have enough time to check this suggestion against all of the features of the mod but if this feature still hasn’t been implemented and you’d like to see it added to a newer version of the mod then please do create a new issue so we can review your suggestions again :+1:
