### ISSUE TITLE
Builder copies blocks without NBT

### ISSUE THREAD

**Issue by 666lumberjack** [McJtyMods/RFTools#780]
When using the Builder to copy a structure including blocks that have NBT (such as Forestry Wood Piles, which use NBT to differentiate between species) it places them without any NBT data. 

Using RFTools 1.10-5.53.

**Comment by MichaelHillcox** [comment]
Thank you for taking the time to create this issue, as we're no longer supporting versions below `1.12`, I'm going to go ahead and close it but if this bug seems to continue over to newer versions, please do report it again so we can investigate the issue further.
