### ISSUE TITLE
[1.10.2][5.51] Modular Storage content display glitch

### ISSUE THREAD

**Issue by Aedda** [McJtyMods/RFTools#781]
I initially thought this was just a block display glitch but in testing it for this issue it appears to be slightly more glitchy.

If you make a Modular Storage and put a Storage Module in it, the bar graph on the front will display as empty. The tooltip for the module will read 0/x00 stacks.

Place 1 item into the inventory, the bar graph now may still read as empty until the GUI is closed and opened and then closed again. The tooltip will read 1/x00 stacks, the GUI will show [Z] 1/x00.

Open the GUI, remove the module, replace the same module. The tooltip will now say 2/x00 stacks however the GUI will read correctly as [Z] 1/x00. Removing the module from the machine resets the tooltip to 1/x00 stacks. The jump in stack count increases as the used storage also increases e.g. 42->55.

Removing and replacing the module will cause the bar graph on the front to randomly display between empty and 1/8 full even if the module is empty. Removing the module always makes the graph reset to appear as empty.

**Comment by MichaelHillcox** [comment]
Thank you for taking the time to create this issue, as we're no longer supporting versions below `1.12`, I'm going to go ahead and close it but if this bug seems to continue over to newer versions, please do report it again so we can investigate the issue further.
