### ISSUE TITLE
Shield protector not doing damage to enderman

### ISSUE THREAD

**Issue by JorisvanRoy** [McJtyMods/RFTools#782]
Hi,

I am playing Skyexchange on mc 1.10.2 and i tried to setup a shield to damage enderman to kill them but when i had my config like this [https://gyazo.com/579ae7cf49c5565157e81eb7b618d86c](url) . it didnt damage the enderman, but when i had it the same with pigman they do get damaged. i hope this helped u maybe find a bug.

**Comment by McJty** [comment]
That's weird. Certainly working for me. Can you show me a screenshot of the shield and enderman in it?

**Comment by MichaelHillcox** [comment]
Thank you for taking the time to create this issue, as we're no longer supporting versions below `1.12`, I'm going to go ahead and close it but if this bug seems to continue over to newer versions, please do report it again so we can investigate the issue further.
