### ISSUE TITLE
Dimlet with key *** is missing

### ISSUE THREAD

**Issue by b4ka** [McJtyMods/RFTools#789]
i deletled a mod in my modpack, but the dimlets related to this mod are still here

**Comment by McJty** [comment]
You means the ones you already have in chests and inventories? In that case that's hard to avoid. There is no way to automatically delete these

**Comment by MichaelHillcox** [comment]
Thank you for taking the time to create this issue, as we're no longer supporting versions below `1.12`, I'm going to go ahead and close it but if this bug seems to continue over to newer versions, please do report it again so we can investigate the issue further.
