### ISSUE TITLE
Builder: Quarry: Limit to offsets?

### ISSUE THREAD

**Issue by Cruddly** [McJtyMods/RFTools#790]
I am assuming there is a limit to the offset distances, as I was attempting to leave my builder in my factory and just fly out with the set quarry card to mark off regions, but after a certain distance it wouldnt quarry in the selected spot. If so, could this please be documented? Thanks. Great job on the mod BTW.

**Comment by sherkas** [comment]
512x512x512 Its on the card itself in the tooltips.

**Comment by SummaryPick** [comment]
Sheraks that's not what he is talking about, 512x256x512 is the max dimension, not the offset like he is referring to.  I have had problems with this as well, I've found if I offset too far away from the builder is just bugs out and will instead mine just a few blocks away from the builder.

**Comment by danielevans** [comment]
I'm having this issue fairly consistently, I set the offset to almost any set of values and then use the support feature to show me where it will mine. It is consistently within a few blocks.

<img width="1680" alt="screen shot 2018-11-27 at 15 53 00" src="https://user-images.githubusercontent.com/419699/49117294-6bd80680-f25d-11e8-891c-bfecd30b0f5f.png">
<img width="1680" alt="screen shot 2018-11-27 at 15 53 03" src="https://user-images.githubusercontent.com/419699/49117295-6c709d00-f25d-11e8-8f16-9f9abbbedca8.png">
<img width="1680" alt="screen shot 2018-11-27 at 15 53 43" src="https://user-images.githubusercontent.com/419699/49117297-6c709d00-f25d-11e8-80a4-3cd8b40bf8bf.png">
<img width="1680" alt="screen shot 2018-11-27 at 15 53 47" src="https://user-images.githubusercontent.com/419699/49117300-6d093380-f25d-11e8-97fe-7d8a1ffc31d2.png">

**Comment by danielevans** [comment]
I've just reproduced using the following steps:

Installed the following versions (using MCUpdater), as reported by the in-game mod list:
* Minecraft 1.12.2
* Minecraft Coder Pack 9.42
* Forge Mod Loader 8.0.99.99
* Minecraft Forge 14.23.5.2772
* Redstone Flux 2.1.0.6
* Interaction Wheel 1.12-1.2.7
* McJtyLib 1.12-3.0.7
* RFTools 1.12-7.59

Started a creative, single player map. 
Cheated in a Shape Card (Quarry) and Builder.
Set the quarry card dimesions to 512,256,512
Set the quarry card offset to 1024,0,1024
Inserted quarry card and enabled Support/Preview mode

Expected: With an offset of 1024x1024 and a size of 512x512 the nearest corner should be 768x768 away.

Actual: the visible corner is 4x4 blocks away

Logfile is at https://gist.githubusercontent.com/danielevans/d9b0084967e561a1640e8a9bc1e01cd7/raw/b32d6293a21f036e54cdac4add55915dae4b312c/minecraft-log.txt

<img width="1680" alt="screen shot 2018-11-27 at 16 29 18" src="https://user-images.githubusercontent.com/419699/49118591-223dea80-f262-11e8-82ad-abf6b00d503a.png">
<img width="1680" alt="screen shot 2018-11-27 at 16 29 20" src="https://user-images.githubusercontent.com/419699/49118592-22d68100-f262-11e8-8dd9-fa0e5d56539e.png">

**Comment by josephcsible** [comment]
There's a `maxBuilderOffset` in the config, which defaults to 260. Setting it to higher values, such as 1024, causes it to act as if you only set it to 260. The edge of 512-block wide region that's centered 260 blocks away will indeed be 4 blocks away, so the behavior you're seeing seems to be as intended. Does this seem correct to you?

**Comment by danielevans** [comment]
That was definitely my issue, I missed that config

**Comment by bastetfurry** [comment]
Necroing this as i think it would still fit here, i haven't checked the newest version yet if that is in there but it might be a good idea warning the player that their offset is too high and that there is a limit in the configuration and that they should pester their admin about it. :)

**Comment by Gaibhne** [comment]
Still an issue with distances over at least 1024 (but I tried with 1023 and it still happened)

**Comment by DaAitch** [comment]
I had the same issue with a max distance of 260 and this is how I fixed it.

1. I changed `config/rftools/rftools.cfg`: `I:maxBuilderOffset=100000`
2. after a restart I put the same ShapeCard into the Builder, but I didn't see the visual bounding box change position so I though it did not work
3. so I found `/saves/<yourlevel>/serverconfig/rftoolsbuilder-server.toml` and changed `maxBuilderOffset = 1000000`, but again the bbox didn't move
4. I switched off the bbox, but it didn't disappear so I thought it's just a visual bug
5. then I simple tried it out an it works: offset can now be higher

So I actually don't know what fixed it, but one of those files did it :smile: have fun.

**Comment by JonasDoe** [comment]
> There's a `maxBuilderOffset` in the config, which defaults to 260. Setting it to higher values, such as 1024, causes it to act as if you only set it to 260. The edge of 512-block wide region that's centered 260 blocks away will indeed be 4 blocks away, so the behavior you're seeing seems to be as intended. Does this seem correct to you?

Would be great if the shape card configuration menu would would cap the values I can enter to the maxium one (similar to `maxBuilderDimenions` which cannot be exceeded in the menu). Otherwise the behavior is really unpredictable, meaning the builder block might quarry a part of my base or another structure I want to keep.
