### ISSUE TITLE
Smart wrench crash client

### ISSUE THREAD

**Issue by WetIce** [McJtyMods/RFTools#798]
By using smart wrench rf tools to configure the side of the power cell , the client crash immediately. see enclosed crash report.
[crash-2016-10-22_15.16.24-client.txt](https://github.com/McJty/RFTools/files/545805/crash-2016-10-22_15.16.24-client.txt)
 Thank you for help

**Comment by McJty** [comment]
What version of my mods? McJtyLib, RFTools, ...

**Comment by WetIce** [comment]
Hello 
Thank you for the reply.
I was testing with 2 versions and got the same results
- Rf tool V 1.10-5.53 with mcjylib 1.10-2.1.4
- Rf tool V 1.10-5.55 with mcjylib 1.10-2.2.0

Cheers

**Comment by McJty** [comment]
It looks as if you have a mod in your modpack that has a wrong wrench class. Problem is finding out which one...

**Comment by WetIce** [comment]
Thank you for confirming something that I suspected . easy there are only 5 mods with a wrench. i will remove them and add them one by one
 Is it the class or the item ID?

Thank you

**Comment by MichaelHillcox** [comment]
Thank you for taking the time to create this issue, as we're no longer supporting versions below `1.12`, I'm going to go ahead and close it but if this bug seems to continue over to newer versions, please do report it again so we can investigate the issue further.
