### ISSUE TITLE
Mob dimlet | Dragon | not working

### ISSUE THREAD

**Issue by RealLith** [McJtyMods/RFTools#808]
Hello,

Today i made a new world with 6 diffirent dimlets. This Had to make a flat obsidian world with no effects always noon and mob dimelt of dragons. 

It worked i got the world. But there is a problem with the mobs. Or in this case, Dragons.
It seems its impossible to hit them. They dont move, u cant hit them, u cant interract with it. nothing can even kit or move them. They are stuck in 1 place. 

Before any1 ask, yes the power isint a problem. its full lal the time. 
Yes i can kill other mobs in the same dimmension and all other mobs move.

I tryed:
- Relogging
- Remaking the world
- Making new world with dragon dimlet (tryed 3 diffirent worlds)
- reloading the world.

I see the animation of dragons trying to fly. I get knockback when im next to the dragon so its not a visual thing.

Mobpack played in: All The mods
Modpack on: Curse
mod versions:
- Rftools 1.10-5.57.jar
- Rftools control 1.10-1.50.jar
- rftools dimensions 1.10-4.43.jar
  Minecraft version: 1.10

**Comment by McJty** [comment]
Yes this has been reported before but I don't currently know how to fix this yet. It is on my todo

**Comment by kayila** [comment]
Similarly, a dragon spawned in with an RF tools spawner has the same issue.

**Comment by kayila** [comment]
I think I have a lead on why the dragons derp out. It seems that there some entity data which MUST be set in order for the dragon to function properly. Looking at the spawner code from RFTools, I'm thinking that flag isn't being set. According to the page I found, if that data is unset, the dragon is spawned `hovering with no AI` which describes what's going on when I tried to spawn her in.

The data tag is `DragonPhase` Looks like initializing it to zero should make it fine.

http://minecraft.gamepedia.com/Ender_Dragon#Data_values

**Comment by KFGL** [comment]
I think you should post this in the github repository for RFToolsDimensions as well, as that is the mod that adds dimlets and all the dimension stuff.

**Comment by KFGL** [comment]
Never mind, I just saw it.

**Comment by MichaelHillcox** [comment]
Thank you for taking the time to create this issue, as we're no longer supporting versions below `1.12`, I'm going to go ahead and close it but if this bug seems to continue over to newer versions, please do report it again so we can investigate the issue further.
