### ISSUE TITLE
Suggestion: Storage Scanner

### ISSUE THREAD

**Issue by Teduce** [McJtyMods/RFTools#819]
Now that the scanner lists the total number of  a specific item you have. It would be nice to have  some sort options when you are viewing all routable inventories.  LIke by Number of Items, or by mod,  etc

**Comment by craft-lover** [comment]
Seconded. I have been waiting for sorting options since the storage scanner was first introduced.

**Comment by MichaelHillcox** [comment]
Closed in preference of #722
