### ISSUE TITLE
Shield Projector doesn't works?

### ISSUE THREAD

**Issue by Alninjes** [McJtyMods/RFTools#830]
![1](https://cloud.githubusercontent.com/assets/23341277/20106859/d48f3d68-a5d6-11e6-8b04-ccbe5bd80cfd.jpg)

How can I do this?

**Comment by McJty** [comment]
You can't at the moment. I need to reimplement that. But the shield works with the other visibility modes though

**Comment by Alninjes** [comment]
Okay, thank you, The Shield Projector is really nice...the mod too!
I really love it <3

**Comment by jolli86** [comment]
Do you know when this might be re-implemented? I would really really love to use this when it is ready? Thanks for a great mod by the way :)

**Comment by MichaelHillcox** [comment]
Thank you for taking the time to create this issue, as we're no longer supporting versions below `1.12`, I'm going to go ahead and close it but if this bug seems to continue over to newer versions, please do report it again so we can investigate the issue further.
