### ISSUE TITLE
[1.10-5.59] Builder with fortune quarry card jams up upon hitting XU2 ender lilly

### ISSUE THREAD

**Issue by RealGrep** [McJtyMods/RFTools#835]
As I said in your Discord channel just now, my builder was jammed while I was just starting to quarry The End. I've found out that it will stop forever until I clear the ender lilly (from XU2) in that chunk, or at least the ender lilly it is currently stuck on. It then goes on, and gets stuck on the next ender lilly.

I'm using a fortune quarry card, set to 128x66x128, and voiding anything it has in the quarry card settings. Also with a filter set to block most cruft like andesite, granite, etc, as well as end stone. I tried with a normal non-fortune quarry card, and the same occurs.

This is with RFTools 1.10-5.59, McJtyLib 1.10-2.2.0, MC 1.10.2, and Forge 2122.

I see nothing at all of use in the log files, but obviously available if you think it would be helpful in this case. I usually post it, but pretty sure it won't help here. Should be easily reproducible, as well. One would hope.

**Comment by MichaelHillcox** [comment]
Thank you for taking the time to create this issue, as we're no longer supporting versions below `1.12`, I'm going to go ahead and close it but if this bug seems to continue over to newer versions, please do report it again so we can investigate the issue further.
