### ISSUE TITLE
Elevator that uses connected textured blocks as the platform messes up the textures

### ISSUE THREAD

**Issue by SpeedySpy52** [McJtyMods/RFTools#836]
When not in use, the platform looks fine.
![2016-11-10_15 17 44](https://cloud.githubusercontent.com/assets/18106048/20192668/df036e6c-a758-11e6-9df2-b1534f208524.png)
When in motion, the connected textures of the platform don't work for half of the blocks in an odd checkerboard pattern.
![2016-11-10_15 17 48](https://cloud.githubusercontent.com/assets/18106048/20192669/e02298b8-a758-11e6-87d5-daa94f5f914e.png)
This can be better seen in these photos:
![2016-11-10_15 19 41](https://cloud.githubusercontent.com/assets/18106048/20192735/2c034f84-a759-11e6-9269-1f6b51a44463.png)
![2016-11-10_15 19 50](https://cloud.githubusercontent.com/assets/18106048/20192739/2d1a6a9c-a759-11e6-83b8-854288ee7da0.png)

**Comment by McJty** [comment]
Yes, I know. Not sure if there is much that I can do about this however. I can try
