### ISSUE TITLE
Feature Request: chisel & bits mode for builder.

### ISSUE THREAD

**Issue by tod** [McJtyMods/RFTools#846]
I have no idea how hard this would be, but it would be awesome if you could put the builder in chisel & bits mode and have it use bits to make circles, ellipses, etc even more detailed. I'd even be fine with this mode being limited to 1/16th of the the normal range (basically convert the dimensions to bits instead of blocks).

**Comment by MichaelHillcox** [comment]
As we're only bug fixing 1.12 and C&B has been discontinued, I can't see this being added. Sorry.
