### ISSUE TITLE
Screen RF+ energy module only displays value from single Ender IO capacitor bank instead of whole multiblock

### ISSUE THREAD

**Issue by SubsterNL** [McJtyMods/RFTools#848]
It worked in the 1.7.10 release. It doesn't now. Only displays the energy readout from 1 bank instead of the whole multiblock combined. Which basically makes it useless.

rftools-1.10-5.60.jar
mcjtylib-1.10-2.2.0.jar

Latest Forge

**Comment by SubsterNL** [comment]
Was just wondering if you were ever going to fix any of the issues. This report is pretty old. Some nice mods, unfortunately also quiet a few bugs.

Btw.. report is obviously about EnderIO. Also using the latest beta of that but that hasn't changed anything.

**Comment by McJty** [comment]
I have a lot of work so eventually I get around to them. Currently hard at work with the 1.11 port so everything else has to wait for that

**Comment by SubsterNL** [comment]
Ok m8.. No worries. Appreciate all the hard work you are putting in your mods! :)

**Comment by MichaelHillcox** [comment]
Close as 1.7.10 is no longer supported. If this continues to be a bug on 1.12 or newer, please open a new issue.
