### ISSUE TITLE
Void world Problem

### ISSUE THREAD

**Issue by Medusalem** [McJtyMods/RFTools#855]
If i create a Void world on our server, the Server Kick's everyone and stops responding, Not like not Responding in a crash , it is just not taking any operations, it is seeing people trieng to join, but is not refusing it, they just can't join, i can't stop the server via console, or anything else, it just running and not doind anything...  i do not get a crash log, i can not reproduce it in Singelplayer.

We are running forge version 12,18,2,2125

And our Modpack Dionysos in version 1.20 
https://minecraft.curseforge.com/projects/dionysos

**Comment by McJty** [comment]
What version of RFTools?

**Comment by Medusalem** [comment]
Oh sorry,

Rf tools 1,10-5,60
sctrl 1,10-1,5,2
Dim 1,10 - 4,45

**Comment by McJty** [comment]
How was your dimension made? What dimlets?

**Comment by Medusalem** [comment]
Void, no structures, blackfog, no rain no thunder, 
And other combination i can't remember, we tested diferent combinations.

Other Dimensions, or random generated with numbers are working

**Comment by McJty** [comment]
Can you take the dimension tab in your hand and sneak right click in. Then give me what it shows

**Comment by Medusalem** [comment]
Base seed: 5113770693509903342
Terrain: Terrain_Void
Baseblock Stone
basefluid: null
Biome Controller: Controller_magical
Feature: Feature_none
Sun Brightness: 1.0
Sky Color 1.0 1.0 1.0
Fog color 0.0 0.0 0.0
Weather rain 0.0
celestian angle 0.0

**Comment by McJty** [comment]
Strange... I don't have an immediate explanation for this. Can you give me the full server log in any case? Maybe I can see something suspicious

**Comment by Medusalem** [comment]
Gimme a minute

**Comment by Medusalem** [comment]
Here is the Last hour, up to the point where i joint the Void world:

http://pastebin.com/MLPpbedS

**Comment by Medusalem** [comment]
Anything to find a solution for the Problem i could hand over search for etc?

**Comment by McJty** [comment]
Sorry no. It is always hard to diagnose such problems. I can't think of anything that would cause this I'm afraid

**Comment by Medusalem** [comment]
Okey, nevertheless, thanks for your time, if i find something causing it or something else, should i commend here?

**Comment by McJty** [comment]
yes sure. I'll keep this open as well as it is not resolved

**Comment by MichaelHillcox** [comment]
Thank you for taking the time to create this issue, as we're no longer supporting versions below `1.12`, I'm going to go ahead and close it but if this bug seems to continue over to newer versions, please do report it again so we can investigate the issue further.
