### ISSUE TITLE
Quark Compatibility

### ISSUE THREAD

**Issue by DeGariless** [McJtyMods/RFTools#859]
Minecraft 1.10.2 
rftools-1.10-5.60

Many or your recipes call for an oak chest. Can you please add compatibility for quark so we can use quark chests as well? I'd add this myself with MineTweaker but I don't think that will work nicely for things like the storage modules.

**Comment by DeGariless** [comment]
https://github.com/McJty/RFTools/issues/859

**Comment by xelrix** [comment]
Maybe suggest quarks author to oredict the other chests as oakchest?

**Comment by DeGariless** [comment]
Anyone can make an ore dictionary entry with minetweaker, but in some cases, it's up to the mod author to actually implement them. I get what you're saying, but some of the recipes in my modpack require the separation of different kinds of wood chests. Really hoping to see this happen so I can get rid of my partially working band-aid fix.

**Comment by MichaelHillcox** [comment]
I'd hope this has already been fixed. If not please create a new issue :+1:
