### ISSUE TITLE
Powercell's not linking

### ISSUE THREAD

**Issue by sherkas** [McJtyMods/RFTools#863]
I crafted 2 basic powercells. Crafted 2 link cards.

Placed the cards in the top slot of the one cell (it of course didnt update the link id for the cards). After closing/reopening the gui it did. 
As soon as I placed the link cards in the link slot in any of the cells it wipes them back to blank.

(latest)
rftools 5.62
rftools dim 445

**Comment by McJty** [comment]
What do you mean by 'link slot'? What you have to do is to have a valid card in the top-left slot and *then* while that card is still there another card in the bottom-right slot. Only then will they be linked

**Comment by sherkas** [comment]
That does work. I apologize, I used them before but in this new world I tried and must have forgot how they worked.

**Comment by McJty** [comment]
I need to make the UI a bit more intuitive as many people stumble on this. Suggestions are welcome

**Comment by sherkas** [comment]
Maybe its too simple but use the wrench in the same fashion endergenics work.


If you wrench a powercell, hitting another will link them. Hitting the same cell twice will unlink it.

Have it so when you wrench it once, all similar link ones glow (so you can see whose linked).
