### ISSUE TITLE
"crashing elevator" make chunk unuseable and then crashes game or server.

### ISSUE THREAD

**Issue by mrhades1984** [McJtyMods/RFTools#866]
[crash-2016-11-23_20.25.55-server.txt](https://github.com/McJty/RFTools/files/609943/crash-2016-11-23_20.25.55-server.txt)

**Comment by everseeking** [comment]
Your modpack just released an update that includes the newer RFTools version than the one you currently have in the crash report - [go update](https://minecraft.curseforge.com/projects/hades-effect/files) and see if that fixes your issue.

**Comment by Watchful1** [comment]
I was having this problem and updating rftools to 5.62 fixed it.

**Comment by MichaelHillcox** [comment]
Thank you for taking the time to create this issue, as we're no longer supporting versions below `1.12`, I'm going to go ahead and close it but if this bug seems to continue over to newer versions, please do report it again so we can investigate the issue further.
