### ISSUE TITLE
[lowprio] Elevator screen module logs each click to the console

### ISSUE THREAD

**Issue by SharkWipf** [McJtyMods/RFTools#870]
The RFTools Elevator Screen Modules log every click on each button to the console. 
While I assume this was useful for debugging before, it's been working quite stable for me for months so I doubt it's needed anymore.  
Not an important issue or anything, just a minor annoyance now that players on my server have found out they can use it to annoy me...

**Comment by MichaelHillcox** [comment]
Thank you for taking the time to create this issue, as we're no longer supporting versions below `1.12`, I'm going to go ahead and close it but if this bug seems to continue over to newer versions, please do report it again so we can investigate the issue further.
