### ISSUE TITLE
Shield doesn't fill the shape card shape when terrain changes

### ISSUE THREAD

**Issue by Alriac** [McJtyMods/RFTools#871]
If you place a shield generator with a shape card, shield will be only generated on non-solid blocks like air, water, etc. And it won't fill the air blocks when the terrain is changed, you need to turn it off/on to fill those new air blocks.

That means that if you plan to protect your house with a shield, anyone can excavate under the shield to get inside.

It should extend the shield to the new air blocks like the MFFS mod does.

**Comment by McJty** [comment]
I'm afraid that that would be pretty hard to do efficiently and would also break builds that actually depend on the shield not forming where there are blocks. That's a good way to make holes (doorways) in a shield for example
