### ISSUE TITLE
Sensor not correctly detecting entities in a stack

### ISSUE THREAD

**Issue by eslachance** [McJtyMods/RFTools#876]
I'm attempting to trigger an action whenever a *stack* of items is detected, dropped on the floor. Unfortunately, while the sensor easily detects a single entity item in front of it, as soon as the items merge into a stack, the detection stops working correctly. 

![2016-11-26_13 19 40](https://cloud.githubusercontent.com/assets/643344/20642390/bbe9a722-b3db-11e6-9e43-d11e75c12205.png)

I also tried this with Cobblestone.

Note that I'm on the Direwolf20 pack (1.10.2).

**Comment by McJty** [comment]
Not sure how or if I should solve that because technically a stack of cobble is a single entity. Have to think about that

**Comment by tansheron** [comment]
Users shouldn't need to know how Minecraft is implemented internally to understand the behavior of their tools. As an ordinary user, I would expect it to work the same way that the OP expected it to. As for how the problem can be solved, this seems to work for me (in SensorTileEntity.java):

```
private boolean checkEntities(BlockPos pos1, EnumFacing dir, Class<? extends Entity> clazz) {
        List<Entity> entities = worldObj.getEntitiesWithinAABB(clazz, getCachedBox(pos1, dir));
        int entityCount = entities.size();
        for (Entity entity : entities) {
            if (entity instanceof EntityItem) {
                int stackSize = getEntityItemStackSize((EntityItem)entity);
                // 1 entity is already included in the result of entities.size().
                entityCount += (stackSize - 1);
            }
        }
        return entityCount >= number;
    }
    
    private int getEntityItemStackSize(EntityItem entityItem) {
        ItemStack stack = entityItem.getEntityItem();
        if (stack == null) {
            return 0;
        }

        return stack.stackSize;
    }
```

**Comment by tansheron** [comment]
@McJty, would you prefer to have a separate Items mode? That should meet everyone's needs without affecting backward-compatibility; people who want the new behavior can use the Items mode and people who want the old behavior can use the Entities mode.

**Comment by McJty** [comment]
yes, that might be a good idea yes

**Comment by tansheron** [comment]
@eslachance, your screenshot shows that you tried to use the filter slot in Entities mode. Please note that the only modes in which filters do anything are Block, Fluid, and the proposed Items mode. In the future, we should probably hide the filter slot while other modes are selected so that users aren't misled into thinking it works in every mode.
