### ISSUE TITLE
Server crashes every time when right clicking on modular storage block

### ISSUE THREAD

**Issue by rahangar** [McJtyMods/RFTools#877]
Place down a modular storage block.  Then right click on it.  I see a server crash.  

I have tried this with several different modular storage blocks, and they all crash.   I even crafted new ones and they crash as well.

This started recently after upgrading to hermitpack 1.4.0 after which I upgraded manually to ActuallyAdditions-1.10.2-r81.   I don't know if any of those upgrades are related because I haven't used modular storage for a couple of weeks ... at which time it never crashed.

Storage tablet and other RFTools blocks seem to be working fine.

Please let me know what data you need, and I can provide it.  I don't see any new crash dumps in the crash-reports folder.   I will stop using them for now.

**Comment by McJty** [comment]
I need a crash log

**Comment by rahangar** [comment]
I didn't see any in the crash-reports folder.  Where do I find it?

**Comment by McJty** [comment]
Check in your minecraft logs folder

**Comment by rahangar** [comment]
Please see attached.

**Comment by rahangar** [comment]
[fml-client-latest.txt](https://github.com/McJty/RFTools/files/620674/fml-client-latest.txt)

**Comment by McJty** [comment]
Seems there is some kind of networking error. If you examine the log it is not only rftools that is having issues with this but also IC2. No idea what could cause that however

**Comment by rahangar** [comment]
ok; just to be clear, this is happening 100% of the time when I right click on modular storage blocks.  I can right click all other rftools blocks just fine (dimension blocks, etc) without any issues.  Also, I do not recall using IC2 although the mod is installed as part of the mod pack.

**Comment by MichaelHillcox** [comment]
Thank you for taking the time to create this issue, as we're no longer supporting versions below `1.12`, I'm going to go ahead and close it but if this bug seems to continue over to newer versions, please do report it again so we can investigate the issue further.
