### ISSUE TITLE
[1.10.2] Endergenic Generator randomly stops working as it should

### ISSUE THREAD

**Issue by UnPure** [McJtyMods/RFTools#882]
Hey there.
I'm currently powering my base with Endergenic Generators.
Most of the time its working fine but from time to time they randomly stop working.
Without anything that changes, no restarts and no changes about chunkloading, the generators are suddenly "eating/destroying" all the pearls.
First time i thought it could be a problem with EnderIO conduits.
I recreated the setup with Super Circuit Maker and after a few hours i had the same problem.
I again recreated the complete setup using ONLY RFTools stuff.
Same problem again. Its working fine, every pearl gets send on the 10th tick, the power is running and then it stops working and starts destroying the pearls.
The only way to "fix" that problem is to pick up every single block/machine with a Moving Wand from NotEnoughWands and place it on the same position. After every block is picked up and placed again, the setup is working again for a few hours before the same problem starts again.

A few screenshots that should show how to exactly recreate my setup:
http://imgur.com/a/sbzhr

* All monitors are set to "Pearl Arrived".
* All Sequencer are set to once2.
* The exact ticks from the sequencer are on the first screenshot.
* Every channel for the receiver/transmitter are on the screenshot.
* Ignore the grey receiver/transmitter as they are only a remote shutdown if needed.
* The generators are linked from bottom right (injector) anticlockwise.
* The setup is build in only one chunk and it makes no difference if its chunkloaded or if a player is loading the chunk.

I'm using 
Forge: 12.18.2.2139
RFtools: 5.62
McJtyLib: 2.2.0

The setup is running on a linux server in case that makes any difference.
If you need any other informations, let me know!

Sorry for my bad english, i hope its not to hard to understand.

**Comment by UnPure** [comment]
So after we had that problem we few times more, we tested a little bit more.
It seems like its enough if you pick up and place the 5 Sequencer in the bottom right of the first screen.
No matter if we created the setup with EnderIO Conduits, Super Circuit Maker or RFTools, we always used the 5 sequencer.
I dont know what exactly is going wrong but they seem to be the problem.

**Comment by McJty** [comment]
Do you have other blocks in that chunk? The order in which minecraft ticks tile entities is semi-random. As soon as something modifies in that chunk (i.e. you place stuff/build stuff) it is possible that the timings will change. For that reason it is recommended to build endergenics in chunks on their own without anything else there

**Comment by UnPure** [comment]
No, every setup that we build has its own chunk and nothing is in there besides transceiver/conduits for the energy.

**Comment by MichaelHillcox** [comment]
Hopefully maybe resolved when this is looked into #854 closing in preference of it
