### ISSUE TITLE
Crafter consumes items that should not be consumed

### ISSUE THREAD

**Issue by p3t3rix** [McJtyMods/RFTools#886]
Description:
When crafting blocks from "Flat Colored Blocks" (FCB) in the crafter the items that should not be consumed are consumed. (Modpack used: dw20 1.10.2)

Steps To Reproduce:
1) Put the recipe of a Block from FCB into the crafter.
2) Add the materials needed. For example for a white block: bonemeal, cobble, color picker and the block to duplicate.
3) The crafter now consumes the materials and outputs only one block.

Expected result: The result should be the block but the color picker and the sample block should not be consumed.

I suspect it has something to do with the custom recipe of FCB [(link to source)](https://github.com/AlgorithmX2/FlatColoredBlocks/blob/1.11/src/main/java/mod/flatcoloredblocks/craftingitem/FlatColoredBlockRecipe.java)

![crafter](https://cloud.githubusercontent.com/assets/5238284/20752777/5dc15106-b703-11e6-8236-34ec03b5b6d6.PNG)

**Comment by MichaelHillcox** [comment]
Thank you for taking the time to create this issue, as we're no longer supporting versions below `1.12`, I'm going to go ahead and close it but if this bug seems to continue over to newer versions, please do report it again so we can investigate the issue further.
