### ISSUE TITLE
[Enhancement] Inventory Checker Total Amount

### ISSUE THREAD

**Issue by Aquahatsche** [McJtyMods/RFTools#889]
It'd would be a great enhancement if the inventory checker has an additional mode that can give a redstone signal based on the amount of the whole inventory and not only slot based.

**Comment by McJty** [comment]
RFTools Control actually has ways for that so not sure I'm going to do this on the inventory checker. Undecided

**Comment by MichaelHillcox** [comment]
Unfortunately we're no longer supporting versions older than `1.12` and I don't have enough time to check this suggestion against all of the features of the mod but if this feature still hasn’t been implemented and you’d like to see it added to a newer version of the mod then please do create a new issue so we can review your suggestions again :+1:
