### ISSUE TITLE
Localize tooltips

### ISSUE THREAD

**Issue by Adaptivity** [McJtyMods/RFTools#89]
There are a lot of tooltips. But they are all hardcoded. Use StatCollector.translateToLocal on them.

**Comment by Adaptivity** [comment]
@McJty can I bump this? I still want to fully translate this mod.

**Comment by McJty** [comment]
Ok. Will not be for the next version though as I'm close to finalizing that and don't want to start this right before release.

**Comment by Adaptivity** [comment]
So, since 4.00 version is released, can I expect this for the next version, please?

**Comment by McJty** [comment]
Sorry I didn't get around to this yet as it is a really big job

**Comment by MichaelHillcox** [comment]
Unfortunately we're no longer supporting versions older than `1.12` and I don't have enough time to check this suggestion against all of the features of the mod but if this feature still hasn’t been implemented and you’d like to see it added to a newer version of the mod then please do create a new issue so we can review your suggestions again :+1:
