### ISSUE TITLE
Transmitters all setting to channel 0

### ISSUE THREAD

**Issue by wylderhoads1809** [McJtyMods/RFTools#892]
I've crafted several new transmitters and every time I place them they are on channel 0. I've tried new ones, right clicking in the air, and crafting them with themselves (I assumed this would clear the channel). But they are all on channel 0.  I'm using versions:

1.10.2-forge1.10.2-12.18.2.2166
rftools-1.10-5.62
mcjtylib-1.10-2.2.0

**Comment by McJty** [comment]
How do you see the channel? There is a bug in WAILA where the channel is shown incorrectly. Can you check with TOP?

**Comment by wylderhoads1809** [comment]
I was using WAILA, but I will check with the one probe now.

**Comment by wylderhoads1809** [comment]
Still all 0's with TOP. I even remade the transmitters again to see if that would help.

**Comment by wylderhoads1809** [comment]
An update. I updated to the 1.11/comatlayer version on 1.10 and it appears this issue is only with the transmitters that are cheated in via JEI.

**Comment by MichaelHillcox** [comment]
Thank you for taking the time to create this issue, as we're no longer supporting versions below `1.12`, I'm going to go ahead and close it but if this bug seems to continue over to newer versions, please do report it again so we can investigate the issue further.
