### ISSUE TITLE
Question: Can you have 2 biomes in a world?

### ISSUE THREAD

**Issue by DigitalSketch** [McJtyMods/RFTools#901]
I want to generate world that has nothing but jungle and swampland biomes.  Is this possible?

**Comment by McJty** [comment]
yes, using filtered controller that should work

**Comment by DigitalSketch** [comment]
dumb question probably: but I don't see "Filtered Controller" in JEI How do I make that?

**Comment by McJty** [comment]
At the moment I'm afraid you can't. You have to either:
a) be lucky and find the dimlet in a dimlet house
b) cheat, go to creative and cheat it in using the dimlet workbench

Still working on that part

**Comment by DigitalSketch** [comment]
oh I'd have to find the 2 biome dimlets?

**Comment by DigitalSketch** [comment]
or one dimlet that has both in it?

**Comment by McJty** [comment]
No, you'd have to find the 'filtered controller' dimlet. The biome dimlets you can create in survival using a biome absorber and the dimlet workbench. I recommend checking out a spotlight on rftools dimensions from direwolf. He has a recent one on this

**Comment by DigitalSketch** [comment]
Ahhh found a checkered, and that works :) thanks!

**Comment by MichaelHillcox** [comment]
Unfortunately we're no longer supporting versions older than `1.12` and I don't have enough time to check this suggestion against all of the features of the mod but if this feature still hasn’t been implemented and you’d like to see it added to a newer version of the mod then please do create a new issue so we can review your suggestions again :+1:
