### ISSUE TITLE
[Feature Request] Deep storage module 

### ISSUE THREAD

**Issue by xelrix** [McJtyMods/RFTools#911]
Inspired by MFR DSU, a module that could store a lot of single item.

**Comment by MichaelHillcox** [comment]
Unfortunately we're no longer supporting versions older than `1.12` and I don't have enough time to check this suggestion against all of the features of the mod but if this feature still hasn’t been implemented and you’d like to see it added to a newer version of the mod then please do create a new issue so we can review your suggestions again :+1:
