### ISSUE TITLE
[Feature Request] Fluid storage modules

### ISSUE THREAD

**Issue by xelrix** [McJtyMods/RFTools#912]
Basically, a fluid tank module.

Yeah... I just want to dream rftool to be the only storage solution I need.

**Comment by MichaelHillcox** [comment]
Unfortunately we're no longer supporting versions older than `1.12` and I don't have enough time to check this suggestion against all of the features of the mod but if this feature still hasn’t been implemented and you’d like to see it added to a newer version of the mod then please do create a new issue so we can review your suggestions again :+1:
