### ISSUE TITLE
Storage Scanner search won't release keyboard input

### ISSUE THREAD

**Issue by xenoflot** [McJtyMods/RFTools#922]
Hi,

v5.62  If I give focus to the storage scanner search box and then click the JEI search, JEI displays a flashing cursor, but typed text still goes into the scanner's search box.

Cheers

**Comment by xenoflot** [comment]
Further info: the scanner search box doesn't release focus when you click on the JEI search, but if you click elsewhere (inventory, open space, anywhere _but_ the JEI search) then focus is released normally.

Definitely a low-priority issue.

**Comment by MichaelHillcox** [comment]
Thank you for taking the time to create this issue, as we're no longer supporting versions below `1.12`, I'm going to go ahead and close it but if this bug seems to continue over to newer versions, please do report it again so we can investigate the issue further.
