### ISSUE TITLE
[new block request] Security Shield Projector

### ISSUE THREAD

**Issue by winsrp** [McJtyMods/RFTools#925]
The Shield projector is nice, but if someone has a pickaxe and a shovel they can just make a hole in the ground and pass, and the block protector is great, but has very little range, so the new block works as both the shield projector and the block protector at once.

Here is how it should work:
-it only works with shape cards (so the normal shield projector works best, as is cheaper and more flexible, for normal smaller shields, doors, pasages, bridges, etc)
-It projects a shield, like the normal shield projector, casting a shield over all air blocks
-but also protects all the other blocks of the shape card that are not air
-it also has one special feature, if the power is depleted by damage to the blocks (so you had power going in but it was damage that set the RF buffer to zero, there is a cool down before turning the shield on again, say something like 30 secs. This means that someone is forcing their way in!! So we could use something like RF control to have an alarm system if the security shield projector get to zero and sound an alarm or something. If power goes to zero because you are out of power, then no cool down is needed.
>>>>>>>>>>>>>>>>>>>>
crafting recipe:
-8 block protectors all around and a shield projector in the middle
-the tier of the shield projector will define the tier of the security shield projector block
>>>>>>>>>>>>>>>>>>>>
RF requirements:
-has the same RF buffer of the shield projector + 8 block protectors (so add all the RF all those can have)
-has double the comsuption rate of the shield projector rf/t to keep alive the shield + protection check
-but also has the same consumption of the block protector every hit it eats a chunk of RF
>>>>>>>>>>>>>>>>>>>>
Why make this???
-there is really no other viable security option as of now that could help you protect your stuff in a proper fun, tech way
-the fact that uses RF to protect your "claim" and can be exhausted either by lack of maintenance, bad power management, or brute force of an assault!, is kind of fun
-your mod is so optimized it really has no impact on server performance, not sure how you did it! u know your stuff!
>>>>>>>>>>>>>>>>>>>>
does it look too overpowered?
-well, the way this thing would eat RF, plus what it will eat each time it get hit, is already a very high cost machine.
-if I make a flying island, thing, having the shield projector all around is more OP to be honest, no one can break that stuff!

Please give it a though. 

Thanks, -Winsrp

PD: I'm missing the texture set on the shield projector, good to hide stuff, make secret doors and, that cobble brige over lava that everyone wants to cross but they just fall in! =D

**Comment by MichaelHillcox** [comment]
Unfortunately we're no longer supporting versions older than `1.12` and I don't have enough time to check this suggestion against all of the features of the mod but if this feature still hasn’t been implemented and you’d like to see it added to a newer version of the mod then please do create a new issue so we can review your suggestions again :+1:
