### ISSUE TITLE
Solid shield behind transparent shield not rendering

### ISSUE THREAD

**Issue by Xandaros** [McJtyMods/RFTools#928]
If you have a solid shield directly behind a transparent one (so they basically share a face), the face touching the transparent shield does not render, even though it should be visible.

[![](http://i.imgur.com/Tf3aF4H.png)](http://imgur.com/a/pyvXr)

**Comment by MichaelHillcox** [comment]
Thank you for taking the time to create this issue, as we're no longer supporting versions below `1.12`, I'm going to go ahead and close it but if this bug seems to continue over to newer versions, please do report it again so we can investigate the issue further.
