### ISSUE TITLE
[1.10.2] [Bug] Shield has mental break down if two withers are inside it 

### ISSUE THREAD

**Issue by Dijkstra1** [McJtyMods/RFTools#934]
I setup the the RFTools shield, to kill withers it worked fine but when a second enter it the shields just decided that it was not working, and the two withers escaped, the shield was being supplied with enough power.

**Comment by McJty** [comment]
Are you sure it got enough power and that you were using a high enough tiered shield? The power spike from a wither can be massive. You need very high power input for that

**Comment by Dijkstra1** [comment]
it is tier 2 and has on of your power cells next to it which feed buy a big battery back at the base

**Comment by McJty** [comment]
A single powercell can only do 20K rf/t if it is a max tier. That might not be enough

**Comment by Dijkstra1** [comment]
Well if you do not know if that is enough power then I have no chance, I try putting power cells on 4 sides of the block but i have no desire to let 2 withers loss on a public server

**Comment by McJty** [comment]
There are a few things you can do:
1) Use a higher tier shield. these are more effective
2) Infuse the shield so it uses less power
3) Add multiple powercells next to it
4) Avoid spawning multiple withers at the same time

**Comment by Dijkstra1** [comment]
1 & 2 are looked behind, going to rftools dim and dim builder recipe has been changed in pack to require end game stuff from another mod and we are nowhere near that, 3 can 4 was a mistake block placer formed the withers 2 fast :P

**Comment by MichaelHillcox** [comment]
Thank you for taking the time to create this issue, as we're no longer supporting versions below `1.12`, I'm going to go ahead and close it but if this bug seems to continue over to newer versions, please do report it again so we can investigate the issue further.
