### ISSUE TITLE
Cannot delete Rftools Dimensions 1.10.2

### ISSUE THREAD

**Issue by GldnSabre74** [McJtyMods/RFTools#941]
We have used /rftools safedel id and it always says those dimensions are active. However those dimension have never worked to begin with as they were overwritten with a second players dimension creation. The creation of the dimension did not assign a new id number to it and now all new dimension created are getting the same number assigned to them, so no new dimensions can be created. Looked for the reclaim id but it is not part of the 1.10.2 Rftools.

**Comment by CharZinta** [comment]
We have encountered this as well. Once an ID is made all ID's spawn to that same world. Even using Safedel does not remove the world, removes the folder off the server but RFTOOLS thinks it still exists. 

problem 1) Creating worlds generates the same ID and links to the same world over and over again.
problem 2) Using safedel deletes files/folders on the server but not the "world" from within RFTOOLS. Transmitter knows it doesn't exist but the Enscriber and/or builder do not.

I was able to shutdown the server, remove rftools, restart, delete all rftools items, finish starting, shutdown, add RFTOOLS back and build a new world. 

Problem 3) When doing the above ID2 is still not availabe so RFTOOLS will generate ID3 and then link all future dimlets to this one ID.

Running:
Minecraft 1.10.2
Spongeforge
Forge

list of mods available upon request.  I will attempt to replicate this problem with a pure forge instance and/or RFTOOLS by itself.

**Comment by MichaelHillcox** [comment]
Thank you for taking the time to create this issue, as we're no longer supporting versions below `1.12`, I'm going to go ahead and close it but if this bug seems to continue over to newer versions, please do report it again so we can investigate the issue further.
