### ISSUE TITLE
PSI CAD + RFTools modular storage result in weird search behavior

### ISSUE THREAD

**Issue by Terpo** [McJtyMods/RFTools#952]
http://blog.terpo.org/upload/mc/modlist.txt
latest RB of Forge for MC 1.10.2
compatlayer-1.10-0.1.3.jar
rftools-1.1x-5.71.jar
Psi-r1.0-42.jar

https://youtu.be/Cq3p0Hbjw10

In short: If you have a PSI CAD in your inventory the search bar in RFTools modular storages has weird behavior when updating. Nothing huge, but can be annoying.

**Comment by McJty** [comment]
Hmm, did you also report this with PSI? Could be some kind of interaction but would be nice to know what exactly is going on on the side of PSI

**Comment by Terpo** [comment]
Sry, forgot to post it on the PSI side ^^
ref: https://github.com/Vazkii/Psi/issues/283

**Comment by MichaelHillcox** [comment]
Thank you for taking the time to create this issue, as we're no longer supporting versions below `1.12`, I'm going to go ahead and close it but if this bug seems to continue over to newer versions, please do report it again so we can investigate the issue further.
