### ISSUE TITLE
/rfttp cleanup does not exist

### ISSUE THREAD

**Issue by ossuman** [McJtyMods/RFTools#956]
The documentation says to use /rfttp cleanup in order to clear old dimensions from dialers that were deleted but still appear. Right now it appears the command is not implemented, and there appears no other way to clear them.

**Comment by McJty** [comment]
This command should not be needed if you delete the dimensions properly using safedel? How were the dimensions deleted?

**Comment by ossuman** [comment]
There's a chance I deleted the folders before finding the documentation to use safedel. However, I attached analyzer to my dialing device, and checked the broken dimensions and they were removed from the list

**Comment by MichaelHillcox** [comment]
Thank you for taking the time to create this issue, as we're no longer supporting versions below `1.12`, I'm going to go ahead and close it but if this bug seems to continue over to newer versions, please do report it again so we can investigate the issue further.
