### ISSUE TITLE
[issue][1.1x-5.72] shield projects shows 0% infusion after dimension change, modular storage weird math

### ISSUE THREAD

**Issue by winsrp** [McJtyMods/RFTools#957]
Issue 1

after having infused a shield project to 100%, and putting it on the world (setting it up and everything) and then going to another dimension (nether works) when coming back the shield shows 0% infusion. (but I think it still has 100% but the message shows 0%)

Issue 2

When using the modular storage, storing a recipe (e.g. redstone to blocks) filling the container a bit with some stacks of redstone and then crafting the recipe for a stack of redstone blocks, the amount of stacks that is shown in waila for the card of the storage unit, spikes to several more than what the storage can contain, (e.g. 23578 of 300) this seems like just a visual math glitch as the amount of stacks are re-calculated when you take the storage module tier card and put it back in, and the builder for example can still put stacks in the storage module, but it looks weird.

**Comment by McJty** [comment]
What version of MC?

Also what does TOP show? WAILA isn't always as accurate here. TOP should always show the correct things

**Comment by winsrp** [comment]
minecraft version is 1.10.2, what is TOP?

**Comment by McJty** [comment]
The One Probe. My alternative to WAILA which is used in HermitCraft, Infinity and so on

**Comment by winsrp** [comment]
the infusion level does seem to work on TOP, but the math thing on the storage is still wrong on TOP

**Comment by MichaelHillcox** [comment]
Thank you for taking the time to create this issue, as we're no longer supporting versions below `1.12`, I'm going to go ahead and close it but if this bug seems to continue over to newer versions, please do report it again so we can investigate the issue further.
