### ISSUE TITLE
Builder With Clearing fortune Card Stalls

### ISSUE THREAD

**Issue by wizzbangwa** [McJtyMods/RFTools#960]
Using the builder as a quarry with a clearing fortune card.  I have 3 lava generators supplying power.  Builder is at 10 mrf power.  Card inserted.  A lever is in the on position telling.  The builder is stalled. Y: number is not changing, the status text is not changing.  Nothing is happening.  The builder was working about 3  hours ago.  I changed the coordinates in the card and now the builder doesn't work.  I didn't move anything else around, just changed the card coordinates to mine a different area.

Running on Hermitpack 1.5.1, MC 1.10.2.  I'm showing rftools 5.62.

**Comment by wizzbangwa** [comment]
Some images that hopefully show something I am doing wrong, even though this setup has been working for a few days.

![2016-12-28_15 05 44](https://cloud.githubusercontent.com/assets/15223727/21533429/47d60982-cd0f-11e6-8d48-6d34a39e9aaf.png)
![2016-12-25_11 52 23](https://cloud.githubusercontent.com/assets/15223727/21533431/48f008e0-cd0f-11e6-8a28-4e79fd3f6995.png)
![2016-12-28_15 05 54](https://cloud.githubusercontent.com/assets/15223727/21533432/4a54bfe6-cd0f-11e6-8364-7c781d2a828f.png)
![2016-12-28_15 06 20](https://cloud.githubusercontent.com/assets/15223727/21533434/4b10ef2c-cd0f-11e6-826a-289f6ec06422.png)

**Comment by McJty** [comment]
It is strange that this setup was working because it can't work like that. The builder needs an inventory on top or below and doesn't work with conduits like that

**Comment by MichaelHillcox** [comment]
Thank you for taking the time to create this issue, as we're no longer supporting versions below `1.12`, I'm going to go ahead and close it but if this bug seems to continue over to newer versions, please do report it again so we can investigate the issue further.
