### ISSUE TITLE
Storage Filter Module in Builder (as quarry) not working as desired

### ISSUE THREAD

**Issue by davelien** [McJtyMods/RFTools#961]
This is with RFTools 1.1x-5.72 McJtyLib 1.1x-2.3.1, MC 1.10.2, and Forge 12.18.3.2185, Direwolf20 1.10 FTB pack.

When I install a Storage Filter Module in a Builder, in whitelist mode, all whitelisted items are successfully transferred to an attached chest but additional items are collected and transferred as well.  The items that are collected, which are not whitelisted, seem to be primarily if not exclusively ores from IC2.  Copper Ore 5767/1, Lead Ore 5767/2, Tin Ore 5767/3

The filter is set to blacklist but all other options are left at the default (mod, damage, oredict, etc.)

![image](https://cloud.githubusercontent.com/assets/12649356/21575156/79345862-ceb8-11e6-9c51-0ec560ff3ae1.png)

The Builder contains a Shape Card (Quarry).
![image](https://cloud.githubusercontent.com/assets/12649356/21575151/5b20a6be-ceb8-11e6-8f9f-20035bcdcb9a.png)

**Comment by togreglove** [comment]
I reported this behavior a while back, but was unable to consistently reproduce it at the time. Now I can.

1. Craft a filter.
2. Open the interface, note that it indicates it is in blacklist mode by hovering over icon.
3. Add item to the list.
4. Close interface.
5. Note the tooltip of the filter indicates that the filter is in *whitelist* mode.
6. Re-open interface and note that it still indicates that it is in blacklist mode.
(It is indeed in whitelist mode, regardless of this indication)
7. Click icon to convert to whitelist mode, then back to blacklist mode.
8. Close interface and note that tooltip now correctly indicates it is in blacklist mode.

**Comment by MichaelHillcox** [comment]
Thank you for taking the time to create this issue, as we're no longer supporting versions below `1.12`, I'm going to go ahead and close it but if this bug seems to continue over to newer versions, please do report it again so we can investigate the issue further.
