### ISSUE TITLE
Naming matter transmitter/receiver causing client crash

### ISSUE THREAD

**Issue by dbridle** [McJtyMods/RFTools#965]
Hi McJty,

I'm currently playing through Project Ozone 2 - Kappa and have the following crash when naming matter transmitters/receivers.  Is this a pack issue or something new/known?

http://pastebin.com/QxDmvG68

Thanks!

MC_Tirm

**Comment by McJty** [comment]
This has been reported before but I have never been able to find this and 1.7.10 is no longer maintained so...

**Comment by dbridle** [comment]
After some hours of messing around, I discovered it only happens when I have a tinkers tool in my hand!

Sorry for seeing the previously reported issue, I did do a search, but nothing really came close, so must have been worded differently!

**Comment by MichaelHillcox** [comment]
Close as 1.7.10 is no longer supported. If this continues to be a bug on 1.12 or newer, please open a new issue.
