### ISSUE TITLE
Probabilities of getting a dimlet ?

### ISSUE THREAD

**Issue by Yarillo4** [McJtyMods/RFTools#967]
Hello ! I am loving the mod so far, I think it's great, I just can't seem to find some stuff on the wiki.
Is it specified anywhere how the dimlet researcher and the dimlet scrambler work, probabilities wise ?
I tried to look at the code but I've never coded in Java and couldn't even find the dimlet researcher block.

Thank you c:

**Comment by MichaelHillcox** [comment]
The in-game guide is the place to look
