### ISSUE TITLE
builder not mining/breaking leaves(1.10.2-2202)

### ISSUE THREAD

**Issue by SDUBZ** [McJtyMods/RFTools#968]
rftools-1.1x-5.75
forge 1.10.2-2202

log:
[fml-client-latest..txt](https://github.com/McJty/RFTools/files/683072/fml-client-latest.txt)

**Comment by MichaelHillcox** [comment]
Thank you for taking the time to create this issue, as we're no longer supporting versions below `1.12`, I'm going to go ahead and close it but if this bug seems to continue over to newer versions, please do report it again so we can investigate the issue further.

**Comment by MichaelHillcox** [comment]
#563
