### ISSUE TITLE
Flight module sticking "on"

### ISSUE THREAD

**Issue by xenoflot** [McJtyMods/RFTools#969]
Hi,

I have a custom server pack and I've set up an environmental controller, fed by an IE HV capacitor. There's a single Flight module in it.  Similar to #538 my flight is persisting even after the buff has expired. It persists when out of range of the controller, including across dimensions.

I have tried to replicate this in SSP, with a local test server with configs copied from the production server, and with a stripped-down pack, but I can't! It only happens with our production server. Only difference in testing was that I used an RFT creative powercell rather than an IE HV cap.

If I disable the EnvCtlr with its redstone button, the buff expires as expected.

I have enabled debug in rftools.cfg on both server and client but I'm not seeing anything extra in the regular logs.  Is the additional info supposed to go into the regular logs?

If you have any ideas on how I can troubleshoot, please let me know!

Cheers

**Comment by McJty** [comment]
Version please?

**Comment by xenoflot** [comment]
oops!

rftools-1.1x-5.75
mcjtylib-1.1x-2.3.1
compatlayer-1.10-0.1.6
forge 2185
mc 1.10.2

Update: Having the controller disabled isn't a sure-fire way of ensuring the buff expires.
/tp anotherplayer DID clear it!
My brain hurts.

**Comment by MichaelHillcox** [comment]
Thank you for taking the time to create this issue, as we're no longer supporting versions below `1.12`, I'm going to go ahead and close it but if this bug seems to continue over to newer versions, please do report it again so we can investigate the issue further.
