### ISSUE TITLE
Screen breaks, can't interact with buttons MC 1.7.10

### ISSUE THREAD

**Issue by Neuron67** [McJtyMods/RFTools#970]
Tried version 4.22 and 4.23 of RFTools with Mcjtylib 1.8.1

**Comment by McJty** [comment]
Note that it is left click to interact with a button. Not right click as you might be used too

**Comment by Neuron67** [comment]
TRied both with item in hand and without.

**Comment by Neuron67** [comment]
I should probably mention that I also have this working fine in 1.10.2.
Love the mod and can't do without on 1.7.10

**Comment by McJty** [comment]
You don't need an item in hand. You need to use the LEFT mouse button to hit a button on a screen. Not the right button

**Comment by Neuron67** [comment]
I hesitated reporting this issue because I have made simple errors in the past but I have tried everything I can think of to place a screen and interact with it in 1.7.10.
I expected to find a solution from reading other posts because I believed I was doing something wrong.
To my surprise, I seem to be the only one having this issue.

**Comment by Neuron67** [comment]
I can assure you, I'm not the kind of person that yells "HELP" before reading up.
I've even removed all other mods one by one and created new worlds. No change.
Forge version is 10.13.4.1558-1.7.10

**Comment by McJty** [comment]
Why are you ignoring my question? Do you press the left mouse button on the screen?

**Comment by Neuron67** [comment]
I'm not ignoring your question. I answered it right away.
You must have missed it.

**Comment by Neuron67** [comment]
I tried both (left and right click)
I also stated that I have it working fine in 1.10 .2.

**Comment by McJty** [comment]
No idea then. Nobody ever reported this. Maybe some other mod is preventing left clicks on blocks or something

**Comment by Neuron67** [comment]
Well thanks for the great mod. I'll keep trying as I come up with ideas.

**Comment by Neuron67** [comment]
Can you tell me what the latest version of forge was for 1.7.10?
I went to the forge website but their latest seems older than what I have????

**Comment by Neuron67** [comment]
I'm an idiot for not trying this sooner but I discovered that in Survival mode the screen doesn't break.
Was that your intention with version 4.2.3?
Obviously it was changed in the 1.10.2 version.
Is there a way to change the setting in 4.2.3 or 4.2.2?

**Comment by Neuron67** [comment]
Created a new profile
Forge-10.13.4.1614
Installed only CofhLib-1.7.10 1.1.2-182
                      rftools-4.23
                      mcjtylib-1.8.1
                      EnderIO-1.7.10-2.2.8.381 (energy source for screen controller)

Screen still breaks when left click in Creative mode
Can someone please verify this?

**Comment by McJty** [comment]
I think this feature was not implemented in 1.7.10. It is only fixed in 1.10.2

**Comment by Neuron67** [comment]
which feature are you referring to?

**Comment by McJty** [comment]
>Screen still breaks when left click in Creative mode

In 1.10 that is prevented. But not in 1.7.10

**Comment by Neuron67** [comment]
On the following page there is an image showing two examples of screens and it appears to be a screencap taken in creative mode.... am I mistaken?
[](https://github.com/McJty/RFTools/wiki/RFTools-Screen)

**Comment by McJty** [comment]
No? But what has that to do with it?

**Comment by Neuron67** [comment]
There are a few more references in your overview of rftools to the use of creative mode and none mention that the screen can't be interacted with in that mode.

**Comment by McJty** [comment]
No but they also don't mention that it *can* be interacted with

**Comment by Neuron67** [comment]
You're right but how can I be the only one that has discovered this?

**Comment by Neuron67** [comment]
All I want is for the mod to work properly in 1.7.10 where I have all of my mods working fine together; about 30 or so.
I'm not trying to criticize anyone.

**Comment by McJty** [comment]
I know but unfortunatelly I no longer mod for 1.7.10. I already have tons of work on 1.10.2 and 1.11.2 with all the mods that I'm having and I simply don't have the time for it. Sorry

**Comment by Neuron67** [comment]
I understand that you're busy like many other modders you must keep up with the latest versions but I don't expect you to rewrite any code to solve this issue. I just need a tip or two on how to fix it. It has to be a conflict of some kind between versions of rftools and forge or something.

**Comment by McJty** [comment]
No, it is actually a bug in rftools. The 1.10 version has it fixed. But this is something mods themselves have to handle (i.e. preventing breaking in creative)

**Comment by Neuron67** [comment]
I have to ask why you didn't just say that in the beginning?
You led me to believe I was the only one having this issue!

**Comment by McJty** [comment]
Well this was (for me) a bit confusing conversation I must say :-)
