### ISSUE TITLE
[1.10.2] Unable to craft item from Storage Module

### ISSUE THREAD

**Issue by Protheus** [McJtyMods/RFTools#971]
**Issue:**
I created a Storage Module, added a Storage Module Tier 3 card and a Generic Storage module.
I placed 4 redstone and a book in the storage with other stuff. 

Now when I place the items in the crafting area, the rftools books comes up.
When I press 1.. it doesn't craft the book.. 

**What should happen:**
When pressing the 1, 4, 8 or stack button the item should be created and placed in your inventory, it is not doing that now.

**Screenshot:**
http://imgur.com/a/QRptO

**Versions:**
MC: 1.10.2
RFTools: rftools-1.1x-5.76 
mcjtylib-1.1x-2.3.1
Forge: 2185

**Comment by Protheus** [comment]
It seems the left part where you can craft and store isn't active for me. When you place a recipe I can't press the store button to remember the recipe

![capture](https://cloud.githubusercontent.com/assets/1455178/21748496/d1c6a03c-d586-11e6-9cb3-90c3c7913063.PNG)

**Comment by Darkere** [comment]
The store button only appears if you have highlighted the slot you want to store the recipe in beforehand.

Not being able to craft is another problem though.

**Comment by McJty** [comment]
Why does your book look so weird? Are you using a texture pack?

**Comment by Protheus** [comment]
Aaah oke will need to highlight it first, tnx.

Yes, using a texturepack... Soartex fanver

**Comment by Silvrus** [comment]
Also having difficulty crafting sometimes. Latest issue was IC2 copper cable. Several stacks of copper wire and rubber, storage scanner actually highlighted the result slot red for some reason. Other times I've click to craft a stack of something and get 4 instead. A restart _seems_ to make it work correctly again.

**Comment by davqvist** [comment]
One thing I found out is that it crafting items with NBT data doesn't correctly work. That is the issue with the Copper Cables for IC2 for example, pretty confident.

**Comment by MichaelHillcox** [comment]
Thank you for taking the time to create this issue, as we're no longer supporting versions below `1.12`, I'm going to go ahead and close it but if this bug seems to continue over to newer versions, please do report it again so we can investigate the issue further.
