### ISSUE TITLE
Attempting to add a userdimlet.json!

### ISSUE THREAD

**Issue by ChristopherFinn** [McJtyMods/RFTools#974]
Hello McJty!

Huge fan of the mod, really enjoying all the features you've implemented. I was just curious if you could help me out with an addition to the mod?
I attempted to follow your guide on adding a material so I began with

`[
	["material", "bigreactors", "blockMetals", 0 ]

dimletsettings {
	I:"rarity.Material.tile.bigreactors:blockMetals"=4
	I:"rfcreate.Material.tile.bigreactors:blockMetals"=45000
	I:"rfmaintain.Material.tile.bigreactors:blockMetals"=15000
	I:"ticks.Material.tile.bigreactors:blockMetals"=1000
	
}
]`

The server still starts but I can't find any way to verify if it is working or not. I haven't seen it after hours of looking nor can I find it in the Workbench menu. All the code posted above was implemented in the userdimlets.json file that I added to the directory.

I am attempting to do this in Direwolf20 1.10.2 through MCProHosting, maybe that'll help narrow down the issue. If you can get back to me that'd be great! 

Thanks for mods,
Christopher

**Comment by McJty** [comment]
The wiki is outdated and only valid for 1.7.10. You need to change the dimlets.json file in the config directory instead. Look for similar rules that have material in them and add your custom right BEFORE the first special marker line. Let me know if that helps

**Comment by ChristopherFinn** [comment]
Thanks for the reply!
I attempted to add the custom dimlet to the dimlets.json.

I used the following code,
`{
    "filter": {
      "mod": "bigreactors",
      "name": "blockMetals",
      "type": "material",
      "property": {
        "type": "0"
      }
    },
    "settings": {
      "rarity": 5,
      "create": 80000,
      "maintain": 20000,
      "ticks": 1000,
      "worldgen": true,
      "dimlet": true
    }
  },`

From what I've gathered, and I don't know much so feel free to correct me, is that the blocks run off metadata and don't have an actual name?
<img width="1229" alt="screen shot 2017-01-11 at 9 47 15 am" src="https://cloud.githubusercontent.com/assets/25053150/21853015/5b318cac-d7e3-11e6-95da-64b69a540ad8.png">
This is the Developers Delight tool used on the Yellorium Block.
<img width="1226" alt="screen shot 2017-01-11 at 9 46 54 am" src="https://cloud.githubusercontent.com/assets/25053150/21853016/5b36e8a0-d7e3-11e6-8328-7ec957868079.png">
This is the Developers Delight tool used on the Yellorium ore.
In the bottom right hand corner of the tool, there is a 0. When I use any other ore in the mod with the tool that number changes from anywhere between 0-3 for the different full blocks, and 0-2 for the 3 different ore types. I can only imagine this means that their names would be blockMetals:0-3 or is that just wrong in general and I'm missing something? 

After adding the new lines of code to the dimlets.json the server still booted up so no errors there, just no new dimlet that I can find. 

Thanks again for all the help,
Christopher

**Comment by McJty** [comment]
Can you paste me your dimlets.json completely?

**Comment by ChristopherFinn** [comment]
[
  "Everything below this line will be regenerated from defaults every time. Remove this line if you do not want that",
  {
    "filter": {
      "name": "owner",
      "type": "special"
    },
    "settings": {
      "rarity": 0,
      "create": 0,
      "maintain": 0,
      "ticks": 0,
      "worldgen": false,
      "dimlet": true
    }
  },
  {
    "filter": {
      "name": "cheater",
      "type": "special"
    },
    "settings": {
      "rarity": 0,
      "create": 0,
      "maintain": 0,
      "ticks": 0,
      "worldgen": false,
      "dimlet": true
    }
  },
  {
    "filter": {
      "name": "noanimals",
      "type": "special"
    },
    "settings": {
      "rarity": 2,
      "create": 5000,
      "maintain": 40,
      "ticks": 10,
      "worldgen": false,
      "dimlet": true
    }
  },
  {
    "filter": {
      "name": "spawn",
      "type": "special"
    },
    "settings": {
      "rarity": 2,
      "create": 10000,
      "maintain": 300,
      "ticks": 100,
      "worldgen": false,
      "dimlet": true
    }
  },
  {
    "filter": {
      "name": "seed",
      "type": "special"
    },
    "settings": {
      "rarity": 2,
      "create": 1000,
      "maintain": 0,
      "ticks": 100,
      "worldgen": false,
      "dimlet": true
    }
  },
  {
    "filter": {
      "name": "seed",
      "type": "special"
    },
    "settings": {
      "rarity": 2,
      "create": 1000,
      "maintain": 0,
      "ticks": 100,
      "worldgen": false,
      "dimlet": true
    }
  },
  {
    "filter": {
      "name": "peaceful",
      "type": "special"
    },
    "settings": {
      "rarity": 5,
      "create": 50000,
      "maintain": 30000,
      "ticks": 900,
      "worldgen": false,
      "dimlet": true
    }
  },
  {
    "filter": {
      "name": "efficiency",
      "type": "special"
    },
    "settings": {
      "rarity": 5,
      "create": 100000,
      "maintain": -20,
      "ticks": 900,
      "worldgen": false,
      "dimlet": true
    }
  },
  {
    "filter": {
      "name": "mediocreefficiency",
      "type": "special"
    },
    "settings": {
      "rarity": 4,
      "create": 100000,
      "maintain": -5,
      "ticks": 400,
      "worldgen": false,
      "dimlet": true
    }
  },
  {
    "filter": {
      "type": "digit"
    },
    "settings": {
      "rarity": 0,
      "create": 0,
      "maintain": 0,
      "ticks": 0,
      "worldgen": false,
      "dimlet": true
    }
  },
  {
    "filter": {
      "mod": "tconstruct",
      "name": [
        "ore",
        "metal"
      ],
      "type": "material",
      "property": {
        "type": "COBALT"
      }
    },
    "settings": {
      "rarity": 5,
      "create": 80000,
      "maintain": 20000,
      "ticks": 1000,
      "worldgen": true,
      "dimlet": true
    }
  },
  {
    "filter": {
      "mod": "tconstruct",
      "name": [
        "ore",
        "metal"
      ],
      "type": "material",
      "property": {
        "type": "ARDITE"
      }
    },
    "settings": {
      "rarity": 5,
      "create": 80000,
      "maintain": 20000,
      "ticks": 1000,
      "worldgen": true,
      "dimlet": true
    }
  },
  {
    "filter": {
      "mod": "minecraft",
      "name": "stone",
      "type": "material"
    },
    "settings": {
      "rarity": 0,
      "create": 5,
      "maintain": 1,
      "ticks": 1,
      "worldgen": true,
      "dimlet": true
    }
  },
  {
    "filter": {
      "mod": "tconstruct",
      "name": "metal",
      "type": "material",
      "property": {
        "type": "KNIGHTSLIME"
      }
    },
    "settings": {
      "worldgen": false,
      "dimlet": false
    }
  },
  {
    "filter": {
      "mod": "bigreactors",
      "name": "blockMetals",
      "type": "material",
      "property": {
        "type": "0"
      }
    },
    "settings": {
      "rarity": 5,
      "create": 80000,
      "maintain": 20000,
      "ticks": 1000,
      "worldgen": true,
      "dimlet": true
    }
  },
  {
    "filter": {
      "mod": "tconstruct",
      "name": "metal",
      "type": "material",
      "property": {
        "type": "MANYULLYN"
      }
    },
    "settings": {
      "rarity": 5,
      "create": 80000,
      "maintain": 20000,
      "ticks": 1000,
      "worldgen": true,
      "dimlet": true
    }
  },
  {
    "filter": {
      "mod": "biomesoplenty",
      "name": [
        "hard_sand",
        "crag_rock",
        "dried_dirt",
        "dirt",
        "hard_dirt",
        "planks_0",
        "stone",
        "log_0",
        "sand",
        "log_2",
        "log_1",
        "ash_block",
        "ash_stone",
        "hard_ice",
        "mud",
        "log_3"
      ],
      "type": "material"
    },
    "settings": {
      "rarity": 2,
      "create": 100,
      "maintain": 30,
      "ticks": 10,
      "worldgen": true,
      "dimlet": true
    }
  },
  {
    "filter": {
      "mod": "flatcoloredblocks",
      "name": "flatcoloredblock_glowing.*",
      "type": "material"
    },
    "settings": {
      "rarity": 4,
      "create": 500,
      "maintain": 500,
      "ticks": 100,
      "worldgen": false,
      "dimlet": true
    }
  },
  {
    "filter": {
      "mod": "flatcoloredblocks",
      "name": "flatcoloredblock.*",
      "type": "material"
    },
    "settings": {
      "rarity": 2,
      "create": 100,
      "maintain": 50,
      "ticks": 10,
      "worldgen": false,
      "dimlet": true
    }
  },
  {
    "filter": {
      "mod": "biomesoplenty",
      "name": [
        "gem_block",
        "gem_ore"
      ],
      "type": "material"
    },
    "settings": {
      "rarity": 3,
      "create": 2000,
      "maintain": 1000,
      "ticks": 90,
      "worldgen": true,
      "dimlet": true
    }
  },
  {
    "filter": {
      "mod": "thaumcraft",
      "name": [
        "ore_cinnabar",
        "ore_amber"
      ],
      "type": "material"
    },
    "settings": {
      "rarity": 3,
      "create": 2000,
      "maintain": 1000,
      "ticks": 90,
      "worldgen": true,
      "dimlet": true
    }
  },
  {
    "filter": {
      "mod": "thaumcraft",
      "name": [
        "translucent",
        "log",
        "stone"
      ],
      "type": "material"
    },
    "settings": {
      "rarity": 4,
      "create": 4000,
      "maintain": 3000,
      "ticks": 200,
      "worldgen": true,
      "dimlet": true
    }
  },
  {
    "filter": {
      "name": [
        "red_sandstone",
        "cobblestone",
        "dirt",
        "netherrack",
        "sandstone",
        "nether_brick",
        "stonebrick"
      ],
      "type": "material"
    },
    "settings": {
      "rarity": 0,
      "create": 3,
      "maintain": 1,
      "ticks": 10,
      "worldgen": true,
      "dimlet": true
    }
  },
  {
    "filter": {
      "name": "end_stone",
      "type": "material"
    },
    "settings": {
      "rarity": 4,
      "create": 1000,
      "maintain": 1000,
      "ticks": 100,
      "worldgen": true,
      "dimlet": true
    }
  },
  {
    "filter": {
      "name": "bedrock",
      "type": "material"
    },
    "settings": {
      "rarity": 4,
      "create": 1000,
      "maintain": 300,
      "ticks": 50,
      "worldgen": true,
      "dimlet": true
    }
  },
  {
    "filter": {
      "name": [
        "glass",
        "packed_ice",
        "stained_glass"
      ],
      "type": "material"
    },
    "settings": {
      "rarity": 3,
      "create": 100,
      "maintain": 100,
      "ticks": 50,
      "worldgen": true,
      "dimlet": true
    }
  },
  {
    "filter": {
      "name": "wool",
      "type": "material"
    },
    "settings": {
      "rarity": 4,
      "create": 300,
      "maintain": 500,
      "ticks": 100,
      "worldgen": true,
      "dimlet": true
    }
  },
  {
    "filter": {
      "name": [
        "stained_hardened_clay",
        "hardened_clay",
        "clay"
      ],
      "type": "material"
    },
    "settings": {
      "rarity": 2,
      "create": 100,
      "maintain": 100,
      "ticks": 50,
      "worldgen": true,
      "dimlet": true
    }
  },
  {
    "filter": {
      "name": "slime_block",
      "type": "material"
    },
    "settings": {
      "rarity": 5,
      "create": 1000,
      "maintain": 1000,
      "ticks": 500,
      "worldgen": false,
      "dimlet": true
    }
  },
  {
    "filter": {
      "name": [
        "prismarine",
        "log",
        "purpur_block",
        "log2",
        "planks",
        "end_bricks"
      ],
      "type": "material"
    },
    "settings": {
      "rarity": 2,
      "create": 100,
      "maintain": 100,
      "ticks": 50,
      "worldgen": true,
      "dimlet": true
    }
  },
  {
    "filter": {
      "mod": "rftoolsdim",
      "name": "dimensional_.*_block",
      "type": "material"
    },
    "settings": {
      "rarity": 3,
      "create": 200,
      "maintain": 100,
      "ticks": 50,
      "worldgen": true,
      "dimlet": true
    }
  },
  {
    "filter": {
      "name": [
        "dimensional_shard_ore",
        "emerald_ore",
        "diamond_ore",
        "glowstone"
      ],
      "type": "material"
    },
    "settings": {
      "rarity": 5,
      "create": 40000,
      "maintain": 10000,
      "ticks": 800,
      "worldgen": true,
      "dimlet": true
    }
  },
  {
    "filter": {
      "name": [
        "lapis_ore",
        "gold_ore",
        "quartz_ore"
      ],
      "type": "material"
    },
    "settings": {
      "rarity": 4,
      "create": 20000,
      "maintain": 3500,
      "ticks": 400,
      "worldgen": true,
      "dimlet": true
    }
  },
  {
    "filter": {
      "name": [
        "coal_ore",
        "redstone_ore",
        "iron_ore"
      ],
      "type": "material"
    },
    "settings": {
      "rarity": 3,
      "create": 8000,
      "maintain": 1400,
      "ticks": 300,
      "worldgen": true,
      "dimlet": true
    }
  },
  {
    "filter": {
      "name": ".*_ore",
      "type": "material"
    },
    "settings": {
      "rarity": 4,
      "create": 2000,
      "maintain": 1000,
      "ticks": 500,
      "worldgen": true,
      "dimlet": true
    }
  },
  {
    "filter": {
      "name": [
        "emerald_block",
        "diamond_block"
      ],
      "type": "material"
    },
    "settings": {
      "rarity": 5,
      "create": 80000,
      "maintain": 20000,
      "ticks": 1000,
      "worldgen": true,
      "dimlet": true
    }
  },
  {
    "filter": {
      "name": [
        "obsidian",
        "gold_block",
        "quartz_block",
        "lapis_block"
      ],
      "type": "material"
    },
    "settings": {
      "rarity": 5,
      "create": 30000,
      "maintain": 9000,
      "ticks": 500,
      "worldgen": true,
      "dimlet": true
    }
  },
  {
    "filter": {
      "name": [
        "redstone_block",
        "iron_block",
        "coal_block"
      ],
      "type": "material"
    },
    "settings": {
      "rarity": 4,
      "create": 15000,
      "maintain": 6000,
      "ticks": 300,
      "worldgen": true,
      "dimlet": true
    }
  },
  {
    "filter": {
      "type": "material"
    },
    "settings": {
      "worldgen": false,
      "dimlet": false
    }
  },
  {
    "filter": {
      "name": "water",
      "type": "liquid"
    },
    "settings": {
      "rarity": 0,
      "create": 10,
      "maintain": 10,
      "ticks": 10,
      "worldgen": true,
      "dimlet": true
    }
  },
  {
    "filter": {
      "mod": "tconstruct",
      "name": [
        "purpleslime",
        "molten_knightslime"
      ],
      "type": "liquid"
    },
    "settings": {
      "worldgen": false,
      "dimlet": false
    }
  },
  {
    "filter": {
      "mod": [
        "tconstruct",
        "buildcraft|energy",
        "pneumaticcraft"
      ],
      "type": "liquid"
    },
    "settings": {
      "rarity": 5,
      "create": 3000,
      "maintain": 3000,
      "ticks": 100,
      "worldgen": true,
      "dimlet": true
    }
  },
  {
    "filter": {
      "mod": "thaumcraft",
      "name": "purifying_fluid",
      "type": "liquid"
    },
    "settings": {
      "rarity": 5,
      "create": 4000,
      "maintain": 4000,
      "ticks": 500,
      "worldgen": false,
      "dimlet": true
    }
  },
  {
    "filter": {
      "mod": "thaumcraft",
      "type": "liquid"
    },
    "settings": {
      "rarity": 3,
      "create": 1000,
      "maintain": 800,
      "ticks": 50,
      "worldgen": true,
      "dimlet": true
    }
  },
  {
    "filter": {
      "mod": "biomesoplenty",
      "type": "liquid"
    },
    "settings": {
      "rarity": 3,
      "create": 1000,
      "maintain": 500,
      "ticks": 50,
      "worldgen": true,
      "dimlet": true
    }
  },
  {
    "filter": {
      "name": "lava",
      "type": "liquid"
    },
    "settings": {
      "rarity": 5,
      "create": 3000,
      "maintain": 2000,
      "ticks": 100,
      "worldgen": true,
      "dimlet": true
    }
  },
  {
    "filter": {
      "name": "water",
      "type": "liquid"
    },
    "settings": {
      "rarity": 0,
      "create": 10,
      "maintain": 5,
      "ticks": 5,
      "worldgen": true,
      "dimlet": true
    }
  },
  {
    "filter": {
      "type": "liquid"
    },
    "settings": {
      "rarity": 5,
      "create": 10000,
      "maintain": 10000,
      "ticks": 1000,
      "worldgen": false,
      "dimlet": true
    }
  },
  {
    "filter": {
      "mod": "biomesoplenty",
      "type": "mob"
    },
    "settings": {
      "rarity": 3,
      "create": 2000,
      "maintain": 1000,
      "ticks": 400,
      "worldgen": true,
      "dimlet": true
    }
  },
  {
    "filter": {
      "mod": "tconstruct",
      "type": "mob"
    },
    "settings": {
      "rarity": 5,
      "create": 2000,
      "maintain": 1000,
      "ticks": 400,
      "worldgen": true,
      "dimlet": true
    }
  },
  {
    "filter": {
      "mod": [
        "pneumaticcraft",
        "buildcraft|robotics"
      ],
      "type": "mob"
    },
    "settings": {
      "worldgen": false,
      "dimlet": false
    }
  },
  {
    "filter": {
      "mod": "thaumcraft",
      "name": "Turret.*",
      "type": "mob"
    },
    "settings": {
      "worldgen": false,
      "dimlet": false
    }
  },
  {
    "filter": {
      "mod": "thaumcraft",
      "name": [
        "Tainted.*",
        "brainyzombie"
      ],
      "type": "mob"
    },
    "settings": {
      "rarity": 4,
      "create": 4000,
      "maintain": 5000,
      "ticks": 700,
      "worldgen": true,
      "dimlet": true
    }
  },
  {
    "filter": {
      "mod": "thaumcraft",
      "type": "mob"
    },
    "settings": {
      "rarity": 5,
      "create": 4000,
      "maintain": 5000,
      "ticks": 700,
      "worldgen": true,
      "dimlet": true
    }
  },
  {
    "filter": {
      "name": [
        "skeleton",
        "lavaslime",
        "endermite",
        "zombie",
        "silverfish",
        "spider",
        "creeper",
        "cavespider"
      ],
      "type": "mob"
    },
    "settings": {
      "rarity": 2,
      "create": 300,
      "maintain": 100,
      "ticks": 200,
      "worldgen": true,
      "dimlet": true
    }
  },
  {
    "filter": {
      "name": [
        "snowman",
        "chicken",
        "wolf",
        "ozelot",
        "cow",
        "slime",
        "pig",
        "bat",
        "rabbit",
        "entityhorse",
        "mushroomcow",
        "squid",
        "sheep"
      ],
      "type": "mob"
    },
    "settings": {
      "rarity": 3,
      "create": 500,
      "maintain": 200,
      "ticks": 300,
      "worldgen": true,
      "dimlet": true
    }
  },
  {
    "filter": {
      "name": [
        "blaze",
        "pigzombie",
        "witch",
        "ghast"
      ],
      "type": "mob"
    },
    "settings": {
      "rarity": 3,
      "create": 6000,
      "maintain": 3000,
      "ticks": 700,
      "worldgen": true,
      "dimlet": true
    }
  },
  {
    "filter": {
      "name": [
        "villager",
        "villagergolem",
        "guardian",
        "enderman"
      ],
      "type": "mob"
    },
    "settings": {
      "rarity": 4,
      "create": 10000,
      "maintain": 5000,
      "ticks": 800,
      "worldgen": true,
      "dimlet": true
    }
  },
  {
    "filter": {
      "name": "witherboss",
      "type": "mob"
    },
    "settings": {
      "rarity": 6,
      "create": 8000,
      "maintain": 8000,
      "ticks": 900,
      "worldgen": true,
      "dimlet": true
    }
  },
  {
    "filter": {
      "name": "enderdragon",
      "type": "mob"
    },
    "settings": {
      "rarity": 6,
      "create": 10000,
      "maintain": 10000,
      "ticks": 900,
      "worldgen": false,
      "dimlet": true
    }
  },
  {
    "filter": {
      "type": "mob"
    },
    "settings": {
      "rarity": 5,
      "create": 1000,
      "maintain": 1000,
      "ticks": 200,
      "worldgen": false,
      "dimlet": true
    }
  },
  {
    "filter": {
      "type": "patreon"
    },
    "settings": {
      "rarity": 2,
      "create": 10,
      "maintain": 0,
      "ticks": 1,
      "worldgen": false,
      "dimlet": true
    }
  },
  {
    "filter": {
      "type": "sky"
    },
    "settings": {
      "rarity": 0,
      "create": 100,
      "maintain": 1,
      "ticks": 1,
      "worldgen": true,
      "dimlet": true
    }
  },
  {
    "filter": {
      "type": "structure"
    },
    "settings": {
      "rarity": 3,
      "create": 600,
      "maintain": 100,
      "ticks": 900,
      "worldgen": true,
      "dimlet": true
    }
  },
  {
    "filter": {
      "type": "terrain"
    },
    "settings": {
      "rarity": 0,
      "create": 100,
      "maintain": 1,
      "ticks": 1,
      "worldgen": true,
      "dimlet": true
    }
  },
  {
    "filter": {
      "type": "time"
    },
    "settings": {
      "rarity": 2,
      "create": 300,
      "maintain": 20,
      "ticks": 10,
      "worldgen": true,
      "dimlet": true
    }
  },
  {
    "filter": {
      "type": "weather"
    },
    "settings": {
      "rarity": 1,
      "create": 100,
      "maintain": 50,
      "ticks": 10,
      "worldgen": true,
      "dimlet": true
    }
  },
  {
    "filter": {
      "type": "special"
    },
    "settings": {
      "rarity": 5,
      "create": 1000,
      "maintain": 1000,
      "ticks": 1000,
      "worldgen": false,
      "dimlet": true
    }
  },
  {
    "filter": {
      "type": "feature"
    },
    "settings": {
      "rarity": 0,
      "create": 100,
      "maintain": 1,
      "ticks": 1,
      "worldgen": true,
      "dimlet": true
    }
  },
  {
    "filter": {
      "type": "effect"
    },
    "settings": {
      "rarity": 3,
      "create": 200,
      "maintain": 0,
      "ticks": 100,
      "worldgen": true,
      "dimlet": true
    }
  },
  {
    "filter": {
      "name": "minecraft:sky",
      "type": "biome"
    },
    "settings": {
      "rarity": 5,
      "create": 5000,
      "maintain": 10000,
      "ticks": 100,
      "worldgen": false,
      "dimlet": true
    }
  },
  {
    "filter": {
      "type": "biome"
    },
    "settings": {
      "rarity": 1,
      "create": 100,
      "maintain": 0,
      "ticks": 1,
      "worldgen": true,
      "dimlet": true
    }
  },
  {
    "filter": {
      "type": "controller"
    },
    "settings": {
      "rarity": 1,
      "create": 100,
      "maintain": 0,
      "ticks": 1,
      "worldgen": true,
      "dimlet": true
    }
  },
  {
    "settings": {
      "rarity": 0,
      "create": 10,
      "maintain": 10,
      "ticks": 10,
      "worldgen": true,
      "dimlet": true
    }
  }
]

**Comment by McJty** [comment]
Your rule is gone. You have to add it BEFORE that line that says:
"Everything below this line will be regenerated from defaults every time. Remove this line if you do not want that",

**Comment by ChristopherFinn** [comment]
I'm sorry, I'm a little confused. 
Is the rule the first thing that I created when I began this thread?
`[
["material", "bigreactors", "blockMetals", 0 ]

dimletsettings {
I:"rarity.Material.tile.bigreactors:blockMetals"=4
I:"rfcreate.Material.tile.bigreactors:blockMetals"=45000
I:"rfmaintain.Material.tile.bigreactors:blockMetals"=15000
I:"ticks.Material.tile.bigreactors:blockMetals"=1000

}
]`

Or is the rule the new thing that I added to the dimlets.json?
`{
"filter": {
"mod": "bigreactors",
"name": "blockMetals",
"type": "material",
"property": {
"type": "0"
}
},`

I should really learn Java, sorry for the confusion. Not sure where to throw some of these things.

**Comment by McJty** [comment]
You see the line that says:

"Everything below this line will be regenerated from defaults every time. Remove this line if you do not want that",

?

Put your rule:

{ "filter": { "mod": "bigreactors", "name": "blockMetals", "type": "material", "property": { "type": "0" } },

Before that line. Otherwise it will be removed (that's what the line says)

**Comment by ChristopherFinn** [comment]
I've added the rule before:
"Everything below this line will be regenerated from defaults every time. Remove this line if you do not want that",
but now I'm getting a bad string error. I must be doing something wrong, but this is what it looks like.

`[
  { "filter": { "mod": "bigreactors", "name": "blockMetals", "type": "material", "property": { "type": "0" } },
  ]
[
  "Everything below this line will be regenerated from defaults every time. Remove this line if you do not want that",
  {`

**Comment by McJty** [comment]
yes, that's wrong. Don't put the "Everything below this line will be regenerated from default..." in a [].
It must be like this:

[
{ "filter": { "mod": "bigreactors", "name": "blockMetals", "type": "material", "property": { "type": "0" } },
"Everything below this line will be regenerated from defaults every time. Remove this line if you do not want that",
{
"filter": {
"name": "owner",
"type": "special"
},

**Comment by ChristopherFinn** [comment]
Would this be coming up in the dimlet workbench? I'm not seeing it anywhere, but if there is a way for me to troubleshoot and search for it that'd be amazing.

**Comment by McJty** [comment]
It should come up there yes

**Comment by ChristopherFinn** [comment]
Strange, I'm still only getting the stock liquid one that was in the pack when I began. I'll have to look into it more unless you have any other ideas!

**Comment by McJty** [comment]
Try removing the "property": { "type": "0" } from your config entry

**Comment by ChristopherFinn** [comment]
Didn't seem to work. I'm guessing its something with the Extreme Reactors port. :/ I'm willing to try any ideas you have, hopefully im implementing them correctly. If you're free I can use skype or any other way of communicating that you're comfortable with if thats an option. I really appreciate all the help.
