### ISSUE TITLE
You Are Here indicator for elevator screens

### ISSUE THREAD

**Issue by xenoflot** [McJtyMods/RFTools#978]
At the moment from a glance at an elevator screen we can determine:

* The available destinations
* The current position of the elevator

What we can't see is where we are right now. I know that I can put a vanilla button on the elevator block as a "Call button" but it breaks the aesthetic of the high-tech looking screen.

If possible, it would be nice if there were some kind of marker to indicate the current floor. Perhaps emboldening of the name, or switch current position to a chevron and use the background highlight to indicate "you are here".

Reasoning it out, I guess the easiest way to do that would be to bind the button module to the elevator block for the floor it "owns", rather than on the master block. Not a small amount of work, I'm sure :) Anyway, just throwing out ideas. I'll keep using wooden call buttons for now :-)

Cheers!

**Comment by ExDomino** [comment]
I agree with this. ^_^

**Comment by McJty** [comment]
You can use a high tech screen with button module too

**Comment by MichaelHillcox** [comment]
Unfortunately we're no longer supporting versions older than `1.12` and I don't have enough time to check this suggestion against all of the features of the mod but if this feature still hasn’t been implemented and you’d like to see it added to a newer version of the mod then please do create a new issue so we can review your suggestions again :+1:
