### ISSUE TITLE
Issues with Open Computers compatibility

### ISSUE THREAD

**Issue by lkoelln** [McJtyMods/RFTools#988]
Heyho,

At first: I'm using the current HermitPack version 1.6 (Minecraft 1.10.2) with RFTools (rftools-1.1x-5.76, rftoolsctrl-1.1x-1.6.3, rftoolsdim-1.1x-4.52) and OpenComputers 1.10.2-1.6.1.6

I also posted this Issue on the Open Computers Github site, because I dont know on which side the problem lies:
https://github.com/MightyPirates/OpenComputers/issues/2224

What I'm trying to do is to get around of the ticking problems with the Endergenic Generator described in #900 and #854 after server restarts. After the server restarts, I want robots to pickup my generators and replace and reconfigure them. Should be a relative easy task but I'm running in some problems:

**First the placing of an Endergenic Generator.** If the robot tries to place the block, it just fails. But if I'm giving it a Smart Wrench in the tool equipment slot, it can place the block, but it still has the placed block in its inventory and used up the wrench and placed it as a generator.
This also happens with other RFTools blocks (Pearl Injector, Ender Monitor, Elevator, Dimension Enscriber) that I tried. Not with Shield Templates btw.
I also found out that it doesn't need a wrench to place it. It can also be another block like cobblestone. So I found a way to make Endergenic Generators out of cobblestone. Neat ;-)
I did not have this problems with blocks from other mods I tested like EnderIO or Mekansim.

**Second problem is to let the robot use the wrench** to set the destination of a generator.
It can use the wrench to sneak-rightclick and pick up the generator, though. It just seems the generator won't recognize its right-clicks to set the destination. 

Any Idea why these things are happening? If someone could give me a direction which files would be relevant, i could take a look, too :) 
Would be nice if this can be fixed in a future version :) Using the robots to replace and fix the timing issues would be a neat little fix.

**Comment by MichaelHillcox** [comment]
Thank you for taking the time to create this issue, as we're no longer supporting versions below `1.12`, I'm going to go ahead and close it but if this bug seems to continue over to newer versions, please do report it again so we can investigate the issue further.
