### ISSUE TITLE
Applied Energistics' ME systems are not accepting power from RFTools powercells.

### ISSUE THREAD

**Issue by xenoflot** [McJtyMods/RFTools#989]
Hi,

I've found that Applied Energistics' ME systems (controller and power-acceptor) are not accepting power from RFTools powercells. 

I reported this to the AE2 team and they responded that there may be an issue with RFTools's detection of their blocks as power acceptors.  https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/2750

Would you please have a look?

    Minecraft Version: 1.10.2
    AE2 Version: appliedenergistics2-rv4-alpha-11
    Forge Version: 2185
    compatlayer-1.10-0.1.7
    rftools-1.1x-5.76
    actuallyadditions-1.10.2-r97

Cheers!

**Comment by MichaelHillcox** [comment]
Apparently sorted in ME but who knows
