### ISSUE TITLE
Riding horses on elevators is an interesting experience.

### ISSUE THREAD

**Issue by PBlock96** [McJtyMods/RFTools#995]
On version 5.81 on MC 1.11.2 with forge version 13.20.0.2222 (just the versions I confirmed with. This was first noticed on 1.10.2 with RF Tools version 5.59 and forge version 12.18.2.2124) the player view while riding a horse up an elevator teleports the player around and on high enough distanced (~20 blocks ) the player and horse will drop out of the elevator and teleport to the original location while the elevator will continue to its destination.

**Comment by MichaelHillcox** [comment]
Thank you for taking the time to create this issue, as we're no longer supporting versions below `1.12`, I'm going to go ahead and close it but if this bug seems to continue over to newer versions, please do report it again so we can investigate the issue further.
