### ISSUE TITLE
RFTools Builder used as quarry

### ISSUE THREAD

**Issue by TheDCPlaya** [McJtyMods/RFTools#999]
Started using Builder as a quarry and it tried to quarry Minecraft:dirt and failed with chat message http://i.imgur.com/Y7VU7FZ.png

**Comment by McJty** [comment]
I need more info. Version of MC. Version of RFTools. Perhaps a log

**Comment by TheDCPlaya** [comment]
MC version is 1.10.2 RFTools 1.1x-5.81 no log unfortunatly

**Comment by McJty** [comment]
Can you also tell me exactly what you did to reproduce this? What kind of quarry card? How was it configured?

**Comment by MichaelHillcox** [comment]
Thank you for taking the time to create this issue, as we're no longer supporting versions below `1.12`, I'm going to go ahead and close it but if this bug seems to continue over to newer versions, please do report it again so we can investigate the issue further.
